### PR TITLE
OrderedRDD2 only

### PR DESCRIPTION
**Pull request by cseed**
Builds on: https://github.com/hail-is/hail/pull/2301

We're on the home stretch.  Will integrate this into VSM in the next PR.

### CODE REVIEW

**Comment by cseed** [comment]
https://github.com/hail-is/hail/pull/2301 is now in.  This should be ready for a look.  How's your ASHG schedule?  Let me know if you want me to give this to someone else.

**Comment by tpoterba** [comment]
I've already started a review, and should be able to finish sometime after 1:30 (end of Broad booth Hail demo) tomorrow!

**Comment by cseed** [comment]
Thanks Tim!  You're the best.  Good luck with the posters/demos.

**Comment by cseed** [comment]
This is a useful discussion: https://stackoverflow.com/questions/26619478/are-dependent-pull-requests-in-github-possible

If I create multiple, stacked branches in hail-is/hail and PR them against each other, NOT master (except the first one), then they can be reviewed independently.  I might start trying to do this.  I still have a bunch more PRs on this RegionValue stuff.  :-/

**Comment by cseed** [comment]
And then you don't merge them until they are all ready to go in.

**Comment by cseed** [comment]
Already got merged in as part of https://github.com/hail-is/hail/pull/2308.  Will address comments with a separate PR.

**Pull request closed without merging**
