### PR TITLE
[hail] Add 'compression' parameter to export_block_matrices

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by julirsch** [comment]
It would be awesome if we could get this merged today @tpoterba!

**Comment by tpoterba** [comment]
random test failure...

**Comment by julirsch** [comment]
Tried to run this tonight:
```# Export LD matrices
list_range = [list(range(x.start_idx, x.end_idx + 1)) for x in list_meta[0:5]]
bms = [bm_ld.filter(x,x) for x in list_range]
hl.experimental.export_block_matrices(bms, out_dir + out_name + "_" + tissue + "_ld",
                                      overwrite = True, delimiter = " ", compression = "gz")```

With error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-cf064969eda4> in <module>()
      3 bms = [bm_ld.filter(x,x) for x in list_range]
      4 hl.experimental.export_block_matrices(bms, out_dir + out_name + "_" + tissue + "_ld",
----> 5                                       overwrite = True, delimiter = " ", compression = "gz")

TypeError: export_block_matrices() got an unexpected keyword argument 'compression'```

On a notebook started using:

```hailctl dataproc connect yakov notebook```

Am I missing something :)?

**Comment by julirsch** [comment]
@tpoterba would it also be possible to provide a parameter to limit the number of digits after the decimal? for example, `digits = 8` would correspond to an output of 1.00000000

**Comment by tpoterba** [comment]
yeah, sure, will make an issue

**Pull request merged**
