### PR TITLE
Changing VEP schema type of hgnc_id field from TInt to TString to support GRCh38

### PR DESCRIPTION
**Pull request by bw2**
…

### CODE REVIEW

**Comment by bw2** [comment]
Also, I've created `gs://hail-common/vep/vep/GRCh37`, `gs://hail-common/vep/vep/GRCh38`
directories with VEP configs and loftee data files, so you can now run 
```
gcloud dataproc clusters create $CLUSTER
...
--initialization-actions gs://hail-common/hail-init.sh,gs://hail-common/vep/vep/GRCh37/vep85-GRCh37-init.sh

or 

--initialization-actions gs://hail-common/hail-init.sh,gs://hail-common/vep/vep/GRCh38/vep85-GRCh38-init.sh
```

**Comment by bw2** [comment]
oops, just fixed.

**Comment by johnc1231** [comment]
Alright awesome. I'm good to approve this, but if you could, please rebase this off of branch "breakingbad" and PR into that. We're currently putting all potentially pipeline breaking changes into that branch until we merge that whole thing into master at once for 0.1 release

**Comment by bw2** [comment]
ok let me try that

**Pull request closed without merging**
