### PR TITLE
[batch] Add more info to UI pages

### PR DESCRIPTION
**Pull request by jigold**
@danking Feel free to reassign to Carolin if you're happy with the overall concept. We were trying to check off a task for February on the ToDo list.

cc: @CDiaz96 

Screen Shot 2021-02-19 at 11 25 29 AM

Screen Shot 2021-02-19 at 11 25 38 AM

Screen Shot 2021-02-19 at 11 25 52 AM

### CODE REVIEW

**Comment by danking** [comment]
Looks good but I think we need to stop making links the size of a single character. Let's make the entire `Batch 1` header clickable and also the whole `Batch ID: 1` clickable.

**Comment by danking** [comment]
And the entire ID cell should be clickable as well, not just the number `1`.

**Comment by jigold** [comment]
> Let's make the entire Batch 1 header clickable

Why would you want to do that? You're already on that page?

> And the entire ID cell should be clickable as well, not just the number 1.

Can we make this a separate PR that maybe Carolin can do? I think it requires CSS or something more complicated than that.

**Comment by jigold** [comment]
Bump. @CDiaz96 Let me know if you want to walk through this again.

**Review by CDiaz96 — APPROVED** [review]

**Review by CDiaz96 — APPROVED** [review]

**Review by CDiaz96 — APPROVED** [review]

**Pull request merged**
