### PR TITLE
add vep check to ci

### PR DESCRIPTION
**Pull request by jbloom22**

### CODE REVIEW

**Comment by konradjk** [comment]
Looks like this failed due to the wrong init script. Probably just need to update cloudtools on the CI server?

**Comment by jbloom22** [comment]
Yeah, Dan is fixing the underlying CI issue regarding cloudtools update, hopefully it then works

**Comment by danking** [comment]
@konradjk pssh, what is this "server" you speak of.

The kubernetes pod indeed needs a newer version of cloud tools. We always grab the latest when running the hail PR jobs. Unfortunately the deploy for cloud tools on python3 was broken. That's being fixed by https://github.com/Nealelab/cloudtools/pull/101.

**Comment by cseed** [comment]
Awesome.  God, how long was this in coming.

No for this PR, but I observe this seems a bit error prone:

 > --vep
 >     actual = hl.vep(expected.select_rows(), 'gs://hail-common/vep/vep/vep85-loftee-gcloud.json', csq=csq)

We should probably think a bit more about the vep/cloudtools interface after this.  I'm thinking `cloudtools --vep --vep-version=85 --vep-assembly=GRCh37 --loffee-version=beta ...` and then just `hl.vep(foo, csq=csq)` where the properties file defaults to something set up by cloudtools.  @konradjk?

**Comment by konradjk** [comment]
@cseed that seems sensible to me, especially because you can only basically use one json per combination of things (of course, you should be able to override if you want to change it)

**Pull request merged**
