### PR TITLE
[hail] Fix crash in ld_prune because we weren't imputing missing GTs

### PR DESCRIPTION
**Pull request by tpoterba**
Assigned Jackie because I want to make sure this is correct.

### CODE REVIEW

**Comment by jigold** [comment]
Unfortunately, I'm not sure. @jbloom22 or @alexb-3 -- do you remember if you have a matrix of genotypes and you want to compute the pearson correlation between variants, what is the right thing to do with missing values? Can you just mean impute for those? I looked at the local prune algorithm, and it looks like the missing values are mean imputed:

```scala
      val gtMean = gtSum.toDouble / nPresent
      val gtSumAll = gtSum + nMissing * gtMean
      val gtSumSqAll = gtSumSq + nMissing * gtMean * gtMean
      val gtCenteredLengthRec = 1d / math.sqrt(gtSumSqAll - (gtSumAll * gtSumAll / nSamples))
```

**Comment by tpoterba** [comment]
> I looked at the local prune algorithm, and it looks like the missing values are mean imputed

Yeah, that's why I went with this solution; it seemed consistent./

**Comment by tpoterba** [comment]
although, wait, it looks like this also standardizes...

**Comment by alexb-3** [comment]
I think this will deflate the value; the better thing would be to omit
terms where either genotype is missing, and then normalize by N_nonmissing.

**Comment by tpoterba** [comment]
> I think this will deflate the value; the better thing would be to omit
terms where either genotype is missing, and then normalize by N_nonmissing.

This is a big redesign -- we use matrix multiplication to compute the correlations in parallel.

It looks like the local prune stuff does mean-center and standardize, so I'll change it to match that. That sound OK?

**Comment by alexb-3** [comment]
Makes sense, but what about the following: replace missing values with 0
*after* standardization, so you can still use matrix multiplication; the
only extra thing is computing N_nonmissing for each pair.

**Comment by tpoterba** [comment]
> Makes sense, but what about the following: replace missing values with 0
*after* standardization, so you can still use matrix multiplication; the
only extra thing is computing N_nonmissing for each pair.

Yep, that's what we do.

**Comment by tpoterba** [comment]
bump

**Comment by jigold** [comment]
I don't feel qualified to look at this change.

**Comment by jbloom22** [comment]
I’ll look for closely once I get to the retreat, but first impression is that centering and normalizing are redundant.

**Comment by alexb-3** [comment]
Maybe no longer relevant, but zeroing missings *after* centering is
equivalent to using non-missing terms only rather than mean imputing,
provided you then use N_nonmissing for the final normalization.

**Comment by tpoterba** [comment]
I fixed this; it's a much more obvious change (the unfilter comes before the or_else). Should be reviewable now.

**Pull request merged**
