### PR TITLE
[release] 0.2.123

### PR DESCRIPTION
**Pull request by daniel-goldstein**
I also amended the previous changelog with some PRs that I missed.

### CODE REVIEW

**Review by danking — APPROVED** [review]
Wait for https://github.com/hail-is/hail/pull/13648 to merge

**Comment by danking** [comment]
#13648 is merged, just check if there are any new changelog entries and then we're good to go

**Comment by danking** [comment]
```
manifest for us-docker.pkg.dev/hail-vdc/hail/hailgenetics/hail:0.2.123 not found: manifest unknown: Failed to fetch "0.2.123"
```

**Comment by daniel-goldstein** [comment]
@danking That's because we weren't actually respecting the `HAIL_GENETICS_HAIL_IMAGE` for the default python image and always referencing Dockerhub. This didn't manifest until now because we were using the `python-dill` images which do not change every release

**Pull request merged**
