### PR TITLE
add tile generator

### PR DESCRIPTION
**Pull request by maccum**
This branch has code to generate the image tiles for an interactive manhattan plot. See
 https://github.com/hail-is/hail-manhattan for javascript code, and for a jupyter notebook with an example of using this code). 

Not intended for users right now, so should possibly not actually be merged yet.

### CODE REVIEW

**Comment by danking** [comment]
@cseed should someone be assigned to this PR?

**Comment by danking** [comment]
I rolled the scorecard dice and it came up @patrick-schultz

**Comment by danking** [comment]
@patrick-schultz maybe we should raise this PR at check-in. I think we should get it into mainline because then we'll be forced to deal with it as we change the code base. Maybe we should hide it form users though?

**Comment by cseed** [comment]
I'm going to close this for now.

**Pull request closed without merging**
