### PR TITLE
[tls] clean up TLS

### PR DESCRIPTION
**Pull request by danking**
`tls.py` has many different functions with long names. This change reduces it to three functions:

- internal_server_ssl_context
- internal_client_ssl_context
- external_client_ssl_context

I also added `httpx.py` which contains the HTTPS-related functions that `tls.py` previously
contained. I also simplified the HTTPS-related functions to just:

- client_session
- blocking_client_session

I determine internal vs. external using the deploy config.

---

An [`ssl.SSLContext`](https://docs.python.org/3/library/ssl.html#ssl.SSLContext) defines how a
network library (such as `aiohttp`) should perform SSL/TLS. Let's look at an example:

```python3
server_ssl_context = ssl.create_default_context(
    purpose=Purpose.CLIENT_AUTH,
    cafile='/incoming.cacerts')
server_ssl_context.load_cert_chain(ssl_config['cert'],
                                   keyfile=ssl_config['key'],
                                   password=None)
server_ssl_context.verify_mode = ssl.CERT_OPTIONAL
server_ssl_context.check_hostname = False
```

The first function call states that we are a *server* performing *client
authentication* (`Purpose.CLIENT_AUTH`). We also state that anyone who sends requests to us will be
identified by a certificate that is trusted by our certificate database: `/incoming.cacerts` (which
is a file).

`load_cert_chain` states where to find the certificates and secret key that prove who we are. The
certificate and secret key together are like a property title that proves someone owns a house. The
`password=None` means that our secret key has no password. Some keys are themselves locked by a
password.

`verify_mode` means what do we expect our clients to have. `CERT_OPTIONAL` means anonymous clients
are OK. This is how servers normally operate (https://google.com does not care who you are).

`check_hostname` means should we verify that the client certificate matches the client's
hostname. Since we allow anonymous clients, this must be `False`.

---

`test-address.py` is a gross hack. It will disappear in subsequent PRs. For now, I pushed all the
gross hack stuff into that file alone.

### CODE REVIEW

**Review by jigold — CHANGES_REQUESTED** [review]
This looks fine to me. I'm just not sure why there were so many different functions before for the ssl_context and now you're able to have 3. Were they just not used anywhere?

Also, you have an error somewhere because create_billing_projects failed

**Comment by danking** [comment]
One of them was unused. Two of them (one SSLContext and one session) was only for address, so I in-lined it there. Address needs to change anyway.  All the `context_specific..` garbage was over complicated. We should always get the SSLContext or HTTP Session that works in your environment (k8s, gce, or external).

**Comment by danking** [comment]
The test is fixed, we don't use encryption to talk to the internal gateway. I had to fix https.client_session to handle the gce case.

**Review by jigold — DISMISSED** [review]

**Comment by danking** [comment]
I disabled hostname checks for address, since address communicates directly by IP address, hostname checks don't work (there's no hostname)

**Comment by jigold** [comment]
Why did you close this? Should I move on to the next PR?

**Comment by danking** [comment]
Yeah, I reorganized it into several smaller PRs

**Comment by jigold** [comment]
I'm confused. I was ready to approve this pending the test passing. Now there's stacked PRs that include these changes. What PR should I look at?

**Comment by danking** [comment]
ah you're right, I got turned around this was the new broken up PR.

**Comment by jigold** [comment]
Not sure why the BatchPoolExecutor test failed, but approving.

**Review by jigold — APPROVED** [review]

**Pull request merged**
