### PR TITLE
[query] Add assertion that emitted and inferred ptype match

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by tpoterba** [comment]
oh dear

**Comment by tpoterba** [comment]
OK, I have to think what I want to do here. The problem is here:

https://github.com/hail-is/hail/blob/19dac15f9acf50f68274c0c3bd658cde7d16e917/hail/src/main/scala/is/hail/types/physical/stypes/concrete/SBaseStructPointer.scala#L58-L62

(array has the same problem)

**Comment by tpoterba** [comment]
The requiredness of the loaded code is the requiredness of the field type. However, if the struct itself is optional, the EmitCode needs to be optional too, regardless of the requiredness of the field.

**Comment by tpoterba** [comment]
I think what I want is for STypes to not track requiredness at the top level at all. We can't quite do this yet, though.

**Comment by johnc1231** [comment]
Will approve when benchmarks finish

**Review by johnc1231 — APPROVED** [review]

**Pull request merged**
