### PR TITLE
[deps] update mypy to 900 series

### PR DESCRIPTION
**Pull request by chrisvittal**
Compilation of the typed-ast version range that mypy 780 used was broken
in python 3.10.

### CODE REVIEW

**Review by daniel-goldstein — DISMISSED** [review]

**Comment by danking** [comment]
Thank you for making this fix Chris!

**Comment by danking** [comment]
Are you running this locally?
```
(cd hail/python && python3 -m mypy --config-file ../../setup.cfg hailtop)
```

**Comment by danking** [comment]
I get these errors locally with mypy 0.934

**Comment by danking** [comment]
I think it's transitively checking types in the dependencies of hailtop and we probably import hail in hailtop somewhere even though we really ought not to.

**Comment by danking** [comment]
Ah, the batch docs import hail

**Comment by danking** [comment]
add this to the setup.cfg:
```
exclude = hailtop/batch/docs
```

**Comment by daniel-goldstein** [comment]
Looks like the Azure library does something kind of lame here where `commit_block_list`'s signature accepts an argument of type `List[BlobBlock]` but they actually accept either the `BlobBlock` or the string id:

```python
    def _commit_block_list_options( # type: ignore
            self, block_list,  # type: List[BlobBlock]
            content_settings=None,  # type: Optional[ContentSettings]
            metadata=None,  # type: Optional[Dict[str, str]]
            **kwargs
        ):
        # type: (...) -> Dict[str, Any]
        if self.require_encryption or (self.key_encryption_key is not None):
            raise ValueError(_ERROR_UNSUPPORTED_METHOD_FOR_ENCRYPTION)
        block_lookup = BlockLookupList(committed=[], uncommitted=[], latest=[])
        for block in block_list:
            try:
                if block.state.value == 'committed':
                    block_lookup.committed.append(encode_base64(str(block.id)))
                elif block.state.value == 'uncommitted':
                    block_lookup.uncommitted.append(encode_base64(str(block.id)))
                else:
                    block_lookup.latest.append(encode_base64(str(block.id)))
            except AttributeError:
                block_lookup.latest.append(encode_base64(str(block)))
```

IIUC, the `str` type there is correct in how we treat the field, but I'm guessing mypy was complaining?

**Comment by chrisvittal** [comment]
correct

**Review by daniel-goldstein — CHANGES_REQUESTED** [review]
I think I might prefer then leaving the type as `str` since we control it, and add a `# type: ignore` comment on the offending line with a very brief explanation as to the Azure signature bug.

**Review by daniel-goldstein — APPROVED** [review]

**Pull request merged**
