### PR TITLE
geom_boxplot

### PR DESCRIPTION
**Pull request by ammekk**
Added a geom to support boxplots.

### CODE REVIEW

**Comment by johnc1231** [comment]
Ok, so the main problem with this PR is that it uses `precomputed`, which doesn't respect faceting right now. So it'll end up plotting the same plot on each facet since it'll just compute the overall quantiles once.

**Comment by danking** [comment]
@tpoterba we'll need a champion and a reviewer for this one as well

**Comment by danking** [comment]
@patrick-schultz , does this PR have a path to merging or does it require a rethink of our ggplot implementation? If the former, perhaps we could pull Iris in to finish this?

**Comment by patrick-schultz** [comment]
I haven't had a chance to look into this and understand how precomputed and faceting work and interact. If Iris wants to give that some thought, I'd be happy to advise. If there is a real obstruction to doing this in the current design, it would be good for both Iris and I to understand it before starting a redesign.

**Comment by ammekk** [comment]
Thats a great point
________________________________

**Comment by danking** [comment]
@iris-garden reopen if this is still a relevant PR to your work

**Pull request closed without merging**
