### PR TITLE
🙈

### PR DESCRIPTION
**Pull request by danking**

### CODE REVIEW

**Comment by johnc1231** [comment]
Have we ever actually merged a PR like that? I figured "covered eyes monkey" was an abbreviation of "WIP" (like, don't look at this yet). I agree it does seem like it'll happen eventually though, so probably better to stick to "WIP"

**Comment by tpoterba** [comment]
oo, could we add something to CI that blocks merge for a github PR with less than like 5 chars in the title?

**Comment by tpoterba** [comment]
we can scrape that from github right?

**Comment by johnc1231** [comment]
That's probably more code complication for CI that could be easily avoided by just sticking to the "WIP" tag.

**Comment by danking** [comment]
Yes we could do that. I added the WIP tag. Sometimes PR testing is easier than dev deploy

**Comment by tpoterba** [comment]
ok, sure, I think I overreacted. I think I was just burned by seeing "wip" in the commit history while making the changelog 😉

**Comment by tpoterba** [comment]
WIP label should be anything goes.

**Comment by danking** [comment]
I added an asana task for CI to use the PR message for single commit PRs

**Comment by tpoterba** [comment]
oh, sweet. Is that possible?

**Comment by danking** [comment]
There's some arguments that might let us do that: https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button I'm not sure exactly what the messages look like. We could at least grab the PR message and supply it as "additional" text.

**Pull request closed without merging**
