### PR TITLE
[lint] replaces black with ruff

### PR DESCRIPTION
**Pull request by iris-garden**

### CODE REVIEW

**Comment by iris-garden** [comment]
There's a pretty sizeable amount of changes that had to be made manually, so the merge conflicts might be a lot more painful with this one than https://github.com/hail-is/hail/pull/14119; not sure if that's a case for delaying this or not. I think many of those manual changes could also be made using the `--unsafe-fixes` flag to `ruff`, but it seemed better to try doing them manually to try and avoid introducing too many issues.

The lint config changes, automatic changes from `ruff`, and manual changes required to make the `ruff` check pass are split into separate commits, so hopefully that will make the review easier

**Comment by iris-garden** [comment]
putting this back in the WIP stack while i try using `--unsafe-fixes` and see if it differs from the manual changes significantly, and break out the manual fixes into separate commits based on which rule they address

**Comment by daniel-goldstein** [comment]
ya I imagine activating ruff lints will cause a bunch of changes, probably best to introduce ruff linting and ruff formatting separately

**Comment by iris-garden** [comment]
looks like the differences between `--unsafe-fixes` and my manual edits based on the feedback the linter gave were:
* `assert <boolean value> == True` becomes `assert <boolean value> is True`, not `assert <boolean value>`
*  `if <value> == foo or <value> == bar` becomes `if <value> in (foo, bar)`, not `if <value> in {foo, bar}`
* `<unused variable> = foo` becomes `foo` instead of being deleted outright
those seem fine, though i think the manual version of the latter two is better in the cases where i had added it, as i only used sets for hashable types and deleted things that didn't have side effects, afaik

**Comment by iris-garden** [comment]
sounds good @daniel-goldstein, see https://github.com/hail-is/hail/pull/14131; hopefully that should accomplish what you're suggesting?

**Comment by iris-garden** [comment]
closing for now in favor of https://github.com/hail-is/hail/pull/14131 and the progressive addition of rules it suggests.

**Comment by iris-garden** [comment]
also pushing the changes made with `--unsafe-fixes` because they're broken out from each other more clearly

**Pull request closed without merging**
