### PR TITLE
One RVD

### PR DESCRIPTION
**Pull request by patrick-schultz**
* Remove `UnpartitionedRVD`
* Combine `OrderedRVD` and `RVD` into one class, called `RVD`
* With the hierarchy collapsed, reorganize and simplify new `RVD` API

This touches a lot of lines, so I was careful to organize it into small commits, with good commit descriptions. In particular, "reorder OrderedRVD methods" *only* reorders, and "OrderedRVD -> RVD" *only* renames. Those two account for most of the line-change count, other than deleted files.

### CODE REVIEW

**Comment by patrick-schultz** [comment]
TBD

**Comment by cseed** [comment]
@danking is getting hammered, can you assign this to someone else?

**Comment by patrick-schultz** [comment]
Oh sure, I didn't see all the other repos when I assigned him.

**Comment by tpoterba** [comment]
Basically I mean rename RVD -> OrderedRVD (and partitioner, and type) for now so the diff is comparable

**Comment by tpoterba** [comment]
then after we can do that rename as a follow-up

**Comment by tpoterba** [comment]
another option is to PR everything up to the reorder, then do the reorder, then everything up to the rename, etc

**Comment by patrick-schultz** [comment]
Okay, I pulled out the OrderedRVD -> RVD rename, and merged in the table key change.

**Comment by patrick-schultz** [comment]
I spent a fair amount of time organizing the sequence of commits and writing descriptions, so I really recommend looking at individual commits to understand the changes.

**Comment by tpoterba** [comment]
yeah, sorry, I noticed that after I spent a bit of time looking at the diff.

That should also make it super easy to break up this PR into smaller chunks -- first few commits, next few, etc. Thoughts?

**Comment by tpoterba** [comment]
I also don't think github has good utilities for doing per-commit review rather than per-PR

**Comment by patrick-schultz** [comment]
Splitting up. First chunk is #4385.

**Pull request closed without merging**
