### PR TITLE
write splitmulti in python

### PR DESCRIPTION
**Pull request by catoverdrive**
With the changes in #4042 and #4043, the timing on this on `profile75.vcf.bgz` (on my laptop) is pretty close to the original--I'm seeing ~1 minute 2 seconds on the original and somewhere between 1 minute 4 seconds and 1 minute 14 seconds on the current version. I'm going to continue to investigate the timing changes and will update this PR accordingly.

### CODE REVIEW

**Comment by danking** [comment]
@catoverdrive should this be assigned to anyone?

**Comment by catoverdrive** [comment]
I'm still working on some memory/join issues. I'll assign once I'm happier with how that's looking

**Comment by catoverdrive** [comment]
can close this in the meantime.

**Comment by danking** [comment]
👌

**Pull request closed without merging**
