### PR TITLE
[base] fix mysql-client by pinning to 8.0.26

### PR DESCRIPTION
**Pull request by danking**

### CODE REVIEW

**Review by jigold — APPROVED** [review]

**Comment by danking** [comment]
@jigold why WIP?

**Comment by jigold** [comment]
https://hail.zulipchat.com/#narrow/stream/300487-Hail-Batch.20Dev/topic/weird.20behavior/near/263676847

**Comment by danking** [comment]
Ah, that's because website_image lacked enough resources, I added a change to address that to this PR.

**Comment by danking** [comment]
All image builds need at least 10 GiB of storage for :waves hands: docker.

**Pull request merged**
