### PR TITLE
[ci] Add production prefix to tags deployed in production

### PR DESCRIPTION
**Pull request by daniel-goldstein**

### CODE REVIEW

**Review by jigold — APPROVED** [review]

**Review by jigold — CHANGES_REQUESTED** [review]
Can we make this `prod`? There's no negative lookahead with Go Regex so I have to write something manually that is O(n_char).

**Comment by jigold** [comment]
Actually. It will be easier if we do the opposite and tag the rest with "tmp" or something.

**Comment by jigold** [comment]
I need a single GO regex that matches the tags that we are okay deleting

> If specified, any image where all tags match this given regular expression will be deleted. The image will not be delete if it has other tags that do not match the given regular expression. The regular expressions are parsed according to the [Go regexp package](https://golang.org/pkg/regexp/syntax/).

**Comment by jigold** [comment]
I'm not sure if you can easily specify multiple groups.

**Comment by jigold** [comment]
This also leaves me a bit nervous as it means we'll never delete production images.

**Comment by daniel-goldstein** [comment]
> 

Does this not work? `((dev)|(pr)|(test))-.*`

**Comment by daniel-goldstein** [comment]
> This also leaves me a bit nervous as it means we'll never delete production images.

We can still do this, no?

**Comment by jigold** [comment]
Closing in favor of only deleting untagged images.

**Pull request closed without merging**
