### PR TITLE
[hail] Move agg.inbreeding to Python

### PR DESCRIPTION
**Pull request by tpoterba**
stacked on #6816

### CODE REVIEW

**Comment by tpoterba** [comment]
stacked PR is in, ready for review.

**Comment by johnc1231** [comment]
This PR is failing tests

**Comment by tpoterba** [comment]
will fix

**Comment by tpoterba** [comment]
This change uncovered a problem with lowering -- `AggLet` nodes are not tolerated inside MatrixMapCols/MatrixMapRows. I'll follow up with a PR to fix this for MatrixMapRows and add targeted tests.

**Pull request merged**
