### PR TITLE
[ci] Turn off Azure required status

### PR DESCRIPTION
**Pull request by jigold**

### CODE REVIEW

**Review by danking — APPROVED** [review]

**Comment by jigold** [comment]
Did we still want this change?
@danking @daniel-goldstein

**Comment by danking** [comment]
I think no. The frequency of failures is a bit lower than it was.

**Comment by danking** [comment]
I restored hail-ci-azure as a GitHub required status.

**Comment by johnc1231** [comment]
I'm fine with this, though I think frequency of failures is still relatively high. I have been hitting retry on PRs when i notice.

**Pull request closed without merging**
