### PR TITLE
PTypes 40: Remove references to TableType.rvdType

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by cseed** [comment]
This isn't compiling.  Also, I can't find the definition of canonicalRVDType.  I'll take another pass once these get fixed up.

**Comment by tpoterba** [comment]
agh, it was compiling yesterday

**Comment by cseed** [comment]
Not fixed.

**Comment by tpoterba** [comment]
where do you see that?

**Comment by cseed** [comment]
The tests are being rerun, they were failing a second ago.

@danking it's known that we want to be able to view previous test runs in ci exactly for cases like this.

**Comment by tpoterba** [comment]
ah, weird...

**Comment by tpoterba** [comment]
passing

**Pull request merged**
