### PR TITLE
[batch] Allow finer granularity for JVM memory settings

### PR DESCRIPTION
**Pull request by lgruen**
This is useful for tuning resource consumption of large QoB jobs.

#assign services

### CODE REVIEW

**Comment by jigold** [comment]
@danking Do you have an opinion on this change? I thought we didn't want to create too many JVMs on the worker.

**Comment by danking** [comment]
@lgruen are y'all running with this change now? I was vaguely concerned that with ~32 JVMs alive that would negatively impact the machine. Do you find that the JVM's RAM gets swapped out and the machines are generally stable?

**Comment by lgruen** [comment]
> @lgruen are y'all running with this change now? I was vaguely concerned that with ~32 JVMs alive that would negatively impact the machine. Do you find that the JVM's RAM gets swapped out and the machines are generally stable?

Yes, we haven't seen any issues with this so far, but also have only been running with this change for a few days.

**Review by danking — APPROVED** [review]
fyi @daniel-goldstein , @jigold

**Pull request merged**
