### PR TITLE
[query] Better error message when using `in` incorrectly

### PR DESCRIPTION
**Pull request by johnc1231**
Let me know if you think the error message is clear.

### CODE REVIEW

**Comment by tpoterba** [comment]
we should put this on top level expression. Someone could do something like `'NA12878' in mt.s` and that should have an error as well.

**Comment by johnc1231** [comment]
@tpoterba, I thought about that, but it would break compatibility, since we currently allow:

```
"x" in hl.struct(x = 3, y = 5)
```

**Comment by tpoterba** [comment]
oh, right, good point. though I think maybe StructExpression would override the Expression definition?

**Comment by johnc1231** [comment]
I guess I could put it on top level and then override it for `StructExpression`

**Comment by johnc1231** [comment]
Is there any `in` behavior besides the struct one? I don't know of any, but I don't often use things like `Interval` or `Call` ,etc.

**Comment by tpoterba** [comment]
TupleExpression may override (with something wrong) too.

**Comment by johnc1231** [comment]
Ok, so now there's a generic catch all error on `Expression`, and I override it on `StructExpression` to make sure that one works. `CollectionExpression` and `StringExpression` also get overrides to give appropriate examples.

**Comment by johnc1231** [comment]
@konradjk @tpoterba I think this is ready to merge whenever.

**Comment by johnc1231** [comment]
Bump

**Pull request merged**
