### PR TITLE
Fix fam parser to read -9 as missing

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by jbloom22** [comment]
We already had this debate, the docs take a missing parameter to handle the quantitative case flexibly:
https://hail.is/docs/devel/methods/impex.html#hail.methods.import_fam

**Comment by jbloom22** [comment]
We could add a warning to the docs to make it even clearer.

**Comment by tpoterba** [comment]
what should we do here? PLINK does use -9 as a default missing value, so we should too.

**Comment by tpoterba** [comment]
PLINK just uses any non-numeric as missing as well.

**Pull request merged**
