### PR TITLE
[ci] statuses should reflect GitHub's belief, not our belief

### PR DESCRIPTION
**Pull request by danking**

### CODE REVIEW

**Comment by johnc1231** [comment]
@danking Has conflicts

**Comment by danking** [comment]
bump

**Comment by danking** [comment]
@cseed bump

**Comment by cseed** [comment]
Bumped.  I will look at this after my meetings today.

**Comment by danking** [comment]
Thanks for the review! This indeed seems more aligned with the CI design philosophy.

**Pull request merged**
