### PR TITLE
[batch2] add ubuntu to disk image and change tests to use ubuntu

### PR DESCRIPTION
**Pull request by jigold**

### CODE REVIEW

**Comment by jigold** [comment]
The disk image is 3.3 GB.

**Comment by cseed** [comment]
All our images are based on ubuntu:18.04.

**Comment by jigold** [comment]
I rebuilt the disk image from scratch and it's 2.1 GB. I'm not sure we can do much better than that if we cache the batch2 image on there. However, I found if we don't do that, it adds up to an extra minute.

**Comment by jigold** [comment]
Closing this in favor of #7233

**Pull request closed without merging**
