### PR TITLE
[qob] cancel the QoB test batch after a test is complete

### PR DESCRIPTION
**Pull request by danking**

### CODE REVIEW

**Review by daniel-goldstein — CHANGES_REQUESTED** [review]
Can we do this only on failures/timeouts?

**Comment by danking** [comment]
I'm merging into https://github.com/hail-is/hail/pull/13325, but @daniel-goldstein , I'd still like your review of the updated code.

**Comment by danking** [comment]
If you're satisfied, you can close. If you're not, leave me a review and I'll use this PR to fix main after the omnibus lands.

**Comment by danking** [comment]
Closing to make room in CI for other PRs.

**Comment by danking** [comment]
Closing to ease CI burden

**Review by daniel-goldstein — DISMISSED** [review]
@danking Can you explain what's happening in this PR? How come this doesn't have to be a fixture? Is this cancelling the test task or something else?

**Comment by danking** [comment]
@daniel-goldstein sorry I was a dummy, what I had didn't actually do what I thought it did.

It's a bit complex to get access to test information in a fixture, but there's some docs on how to do it. I did that. Now the fixture checks and only tears down a batch when the test failed.

**Pull request merged**
