### PR TITLE
[c++] use SparkBackend if cpp flag is turned on

### PR DESCRIPTION
**Pull request by catoverdrive**
This is independent of #5469, but I don't know if we wanted to wait on that to land before this happens.

### CODE REVIEW

**Comment by cseed** [comment]
This is only enabled if the cpp feature flag is turned on.  I don't think it is ever turned on in the tests.

**Comment by tpoterba** [comment]
ah, OK.

I'll un-block tomorrow, since I think there's already a queue of approved PRs and I have at least 2 that will need to go in this evening.

**Comment by cseed** [comment]
Yeah, totally fine, no hurry.

**Comment by catoverdrive** [comment]
@tpoterba can I dismiss your review?

**Comment by tpoterba** [comment]
Yes!

**Pull request merged**
