### PR TITLE
[hail] include the diagonal in PCRelate

### PR DESCRIPTION
**Pull request by danking**
CHANGELOG: `hl.pc_relate` now includes values on the diagonal of kinship, IBD-0, IBD-1, and IBD-2

### CODE REVIEW

**Comment by tpoterba** [comment]
how would this work with maximal_independent_set?

**Comment by danking** [comment]
Ugh. I added a keyword parameter that defaults to the old behavior.

**Comment by tpoterba** [comment]
Yeah, annoying. We should probably be boxing this up so that most users never actually use maximal_independent_set but just `prune_related_samples(mt, ...)` and we can do what we want in there.

**Comment by tpoterba** [comment]
Hail is 1-2 levels of abstraction too low for most users

**Comment by danking** [comment]
One of us should do one boring genetics project with someone and just publish whatever we write during that process.

**Comment by danking** [comment]
bump @chrisvittal

**Review by chrisvittal — APPROVED** [review]

**Comment by olavurmortensen** [comment]
Awesome, thanks guys!

**Pull request merged**
