### PR TITLE
Fixed use of grid partitioner

### PR DESCRIPTION
**Pull request by johnc1231**
Accidentally set things up so that there would only be one block per partition. That should not be the case.

### CODE REVIEW

**Comment by danking** [comment]
I think you still need the type annotation.

**Comment by johnc1231** [comment]
@danking Yeah I do. I also realized that the way I'm constructing the object now uses an apply method, not a constructor. So I'll have to fiddle with the reflection a bit too. Sorry about that. Could have sworn I hit test button before submitting.

**Comment by danking** [comment]
I never hit test before submitting. 😁

**Comment by johnc1231** [comment]
@danking Should be all fixed now.

**Pull request merged**
