### PR TITLE
hail.vep.assembly setting to allow assemblies other than GRCh37

### PR DESCRIPTION
**Pull request by bw2**
Also, added hail.vep.extra_plugins for specifying additional plugins beyond the default ones (such as LoF_splice.pm for predicting variants' probability of splice junction disruption or creation)

### CODE REVIEW

**Comment by bw2** [comment]
Also, added the following files under gs://hail-common/vep/vep

gs://hail-common/vep/vep/run_hail_vep85_GRCh37_vcf.sh
gs://hail-common/vep/vep/run_hail_vep85_GRCh38_vcf.sh
gs://hail-common/vep/vep/vep85-GRCh37-gcloud.properties
gs://hail-common/vep/vep/vep85-GRCh37-init.sh
gs://hail-common/vep/vep/vep85-GRCh38-gcloud.properties
gs://hail-common/vep/vep/vep85-GRCh38-init.sh
gs://hail-common/vep/vep/homo_sapiens/85_GRCh38/

**Comment by cseed** [comment]
Code looks good.  Can you update the VariantDataset.vep function documentation?  In particular, note that plugin overrides human_ancestor and conservation file.

plugin in cleaner.  We should remove the latter when we start version 0.2: https://github.com/hail-is/hail/issues/1728

**Comment by bw2** [comment]
I've updated the docs. 
One remaining issue is how to allow multiple `--plugin` options  (http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html) ?

**Comment by cseed** [comment]
Will the additional --plugin options change the output schema?  We fix the schema in the VEP command which is one reason we've resisted supporting general VEP options.  To support a general schema, we probably need to impute the schema from the VEP JSON output.

**Pull request merged**
