### PR TITLE
Hail subproject

### PR DESCRIPTION
**Pull request by cseed**
FYI @tpoterba 

moved everything to hail/

deleted changes.md (completely out of date) and acknowledgements.txt (not maintained and subsumed by git history, I think)

the test scripts (still at the top-level) cd into hail

### CODE REVIEW

**Comment by cseed** [comment]
FYI, I need to update developer getting started.

**Comment by cseed** [comment]
OK, fixed.

**Comment by tpoterba** [comment]
the one thing in acknowledgements was Jack Kosmicki's contribution, which didn't show up on git because of squashing

**Comment by tpoterba** [comment]
we could just add a note to hl.transmission_disequilibrium_test actually

**Comment by cseed** [comment]
Hmm.  I'm not sure how to handle that.  Jack is in the history now (he created the original acknowledgments file):

```
commit 05fd2e68413f0cdbd6a57304c0d91e93d0c8fbdf
Author: Jack Kosmicki <kosmickij@gmail.com>
Date:   Thu Nov 3 16:55:23 2016 -0400

    Create acknowledgements.txt (#1053)
```

**Comment by tpoterba** [comment]
oh, right - we had him create that so he was in the history too. But we can delete it.

**Comment by cseed** [comment]
> Conflicting files
 > src/main/scala/is/hail/expr/ir/IR.scala

Damnit.

**Pull request merged**
