### PR TITLE
[ci] allow core AUS devs to see CI pages

### PR DESCRIPTION
**Pull request by danking**
They all have broad emails now, which is what I used for their Batch usernames.

### CODE REVIEW

**Review by jigold — APPROVED** [review]

**Comment by lgruen** [comment]
@danking Thanks a lot! Is it possible that our Hail Batch accounts aren't fully set up yet? @illusional and I are getting a 401 when trying to log into https://batch.hail.is, typically after a redirect loop.

**Comment by danking** [comment]
Ah, hmm, I added your Broad account names, not your populationgenomics names.

If it's not too much trouble, I think the easiest thing to do is to visit http://auth.hail.is/signup and use your Broad credentials. Michael appears to have never had a Hail Batch account under his populationgenomics email anyway.

**Comment by lgruen** [comment]
> I think the easiest thing to do is to visit http://auth.hail.is/signup and use your Broad credentials

That worked, thanks! I think I accidentally tried `http://batch.hail.is/signup` (or similar) before, which sent me into a redirect loop.

**Comment by lgruen** [comment]
@danking I can now access https://auth.hail.is/user successfully (for the `lgruensc` user), but https://ci.hail.is/batches/3654512 or similar still results in a "redirected you too many times" followed by a 401.

**Comment by daniel-goldstein** [comment]
Vlad should also contact us after signing up so we can fix his developer status.

**Comment by lgruen** [comment]
@daniel-goldstein Yay, it's working now, thank you! Vlad is still on leave, but I'll let him know.

**Comment by vladsavelyev** [comment]
Hey hey everyone, I'm back! I created a user (`vsavelye`, no last `v` - the Broad knows better!).
cc @danking @daniel-goldstein
Thank you! :)

**Comment by daniel-goldstein** [comment]
@vladsavelyev Made you a developer on our GCP instance. Let me know if you run into any issues!

**Pull request merged**
