### PR TITLE
[query] Lowering uses encoded literals instead of java lits

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by danking** [comment]
In my PR (#11681), I used `GetTupleElement` so that missingness propagated correctly. Should we do that here as well?

I also pasted the encoder/decoder issue uncovered by this change in #11681.

**Review by danking — CHANGES_REQUESTED** [review]
taking off my queue, dismiss when we've resolved the encoding issue

**Comment by tpoterba** [comment]
@danking this works now!

**Comment by tpoterba** [comment]
(was failing due to the same encoder bug)

**Pull request merged**
