### PR TITLE
[docker] Add config support for docker prefix and root image

### PR DESCRIPTION
**Pull request by daniel-goldstein**

### CODE REVIEW

**Comment by vladsaveliev** [comment]
Thanks so much Daniel!! This is awesome.

I can't seem to be able to merge though, probably due to permissions?
Screen Shot 2021-04-22 at 9 58 00 am

There are also conflicts, but I'm resolving them right now :)

**Comment by vladsaveliev** [comment]
Ah, learned from Leo that the merge button will be available after the tests pass :)

**Comment by vladsaveliev** [comment]
I resolved the conflicts in the original PR (https://github.com/hail-is/hail/pull/10107/), however, I can't do it for this one. Daniel, would you be able to take a look at the conflicting files?

**Comment by daniel-goldstein** [comment]
No worries @vladsaveliev! I put this PR up just to work through the CI tests. I meant once you merge my changes into your branch and your PR goes in I will close this one.

**Comment by vladsaveliev** [comment]
Daniel, the CI still doesn't seem to work though?

Also, re:
> I meant once you merge my changes into your branch

This PR is created against the main branch, not my branch though, so if merged, it would go directly into main. Okay with me!

**Comment by daniel-goldstein** [comment]
Hm ok, I'm going to push this PR through to avoid more merge conflict setbacks and think about how to improve this workflow for the future. Sorry for all the hassle!

**Review by danking — APPROVED** [review]

**Pull request merged**
