### PR TITLE
[query] Add `ignore_in_sample_allele_frequency` flag to `hl.de_novo`

### PR DESCRIPTION
**Pull request by tpoterba**
Also take the opportunity to implement the check on pop_frequency_prior
in accordance with our years-old comment.

### CODE REVIEW

**Comment by tpoterba** [comment]
context: https://discuss.hail.is/t/prior-and-pop-frequency-prior-in-de-novo/1718/5

**Comment by johnc1231** [comment]
Failing a local backend test

**Comment by tpoterba** [comment]
fixed the local backend test (had to do with the HailUserException not getting extracted properly in lowered execution, which I'm punting on right now).

Docs build is now failing, which I think is a problem in main.

**Comment by johnc1231** [comment]
Ah, sorry about that. I'll fix the `HailUserException` thing on local backend in a separate PR.

**Review by johnc1231 — APPROVED** [review]
Sorry, meant to approve when I commented earlier this morning

**Comment by johnc1231** [comment]
#9569 Fixes the `HailUserException` error you encountered. `LocalBackend` now correctly handles `HailUserException`s

**Pull request merged**
