### PR TITLE
Allow os.PathLike paths for Batch.read_input()/read_input_group()

### PR DESCRIPTION
**Pull request by jmarshall**

### CODE REVIEW

**Comment by jmarshall** [comment]
For your consideration… We often have a `pathlib.Path` or `cloudpathlib.CloudPath` that we've built up by parts, which is then the path to be used as an input resource:

```python
res = mybatch.read_input(str(mycloudpath))
```

Periodically we accidentally omit the `str(…)`, which leads to a semi-obscure error message and an extra editing round-trip.

There is a point of view that `read_input()` and `read_input_group()` could also accept `os.PathLike` objects directly, and have Hail convert them to `str` itself, e.g. in `_new_input_resource_file()` which underlies both methods, as per this PR.

The difficulty is how to do that conversion: `str(…)` does the trick for [`pathlib.Path`](https://docs.python.org/3.12/library/pathlib.html#operators) and [`cloudpathlib.CloudPath`](https://cloudpathlib.drivendata.org/stable/api-reference/cloudpath/), returning the path and URL, respectively, as a string.

But it looks like in theory there might be [`os.PathLike`](https://docs.python.org/3/library/os.html#os.PathLike) subclasses that don't define `__str__()` to produce a usable path/URL. The official conversion method appears to be [`os.fspath()`](https://docs.python.org/3/library/os.html#os.fspath), but that does not do the right thing for `cloudpath.CloudPath` — there it downloads the remote file and returns a local path — which is not at all what Hail needs.

However probably this is a theoretical concern and `str(…)` will be fine…

**Review by daniel-goldstein — APPROVED** [review]
This is great, thank you @jmarshall! I think it is just better to go with `str` for the time-being. If someone comes along with a `PathLike` that does not have this desired behavior they should find out quickly and we can work to fix it.

**Review by daniel-goldstein — CHANGES_REQUESTED** [review]
@jmarshall Could you use `Union` instead of `|` for the types? We still support python3.9 which doesn't support that syntax.

**Comment by daniel-goldstein** [comment]
We'll be dropping 3.9 soon but haven't done so yet.

**Comment by jmarshall** [comment]
Done. We've been on 3.10+ for a long while, and it's very easy to start taking the nicer syntax for granted :smile:

**Review by daniel-goldstein — APPROVED** [review]
Indeed, I look forward to our turn!

**Pull request merged**
