### PR TITLE
[lowering] Remove uses of RVDToTableStage in matrix writers

### PR DESCRIPTION
**Pull request by chrisvittal**
Based on [this comment](https://github.com/hail-is/hail/pull/12185#discussion_r985974224)

### CODE REVIEW

**Review by tpoterba — APPROVED** [review]

**Comment by tpoterba** [comment]
Do you want to go delete all the unstaged implementations of things that have good staged implementations next? There's no reason we still need TableNativeWriter.apply, for instance 😲  💯

**Comment by chrisvittal** [comment]
Sure, sounds great. I am once again asking if I can remove local staging functionality (stageLocally).

**Comment by tpoterba** [comment]
Nope, we should add that. You're right, that's the reason we can't get rid of those unstaged ones yet.

**Comment by tpoterba** [comment]
(I think it's a super quick project)

**Pull request merged**
