### PR TITLE
Added 2nd version of split to expr language taking 2nd argumen n-splits

### PR DESCRIPTION
**Pull request by Fedja**

### CODE REVIEW

**Comment by jbloom22** [comment]
You write: "Setting `limit` to negative disables limiting the number of split and trailing empty strings are preserved."

So if negative, your split is the same as the old split?

Regarding "trailing empty strings are preserved", how does a string have trailing empty strings?

**Comment by Fedja** [comment]
@jbloom22 
"a|b|c||d||".split("\\|") -> ["a","b","c","","d"]
where as 
"a|b|c||d||".split("\\|",-1) -> ["a","b","c","","d","",""]

**Comment by jbloom22** [comment]
Ok.  In "Setting limit to negative disables limiting the number of split and trailing empty strings are preserved", you're missing "s" on split, and it's not clear if negative is necessary for trailing empty strings to be preserved.  How about:

Setting limit to negative disables limiting the number of splits. Trailing empty strings are preserved, so "a,b,,".split(",", -1) gives ["a", "b", ""]

**Comment by Fedja** [comment]
yes much clearer. Corrected!

**Comment by jbloom22** [comment]
In fact we got it wrong:
```
scala> "a,b,,".split(",", -1)
res0: Array[String] = Array(a, b, "", "")
```

**Comment by Fedja** [comment]
oh g-sus yes... we are good at arriving to wrong conclusions together. Corrected once more.

**Comment by jbloom22** [comment]
It's not clear what happens to empty strings at the beginning.  I think if you replace with this, we'll be all set:

Setting `limit` to negative disables limiting the number of splits.  Trailing empty strings are preserved, so ",a,b,,".split(",", -1) gives ["", "a", "b", "", ""] whereas ",a,b,,".split(",") gives ["", "a", "b"].

**Comment by jbloom22** [comment]
Great, go ahead and merge.

**Comment by Fedja** [comment]
Great. I don't think I have write access to merge

**Pull request merged**
