### PR TITLE
[hail] use TLS for a whole variety of links in Hail.

### PR DESCRIPTION
**Pull request by danking**
mumble mumble MITM mumble mumble

### CODE REVIEW

**Comment by johnc1231** [comment]
Docs are failing to build

**Comment by danking** [comment]
Wow. Fuck libxml. It doesn't support HTTPS references. What century are we living in

**Comment by danking** [comment]
```
# xsltproc -o fuckyou.html --html fuckyou.xslt
compilation error: file fuckyou.xslt line 2 element stylesheet
xsltParseStylesheetProcess : document is not a stylesheet
# vim fuckyou.xslt 
# cat fuckyou.xslt 
<?xml version="1.0" encoding="ISO-8859-15"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
</xsl:stylesheet>
# xsltproc -o fuckyou.html --html fuckyou.xslt
```

www.w3.org definitely speaks TLS based on `curl`.

**Comment by danking** [comment]
bump

**Comment by danking** [comment]
@johnc1231 you already peeked at this, so do you mind properly reviewing it? It passes the tests now.

**Comment by johnc1231** [comment]
Happy to

**Pull request merged**
