### PR TITLE
Add Maximize and MinimizeLets optimizer passes

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by tpoterba** [comment]
Agh, this isn't good enough.

It feels like the right thing might be to lift up the lets, optimize, then push down.

This has the added benefit of making it trivial to collapse multiple identical let bindings.

**Comment by tpoterba** [comment]
For reference, here is the IR generated by `read_matrix_table().count_cols()` which I want to optimize to `I64(blah)`:

```
(TableCount
  (TableKeyBy (s) False
    (TableParallelize None
      (Let __cols_and_globals
        (TableGetGlobals
          (TableZipUnchecked
            (TableMapGlobals
              (TableMapGlobals
                (TableRead "/Users/tpoterba/data/profile.mt/rows" True Table{global:Struct{},key:[locus,alleles],row:Struct{locus:Locus(GRCh37),alleles:Array[String]}})
                (Literal Struct{} <literal value>))
              (InsertFields
                (Ref global)
                (__cols
                  (GetField rows
                    (TableCollect
                      (TableRead "/Users/tpoterba/data/profile.mt/cols" False Table{global:Struct{},key:[],row:Struct{s:String}}))))))
            (TableRead "/Users/tpoterba/data/profile.mt/entries" True Table{global:Struct{},key:[],row:Struct{`the entries! [877f12a8827e18f61222c6c8c5fb04a8]`:Array[Struct{}]}})))
        (MakeStruct
          (rows
            (ArrayMap elt
              (ArraySort True
                (ArrayMap i
                  (ArrayRange
                    (I32 0)
                    (ArrayLen
                      (GetField __cols
                        (Ref __cols_and_globals)))
                    (I32 1))
                  (Let __cols_element
                    (ArrayRef
                      (GetField __cols
                        (Ref __cols_and_globals))
                      (Ref i))
                    (MakeStruct
                      (_1
                        (SelectFields (s)
                          (Ref __cols_element)))
                      (_2
                        (Ref __cols_element)))))
                (True))
              (GetField _2
                (Ref elt))))
          (global
            (SelectFields ()
              (Ref __cols_and_globals))))))))
```

**Comment by tpoterba** [comment]
(note this is coming from a downstream commit where I've written a lowerer for MatrixRead, that's what the `TableZipUnchecked` is for)

**Comment by cseed** [comment]
1.  I really don't understand what this code is trying to do.  Can you give me a short explanation in English?

2.  I think you just need single-use Let forwarding to optimize this.  It looks like:

Push down the TableCount.  (TableCount (Paralellelize ...)) should turn into (ArrayLen (GetField rows ...)).

Push the ArrayLen/GetField into the Let.  (Is this what your "MaximizeLets" is doing?  I think that would traditionally be called let lifting.)

Now you have (Let __cols_and_globals (ArrayLen (GetField __cols (Ref __cols_and_globals))).

Then you forward the single-use Let, and the rest of the code simplifies into (ArrayLen (TableCollect (TableRead "cols"))), and that should have the static number of rows and be able to be simplified.

3. So how should single-use Let forwarding work?  You need two things: to determine there is only one use, and that the single use isn't in a more expensive context, e.g. you don't want to forward a single-use Let into a loop: (Let expensive X (ArrayMap a x <use expensive once>)).

Since our control flow is structured, there is a static notion of "loop nesting depth", e.g. in the above code, the Let has nesting depth 0, and the use in the ArrayMap body has nesting depth 1.  You can only forward into the same nesting depth.

4. Final question is, do you want the let forwarding pass to also delete unused Lets?  If you delete a let, that might delete references that make other lets single (or zero) use.  In this case, it might be nice to build a "use-def chain" data structure, that keeps, for each let, its list of uses (and vice versa).  Then, when you delete a Let, you can dynamically delete the references for the right hand side, possibly creating additional optimization opportunities.

**Comment by tpoterba** [comment]
This has grown too big. I will break it up into at least 2 pieces.

**Comment by tpoterba** [comment]
AnonymizeBindings/LiftLets and ForwardLets are independent, so I'll re-PR ForwardLets first.

**Comment by cseed** [comment]
This is out of date now, right?  Should we close it?

**Comment by tpoterba** [comment]
yeah.

**Pull request closed without merging**
