### PR TITLE
[query] better error message when info array field has missing elements

### LINKED ISSUE #13346: [query] bad error message when user needs to use array_elements_required=False
If you're encountering this issue the quick fix is to use `array_elements_required=False`

```
hl.import_vcf(..., array_elements_required=False)
```

---

### What happened?

https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query-0.2E2-support/topic/checkpoint.20with.20missing.20fields

```
is.hail.utils.HailException: gs://jn-vcf-cleanup-central1/McCarroll-Macosko-UM1-BICAN-Express-WGS-2023-0626/McCarroll-Macosko-UM1-BICAN-Express-WGS-2023-0626.vcf.gz:offset 1344376382: error while parsing line
chr1	10403	.	ACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC	A,ACCCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC	.	LowQual	AC=1,1;AF=0.250,0.250;AN=4;AS_QUALapprox=0|23|45;AS_VQSLOD=.,.;AS_YNG=.,.;QUALapprox=45	GT:AD:GQ:RGQ	./.	0/1:23,7,0:20:23	./.	./.	./.	0/2:6,0,4:35:45	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.

	at is.hail.utils.ErrorHandling.fatal(ErrorHandling.scala:21)
	at is.hail.utils.ErrorHandling.fatal$(ErrorHandling.scala:21)
	at is.hail.utils.package$.fatal(package.scala:78)
	at is.hail.io.vcf.MatrixVCFReader.$anonfun$executeGeneric$7(LoadVCF.scala:1934)
	at is.hail.io.vcf.MatrixVCFReader.$anonfun$executeGeneric$7$adapted(LoadVCF.scala:1922)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:515)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at __C2005collect_distributed_array_matrix_native_writer.apply_region1_27(Unknown Source)
	at __C2005collect_distributed_array_matrix_native_writer.apply(Unknown Source)
	at __C2005collect_distributed_array_matrix_native_writer.apply(Unknown Source)
	at is.hail.backend.BackendUtils.$anonfun$collectDArray$6(BackendUtils.scala:52)
	at is.hail.utils.package$.using(package.scala:635)
	at is.hail.annotations.RegionPool.scopedRegion(RegionPool.scala:162)
	at is.hail.backend.BackendUtils.$anonfun$collectDArray$5(BackendUtils.scala:51)
	at is.hail.backend.spark.SparkBackendComputeRDD.compute(SparkBackend.scala:751)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

is.hail.utils.HailException: cannot set missing field for required type +PCString
```

Notice in particular:
```
AS_VQSLOD=.,.;AS_YNG=.,.
```
These fields are array fields containing missing values. By default, Hail errors when parsing these due to the inherent ambiguity of a single dot: is it a missing array or an array with one, missing, element.

The error message should suggest that the user try using array_elements_required. The docs for `import_vcf` should provide enough information for the user to understand what this does.

We should also consider making this the default.

### Version

0.2.120

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by danking**
Fixes #13346.

Another user was confused by this: https://github.com/hail-is/hail/issues/14102. Unfortunately, the world appears to have embraced missing values in VCF array fields even though the single element case is ambiguous. In #13346, I proposed a scheme by which we can disambiguate many of the cases, but implementing it ran into challenges because LoadVCF.scala does not expose whether or not an INFO field was a literal "." or elided entirely from that line.

Anyway, this error message actually points users to the fix. I also changed some method names such that every method is ArrayType and never TypeArray.

### CODE REVIEW

**Comment by danking** [comment]
Redistribute some work away from Patrick.

**Comment by danking** [comment]
bump; merge conflicts now fixed.

**Comment by danking** [comment]
@chrisvittal bump, I want to include this in 0.2.127!

**Review by chrisvittal — APPROVED** [review]
done!

**Pull request merged**
