### PR TITLE
[query] update to latest google storage APIs

### PR DESCRIPTION
**Pull request by danking**
It is possible this addresses #12950 for two reasons:
1. In 2.25.0, they rewrote the BlobWriteChannel entirely. [commit](https://github.com/googleapis/java-storage/commit/1b52a1053130620011515060787bada10c324c0b).
2. Also in 2.25.0, after the rewrite, they fixed in issue with tracking offsets after incremental flushes. Maybe the issue existed in the old code too?. [commit](https://github.com/googleapis/java-storage/commit/c099a2f4f8ea9afa6953270876653916b021fd9f).
3. In 2.22.4 they modified the BlobWriteChannel to use a different retry method. [commit](https://github.com/googleapis/java-storage/commit/1b52a1053130620011515060787bada10c324c0b).

Anyway, all circumstantial.

### CODE REVIEW

**Review by chrisvittal — DISMISSED** [review]
fix the build, but it should be fine

**Comment by danking** [comment]
Snyk is failing because it suddenly realized that we have dependencies (#security 🤦 ). I will fix those issue separately.

**Comment by danking** [comment]
https://github.com/hail-is/hail/pull/13561

**Comment by danking** [comment]
Yikes, this made the Hail wheel nearly 300 MB.

**Comment by danking** [comment]
OK, there was a `justSpark` "configuration". I dunno what that means, it wasn't referenced by the other configurations. I initially made it `implementation` which includes it in the shadow JAR. I switched it to `shadow` b/c mllib (the only thing in the justSpark) should be provided by Spark at runtime anyway.

**Comment by danking** [comment]
@ehigham Chris is out so reassigning to you.

**Comment by ehigham** [comment]
Seems the `testImplementation` doesn't configure the classpath for tests correctly - javatests are currently failing with `Error: Could not find or load main class org.testng.TestNG`

**Comment by danking** [comment]
Hmm. I’ll have to sort this out tomorrow. Not sure what’s going on with that. It seems like the shadowTestJar target is probably not correctly pulling in the testImolemebtation configuration.

**Comment by danking** [comment]
Gah, OK, I think I have it now, but there was one more detail:

The gradle configuration `testCompileOnly` [1] *does not* inherit from the `shadow` configuration (as evidence see [this search](https://github.com/search?q=repo%3Ajohnrengelman%2Fshadow%20extendsFrom&type=code) of the shadow repo). We must explicitly request that `shadow` dependencies are included in the compile-time class path of the tests.

This is as it should be: the things in `shadow` are things which are provided to us by our runtime environment. That's true of both the *test* runtime environment and the normal runtime environment. The Gradle Shadow plugin takes a different perspective, it suggests that `shadow` dependencies shouldn't be used in the tests at all.


[1] NB: `testCompile` does not exist but you don't get an error if you try to use it, thanks for nothing gradle.

**Comment by danking** [comment]
Alright alright jeez I can't program any more. I also needed to explicitly request that all the test and main classes from our project should be in the JAR.

**Comment by danking** [comment]
bump @ehigham

**Review by ehigham — APPROVED** [review]
If it builds and the tests run I think it's probably ok

**Pull request merged**
