### PR TITLE
Added unsafe serializers.

### PR DESCRIPTION
**Pull request by cseed**

### CODE REVIEW

**Comment by cseed** [comment]
bump

**Comment by tpoterba** [comment]
I think Wednesday is the earliest I'll be able to get to this ☹️

**Comment by cseed** [comment]
No worries.  I have a day or two at least to clean up the ordrdd2 rebase.  I might check if @danking has time.

**Comment by cseed** [comment]
Thanks Tim!

It is easy to fix the Kryo serializers, but the function we need (require) is protected, so we need to use reflection or put something in the Kryo package to access it.  Java serializers are trickier.  Best I can think of is to have a thread-local pool of something like 8KB blocks to copy to/from.

**Pull request merged**
