### PR TITLE
[query] Add EContainer

### PR DESCRIPTION
**Pull request by chrisvittal**
EContainer is a superclass of EArray and EPackedInts that has an element
type.

### CODE REVIEW

**Comment by tpoterba** [comment]
what does the additional abstraction buy us here? We've kinda gone crazy with this on ptype/type and it's gotten in the way in the past

**Comment by chrisvittal** [comment]
The representation of many of our types are structs. Put them in an array, and we get arrays of structs. So they're struct of array encoded. This lead to a complication for NDArrays as their current representation is `TStruct{..., data: TArray(elementType)}`. I need a way to get the element type of the EType for constructing the PNDArray we return when we build a decoder.

**Comment by chrisvittal** [comment]
The other solution is another match.

**Comment by tpoterba** [comment]
alright, sure. We may want to revisit as we push ahead with new etypes to make sure we have the right abstractions.

**Pull request merged**
