### PR TITLE
Support passing an authorization token to the ServiceBackend.

### PR DESCRIPTION
**Pull request by vladsaveliev**
This is useful for launching batches on behalf of other users.

### CODE REVIEW

**Comment by vladsaveliev** [comment]
#assign services

**Comment by danking** [comment]
@jigold this seems roughly fine to me, though we should make the token argument a non-underscore one on BatchClient. They should probably all be kwargs too. I'm not sure how public we consider the aioclient.

**Review by jigold — APPROVED** [review]

**Review by jigold — CHANGES_REQUESTED** [review]
See comment.

**Comment by vladsaveliev** [comment]
Thanks a lot for looking into the PR!

Made `Optional[str]`, and leaving the parameter with the underscore for this PR.

**Comment by danking** [comment]
@vladsaveliev I dismissed Jackie's review. That will make it show up in her reviewing queue in our CI system. In the future feel free to dismiss reviews if you've addressed the concerns!

**Review by jigold — APPROVED** [review]

**Comment by vladsaveliev** [comment]
Thanks you :)

Could you also make a release soon after this PR is merged, if reasonable? Would be handy to be able to try the package in our setup!

**Comment by danking** [comment]
Sure

**Comment by vladsaveliev** [comment]
@jigold and @danking, I can't see why `ci-test` is failing, unfortunately. Can you take a look?

(and I should look into setting up Hail CI in our infra as well :-))

**Comment by danking** [comment]
@vladsaveliev , we've had a bit of CI instability here which is causing tests to fail. Looks like it's merged now, I'll do a release.

**Comment by danking** [comment]
https://github.com/hail-is/hail/pull/11487

**Comment by vladsaveliev** [comment]
Thank you!!

**Pull request merged**
