### PR TITLE
[notebook] Banish 50x

### PR DESCRIPTION
**Pull request by danking**
Assigning @tpoterba since he (and cotton) have the most context to review this.

A few preliminaries:

1. I noticed the proxy headers were not quite right when you're testing this without SSL or on some non-standard port. `$host` does not include the port, `$http_host` does. `$scheme` returns `http` or `https` depending on how the user connected to gateway
2. The admin privilege check was too restrictive, if `delete_worker_pod` is called by `/new` there's no need to check admin privs
3. I realized that the timeout logic wasn't quite right because a misconfigured gateway (I was testing with a broken gateway config) will return 5xx codes, but that doesn't mean the server is alive. We probably should error here, but I'm hesitant to add new error modes so close to a tutorial.

Ok, how does this work? Basically, if the gateway cannot connect to the notebook pod, we intercept the error and redirect the user to the "create new notebook" webpage. That webpage deletes whatever remains of the users previous notebook pod & service. Here are the pieces:

1. `recursive_error_pages on;` the internet suggests that without this we cannot use `error_page` with an "internal" rule (the `@` rules are internal rules that users cannot directly access)
2. `proxy_connect_timeout` defaults to 60s which is a shit user experience if your pod dies. Honestly, I might set this to 100ms. This is all inside a datacenter.
3. `proxy_intercept_errors` permits us to use `error_page` with 5xx errors from failing to connect to the proxy

---

I tested this with a pile of hacks to deploy this into an anonymous namespace in `vdc`. I'm not ready to PR those changes, they need a clean up before others use them. Sometime next week I hope to get that in. Getting it requires some restructuring of `vdc/` and `gateway/` to be more modular.

### CODE REVIEW

**Comment by danking** [comment]
buuuuump

**Comment by danking** [comment]
sorry tim, I'm hammering you with all these :/

**Comment by tpoterba** [comment]
> I tested this with a pile of hacks to deploy this into an anonymous namespace in vdc. I'm not ready to PR those changes, they need a clean up before others use them. Sometime next week I hope to get that in. Getting it requires some restructuring of vdc/ and gateway/ to be more modular.

Oh, I read that as you weren't ready to merge this. It sounds like you aren't ready to PR the testing stuff?

**Comment by danking** [comment]
yeh, living on the edge ;)

**Pull request merged**
