### PR TITLE
Add regex match as a method on StringExpression

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by tpoterba** [comment]
That's handled in the typechecker on `StringExpression.matches` -- we don't generate `RegexMatch` AST nodes anywhere else.

However, there's still a problem that I haven't yet resolved -- it's possible to get parse errors if the string given doesn't parse to a valid 0.1-expr-language string literal. I think there might be additional unescaping going on somewhere in the python/java connector.

Still, I think we should merge this in and figure out how to solve this problem later.

**Comment by catoverdrive** [comment]
Oh! I totally didn't catch that `matches` was on `StringExpression` and so that would necessarily be a string--that makes sense.

When would the given string not parse to a valid 0.1 string literal?

**Comment by tpoterba** [comment]
It can fail due to invalid escape characters. Like strexp.matches('\d+') would fail because `'\d` is an invalid escape char.

**Comment by tpoterba** [comment]
Though this really seems like it's a problem with additional unescaping going on.

**Comment by catoverdrive** [comment]
Ah you mean problems with the regex expression. Seems reasonable.

**Pull request merged**
