### PR TITLE
[batch,pipeline] add pvc size parameter

### PR DESCRIPTION
**Pull request by jigold**

### CODE REVIEW

**Comment by konradjk** [comment]
Does it have to be in `Gi` not `G`? Otherwise interface looks good (don't know much about batch internals so can't comment on those)

**Comment by jigold** [comment]
Not sure. Couldn't quickly find a reference for valid arguments. Will keep looking.

**Comment by jigold** [comment]
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/resources.md#resource-quantities

**Comment by konradjk** [comment]
if you can't find it, then `self._storage = f'{storage.rstrip("i")}i'` seems fine to me 😄 (this is why i'm not a software engineer)

**Comment by jigold** [comment]
This will require a database change.

**Pull request merged**
