### PR TITLE
fix flatten and expandTypes

### LINKED ISSUE #4286: Table.flatten is broken
```python
hl.utils.range_table(10).key_by(x = hl.struct(a=1, b=2)).flatten().count()

Java stack trace:
java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:212)
	at is.hail.expr.ir.TableMapRows.<init>(TableIR.scala:546)
	at is.hail.table.Table.select(Table.scala:448)
	at is.hail.table.Table.flatten(Table.scala:565)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
```

Assigned patrick because this might be fixed by things he is working on

### PR DESCRIPTION
**Pull request by patrick-schultz**
fixes #4286

I was rushing to get a fix in before I leave for the weekend. `expandTypes` is now doing a scan to compute the new range bounds. A real fix would map over the range bounds, taking representations of complex types to corresponding representations of their fundamental types.

### CODE REVIEW

**Comment by tpoterba** [comment]
I think the right fix here is actually to have expand / flatten strip keys

**Comment by patrick-schultz** [comment]
Strip keys, or only expand/flatten value fields?

**Comment by tpoterba** [comment]
definitely the former, these are used almost exclusively for compatibility with spark/pandas

**Comment by tpoterba** [comment]
I also think people would be unhappy if we shuffled unnecessarily

**Pull request merged**
