### PR TITLE
[hail/ptypes] replace ir.pType with .pType2

### PR DESCRIPTION
**Pull request by akotlar**
Stacked on #7959 

Utterly fails tests

At first glance, not sure this is possible without having InferPType called from within def pType on null.

### CODE REVIEW

**Comment by tpoterba** [comment]
yeah, would not expect this to work yet.

**Comment by akotlar** [comment]
```scala
def emit(mbLike: EmitMethodBuilderLike): Code[Unit] =
          // wrapped methods can't contain uses of Recur
          useValues(mbLike.mb, ir.pType, mbLike.emit.emit(ir, env, EmitRegion.default(mbLike.emit.mb), container, None))
```

**Comment by tpoterba** [comment]
hold off on this for now, regardless. It'll put me in rebase hell with the agg refactoring I'm doing.

**Comment by akotlar** [comment]
K, wip tag added, will wait.

**Comment by akotlar** [comment]
will close, there's a more gradual way of doing this without touching InferPType and introducing merge hell for you/me

**Pull request closed without merging**
