### PR TITLE
Remove TableGroupWithinPartitions IR Node

### PR DESCRIPTION
**Pull request by johnc1231**
It's entirely expressible in python now.

### CODE REVIEW

**Comment by johnc1231** [comment]
Tests are failing, seems like the PruneDeadFields rule can change the type in a way that removes the keys? Investigating.

**Comment by tpoterba** [comment]
oops, probably something I messed up, sorry

**Comment by johnc1231** [comment]
No worries. Haven't gotten a chance to figure it out yet, but I know that when I remove the PruneDeadFields step it works, so it's definitely something in there.

**Comment by johnc1231** [comment]
Closing until I fix

**Pull request closed without merging**
