### PR TITLE
resolves #836 -- add edit links to FAQ

### LINKED ISSUE #836: The FAQ should have edit links

### PR DESCRIPTION
**Pull request by jigold**
@danking: I can't figure out why all of the edit links are clickable except for the Annotations and Exporting Data ones. They're auto-generated with the same code.

### CODE REVIEW

**Comment by danking** [comment]
@jigold I think they're "covered up" by the jump target link. I wonder if we can get rid of the negative margin and use something else?

Actually easier thing that may work: set the z-index of jump targets to -999.

**Comment by jigold** [comment]
@danking Thanks for the help! Modifying the z-index of h4 worked. Removing the empty content field worked on the FAQ page but messed up the formatting on the commands reference page.

**Comment by cseed** [comment]
What wrong with the command reference formatting?  A quick glance but I didn't see the problem.

**Comment by danking** [comment]
@jigold if there's still a problem with the formatting open a new PR, I'm gonna merge this one in because I don't see any issues.

**Pull request merged**
