### PR TITLE
added region value int, float array sum aggregators

### PR DESCRIPTION
**Pull request by cseed**

### CODE REVIEW

**Comment by catoverdrive** [comment]
These were taken out in this PR: #3535 with I think the idea to do some sort of type promotion so that the return was always the 64-bit version? @jigold is that right? If so I'll put the type conversions into Python; currently sum(int32) and sum(float32) aren't being converted to IR.

**Comment by catoverdrive** [comment]
ah, also see: http://discuss.hail.is/t/clarification-of-agg-sum-behavior/493

**Comment by jigold** [comment]
Yes, that's correct. I didn't feel strongly about this one way or the other, but I think others did.

**Comment by catoverdrive** [comment]
oh wait never mind---`array_sum`! I can't read >.>

**Comment by cseed** [comment]
I agree array_sum and sum should behave analogously.  This implements the current documented behavior for array_sum, but I will change it to promote as sum does.

**Pull request closed without merging**
