### PR TITLE
[ci] Expose batch user volumes

### PR DESCRIPTION
**Pull request by jigold**
Needed so #5866 will pass tests.

### CODE REVIEW

**Comment by danking** [comment]
When CI is testing itself, it will start pods in `test`, but `test` is missing the user secret.

```
(hail) dking@wmb16-359 # k get secrets user-jwt-vkqfw -n test       
Error from server (NotFound): secrets "user-jwt-vkqfw" not found
```

**Comment by jigold** [comment]
What's the issue with this PR?

**Comment by jigold** [comment]
Ok. @akotlar this is why the secrets need to be duplicated in test.

**Comment by danking** [comment]
Sorry, I waffled a bit and was worried it would merge before I could request changes, then unconvinced myself, then re-convinced myself and was worried it would merge again.

**Comment by jigold** [comment]
Should be good now.

**Pull request merged**
