### PR TITLE
Add Brandon Franco to dev list

### PR DESCRIPTION
**Pull request by danking**
@cseed can you confirm that this is the only place I need to add Brandon for him to get merging into master?

### CODE REVIEW

**Comment by akotlar** [comment]
We'll also need to whitelist him, have him register an account with auth0, and then create the jwt accouterments. Would be nice to automate that at some point.

**Comment by danking** [comment]
@akotlar where are the other whitelists? I'll have him log into auth0 now.

**Comment by akotlar** [comment]
Stored under notebook-secrets : data.authorized_users

**Comment by akotlar** [comment]
I separately need to add him to the users.yml secrets (users: data["users.yml"]) which contains the resource definition. I need to PR the merger of these

**Comment by akotlar** [comment]
Notebook will need to be restarted for the secret to be re-read

**Pull request merged**
