### PR TITLE
[0.1] Allow empty strings in BGEN reader

### PR DESCRIPTION
**Pull request by jigold**

### CODE REVIEW

**Comment by tpoterba** [comment]
yeah, CI is definitely broken for 0.1. Let's chat today about possible strategies

**Comment by jigold** [comment]
@tpoterba Can you double check the changes? I removed the docs-2.0.2 requirement since it wasn't doing anything. Once this goes in, we can rerun all of the other 0.1 PRs.

**Comment by tpoterba** [comment]
passing??? omg!

**Comment by tpoterba** [comment]
thanks for taking the time to fix 0.1!

**Pull request merged**
