### PR TITLE
Added KeyTable conversion to VariantDataset, removed keys on import, …

### PR DESCRIPTION
**Pull request by tpoterba**
…added optimized keyBy in scala / python

### CODE REVIEW

**Comment by tpoterba** [comment]
Also removed ImportAnnotationsTable

**Comment by jbloom22** [comment]
when you rebase, add this method as another way to create a vds on the VariantDateset class documentation in dataset.py

**Comment by johnc1231** [comment]
Addresses some of #1505

**Comment by jigold** [comment]
The integration test is failing. Otherwise, looks good.

**Comment by jigold** [comment]
Sorry, was actually a docs failure. I'll see if I can figure out what it is.

**Comment by tpoterba** [comment]
I can't update that until this goes in, though.  Otherwise everything else will fail

**Pull request merged**
