### PR TITLE
add parallelized write block matrices functions

### PR DESCRIPTION
**Pull request by cseed**
added `export_block_matrices` and `block_matrices_tofiles` to `experimental`, parallel versions of `BlockMatrix.export` and `BlockMatrix.tofile`, in the style of `write_matrix_tables`.

### CODE REVIEW

**Comment by tpoterba** [comment]
@cseed meant to be one of the other daniels? 😉

**Comment by cseed** [comment]
Thanks!  Too many Daniels!

**Comment by cseed** [comment]
@daniel-goldstein bump.  Jacob and Qingbo are waiting on this for an analysis.

**Comment by daniel-goldstein** [comment]
Whoops, had nearly finished this this morning before I was sidetracked. Thanks for the reminder.

**Comment by julirsch** [comment]
Would it be possible to have something similar for regular old Tables? For example, to export a Table to multiple .tsv (in parallel)? I think a major use case would be to write a separate tsv for all unique values of a specific column.

Thoughts, @danking @tpoterba?

**Comment by tpoterba** [comment]
I wrote this to support another project in Ben's group: https://hail.is/docs/0.2/experimental.html?highlight=export_entries_b#hail.experimental.export_entries_by_col

**Comment by tpoterba** [comment]
oh, I see. Separate tsv for all unique values...

Yeah, this is something we definitely want. We've discussed the ability to do 

`ht.group_by`, and then do any of the standard operations on the grouped table -- annotate, filter, aggregate, scan, write, export, etc. It's definitely going to be a while before we get here though!

**Comment by julirsch** [comment]
@tpoterba I think we found a work around!

One last thing -- the `delimiter` argument is v. useful. Would it be possible to also block gzip / gzip the `.tsv` outputs?

**Comment by tpoterba** [comment]
Can you be a bit more specific? Are you talking about Table `export`? I think if you use a `.bgz` folder name with one of the parallel modes, the individual files will be block gzipped, but may not have the right extension.

**Comment by julirsch** [comment]
Yes, sorry. Would it be possible to add an argument to `export_block_matrices` to gzip (or block gzip) each output `.tsv` file?

**Comment by tpoterba** [comment]
oh, yeah, definitely, that's easy. Can do it now.

**Comment by tpoterba** [comment]
fixed here: #6349

**Pull request merged**
