### PR TITLE
[query/service] implement parse_vcf_metadata

### PR DESCRIPTION
**Pull request by danking**

### CODE REVIEW

**Comment by danking** [comment]
No new tests are passing because we need to implement VCF export first.

**Comment by tpoterba** [comment]
I have another proposal here to delete this endpoint entirely and replace it with an IR function

**Comment by chrisvittal** [comment]
I'm personally in favor of this change adding a switch to the protocol. It avoids running the compiler.

**Review by tpoterba — APPROVED** [review]
I can't really reject a working fix. I think in the future I might want to implement this as an IR function because we could delete all of this code, but 🤷

**Pull request merged**
