### PR TITLE
remove ibd-prune and tests

### PR DESCRIPTION
**Pull request by danking**
@jigold identified `ibd_prune` as one of the slowest parts of the python doc test.

This method is simply not effective. Users should use `pc_relate` or `ibd` in conjunction with `KeyTable.maximal_independent_set`. I didn't reimplement `ibd_prune` in terms of them simply to save time and because getting master builds going fast is important when we have limited build agents.

### CODE REVIEW

**Comment by jigold** [comment]
The other option is to add `# doctest: +SKIP` next to any `ibd_prune` command in the docs.

**Comment by danking** [comment]
Since this approach is too slow for anyone's use case, I'm inclined to just remove it.

**Comment by johnc1231** [comment]
Sorry about this. GraphX was not a good solution.

**Comment by danking** [comment]
@johnc1231 oh john this is definitely not your fault :P I lead you astray

**Pull request merged**
