### PR TITLE
Release 0.2.66

### PR DESCRIPTION
**Pull request by jigold**
Stacked on #10397 and #10418

### CODE REVIEW

**Comment by jigold** [comment]
cc: @johnc1231 @tpoterba

**Review by danking — CHANGES_REQUESTED** [review]
You gotta update the Hail change log too, this is the only one I see:

#10398 CHANGELOG: Add BlockMatrix.to_ndarray

You can find this with `git log 0.2.65..hi/main`  and search for CHANGELOG. I also usually check for other commits that maybe *should* have a changelog entry.

**Comment by jigold** [comment]
I was going to let John and Tim fill those in.

**Comment by johnc1231** [comment]
I'll fill in no worries.

**Comment by johnc1231** [comment]
Added the two I know about, signing off for the day now though.

**Comment by tpoterba** [comment]
seems fine to me!

**Review by danking — APPROVED** [review]

**Pull request merged**
