### PR TITLE
[hail][feature] Added scatter options to QQ plots.

### PR DESCRIPTION
**Pull request by lfrancioli**

### CODE REVIEW

**Comment by tpoterba** [comment]
@lfrancioli `Slope` was introduced to bokeh in a later version. I'll go through and update some of our python dependencies when I get a chance this week, which should mean this can just go in at that point.

**Comment by lfrancioli** [comment]
Great! Yeah, I had noticed that this was a version problem.

**Comment by tpoterba** [comment]
rebased, hopefully will pass and go in! 🤞

**Comment by tpoterba** [comment]
boom!

**Comment by lfrancioli** [comment]
woohoo! Thanks Tim!

**Pull request merged**
