### PR TITLE
Add "describe" as a method on Struct / StructExpression

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by patrick-schultz** [comment]
Feel free to push back, but having two functions with almost identical implementations really smells. Is there a reasonable place to put the factored out common function?

**Comment by tpoterba** [comment]
don't merge yet, I intend to address your comment

**Comment by tpoterba** [comment]
I tried to abstract this method call and it ended up looking much worse. I deleted/cleaned up some code so there's not as much duplication now.

**Comment by patrick-schultz** [comment]
This is fine, go ahead and merge. Sorry for making a fuss on such a tiny PR, I'm just sensitive to code duplication.

**Comment by tpoterba** [comment]
no need to apologize for this! there was extra code hanging around that just added noise, so more work was definitely required. It's also good for my own development to slow down and be more attentive to that kind of thing sometimes :)

**Pull request merged**
