### PR TITLE
[hailtop/utils] Allow OnlineBoundedGather2.call to return values

### PR DESCRIPTION
**Pull request by chrisvittal**
This was breaking RouterFS.ls

Tested in the export_vcf lowering branch

### CODE REVIEW

**Comment by chrisvittal** [comment]
I have no idea why `test_range_matrix_table_n_lt_partitions` is failing on this branch. Running it locally hangs.

**Review by danking — APPROVED** [review]

**Comment by chrisvittal** [comment]
Why won't this merge?

**Comment by danking** [comment]
I retried

**Comment by danking** [comment]
My index bgen PR won the race, but this should be next.

**Comment by danking** [comment]
a test job got preempted so that added ~20 minutes to total test time

**Comment by danking** [comment]
Ugh, and in Azure, the batch-driver was too slow coming alive and it failed the build. Retried.

**Pull request merged**
