### PR TITLE
Revert "Revert "Cpp5 - support for Scala-generated C++ (#4211)" (#4239)"

### PR DESCRIPTION
**Pull request by danking**
This reverts commit e9e8a40bb4f0c2337e5088c26186a4da4948bed2.

### CODE REVIEW

**Comment by danking** [comment]
cc: @rcownie @cseed This will restore cpp5, when we're confident that it will work on dataproc.

**Comment by cseed** [comment]
I haven't looked into it, but it looks like the libhail for cpp5 got built differently than the other prebuilt .so in a way that's incompatible with dataproc.  If we rebuild it on a dataproc head node, for example, it should probably be good to go.

Before we do that, I would like to see dataproc testing get set up ... which of course @danking is already on: https://github.com/hail-is/hail/pull/4241.  Nice!

**Comment by catoverdrive** [comment]
@danking looks like this is passing tests on the newest version of cloudtools.

**Comment by danking** [comment]
@catoverdrive suspicious. 1.1.16 doesn't include your changes, afaik.

**Comment by catoverdrive** [comment]
It's testing with the correct image, though?

**Comment by danking** [comment]
The log shows cloud tools 1.1.16 was using 1.2-deb9 for the cluster image and I can confirm cloud tools 1.2.0 does as well.

**Comment by cseed** [comment]
@danking Tests are passing.  What's the problem?

Strange, cloudtools is showing 2.0.0 available, but pip is installing 1.1.6.

```
+ pip search cloudtools
cloudtools (2.0.0)           - Collection of utilities for working on the Google Cloud Platform.
datawire-cloudtools (0.2.6)  - Datawire Cloud Tools
cloudseed (0.0.1)            - Cloudtools
+ pip install -U cloudtools
Collecting cloudtools
  Downloading https://files.pythonhosted.org/packages/47/f1/bec895151ea74b2117c66620840e9a86436b376927b557b080289b61f754/cloudtools-1.1.16-py3-none-any.whl
Installing collected packages: cloudtools
Successfully installed cloudtools-1.1.16
```

Ah,  cloudtools 1.2.0 and 2.0.0 were set up as python 2 packages, see https://pypi.org/simple/cloudtools/:

```
cloudtools-1.1.16-py2-none-any.whl
cloudtools-1.1.16-py3-none-any.whl
cloudtools-1.2.0-py2-none-any.whl
cloudtools-2.0.0-py2-none-any.whl
```

1.1.16 is set up for both.  @liameabbott I assume we're only supporting Python 3?

**Comment by tpoterba** [comment]
The problem is that `gsutil` only works with python2. So you'll need a python2 binary available as well

**Comment by danking** [comment]
@cseed, details below, exec summary: a series of confusions and confusing interfaces lead to cloud tools deployment issues. The resolution is to fix the deploy script to always deploy `cloudtools` for python 2 and 3 (because *it* works with both). Users will need `python2` somewhere on their PATH, but `gsutil` will guide them through that, i.e. not our problem.

There is no problem except that I cannot approve my own PR. I noticed @catoverdrive wasn't actually assigned, so it wasn't in her scorecard queue.

---

There was a bit of confusion around this recently that @catoverdrive figured out. So, `gsutil` only supports `python2`, but it's happy to search through your path for a variety of binaries with suggestive names until it finds a valid python 2.x binary. `cloudtools` itself works with any version of python (there was a recent breaking change in the release of python 3.7, which broke cloud tools [but that's been resolved in an open PR](https://github.com/Nealelab/cloudtools/pull/91/files#diff-7decff7c08c5270a32982ea34483b8cbR11)).

Now, wrt PYPI, @catoverdrive discovered that the version of python you use to run `setup.py bdist_wheel` determines which version of python is deployed. This is rather confusing and, since none (or many?) of us did not know this, we accidentally uploaded a variety of [cloud tools versions on pypi, as you've noted](https://pypi.org/simple/cloudtools/).

There was some earlier confusion wherein I thought we should only support `python2`, but that was a mistake on my end. We should support both versions, and when the user tries to start a cluster, `gsutil` will provide an error message guiding them to install `python2`.

**Pull request merged**
