### PR TITLE
[hail] extra assert in EType.fromTypeAndAnalysis

### PR DESCRIPTION
**Pull request by danking**

### CODE REVIEW

**Comment by danking** [comment]
I'm not sure this is kosher, but I think it is.

**Comment by danking** [comment]
I'm not sure this is kosher, but I think it is.

**Review by tpoterba — DISMISSED** [review]

**Comment by tpoterba** [comment]
er, need to fix size

**Comment by danking** [comment]
I added a size to RStruct.

**Review by tpoterba — APPROVED** [review]

**Pull request merged**
