### PR TITLE
[hail] die maven die

### PR DESCRIPTION
**Pull request by danking**

### CODE REVIEW

**Comment by cseed** [comment]
@tpoterba did you take this over from @danking while he's away?  I noticed you pushed a commit.

**Comment by tpoterba** [comment]
I fixed something that was definitely broken, and then added scala dependencies that didn't fix scala being missing.

**Comment by cseed** [comment]
@catoverdrive @tpoterba We should probably pick one person to take this over so we don't have duplicate effort with multiple people making/pushing fixes.

**Comment by tpoterba** [comment]
you don't buy into the hot potato style of software development?

**Comment by cseed** [comment]
I prefer the volley of arrows model: https://giphy.com/gifs/hero-jet-li-arrows-IqxIYOQCIrtXq

**Comment by tpoterba** [comment]
go go go

**Pull request merged**
