### PR TITLE
[batch] add worker local SSD and PD SSD options to globals

### PR DESCRIPTION
**Pull request by cseed**
Expose in front end
Currently unused

### CODE REVIEW

**Comment by cseed** [comment]
In addition to the main change:
 - I made all the global configuration options editable now that we have flexible billing,
 - We now check the worker cores and standing worker cores against the worker type to make sure they are valid (there is no highmem/highcpu-1).

**Comment by jigold** [comment]
The reason we didn't expose the other parameters was what if we had 16 core jobs waiting to be scheduled and then we changed the worker pool size to 4 cores.

**Comment by jigold** [comment]
It looks fine other than the comment I made above.

**Comment by cseed** [comment]
> The reason we didn't expose the other parameters was what if we had 16 core jobs waiting to be scheduled and then we changed the worker pool size to 4 cores.

Yep.  Let's call that admin operator error and let's not do that.  The other reason was we had hardcoded the billing computation in the code, but that's fixed now.  But it is hardcoded in the documentation, so we still shouldn't really be changing any of these settings (I see this mainly for the second instance at this point).

Separately, we should decouple the billing from the details of the implementation so we get a bit more flexibility on the backend in the main instance, as we've discussed.

I'm OK with this.

**Pull request merged**
