### PR TITLE
[query] re-enable the statgen tests

### PR DESCRIPTION
**Pull request by danking**
Compare to a deploy job wherein the string "test_statgen.py" does not appear: https://ci.hail.is/batches/6942543/jobs/58 .

### CODE REVIEW

**Comment by danking** [comment]
This was introduced last month https://github.com/hail-is/hail/blame/main/hail/python/test/hail/methods/test_statgen.py#L15-L17 . The tests all appear to still pass.

**Review by chrisvittal — APPROVED** [review]

**Comment by danking** [comment]
@patrick-schultz do we expect that after the randomness PR we need to update random tests (in this case, balding Nichols) because the sequence of generated numbers has changed?

(Context: it appears the randomness PR accidentally disabled the test_statgen.py tests which included a balding Nichols test)

**Comment by danking** [comment]
the test:
```
___________________ Tests.test_balding_nichols_model_phased ____________________
[gw1] linux -- Python 3.7.15 /usr/bin/python3

self = <test.hail.methods.test_statgen.Tests testMethod=test_balding_nichols_model_phased>

    def test_balding_nichols_model_phased(self):
        bn_ds = hl.balding_nichols_model(1, 5, 5, phased=True)
        assert bn_ds.aggregate_entries(hl.agg.all(bn_ds.GT.phased)) == True
        actual = bn_ds.GT.collect()
        expected = [
            hl.Call(a, phased=True)
            for a in [
                    [0, 1], [0, 0], [0, 1], [0, 0], [1, 0],
                    [1, 1], [0, 1], [1, 1], [0, 0], [0, 1],
                    [1, 0], [0, 0], [1, 0], [0, 0], [0, 0],
                    [1, 1], [1, 1], [1, 0], [0, 1], [1, 1],
                    [1, 1], [1, 1], [1, 1], [1, 1], [1, 1]]]
>       assert actual == expected
E       assert [Call(alleles=[0, 0], phased=True), Call(alleles=[0, 0], phased=True), Call(alleles=[0, 0], phased=True), Call(alleles=[0, 0], phased=True), Call(alleles=[0, 0], phased=True), Call(alleles=[0, 0], phased=True), Call(alleles=[0, 0], phased=True), Call(alleles=[0, 0], phased=True), Call(alleles=[0, 0], phased=True), Call(alleles=[0, 0], phased=True), Call(alleles=[1, 0], phased=True), Call(alleles=[1, 0], phased=True), Call(alleles=[1, 1], phased=True), Call(alleles=[1, 0], phased=True), Call(alleles=[0, 1], phased=True), Call(alleles=[1, 1], phased=True), Call(alleles=[1, 1], phased=True), Call(alleles=[1, 1], phased=True), Call(alleles=[1, 1], phased=True), Call(alleles=[1, 1], phased=True), Call(alleles=[1, 1], phased=True), Call(alleles=[1, 1], phased=True), Call(alleles=[1, 1], phased=True), Call(alleles=[1, 1], phased=True), Call(alleles=[1, 1], phased=True)] == [Call(alleles=[0, 1], phased=True), Call(alleles=[0, 0], phased=True), Call(alleles=[0, 1], phased=True), Call(alleles=[0, 0], phased=True), Call(alleles=[1, 0], phased=True), Call(alleles=[1, 1], phased=True), Call(alleles=[0, 1], phased=True), Call(alleles=[1, 1], phased=True), Call(alleles=[0, 0], phased=True), Call(alleles=[0, 1], phased=True), Call(alleles=[1, 0], phased=True), Call(alleles=[0, 0], phased=True), Call(alleles=[1, 0], phased=True), Call(alleles=[0, 0], phased=True), Call(alleles=[0, 0], phased=True), Call(alleles=[1, 1], phased=True), Call(alleles=[1, 1], phased=True), Call(alleles=[1, 0], phased=True), Call(alleles=[0, 1], phased=True), Call(alleles=[1, 1], phased=True), Call(alleles=[1, 1], phased=True), Call(alleles=[1, 1], phased=True), Call(alleles=[1, 1], phased=True), Call(alleles=[1, 1], phased=True), Call(alleles=[1, 1], phased=True)]
E         At index 0 diff: Call(alleles=[0, 0], phased=True) != Call(alleles=[0, 1], phased=True)
E         Full diff:
E           [
E         -  Call(alleles=[0, 1], phased=True),
E            Call(alleles=[0, 0], phased=True),
E         -  Call(alleles=[0, 1], phased=True),
E         ?                   ^
E         +  Call(alleles=[0, 0], phased=True),
E         ?                   ^
E         +  Call(alleles=[0, 0], phased=True),
E         +  Call(alleles=[0, 0], phased=True),
E         +  Call(alleles=[0, 0], phased=True),
E         +  Call(alleles=[0, 0], phased=True),
E         +  Call(alleles=[0, 0], phased=True),
E         +  Call(alleles=[0, 0], phased=True),
E         +  Call(alleles=[0, 0], phased=True),
E            Call(alleles=[0, 0], phased=True),
E            Call(alleles=[1, 0], phased=True),
E         -  Call(alleles=[1, 1], phased=True),
E         -  Call(alleles=[0, 1], phased=True),
E         -  Call(alleles=[1, 1], phased=True),
E         -  Call(alleles=[0, 0], phased=True),
E         -  Call(alleles=[0, 1], phased=True),
E            Call(alleles=[1, 0], phased=True),
E         -  Call(alleles=[0, 0], phased=True),
E         -  Call(alleles=[1, 0], phased=True),
E         -  Call(alleles=[0, 0], phased=True),
E         -  Call(alleles=[0, 0], phased=True),
E         -  Call(alleles=[1, 1], phased=True),
E            Call(alleles=[1, 1], phased=True),
E            Call(alleles=[1, 0], phased=True),
E            Call(alleles=[0, 1], phased=True),
E            Call(alleles=[1, 1], phased=True),
E            Call(alleles=[1, 1], phased=True),
E            Call(alleles=[1, 1], phased=True),
E            Call(alleles=[1, 1], phased=True),
E            Call(alleles=[1, 1], phased=True),
E            Call(alleles=[1, 1], phased=True),
E         +  Call(alleles=[1, 1], phased=True),
E         +  Call(alleles=[1, 1], phased=True),
E         +  Call(alleles=[1, 1], phased=True),
E         +  Call(alleles=[1, 1], phased=True),
E           ]

test/hail/methods/test_statgen.py:1642: AssertionError
------------------------------ Captured log call -------------------------------
WARNING  backend.service_backend:java.py:186 To ensure reproducible randomness across Hail sessions, you must set the "global_seed" parameter in hl.init(), in addition to the local seed in each random function.
INFO     backend.service_backend:java.py:190 balding_nichols_model: generating genotypes for 1 populations, 5 samples, and 5 variants...
INFO     batch_client.aioclient:aioclient.py:741 created batch 859
INFO     batch_client.aioclient:aioclient.py:758 updated batch 859
INFO     batch_client.aioclient:aioclient.py:758 updated batch 859
INFO     batch_client.aioclient:aioclient.py:758 updated batch 859

```

**Comment by patrick-schultz** [comment]
I did update all the random tests in the randomness PR, if I disable any it was definitely unintentional.

**Comment by patrick-schultz** [comment]
I remember having to fix the balding_nichols test multiple times. It's possible there's some issue with it I didn't properly diagnose.

**Comment by danking** [comment]
I think the answer to my question is yes: the new RNG setup may produce a different sequence of number from the old RNG setup, ergo not surprising that the genotypes generated by BN changes from old RNG setup to new RNG setup. I'll just copy in the newly generated GTs and push up.

**Comment by danking** [comment]
Mmm. Nope, I'm wrong. Indeed it seems like the seed is not getting reset properly.

**Comment by danking** [comment]
I can't replicate locally with 
```
make -C hail pytest-qob NAMESPACE=default PYTEST_ARGS='-k "test_balding_nichols_model_phased or test_balding_nichols_stats"'  
```

**Comment by danking** [comment]
wtf. It passes in azure, passes on my laptop under a number of configurations. passes in google on everything but QoB. What's going on

**Comment by danking** [comment]
I marked the balding Nichols test as failing for now because its far more important that we actually run the statgen tests.

**Comment by danking** [comment]
??? It passed (ergo failed the expect-to-fail marker). I removed it. We'll what happens.

**Pull request merged**
