### PR TITLE
[query] Table.write_many

### PR DESCRIPTION
**Pull request by danking**
CHANGELOG: Teach `Table` to `write_many`, which writes one table per provided field.

### CODE REVIEW

**Comment by danking** [comment]
It occurs to me you should reject this until I write a non-lowered execution path since we can't assume a lowered execution is possible yet.

**Comment by danking** [comment]
bump @patrick-schultz, I've another branch that depends on this.

**Comment by danking** [comment]
@tpoterba I forget exactly the conclusion from our last conversation about whether or not new functionality should implement a non-lowered path. This PR's new reader raises an exception if you try to interpret it.

**Comment by patrick-schultz** [comment]
@danking Sorry, from your last comment I thought you wanted to wait on a non-lowered implementation. I looked over this last week and everything looked good. I'll give it a last pass now.

**Review by patrick-schultz — APPROVED** [review]

**Pull request merged**
