### PR TITLE
[compiler] Remove `FastIndexedSeq`

### PR DESCRIPTION
**Pull request by ehigham**
Its functionality is duplicated in `FastSeq`. End the verbosity.

### CODE REVIEW

**Review by ehigham — COMMENTED** [review]
+ ran optimise imports on all affected files

**Comment by ehigham** [comment]
Adding zulip thread for posterity:

Patrick Schultz (he/him)
[12:38 pm](https://hail.zulipchat.com/#narrow/stream/123011-Hail-Query-Dev/topic/FastIndexedSeq/near/392155787)
Ah, that's what I thought, originally FastSeq returned a Seq: https://github.com/hail-is/hail/commit/be415a850eb145c69a830e485d3192331799f14f#diff-75be823f33bdb7bc10ab85e3b954c91a4a7bd48176c2a39f2e3d2e7f7e30fab4

daniel king (he/him)
[12:40 pm](https://hail.zulipchat.com/#narrow/stream/123011-Hail-Query-Dev/topic/FastIndexedSeq/near/392156010)
huh, I wonder when/why that changed

Patrick Schultz (he/him)
[12:40 pm](https://hail.zulipchat.com/#narrow/stream/123011-Hail-Query-Dev/topic/FastIndexedSeq/near/392156041)
[toFastSeq](https://github.com/hail-is/hail/blob/995994c862b93406bc4b5fc37c7f022f7426cd52/hail/src/main/scala/is/hail/utils/richUtils/RichIterator.scala#L145) still does. If you make this change, you should get rid of toFastIndexedSeq too

[ 12:41 pm](https://hail.zulipchat.com/#narrow/stream/123011-Hail-Query-Dev/topic/FastIndexedSeq/near/392156191)
daniel king (he/him) [said](https://hail.zulipchat.com/#narrow/stream/123011-Hail-Query-Dev/topic/FastIndexedSeq/near/392156010):

huh, I wonder when/why that changed

[a month later](https://github.com/hail-is/hail/commit/e2458973ad2bb9b065a56f480e986554b40eed79#diff-75be823f33bdb7bc10ab85e3b954c91a4a7bd48176c2a39f2e3d2e7f7e30fab4), not clear why

**Review by patrick-schultz — CHANGES_REQUESTED** [review]
Can you get `toFastIndexedSeq` on `RichIterator` too?

**Review by patrick-schultz — APPROVED** [review]

**Comment by ehigham** [comment]
> Could you also follow up by adding whatever SHA this ends up being to `.git-blame-ignore-revs`?

https://github.com/hail-is/hail/pull/13684

**Pull request merged**
