### PR TITLE
fixed up statgen typechecks and parameter descriptions

### PR DESCRIPTION
**Pull request by jbloom22**

### CODE REVIEW

**Comment by jbloom22** [comment]
addresses #3113

**Comment by tpoterba** [comment]
I don't like this solution, I think that they it should be float64 and things should just convert to that.

**Comment by tpoterba** [comment]
I don't like this solution, I think that they it should be float64 and things should just convert to that.

**Comment by tpoterba** [comment]
sorry for the double post. This is very related to the larger expr + typecheck picture I've been thinking about, let's talk about it this afternoon.

**Comment by jbloom22** [comment]
Sounds good, let's talk. Here I'm just fixing the incorrect type checks and docs in the current framework. Do you think it's not worth it?

**Comment by tpoterba** [comment]
oops, didn't mean to close.

**Pull request merged**
