### PR TITLE
[query] Fix PartitionZippedNativeReader

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by johnc1231** [comment]
Is there a test that catches this?

**Comment by tpoterba** [comment]
yeah, going to add one, that's why I haven't assigned.

**Comment by tpoterba** [comment]
this is necessary to run linear_regression_rows_nd with HAIL_DEV_LOWER=1

**Comment by tpoterba** [comment]
I was surprised to see this didn't fail by fixing some fails_local_backend tests. It turns out that we're writing out invalid files with the lowered matrix writer:
```
    def test_indexed_read(self):
        mt = hl.utils.range_matrix_table(2000, 100, 10)
        f = new_temp_file(extension='mt')
        mt.write(f)
        mt2 = hl.read_matrix_table(f, _intervals=[
            hl.Interval(start=150, end=250, includes_start=True, includes_end=False),
            hl.Interval(start=250, end=500, includes_start=True, includes_end=False),
        ])
        self.assertEqual(mt2.n_partitions(), 2)
        self.assertTrue(mt.filter_rows((mt.row_idx >= 150) & (mt.row_idx < 500))._same(mt2))

        mt2 = hl.read_matrix_table(f, _intervals=[
            hl.Interval(start=150, end=250, includes_start=True, includes_end=False),
            hl.Interval(start=250, end=500, includes_start=True, includes_end=False),
        ], _filter_intervals=True)
        self.assertEqual(mt2.n_partitions(), 3)
        self.assertTrue(mt.filter_rows((mt.row_idx >= 150) & (mt.row_idx < 500))._same(mt2))

E               Java stack trace:
E               is.hail.utils.HailException: `intervals` specified on an unindexed matrix table.
E               This matrix table was written using an older version of hail
E               rewrite the matrix in order to create an index to proceed
E               	at is.hail.utils.ErrorHandling$class.fatal(ErrorHandling.scala:11)
E               	at is.hail.utils.package$.fatal(package.scala:77)
E               	at is.hail.expr.ir.MatrixNativeReader$.apply(MatrixIR.scala:166)
E               	at is.hail.expr.ir.MatrixNativeReader$.fromJValue(MatrixIR.scala:184)
...
```

**Comment by tpoterba** [comment]
I think we should just merge this, so we can do more read testing until the writes are fixed.

**Review by johnc1231 — APPROVED** [review]

**Pull request merged**
