### PR TITLE
[dependabot] omnibus of python updates part deux

### PR DESCRIPTION
**Pull request by danking**
- [dependabot/pip/hail/python/decorator-lt-6](/hail-is/hail/tree/dependabot/pip/hail/python/decorator-lt-6)
- [dependabot/pip/hail/python/pytest-xdist-2.5.0](/hail-is/hail/tree/dependabot/pip/hail/python/pytest-xdist-2.5.0)
- [dependabot/pip/hail/python/sphinx-rtd-theme-1.0.0](/hail-is/hail/tree/dependabot/pip/hail/python/sphinx-rtd-theme-1.0.0)
- [dependabot/pip/hail/python/azure-identity-1.8.0](/hail-is/hail/tree/dependabot/pip/hail/python/azure-identity-1.8.0)
- [dependabot/pip/hail/python/curlylint-0.13.0](/hail-is/hail/tree/dependabot/pip/hail/python/curlylint-0.13.0)
- [dependabot/pip/hail/python/dev/pre-commit-2.17.0](/hail-is/hail/tree/dependabot/pip/hail/python/dev/pre-commit-2.17.0)
- [dependabot/pip/hail/python/dev/curlylint-0.13.0](/hail-is/hail/tree/dependabot/pip/hail/python/dev/curlylint-0.13.0)
- [dependabot/pip/hail/python/dev/pytest-xdist-2.5.0](/hail-is/hail/tree/dependabot/pip/hail/python/dev/pytest-xdist-2.5.0)
- [dependabot/pip/hail/python/dev/mypy-0.931](/hail-is/hail/tree/dependabot/pip/hail/python/dev/mypy-0.931)

Merge remote-tracking branches 'hi/dependabot/pip/hail/python/decorator-lt-6', 'hi/dependabot/pip/hail/python/pytest-xdist-2.5.0', 'hi/dependabot/pip/hail/python/sphinx-rtd-theme-1.0.0', 'hi/dependabot/pip/hail/python/azure-identity-1.8.0', 'hi/dependabot/pip/hail/python/curlylint-0.13.0', 'hi/dependabot/pip/hail/python/dev/pre-commit-2.17.0', 'hi/dependabot/pip/hail/python/dev/curlylint-0.13.0', 'hi/dependabot/pip/hail/python/dev/pytest-xdist-2.5.0' and 'hi/dependabot/pip/hail/python/dev/mypy-0.931' into HEAD

### CODE REVIEW

**Comment by danking** [comment]
Failing due to some mypy silliness but only in the pip installed images. Need to somehow modify this to make sure we have all appropriate stubs available and/or ignore missing stubs?

**Comment by daniel-goldstein** [comment]
This is kind of an annoying problem to have because these pip installed versions are frozen in time. I feel like these steps are either redundant (nothing has changed), or will fail because we've updated the checks to improve on what we had at last release.

What do these steps really do for us?

**Comment by daniel-goldstein** [comment]
@johnc1231 Do you have a preference on how we fix this issue? I'd prefer not to manually edit the pip package just to get the test passing, and I'm questioning the value of those checks to begin with.

**Comment by johnc1231** [comment]
The azure check_hail issue? I'm not sure why we are even checking files that we didn't write?

**Comment by johnc1231** [comment]
We should not be linting already released hail, that's dumb. Where do we do that?

**Comment by daniel-goldstein** [comment]
Oh grrr, the current build is extra borked because a minor version bump in the azure blob storage library broke.


Oh I think I totally misunderstood the "pip-installed images".  [here](https://ci.hail.is/batches/774665/jobs/63) is the job I was initially confused about. Not clear why in that batch only the pip-installed hail failed the lint and not the `check_hail` step

**Comment by daniel-goldstein** [comment]
Oh goodness. I need to think about what we actually want to do here

**Comment by danking** [comment]
Let's crash compilers team meeting this week to chat mypy. Services team could ignore the cookbooks directory for mypy purposes; however, the wealth of not-quite-right types makes me think that we should either not have types in hail or enforce mypy.

**Comment by danking** [comment]
I'm closing this until after March 28th. Bigger fish to fry

**Pull request closed without merging**
