### PR TITLE
push-based iteration for TableIR code generation

### PR DESCRIPTION
**Pull request by catoverdrive**

### CODE REVIEW

**Comment by catoverdrive** [comment]
@cseed @patrick-schultz this is what I currently have, if y'all want to take a look and comment.

**Comment by danking** [comment]
should this have an assigned reviewer, or are you just sharing code with others?

**Comment by patrick-schultz** [comment]
Pretty sure she's just sharing for now.

**Comment by patrick-schultz** [comment]
I wouldn't get to it until January either.

**Comment by catoverdrive** [comment]
Closing this stack of PRs. As we discussed, I'll reopen once they're rewritten on top of the SparkBackend stuff.

**Pull request closed without merging**
