### PR TITLE
Fix get / [] docs

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by jbloom22** [comment]
Typos here "Return the value for ``k``, or throw an exception if the key is found."

**Comment by tpoterba** [comment]
Fixed your comment and a bunch more.

**Comment by jbloom22** [comment]
Shouldn't it be *missing*, not found?

"Returns the value for ``k``, or throws an exception if the key is found."

**Comment by tpoterba** [comment]
Missing means something specific. Meant to write "not found"

**Pull request merged**
