### PR TITLE
[query/streams] port stream producers, delete old EmitStream

### PR DESCRIPTION
**Pull request by patrick-schultz**
Stacked on #8204.

This PR finishes the migration to the new EmitStream. It implements all the stream producer nodes: NA, StreamRange, ToStream, MakeStream, ReadPartition, and In (where the function argument is a `Iterator[RegionValue]`). With that, the old EmitStream is no longer used.

cc @cseed

### CODE REVIEW

**Comment by cseed** [comment]
Great!  I think you should focus on the other IR nodes needed for lowering: https://github.com/hail-is/hail/issues/8137.  Once this goes in, I'll look at ripping out joinpoint for my Code[_] hacking and let you know if I need any help.  Thanks @patrick-schultz!

**Comment by patrick-schultz** [comment]
I figured we'd want memory management in place before starting to lower tables to streams, but I'm open to working on those in either order.

**Comment by cseed** [comment]
Oh, yes, I forgot about that, you're quite right.

**Comment by tpoterba** [comment]
I'm waiting for the parent to go in before I review

**Comment by tpoterba** [comment]
can you rebase?

**Comment by cseed** [comment]
Holy shit, last one!  Great work, @patrick-schultz, very exciting!

**Pull request merged**
