### PR TITLE
[hail] Add pom.xml for Maven

### PR DESCRIPTION
**Pull request by jigold**
To make uber jar: `mvn assembly:single`

`compile` automatically runs `make` for the NativeLib stuff.
`clean` automatically runs `make clean` for NativeLib
Not sure if I needed to incorporate `nativeLibTest` or `nativeLibPrebuilt`.

Added two test configurations. One is for all tests and the other is for the set of tests with HAIL_ENABLE_CPP_CODEGEN=1.

I double checked the Python tests pass with the uber jar.

The test output doesn't have the nice formatting that we have in Gradle. Would be some work with listeners and reporters to do that: http://maven.apache.org/surefire/maven-surefire-plugin/examples/testng.html#

There also isn't the `check` input and some other bells and whistles we have in Gradle.

I had to add `com.google.inject:guice` to get rid of some compile warnings with the test-jar.

Let me know if there's other things to add/enable or if this is good enough for ci2. We should probably add some CI tests for this in a makefile somewhere.

### CODE REVIEW

**Comment by cseed** [comment]
Is there an option to build an test assembly jar?  I want to be able to run the Scala tests with just a assembly test jar.

**Comment by cseed** [comment]
And the resources.

**Comment by jigold** [comment]
To run this without running tests: `mvn -Dmaven.test.skip=true package assembly:single`

**Comment by jigold** [comment]
@cseed Should be done now. `assembly:single` will build both jars into `target/hail-0.2-sha-jar-with-dependencies.jar` and `target/hail-0.2-sha-test-jar-with-dependencies.jar`

**Comment by cseed** [comment]
Will integrate with new build system and re-pull.

**Pull request closed without merging**
