### PR TITLE
Optimized BGEN import.

### PR DESCRIPTION
**Pull request by cseed**
Added DosageGenotype.
Directly decode BGEN blocks instead of converting to GenotypeStreams.
Fixed possible bug in BGEN inflation.

### CODE REVIEW

**Comment by cseed** [comment]
Added code to use _0, _1, ..., _N for samples if no BGEN sample block or sample with warning.  I can revert this if you prefer.

**Comment by cseed** [comment]
`import_bgen('sample.bgen').count(genotypes=True)` went from 50s => 14.2s for sample.bgen ~1GB.

**Comment by jigold** [comment]
Did you purposefully omit making this same change for the `GenLoader`?

**Comment by cseed** [comment]
Yes.  1.  I'm not away of anyone using GEN right now, so it is much less important, and 2. my PR was already up to +100 lines.

**Pull request merged**
