### PR TITLE
[python-dill][hailtop] update past the bad version of dill

### PR DESCRIPTION
**Pull request by danking**
Fixes https://github.com/hail-is/hail/issues/13535.

All the new hailgenetics/dill images are now up: https://hub.docker.com/r/hailgenetics/python-dill/tags

### CODE REVIEW

**Comment by jigold** [comment]
Can you remind me how these new images get into the hail-vdc artifact registry and on Azure as well?

**Comment by danking** [comment]
Sure! There's a CI build step that copies everything from hailgenetics into the local repo. [mirror_hailgenetics_images](https://github.com/hail-is/hail/blob/main/build.yaml#L3344C19-L3386). Then, in the worker, we notice a limited set of hailgenetics images and, instead of getting them from docker hub, we get them from our internal repositories.

**Comment by jigold** [comment]
We only copy if the image isn't already present. I think this code is not what you want in mirror images. We should copy if the contents change as well.

```
copy_if_not_present() {
    src_image=$1
    dest_image=$2
    if ! skopeo inspect "docker://docker.io/$1";
    then
        echo "$1 does not exist yet, doing nothing"
    elif skopeo inspect "docker://$2";
    then
      echo "$2 already exists, doing nothing"
    else
      echo "$2 does not exist, copying $1 to $2"
      copy_image $1 $2
    fi
}
```

**Comment by danking** [comment]
ugh, that used to just use copy_image and skopeo did The Right Thing (i.e. copy if it the tag had been updated).

**Comment by danking** [comment]
I'll just manually do this right now.

**Comment by danking** [comment]
Done.

**Comment by danking** [comment]
And a PR to fix the root cause https://github.com/danking/hail/pull/new/fix-mirror-hailgenetics-images.

**Review by jigold — APPROVED** [review]

**Pull request merged**
