### PR TITLE
atgu CV analysis materials update

### PR DESCRIPTION
**Pull request by mkveerapen**

### CODE REVIEW

**Comment by mkveerapen** [comment]
> we don't want to commit these materials -- put them in Google Storage and just commit the link.

I'm not sure how to do this. Would you care to share steps on this?

**Comment by tpoterba** [comment]
The other examples on that page link to tar archives in Google storage:
```
    <h2>BroadE 2020</h2>
    <p>Hail version: 0.2.33</p>
    <p><a href="https://drive.google.com/file/d/1H_unz0kAlnoJws1lH7Ga0lvgHNqJMM1T/view?usp=sharing" target="_blank">Slides</a></p>
    <p><a href="https://storage.googleapis.com/hail-common/workshops/broade_2020.tar" target="_blank">Notebooks and data</a> </p>
```

If you copy the tar file to `gs://hail-common/workshops/neale_2020_cv.tar`, you can just add the link here.

**Comment by mkveerapen** [comment]
> The other examples on that page link to tar archives in Google storage:
> 
> ```
>     <h2>BroadE 2020</h2>
>     <p>Hail version: 0.2.33</p>
>     <p><a href="https://drive.google.com/file/d/1H_unz0kAlnoJws1lH7Ga0lvgHNqJMM1T/view?usp=sharing" target="_blank">Slides</a></p>
>     <p><a href="https://storage.googleapis.com/hail-common/workshops/broade_2020.tar" target="_blank">Notebooks and data</a> </p>
> ```
> 
> If you copy the tar file to `gs://hail-common/workshops/neale_2020_cv.tar`, you can just add the link here.

Ah! I wasn't sure that we had a common bucket to use. 

Separately, I also accidentally pushed a pptx in my PR and I have no idea how to delete it from here. I tried using the view file and three dots and it didn't give me an option to delete it.

**Comment by tpoterba** [comment]
just open a new PR, it's probably easier. Otherwise you can git remove it, commit that change, then squash commits so it's not part of the history.

**Comment by tpoterba** [comment]
closing in favor of new PR?

**Pull request closed without merging**
