### PR TITLE
Renamed VSM => MatrixTable, KeyTable => Table.

### PR DESCRIPTION
**Pull request by cseed**
I hereby declare the api1 deprecated.  Changing Scala to match api2 names.  I'll try to do things in moderately manageable chunks.  I'll do the MatrixTable methods next (filterSamples => filterColumns, etc.)

### CODE REVIEW

**Comment by cseed** [comment]
Hold off this was slightly premature I have to finish fixing up the python side.

**Comment by cseed** [comment]
OK, I verified python tests pass.  Should be ready for a look.

**Comment by cseed** [comment]
"look".

**Comment by tpoterba** [comment]
I don't especially like renaming the Python hail1 api classes KeyTable -> Table and VariantDataset -> MatrixTable. I basically feel like we should leave that interface untouched until we delete it.

**Comment by cseed** [comment]
I agree completely.  No point in putting any energy into hail1.  I think we can do that sooner rather than later.  As soon as the current devel users (basically Robert, Konrad and maybe Laurent) can use hail2 instead of hail1, it goes, even if hail2 is still a bit rough and in flux.  (It is devel, after all.)

**Comment by cseed** [comment]
Do you have a list of unresolved hail2 api issues?  What else is there besides the allele commands?

**Comment by tpoterba** [comment]
Here's my current rough list of things to be done before hail2 is as usable as hail1. It's still pretty long!

## Necessary code work:
 - Add the rest of the core methods from VDS/KT to api2 (#2591 does most for KT, order_by is the only outstanding KT method that's not moved to table there. Same needs to be done for VDS, this isn't too hard)
 - Add the non-core methods to `hail.methods` / `hail.genetics.methods`
    - some stuff here is much harder than the rest, like `filter_alleles`
    - This is mostly just labor, but some require more thought than others, like moving TDT to use hail2 expr
 - Support intervals in the `index_*` methods. It's possible now to join by locus, but not using the `annotateLociTable` fast path.
 - Move to Python 3 so argument order is preserved
 - Test the hail2 api much more rigorously than we do now (at the very least, call each parameter branch for each method!
 - Typecheck the expression language. This isn't super trivial, and making a nice system to integrate our `typecheck` module and expressions will require some thoughtful design work.
 - Some more organization around the package: monkey patching with `import hail.genetics` is an idea I like, but want to think about the edge cases first.

## Documentation
 - Document the `index_*` methods / joins
 - Translate the _Hail Overview_ tutorial
 - Make new tutorials to replace the 2 expr ones we have
 - Fill in docs on api2 methods (they're not all there yet)
 - Fill in docs on expression language (things like __mul__ on NumericExpression haven't been documented)
 - Write "integrative docs" that provide how-tos for common types of workflows. Show the power of annotate / select / group_by/aggregate, etc.

## Longer term QoL:
 - Move over tests to Python as much as possible. I looked at the linear regression suite and it can be moved entirely into Python without many problems.
 - Write a type parser in Python. The nested calls into the JVM for Type._from_java make the library feel extremely sluggish on teensy data.
 - Integrate RV with C/C++, so we can transmit data much more efficiently between Python and Java.
 - Rethink the expr language function registry, because many functions there can be implemented in terms of others in Python.
 - add back in de novo

**Comment by cseed** [comment]
Wait, what are the requested changes?  I didn't rename anything in api1, just the uses of the Scala classes.  I will  rebase now, tho.

**Comment by tpoterba** [comment]
Ah, oops! I extrapolated from the comment change in PCA

**Pull request merged**
