### PR TITLE
[qob] Add feature flags to print IR and inputs on workers

### PR DESCRIPTION
**Pull request by tpoterba**
-

### CODE REVIEW

**Review by daniel-goldstein — DISMISSED** [review]
The argument to `getFlag` needs to its lowercase name not the env variable name.

**Comment by daniel-goldstein** [comment]
Can see an example of this running (with the import / export VCF pipeline) [here](https://batch.azure.hail.is/batches/3423869)

**Comment by tpoterba** [comment]
This is sweet.

**Comment by tpoterba** [comment]
fixed.

**Review by daniel-goldstein — APPROVED** [review]

**Pull request merged**
