### PR TITLE
[auth] Add current Azure display name to CLI and UI

### PR DESCRIPTION
**Pull request by jigold**
I still need to test this works with dev deploy.

### CODE REVIEW

**Review by danking — DISMISSED** [review]
LGTM. We could just merge and check in default. No one is bothered if it breaks.

**Comment by jigold** [comment]
This is not actually working.

**Comment by jigold** [comment]
I'll revisit this once #11115 is merged.

**Review by danking — CHANGES_REQUESTED** [review]
dismiss when you're ready for a new look

**Comment by jigold** [comment]
Closing in favor of #11147

**Pull request closed without merging**
