### PR TITLE
Added a benchmark for linear_regression_rows

### PR DESCRIPTION
**Pull request by johnc1231**
We should start tracking the speed of this as we work to replace it with ndarray version.

### CODE REVIEW

**Comment by johnc1231** [comment]
Alright, I'll look at that. I was copying pc_relate above, which does the balding nichols and checkpoint process as well.

**Comment by danking** [comment]
pc_relate is dominated by the n^3 work, but Tim's point stands, I was just a lazy slub!

**Comment by danking** [comment]
and he let me get away with it!

**Comment by johnc1231** [comment]
I addressed the comment and made a data source that's a GB (defined like: 

```
n_rows = 60_000
n_cols = 4_000
mt = hl.utils.range_matrix_table(n_rows, n_cols)
mt = mt.annotate_entries(unif = hl.rand_unif(0, 1))
```
)

Tests only take like 20 seconds though.

**Comment by johnc1231** [comment]
I'm running this using `hail-bench`, which I thought would restrict me to only one core, but not sure that it did give how fast this went.

**Comment by tpoterba** [comment]
can you look at `top` output while it's running? I want to make sure dgemm isn't multithreading...

**Comment by johnc1231** [comment]
The java process that gets created in htop while benchmarks are running goes over 100% CPU usage. Seen it go up to 300%

**Comment by johnc1231** [comment]
Looks like we probably want to add the following to benchmark somewhere:

```
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export OMP_NUM_THREADS=1
export VECLIB_MAXIMUM_THREADS=1
```

**Comment by tpoterba** [comment]
will go here:
https://github.com/hail-is/hail/blob/18b57caf7779310eb0cbc2a70f47eda06fb037c5/benchmark/scripts/benchmark_in_pipeline.py#L56

Can you add those? Thanks!

**Comment by tpoterba** [comment]
though this is only for the docker one. We'd have to set those ourselves in shell rc for mac, so don't bother with the veclib one.

**Comment by johnc1231** [comment]
Why do we have to add them ourselves in shell rc for mac? Presumably we can also set them in the benchmark code when running benchmarks locally?

**Comment by tpoterba** [comment]
I'm not sure how to set env variables for the Hail java process from Python. I'm sure it can be done

**Comment by johnc1231** [comment]
Hmm, looks like it's something like `spark.executorEnv.FOO=...` based on this: https://spark.apache.org/docs/latest/configuration.html

**Comment by tpoterba** [comment]
oh, awesome. Can you actually set those here:

https://github.com/hail-is/hail/blob/dfce3f7c95454265b7543960811e58fc4419e9d8/hail/python/hail/context.py#L65

**Comment by johnc1231** [comment]
Sure, did that, though I kind of want a way to verify that it worked. Watching top doesn't seem super scientific. Linear regression still only takes like 20 seconds on my laptop. Watching top I see that the cpu usage spikes to 300% for a second at the beginning of each of the benchmark iterations, then falls back down to somewhere between 100% and 110% for the duration of the 20 seconds.

**Comment by tpoterba** [comment]
oh, huh. This seems fine then.

**Comment by danking** [comment]
Does Spark spawn a fresh JVM executor process in local mode?

**Comment by tpoterba** [comment]
not sure how to verify.

**Comment by danking** [comment]
Yeah, it's all in the same JVM process so those variables would have no effect: https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/scheduler/local/LocalSchedulerBackend.scala#L97

**Comment by danking** [comment]
MKL has https://software.intel.com/en-us/node/471142

I ran this:
```
In [1]: import os 
   ...: os.environ["HAIL_HAIL"] = 'in' 
   ...: import hail as hl 
   ...: hl.init()                                                                                                                                                                                                   
```
And read System.getenv("HAIL_HAIL") and got `"in"`.

**Comment by johnc1231** [comment]
Yep, sigh. And I don't want to specify these args on the master node since that would break workflows that do use LMMs and do svd on master node. So I guess I'll add them specifically for the hail in pipeline docker based benchmarking system since we know that's running in local mode and actually want that to have only one core. Given that, should I still leave this executor arguments in place or pull them back out?

**Comment by danking** [comment]
Use os.environ in the test (and remember to set it back to its old value it afterward)

**Comment by johnc1231** [comment]
Ah, edit them specifically in the linear regression benchmark test? Is there a reason we'd want that as opposed to just setting them in the benchmark suite's dockerfile or something?

**Comment by tpoterba** [comment]
> Use os.environ in the test (and remember to set it back to its old value it afterward)


This won't work. Hail has already been initialized. We definitely want to set these for every benchmark, at least for now -- this could be responsible for docker blowing limits (we only allocate 1.5 cores, I think)

**Comment by danking** [comment]
Can we expose a HailContext.setEnv then? That seems like the right thing to do

**Comment by tpoterba** [comment]
we only use 1 core in the benchmarks anyway -- I think the right solution is to set the executor env by default, set them all in the docker script for benchmarks, and not worry too much about non-benchmark local mode for now

**Comment by johnc1231** [comment]
I think I'm just setting the docker script ones for now in this PR. Anything else seems out of scope of adding this random benchmark

**Comment by johnc1231** [comment]
Ok @tpoterba  I added the environment variables where I think you originally wanted them in the pipeline task.

**Comment by tpoterba** [comment]
OK, great. I think we should still add them to the executor env -- do you want to PR that after this goes in?

**Comment by johnc1231** [comment]
Yeah, let's make that a separate thing, I want to like SSH into other nodes and verify it's doing what I thought, and I was also reluctant to add a new option to the HailContext right before we released 0.2.32 in case it slid in first

**Comment by tpoterba** [comment]
yeah, good call.

**Pull request merged**
