### PR TITLE
Split out export from ShowGlobals into ExportGlobals

### PR DESCRIPTION
**Pull request by jbloom22**
- showglobals only prints to the screen
- exportglobals only saves valid json to file

### CODE REVIEW

**Comment by jbloom22** [comment]
This makes `exportglobals` consistent with `exportvariants` and `exportsamples`.  Also, the resulting file is now always valid JSON (no header, and `{}` when empty).

Possible future improvements:
1) Allowing export of a subset of globals using a `-c` expression
2) Truncating output of showglobals if there are really large collections.

**Comment by tpoterba** [comment]
I think I'd prefer keeping `showglobals` as it was (with the -o option to write prettily formatted JSON to a file), and adding a new command that uses expr arguments to export computations of global.  Thoughts, anyone??

**Comment by jbloom22** [comment]
That's reasonable, so long as the export globals command references the showglobals command and vice versa in the docs.  But I think what goes to the file should be actual JSON, as in my exportglobals, even if what goes to the screen has that header, EMPTY, etc.

**Comment by jbloom22** [comment]
@tpoterba do you agree with my comment? Should I modify this PR to only amend showglobals to export valid JSON, and we can come back to a separate exportglobals with expression command?

**Comment by tpoterba** [comment]
I think it's a good idea to write valid JSON.  That's a very positive
change!

**Comment by jbloom22** [comment]
Alright, closing this and making separate PR now.

**Pull request closed without merging**
