### PR TITLE
Added install-deps target to Makefile

### PR DESCRIPTION
**Pull request by johnc1231**
Adds a new target to make file that installs all dependencies and developer dependencies.

### CODE REVIEW

**Comment by johnc1231** [comment]
Sure, I can do that. Seems like the whole "dev-environment.yml" thing is no longer relevant. Do we still want to talk about Conda given that?

**Comment by tpoterba** [comment]
I still think conda is a good idea for developers managing their own environments, yeah.

**Comment by johnc1231** [comment]
I think this is good now?

**Comment by johnc1231** [comment]
Could you explain difference between doing `pip` and `$(PIP)`? Now that I look back at the file, there is `$(pip)` in several places, but never all caps.

**Comment by tpoterba** [comment]
Oh yeah, sorry, this is confusing. 

#6322 (which went in yesterday) changed the `pip` definition to `PIP` to indicate it's supposed to be a user-parameterizable variable.

**Comment by johnc1231** [comment]
Alright, rebased and made the requested change. Noticed one strange thing though. When I do 
`make install-deps`, the print out starts with:

```cat: /secrets//pypi-username: No such file or directory
cat: /secrets//pypi-password: No such file or directory
python3 -m pip install -U -r python/requirements.txt -r python/dev-requirements.txt```

**Comment by tpoterba** [comment]
ah, annoying. It's hard to figure out when stuff is actually going to be executed in make.

We can fix this by moving those definitions inside the target, I think:
```
   pypi-deploy: check-pypi wheel
	  TWINE_USERNAME=$(shell cat $(HAIL_TWINE_CREDS_FOLDER)/pypi-username) \ 
	    TWINE_PASSWORD=$(shell cat $(HAIL_TWINE_CREDS_FOLDER)/pypi-password) \
	    twine upload build/deploy/dist/*
```

mind making that change in a separate branch?

**Comment by johnc1231** [comment]
Sure, I can do that in a separate branch. Do we put this in first?

**Comment by tpoterba** [comment]
yeah, totally. these are orthogonal changes

**Pull request merged**
