### PR TITLE
Added Code.forLoop

### PR DESCRIPTION
**Pull request by johnc1231**
Happy to hear suggestions as to better ways to do this, but I've made too many emitter typos with while loops. I keep either doing something like

```
i := 0,
j := 0,
Code.whileLoop(i < M,
    Code.whileLoop(j < N, 
        ???,
        j := j + 1
    )
   i := i + 1
)
```
(j should be inside the outer whileLoop),
forgetting one of the increments, or forgetting to set the variables to 0 at the beginning. `Code.forLoop` is to force me to include all parts.

### CODE REVIEW

**Comment by johnc1231** [comment]
Also, do we test emitter stuff like this anywhere?

**Comment by akotlar** [comment]
We have tests that use whileLoop in StagedRegionValueSuite (in testing creation of staged arrays), but it would be useful to have this broken out and with deeper coverage of input paths (like your nested array case)

**Comment by johnc1231** [comment]
Is there an easy way for me to write a test that's just "Run some `Code[_] block and check what it returns"?

**Comment by tpoterba** [comment]
yep, you can do the following, with the correct type of T for the return type of the code:
```scala
val fb = EmitFunctionBuilder[T]("foo")
fb.emit(code)
val result = fb.resultWithIndex(0, ctx.r)()
```

**Comment by johnc1231** [comment]
Thanks, that was helpful. Now there's a test.

**Pull request merged**
