### PR TITLE
[query] Mix table stage and table value execution; delete lots of old sparky code

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by danking** [comment]
Should we randomly assign a compilers team member?

**Comment by tpoterba** [comment]
will benchmark then assign.

**Comment by danking** [comment]
Should we close this PR, @tpoterba ?

**Comment by tpoterba** [comment]
Yeah, I'll reopen when I need it. I have some stuff in the works that should hopefully mitigate some of the large classes/methods generated by WSC

**Pull request closed without merging**
