### PR TITLE
[hail] compare bytes before strings in locus ordering

### PR DESCRIPTION
**Pull request by chrisvittal**
New algorithm:
    Check the bytes of the contig string
    If equal, compare the positions
    Otherwise, use the contig ordering

### CODE REVIEW

**Comment by chrisvittal** [comment]
Before, combiner profiling was dominated by `String,<init>` now it's not.

**Comment by tpoterba** [comment]
you'll get even more benefit from staging, to get rid of the `loadField` overhead.

please follow up with DSP for the 1kg gvcfs so we can add a benchmark!

**Comment by tpoterba** [comment]
you'll get even more benefit from staging, to get rid of the `loadField` overhead.

please follow up with DSP for the 1kg gvcfs so we can add a benchmark!

**Comment by chrisvittal** [comment]
We will. But good news! Old 100 exome chr1 test: 38 min, new test: 15 min.

**Comment by tpoterba** [comment]
> We will. But good news! Old 100 exome chr1 test: 38 min, new test: 15 min.

Shhhhh don't tell whoever pays our cloud bill

**Pull request merged**
