### PR TITLE
[query] Build Hail Wheel With Python `build`

### PR DESCRIPTION
**Pull request by ehigham**
setup.py complains awfully when you invoke it directly. Apparently this sort of thing is unacceptable and the recommended workflow for building wheels is to use `build`. See the link below for more information. https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html

### CODE REVIEW

**Comment by danking** [comment]
Can you make the same change to benchmark/Makefile?

**Comment by danking** [comment]
And looks like you gotta add https://pypi.org/project/build/ to the dev-requirements.txt

**Comment by daniel-goldstein** [comment]
Ed and I talked this over on Tuesday and there might be more going into this. @ehigham tag me when this is ready to be looked at

**Comment by ehigham** [comment]
> Can you make the same change to benchmark/Makefile?

Sure. I plan to remove wheel generation from benchmark/Makefile as we don't use it anymore.

**Comment by ehigham** [comment]
Parking as I'm fed up with docker, makefiles and sidequests to sidequests for the time being.

**Comment by daniel-goldstein** [comment]
Unassigning to get it off of my CI queue. Feel free to reassign when you want me to look at it again.

**Review by daniel-goldstein — CHANGES_REQUESTED** [review]
Forgot that we also track requested reviewers not just assignees. This shows up on my CI page until I request changes so doing this to get it off my plate. Dismiss these changes when it's ready for another review.

**Pull request closed without merging**
