### PR TITLE
Added hardcalls command.

### PR DESCRIPTION
**Pull request by cseed**

### CODE REVIEW

**Comment by tpoterba** [comment]
This looks good.  Long-term, we'll have Jon's HCS as an optimized gt-only VDS, yes?

**Comment by cseed** [comment]
On profile.vcf:

```
$ du -sh ~/profile.vds
177M	/Users/cseed/profile.vds
$ du -sh ~/profile.hc.vds
9.6M	/Users/cseed/profile.hc.vds
```

Almost 20x smaller.  Not bad.

**Comment by cseed** [comment]
Eventually I would like something more generic, a generic genotype schema with Jon's encoding for sequences of integer (gt or whatever).  The question is how/what order to get there.

**Comment by cseed** [comment]
~60% the size of plink.  Not bad!

```
-rw-r--r--  1 cseed  1594166068    15M Sep  2 17:39 profile.bed
```

**Pull request merged**
