### PR TITLE
Fix getOrCreate method and add regression test

### PR DESCRIPTION
**Pull request by henrydavidge**
The `HailContext.getOrCreate` method seems to have been broken in #5512. This patch fixes the issue and adds a regression test so that it won't break again.

Since this test must add create a new Hail context, I had to add a gradle task that runs every suite in a separate JVM. I'm not a gradle expert, so if there's a simpler way to accomplish this execution mode, feel free to suggest :).

### CODE REVIEW

**Comment by henrydavidge** [comment]
@tpoterba Can you review please?

**Comment by tpoterba** [comment]
this seems like a lot of hassle, and doesn't test an important piece - whether idempotent initialization actually works from Python. We can test creation of a JVM much more easily from Python than from Scala.

**Comment by tpoterba** [comment]
Let me poke around and see how hard it is

**Comment by tpoterba** [comment]
#5872 fixes the problem and tests more robustly

**Comment by tpoterba** [comment]
will close in favor of that

**Comment by henrydavidge** [comment]
Cool, works for me. Thanks!

**Pull request closed without merging**
