### PR TITLE
implement Table.{any, all} in terms of aggregate

### PR DESCRIPTION
**Pull request by cseed**
move Table.{exists, forall} to test section in Scala

### CODE REVIEW

**Comment by konradjk** [comment]
Don't just want to remove any and all? They're really just convenience methods - not that hard to do `Table.aggregate(hl.any(condition))` compared to `Table.any(condition)`

**Comment by cseed** [comment]
Yeah, I debated this, but they are pretty nice and we use them a lot in our tests.  @tpoterba thoughts?

**Comment by tpoterba** [comment]
I'm happy either way.

**Comment by cseed** [comment]
Let's just leave them in then.

**Pull request merged**
