### PR TITLE
[hailtop.utils]Test for digits needed

### PR DESCRIPTION
**Pull request by CDiaz96**

### CODE REVIEW

**Review by danking — CHANGES_REQUESTED** [review]
Each PR should be for just one change. Can you modify this branch so that it only contains the digits needed test and none of the `grouped` tests?

**Comment by CDiaz96** [comment]
@danking  Yes, I did not mean to do this. I am currently working on fixing it.

**Comment by johnc1231** [comment]
Easiest way is probably to use git interactive rebase: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

And you can just delete the commits you don't want.

**Comment by CDiaz96** [comment]
Thanks @johnc1231, I will read through this right now.

**Pull request closed without merging**
