### PR TITLE
* changed signature of maximal_independent_set method

### PR DESCRIPTION
**Pull request by maccum**
to accept a table of vertices and return a filtered table.

* changed BinaryHeap's tiebreaker function to return
a Long, which matches data type of indices returned by
Table.index()

* added selectGlobal method to Table which takes String*

### CODE REVIEW

**Comment by tpoterba** [comment]
can you give me a few sentences to motivate this change? It seems like the extra table filter step can just be done with:
```
unrelated = hl.maximal_independent_set(df1.i, df1.j)
df2 = df2.filter(hl.is_defined(unrelated[df2.x])
```
Is that wrong?

**Comment by tpoterba** [comment]
This still feels too complex.
How about a flag to return the nodes kept or the nodes removed? If you return the nodes removed, then we can just filter that out of the left table. Would that work?

**Comment by maccum** [comment]
My original motivation for this was to speed up the following code in LD prune: 

```
related_nodes = edges.aggregate(agg.collect_as_set(agg.explode([edges['i'], edges['j']])))
related_nodes_to_keep = maximal_independent_set(edges['i'], edges['j'])
related_nodes_to_remove = related_nodes - set(related_nodes_to_keep)

pruned_ds = (locally_pruned_ds
    .filter_rows(functions.broadcast(related_nodes_to_remove)
                 .contains(locally_pruned_ds.variant_idx), 
                 keep=False))
```
It's my understanding that the last line of this code is slow because passing a large python list over py4j is slow.

Adding a keep/remove flag to maximal_independent_set would address the set logic and slowness of collecting the set of nodes, but not the other speed issue, since maximal_independent_set would still return a python list. 

I could add the keep/remove flag, and also edit the method on the Scala side to create and return a new single-column Table of nodes to remove. Is this preferable?

**Comment by tpoterba** [comment]
Sorry to be naive, I haven't really bumped into this method much.

We can still avoid python lists by returning a table with one column instead of a set!

**Comment by tpoterba** [comment]
oops, I responded before reading the last line. Yes!

**Comment by tpoterba** [comment]
That's a super nice interface.

**Comment by maccum** [comment]
@tpoterba made changes

**Comment by maccum** [comment]
changed the things

**Pull request merged**
