### PR TITLE
[auth] fix this cloud cookie nonsense

### PR DESCRIPTION
**Pull request by danking**
My frustration boiled over and I went to go fix this. This change will cause everyone to become logged out because they will lack the right cookie. That seems fine.

### CODE REVIEW

**Review by jigold — CHANGES_REQUESTED** [review]
Do we need to test this by hand or are you confident it will work? I'm sure this is fine, but I do want to avoid a case where we lock ourselves out of our system.

**Comment by jigold** [comment]
Also, this might break grafana as it sends a cookie to prometheus.

**Comment by danking** [comment]
I addressed the grafana situation.

I dev deployed into my namespace and I'm able to log in.

I cannot test that I've addressed the issue because the default namespace is still using the old version and thus I hit 401s there before even reaching the dev namespace.

**Comment by jigold** [comment]
The tests failed. Can't tell if it's from this commit. Can you double check everything is good or retry?

**Comment by danking** [comment]
OK, should be resolved now. I had a lint error and needed to mount the global config into hello and website.

**Review by jigold — APPROVED** [review]

**Pull request merged**
