### PR TITLE
[hailctl] Replace argparse with typer/click

### PR DESCRIPTION
**Pull request by daniel-goldstein**
Started playing with [typer](https://typer.tiangolo.com/) on the plane. It's a somewhat thin wrapper around `click`, and I'm not entirely sold on one vs the other, but either seems a lot neater than argparse (I remember Cotton tried this years ago but I haven't looked at that PR). Click gives us the easy composition of CLIs, function name as the command name, the use of docstring as the description, help output, and most of the core functionality you see. Typer is the one translating python type hints into click type-checking, default setting, etc. Typer also uses rich if it's installed and allows you to install shell completion which is pretty neat, not sure if you can get that through click or if you need to use a click plugin.

I replaced a couple of the hailctl commands here with the typer/click version. If you like what you see I can keep going on the rest of the commands (you can look to `batch/cli.py` and `hailctl/__main__.py` as an example).

### CODE REVIEW

**Comment by daniel-goldstein** [comment]
This is what `hailctl` looks like:

```

 Usage: hailctl [OPTIONS] COMMAND [ARGS]...

 Manage and monitor hail deployments.

╭─ Options ────────────────────────────────────────────────────────────────────────────────────────────╮
│ --install-completion        [bash|zsh|fish|powershell|pwsh]  Install completion for the specified    │
│                                                              shell.                                  │
│                                                              [default: None]                         │
│ --show-completion           [bash|zsh|fish|powershell|pwsh]  Show completion for the specified       │
│                                                              shell, to copy it or customize the      │
│                                                              installation.                           │
│                                                              [default: None]                         │
│ --help                                                       Show this message and exit.             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Commands ───────────────────────────────────────────────────────────────────────────────────────────╮
│ batch       Manage batches running on the batch service managed by the Hail team.                    │
│ config      Manage Hail configuration.                                                               │
│ curl        Issue authenticated curl requests to Hail infrastructure.                                │
│ version     Print version information and exit.                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯
```


This is what `hailctl batch submit --help` looks like:

```

 Usage: hailctl batch submit [OPTIONS] SCRIPT [ARGUMENTS]...

 Submit a batch with a single job that runs SCRIPT with the arguments ARGUMENTS.

╭─ Arguments ──────────────────────────────────────────────────────────────────────────────────────────╮
│ *    script         PATH            Path to the script [default: None] [required]                    │
│      arguments      [ARGUMENTS]...  [default: None]                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Options ────────────────────────────────────────────────────────────────────────────────────────────╮
│ --files               PATH              Files or directories to add to the working directory of the  │
│                                         job.                                                         │
│                                         [default: None]                                              │
│ --name                TEXT              The name of the batch.                                       │
│ --image-name          TEXT              Name of Docker image for the job                             │
│                                         [default: (hailgenetics/hail)]                               │
│ --output      -o      [text|yaml|json]  [default: text]                                              │
│ --help                                  Show this message and exit.                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by danking** [comment]
This is super neat! I'm not sure what foot guns to look for. Let me do a think

**Review by danking — CHANGES_REQUESTED** [review]
I'm excited for this. Dismiss when it's ready for review!

**Comment by danking** [comment]
The formatting does become a bit much.  This black's preferred rendering.
```
@app.command()
def deploy(
    branch: Annotated[str, typer.Option("--branch", "-b", help="Fully-qualified branch, e.g., hail-is/hail:feature")],
    steps: Annotated[
        List[str],
        typer.Option("--steps", "-s", help="Comma or space-separated list of steps to run."),
    ],
    excluded_steps: Annotated[
        List[str],
        typer.Option(
            "--excluded_steps",
            "-e",
            help="Comma or space-separated list of steps to forcibly exclude. Use with caution!",
        ),
    ],
    extra_config: Annotated[
        List[str],
        typer.Option(
            "--extra-config",
            "-e",
            help="Comma or space-separated list of key=value pairs to add as extra config parameters.",
        ),
    ],
    open: Annotated[
        bool,
        typer.Option("--open", "-o", help="Open the deploy batch page in a web browser."),
    ],
):
    pass

```

We can reduce the noise a bit with aliases:
```
from typing import Annotated as Ann, List
from typer import Opt


@app.command()
def deploy(
    branch: Ann[str, Opt("--branch", "-b", help="Fully-qualified branch, e.g., hail-is/hail:feature")],
    steps: Ann[
        List[str],
        Opt("--steps", "-s", help="Comma or space-separated list of steps to run."),
    ],
    excluded_steps: Ann[
        List[str],
        Opt(
            "--excluded_steps",
            "-e",
            help="Comma or space-separated list of steps to forcibly exclude. Use with caution!",
        ),
    ],
    extra_config: Ann[
        List[str],
        Opt(
            "--extra-config",
            "-e",
            help="Comma or space-separated list of key=value pairs to add as extra config parameters.",
        ),
    ],
    open: Ann[
        bool,
        Opt("--open", "-o", help="Open the deploy batch page in a web browser."),
    ],
):
    pass
```

It seems to me that the benefits of real sub-commands and better dead-option listing is worth the extra noise in the function definition.

**Comment by danking** [comment]
This all looks good to me. We don't have great tests for this stuff. Should I do a careful read through or do you feel comfortable merging without that?

**Comment by daniel-goldstein** [comment]
So ya this is what was giving me pause so would appreciate your take. I threw WIP on so I can make sure it's properly tested before it merges. Here are my thoughts:
- I can manually exercise all the commands, easily enough. Flexing all the options is harder, but I can compare the help for each command. The fact that these files are all lint-free and typecheck gives me confidence I did have before.
- I'm not worried about breaking dev stuff. Basically the only thing I am worried about breaking is the dataproc group.
- I was planning on running the test dataproc scripts prior to removing the WIP, which is something, but obviously does not test all the options.

I think it would be nice to get a close review for dataproc start/submit (the biggest ones that people rely on the most) and everything else can be at whatever granularity you feel comfortable with.

**Comment by daniel-goldstein** [comment]
@danking Thanks to Nick there were a fair number of basic mocking tests for the dataproc CLI and I think they cover the superficial changes that comprise this PR. I altered them a bit to use the typer/click `CLIRunner` which is pretty neat! I also managed to run `test-dataproc-37` successfully.

**Review by danking — APPROVED** [review]
This all seems correct to me! I fiddled a bit with the hailctl dataproc and hdinsight commands. I also looked over the code. Nothing glaringly wrong and a lot much better!

**Comment by danking** [comment]
@daniel-goldstein I slapped a WIP on here in case you wanted to check anything else before merging.

**Pull request merged**
