### PR TITLE
[bugfix] Fix duplicated nodes in maximal_independent_set output

### LINKED ISSUE #5535: Duplicated output when running `hail.methods.maximal_independent_set`
### Hail version:

version 0.2.10-bb21797a1f06

When running hail.methods.maximal_independent_set, the output table can contain the same sample node but multiple times. Is that normal?

With HT:
```
i                     | j                                              |  ibs0 |  ibs1 |
+-----------------------+------------------------------------------------+-------+-------+
| str                   | str                                            | int64 | int64 |
+-----------------------+------------------------------------------------+-------+-------+
| "se::EGAN00001210960" | "cas_scz_celso_eur_sr_PSYC*PT-1TLPS_G08I1020"  |   192 |  2213 |
| "se::EGAN00001210960" | "con_scz_gawli_eur_sr_PSYC*PT-1PZAL_Gaw_99007" |   198 |  2311 |
| "se::EGAN00001210960" | "se::EGAN00001212011"                          |   182 |  2183 |
| "se::EGAN00001210960" | "se::EGAN00001212121"                          |   187 |  2161 |
| "se::EGAN00001210960" | "ue::548084"                                   |   193 |  2246 |
| "se::EGAN00001210960" | "ue::C3045"                                    |   194 |  2279 |
+-----------------------+------------------------------------------------+-------+-------+

+-------+----------+----------+----------+----------+
|  ibs2 |       Z0 |       Z1 |       Z2 |   PI_HAT |
+-------+----------+----------+----------+----------+
| int64 |  float64 |  float64 |  float64 |  float64 |
+-------+----------+----------+----------+----------+
|  3779 | 6.38e-01 | 3.62e-01 | 0.00e+00 | 1.81e-01 |
|  3680 | 6.28e-01 | 3.72e-01 | 0.00e+00 | 1.86e-01 |
|  3753 | 6.08e-01 | 3.92e-01 | 0.00e+00 | 1.96e-01 |
|  3837 | 6.36e-01 | 3.64e-01 | 0.00e+00 | 1.82e-01 |
|  3755 | 6.30e-01 | 3.70e-01 | 0.00e+00 | 1.85e-01 |
|  3734 | 6.23e-01 | 3.77e-01 | 0.00e+00 | 1.88e-01
```

I run:
`rht = hl.maximal_independent_set(ht_test.i, ht_test.j, False)`

and get:
`rht.show()`

```
+-----------------------+
| node |
+-----------------------+
| str |
+-----------------------+
| "se::EGAN00001210960" |
| "se::EGAN00001210960" |
| "se::EGAN00001210960" |
| "se::EGAN00001210960" |
| "se::EGAN00001210960" |
| "se::EGAN00001210960" |
+-----------------------+
```

### PR DESCRIPTION
**Pull request by tpoterba**
Fixes #5535

### CODE REVIEW

**Comment by tpoterba** [comment]
won't this require keying (and therefore shuffling) then?

**Comment by catoverdrive** [comment]
@danking this PR is showing up as approved on the CI, but not as approved here.

**Comment by tpoterba** [comment]
github API troubles?

**Comment by cseed** [comment]
This fixes the CI: https://github.com/hail-is/hail/pull/5757.  I will dismiss my review after that goes in.

**Comment by danking** [comment]
> won't this require keying (and therefore shuffling) then?

@tpoterba yeah but that's the correct answer no?

**Comment by danking** [comment]
Heh, this is all my fault: https://github.com/hail-is/hail/pull/5078/files

**Comment by tpoterba** [comment]
yeah, the `keyed=False` path is for performance and I'm OK leaving that with duplicated nodes

**Comment by danking** [comment]
@tpoterba if you're good with the verbiage I added to the notes, then I'll approve.

**Comment by tpoterba** [comment]
ya

**Pull request merged**
