### PR TITLE
[compiler] mark ApplySeeded as lowerable

### PR DESCRIPTION
**Pull request by patrick-schultz**

### CODE REVIEW

**Review by tpoterba — APPROVED** [review]

**Comment by danking** [comment]
@patrick-schultz this appears to have changed the random outputs somehow. If that's what you expected, I think you just have to copy over the new values in the docs.

**Comment by patrick-schultz** [comment]
I started looking into what's happening here a while ago, and was very confused. Haven't had a chance to look closer yet.

**Comment by danking** [comment]
Bumping this again to keep it on the todo list

**Comment by danking** [comment]
Bump!

**Comment by danking** [comment]
Bump, @patrick-schultz can we resolve this before PCA?

**Comment by patrick-schultz** [comment]
Yeah, I can do that. Sorry to let this sit so long.

**Pull request merged**
