### PR TITLE
[auth] maybe fix auth flow & close security hole

### PR DESCRIPTION
**Pull request by danking**
It seems that sessions sometimes become inaccessible to auth. Using some
logging, I realized that `/login` will set some session parameters that do not
reappear in `/oauth2callback`. While trying to debug this, I deleted my cookie
and everything started working again. Luckily, my phone was still borked. The
fix is to use `new_session` which I discovered with a big red warning in
aiohttp-session's docs: [Always use new_session() instead of get_session() in
your login views to guard against Session Fixation
attacks!](https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.new_session).

If nothing else, we are now safe from session fixation attacks. I do not
understand why this is necessary for correctness.

### CODE REVIEW

**Comment by danking** [comment]
No state. I printed the session in the logs (I was deploying into prod to test while I had a broken cookie). My session had nothing set except that it was marked as created on January 7th. This despite that I saw a log statement from when I hit /login,m that clearly showed me session with all the right values.

My guess is that there was some old signing key or somehow the session got corrupted so you can decode it to get an empty session and add new fields but they fail to be written back.

**Comment by cseed** [comment]
Ah, that's it: the cookie is expired, so if you don't create a new session, the session_data comes back as empty:

```
        if max_age is not None and age > max_age:
            session_data = None
```

Great.

**Comment by danking** [comment]
I find that confusing because Safari displayed the expiration date as in March. 🤷‍♀. It would appear that there's some disconnection between what aiohttp-session considers max age and what Safari considered max age.

**Comment by johnc1231** [comment]
Needs a bump

**Pull request merged**
