### PR TITLE
Clean up count doc

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by jbloom22** [comment]
Did you just add a line break in the first bit?

And I think you should also explain that genotypes=False is faster since it need not unpack the genotypes. Otherwise it's unclear why we'd even make that an option.

**Comment by tpoterba** [comment]
yes, broke up first line because it was too long.

I think this method should just be removed, really.

We have num_samples, count_variants, and query_genotypes that make it easy to do all of this stuff.  The interface is also weird

**Comment by jbloom22** [comment]
So you want folks to do this for callRate?
`call_rate = vds.query_genotypes('gs.fraction(g => g.isCalled)')`

Also, this is grammatically off:
"Perform aggregation queries over genotypes, and returns python objects."

https://hail.is/hail/hail.VariantDataset.html?highlight=query_genotypes#hail.VariantDataset.query_genotypes

**Comment by tpoterba** [comment]
Will make new PR for query fixes

**Pull request merged**
