### PR TITLE
[query/docs] add databricks docs with disclaimers

### PR DESCRIPTION
**Pull request by williambrandler**
Signed-off-by: William Brandler <william.brandler@databricks.com>

Moving the Databricks documentation for Hail to the open source Hail documentation. This project is not part of the Databricks product, and therefore instructions for using the Hail open source project on Databricks should be maintained by the open source community moving forward

Also spilt `other_cloud_providers` into three, AWS, Databricks and Others

### CODE REVIEW

**Comment by danking** [comment]
Hey @williambrandler ! Thanks for your contribution to Hail.

We endeavor to keep our docs always accurate and up-to-date. Our continuous deployment system verifies the correctness of our Google Dataproc and Azure HDInsight instructions before releasing a new version of Hail to PyPI.

Does Databricks have an open source program that would provide us with free credits to incorporate the Databricks platform into our continuous deployment process? Alternatively, I'm comfortable accepting these new instructions with a disclaimer that clearly identifies these instructions as contributed by Databricks and not maintained by the Hail team.

Thanks!

**Comment by jigold** [comment]
@williambrandler Could you please respond to Dan's questions? Thank you!

**Comment by danking** [comment]
We have an outstanding email thread on this. I’ll reply here when that’s resolved.

**Review by danking — DISMISSED** [review]
OK. After some back and forth, I realize we don't have Broadies using Databricks which makes it difficult for me to justify investing in continuous testing of this installation method. Instead, I've added a disclaimer that the Hail team doesn't maintain the docker images discussed here.

**Review by danking — APPROVED** [review]

**Comment by iris-garden** [comment]
Closing in favor of https://github.com/hail-is/hail/pull/12386, which uses my fork since merging is restricted to authorized users.

**Pull request closed without merging**
