### PR TITLE
elasticsearch export

### PR DESCRIPTION
**Pull request by bw2**

### CODE REVIEW

**Comment by danking** [comment]
@bw2 Hey looks like there's some weird version issues. Can you set up the gradle to use a Spark 2.1 compatible version of elastic search if spark version is set to a 2.1.x version and use a Spark 2.0 compatible version of elastic search?

I don't fully understand the error, but it definitely looks like there's a spark version mismatch.

**Comment by bw2** [comment]
@danking I'm not sure if I understood your point, but I noticed some potential mismatches between versions that I've now corrected. The tests don't seem to be running to completion though. They've been running for ~ 24 hours. Is that expected?

**Comment by danking** [comment]
The Hail CI runs the tests against a merge of this branch with master, so they can't start until the merge conflicts are resolved. The GitHub UI uses the same icon for running and not started when a check is required. I think it does this because checks are not required to notify GitHub that they have started.

**Comment by bw2** [comment]
@danking IIUC the TeamCity build is now working with spark-2.1.0 but not spark-2.0.2
(even though running `./gradlew shadowJar archiveZip` on my laptop with spark-2.0.2 works fine.)

From looking at the Maven repo
https://mvnrepository.com/artifact/org.elasticsearch/elasticsearch-spark-20_2.11
and the elasticsearch-spark connector docs
https://www.elastic.co/guide/en/elasticsearch/hadoop/master/spark.html
there's no indication that some versions only support v2.1, though it does say
```
elasticsearch-hadoop allows Elasticsearch to be used in Spark in two ways: through the dedicated support available since 2.1 or through the Map/Reduce bridge since 2.0. Spark 2.0 is supported in elasticsearch-hadoop since version 5.0
```

**Comment by danking** [comment]
It's a bit confusing, but on the CI page you can navigate to the Artifacts tab from which you can open the [build report's index.html](https://ci.hail.is/repository/download/HailSourceCode_HailCi/33165:id/build/reports/tests/index.html). The error looks to me like a Hail problem, not a you problem. I'll investigate further.

**Comment by danking** [comment]
@bw2 that package name is a lie, sadly.

The [maven repository page](https://mvnrepository.com/artifact/org.elasticsearch/elasticsearch-spark-20_2.11/5.5.1) for `org.elasticsearch:elasticsearch-spark-20_2.11:5.5.1` lists  `org.apache.spark:spark-core_2.11:2.1.0` as a dependency, which is decidedly not 2.0.

We'll have to use elasticsearch-spark 5.1.2. It's a bit annoying. You'll have to extend the [spark version-specific logic](https://github.com/hail-is/hail/pull/2049/files#diff-c197962302397baf3a4cc36463dce5eaR44) in `build.gradle`. You'll want to bind a new name, something like `elasticsearchSparkVersion`.

**Comment by danking** [comment]
I'm also inclined to file a bug against that package name.

**Comment by bw2** [comment]
@danking I forgot about 0.1 vs. master and merged+pushed latest master changes, so just move my changes to a new branch and PR. Sorry about that. #2088

**Pull request closed without merging**
