### PR TITLE
[vds] Fix and test `hl.vds.filter_intervals`

### PR DESCRIPTION
**Pull request by tpoterba**
Accept a table or a list.

### CODE REVIEW

**Comment by danking** [comment]
Old PR, closing. @chrisvittal can you take a look at the additional changes Tim made here? It looks like you only made one of them in https://github.com/hail-is/hail/pull/11400 Do we need the rest of this?

**Comment by chrisvittal** [comment]
nah, this is a better PR. I missed it when looking for fixes from zulip.

**Comment by chrisvittal** [comment]
I'll fix.

**Comment by danking** [comment]
Think you @chrisvittal !

**Review by chrisvittal — DISMISSED** [review]
I only fixed merge conflicts.

**Comment by danking** [comment]
There's something fishy happening in the service backend. It keeps timing out the same three test jobs. We'll need to do a little grep+diff to figure which tests are getting started but not terminating. I suspect we'll need to either skip something or ensure that it errors early.

**Comment by danking** [comment]
I'm also seeing this in my PR that removes most spark-only annotations (in favor of fails_service). I think we must have some logic that spins forever.

**Comment by danking** [comment]
Dismissed the review so that CI would focus on other PRs, but feel free to re-enable. We can chat tomorrow about how to test the query service with a custom JAR

**Comment by danking** [comment]
I'm on the train until about noon, but I can peek at this in the afternoon and let you know what I find.

**Comment by danking** [comment]
Sorry, had some unexpected meetings yesterday. Digging in now.

**Review by danking — APPROVED** [review]

**Review by danking — CHANGES_REQUESTED** [review]
(ci is broke, need to do this to unstick)

**Review by danking — APPROVED** [review]

**Comment by danking** [comment]
@chrisvittal, these tests actually pass the local backend. I changed the tests to reflect this, but wanted to ping you to make sure that seems reasonable.

**Comment by danking** [comment]
Actually they both passed on the service backend too.

**Comment by danking** [comment]
Chris, could you do a release next week to get this fix out? Thank you much!

**Pull request merged**
