### PR TITLE
[hail] Fix `hadoop_ls` to glob

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by konradjk** [comment]
Worth adding a test?

**Comment by akotlar** [comment]
@konradjk Python tests exist

**Comment by konradjk** [comment]
One that uses a glob though! I don’t see one at least. Maybe I missed (though I can’t imagine since it should have failed that test before this)

**Comment by akotlar** [comment]
You’re right, it could be useful to have a scala-specific test, but any braking changes away from old le behavior will cause the hadoop_ls test to fail.

**Comment by tpoterba** [comment]
yeah, will add a test for the new functionality though

**Comment by konradjk** [comment]
Out of curiosity, what's different about `assert` and the `self.assertEqual`?

**Comment by tpoterba** [comment]
self.assertEqual is unittest style. We use pytest now, which rewrites Python assert statements to provide good failure messages. New code should use `assert`, I think.

**Comment by johnc1231** [comment]
Somehow block matrix tests seem to be failing on this PR, both for the doctests and for the regular python tests.

**Pull request merged**
