### PR TITLE
Fix annotation DB docs

### PR DESCRIPTION
**Pull request by tpoterba**
Need to make sure that the docs look correct on the artifact from CI.

### CODE REVIEW

**Comment by tpoterba** [comment]
ack this wasn't fixed

**Comment by jigold** [comment]
Sorry about that. I checked the CI preview and it worked fine. Do you want to revert the commit?

**Comment by jigold** [comment]
Actually, I think the better way to do this is to move the `annotationdb` directory from `www` to `python/hail/docs/_static/`. Then I think you can add the following code to `_template/layout.html` near the top of the page. Feel free to push this off on me if it doesn't work right away.

```
  {% if pagename == "annotationdb" %}
    {%- set css_files = css_files + ['_static/annotationdb/bootstrap-treeview.min.css', '_static/annotationdb.css'] %}
    {%- set script_files = script_files + ['_static/annotationdb/bootstrap-treeview.min.js', '_static/annotationdb/clipboard.min.js', '_static/annotationdb/annotationdb.js'] %}
  {% endif %}
```

**Comment by tpoterba** [comment]
Sorry, meant to loop you in. I've been hacking on this a bit and tried what you suggested, but haven't yet gotten it to work. I think we don't need to revert the commit since this is actually an improvement.

**Pull request merged**
