### PR TITLE
[batch] Add environment variable for batch id in worker

### PR DESCRIPTION
**Pull request by jigold**
This is needed for Siwei's recursive pipeline to work.

### CODE REVIEW

**Comment by daniel-goldstein** [comment]
I thought I'd proposed this env variable but then we ended up going with [this](https://github.com/hail-is/hail/pull/12246)?

**Review by daniel-goldstein — CHANGES_REQUESTED** [review]
See comment above

**Comment by jigold** [comment]
I thought the config file was better for QoB where versioning and backwards compatibility is important and there could be substantially more configuration in the future. I don't think we mount that config file in the worker regardless for DockerJobs, but I could be wrong.

**Review by daniel-goldstein — DISMISSED** [review]
> was better for QoB where versioning and backwards compatibility is important

I think we have to fulfill the same backwards compatibility with env variables, though I agree that they are more ergonomic and favorable in this case to a config file. The config file was necessary for JVMJobs because the JVM containers are long-lived, so we cannot update their environment when a new job comes in. Looks like we do [write the config](https://github.com/hail-is/hail/blob/653eff0e1b3fc3fa9bea128a2db6d2bf30f32a1b/batch/batch/worker/worker.py#L1701) in DockerJobs but don't mount it, so let's add this env variable but do the following:

- Remove the use of `write_batch_config` in `DockerJob` and move `write_batch_config` from `Job` into `JVMJob`
- Document where `write_batch_config` is used in `JVMJob` why it's used instead of an env variable. I think I still don't understand the point of further configuration, since that's still possible with environment variables, we just can't change environment variables in JVMContainers like we can with the filesystem

**Review by daniel-goldstein — APPROVED** [review]
awesome, thanks

**Pull request merged**
