### PR TITLE
Update annotatevariants_bed.md

### LINKED ISSUE #861: Make explicit in documentation that bed interval annotation is not inclusive of the first variant

### PR DESCRIPTION
**Pull request by tpoterba**
Fixes #861

### CODE REVIEW

**Comment by jbloom22** [comment]
Wouldn't 0-indexed mean that 100 is included but 105 is not?

**Comment by tpoterba** [comment]
no, I think this is right.  1:100 is really 1:99, so the interval [1:100-1:105)  includes 1:99, 1:100, 1:101, 1:102, 1:103

**Comment by tpoterba** [comment]
I do need to change it actually, to indicate that 105 isn't included, but neither is 104!

**Comment by jbloom22** [comment]
Great, this is much clearer now.

**Pull request merged**
