### PR TITLE
[query] Use index counts rather than index iterator for reads

### PR DESCRIPTION
**Pull request by chrisvittal**
To do this, expose the necessary methods to get the start and end bounds
of an interval queries position within the index. Then just add
a counter to the iterators.

### CODE REVIEW

**Comment by chrisvittal** [comment]
Let's see how ci does

**Comment by tpoterba** [comment]
Can you benchmark?

**Comment by tpoterba** [comment]
Are the benchmarks you posted on #11061 for this branch?

**Comment by chrisvittal** [comment]
yes oops maybe shouldn't post them at 3am

Left is old, right is new, indexed reads got faster, combiner got faster.

```
                                        Benchmark Name      Ratio     Time 1     Time 2   Mem Ratio   Mem 1 (MB)   Mem 2 (MB)
                                        --------------      -----     ------     ------   ---------   ----------   ----------
                           table_read_force_count_ints     120.7%      6.734      8.127      100.0%            1            1
                      ndarray_matmul_float64_benchmark     113.3%      2.968      3.363      100.0%            1            1
                        matrix_table_scan_count_rows_2     112.5%     84.908     95.516      100.0%            1            1
                                read_force_count_p1000     112.3%      3.286      3.692      100.0%            1            1
                                     union_p1000_p1000     109.8%      6.860      7.531      100.0%            1            1
                                sentinel_read_gunzip_2     109.4%     16.148     17.659      100.0%            1            1
                                       union_p10_p1000     109.3%     73.727     80.584      100.0%            1            1
                         write_range_matrix_table_p100     109.2%      5.292      5.777      100.0%            1            1
                               table_aggregate_counter     109.1%     20.077     21.911      100.0%            3            3
                             python_only_10k_transform     108.9%     34.839     37.950      100.0%            1            1
                                sentinel_read_gunzip_3     108.8%     16.276     17.712      100.0%            1            1
                                           split_multi     108.1%     13.139     14.209      100.0%            1            1
                                sentinel_read_gunzip_1     107.6%     16.038     17.263      100.0%            1            1
                                         join_p10_p100     107.4%     11.960     12.848      100.0%            1            1
                             table_aggregate_array_sum     107.2%      8.820      9.453      100.0%            1            1
               table_foreign_key_join_same_cardinality     107.1%     11.470     12.281      100.0%            3            3
                             import_and_transform_gvcf     106.9%     88.277     94.371      100.0%            1            1
                              import_bgen_filter_count     106.8%    156.189    166.814      100.0%            7            7
       table_annotate_many_nested_dependence_constants     106.8%      6.125      6.539      100.0%            1            1
                                                  king     106.3%    425.661    452.628      100.0%            4            4
                                       union_p1000_p10     105.8%     75.901     80.305      100.0%            1            1
                              shuffle_order_by_10m_int     105.6%     54.898     57.987      100.0%            2            2
                shuffle_key_by_aggregate_good_locality     105.3%      9.548     10.051      100.0%           24           24
                       table_big_aggregate_compilation     105.1%     69.388     72.944      100.0%            1            1
                            matrix_multi_write_nothing     104.9%    220.009    230.853      100.0%            1            1
            blockmatrix_write_from_entry_expr_range_mt     104.9%     73.578     77.182      100.0%            1            1
                               write_range_table_p1000     104.7%     26.990     28.267      100.0%            1            1
                                   sentinel_cpu_hash_1     104.7%     26.863     28.127      100.0%            1            1
                                             sample_qc     104.4%     20.570     21.477      100.0%            2            2
                               import_gvcf_force_count     104.3%     74.809     78.025      100.0%            1            1
        table_foreign_key_join_left_higher_cardinality     104.0%     12.035     12.522      100.0%            3            3
                             table_aggregate_int_stats     104.0%     13.214     13.747      100.0%            1            1
                               matrix_table_take_entry     103.9%      1.498      1.557      100.0%            1            1
                      logistic_regression_rows_wald_nd     103.8%     33.613     34.900      100.0%         1257         1257
                           import_bgen_force_count_all     103.8%    154.573    160.491      100.0%            7            7
                        table_read_force_count_strings     103.7%      4.447      4.614      100.0%            1            1
                                            table_show     103.7%      1.136      1.179      100.0%            1            1
                                 read_force_count_p100     103.4%      1.756      1.816      100.0%            1            1
                                  table_key_by_shuffle     103.3%      5.211      5.384      100.0%            2            2
    matrix_table_nested_annotate_rows_annotate_entries     103.2%     14.039     14.487      100.0%            2            2
                                             pc_relate     103.1%    154.830    159.689      100.0%            2            2
               table_big_aggregate_compile_and_execute     102.9%     75.331     77.540      100.0%            1            1
                          large_range_matrix_table_sum     102.6%    141.228    144.855      100.0%           17           17
           variant_and_sample_qc_nested_with_filters_2     102.6%     21.046     21.586      100.0%            1            1
                                import_bgen_info_score     102.4%    201.001    205.852      100.0%            4            4
                                   group_by_take_rekey     102.4%      7.720      7.904      100.0%            4            4
                                       pc_relate_5k_5k     102.2%    365.502    373.592      100.0%            2            2
                    export_range_matrix_table_row_p100     102.2%      2.985      3.050      100.0%            1            1
                   table_range_array_range_force_count     102.1%      3.172      3.240      100.0%          382          382
                                table_range_join_1b_1b     102.1%    201.584    205.802      100.0%            1            1
            export_range_matrix_table_entry_field_p100     102.0%      9.168      9.350      100.0%            1            1
                         logistic_regression_rows_wald     101.8%     29.053     29.565      100.0%            1            1
                          test_left_join_region_memory     101.7%      3.482      3.542      100.0%          573          573
                                write_range_table_p100     101.7%      9.127      9.278      100.0%            1            1
                            table_aggregate_approx_cdf     101.5%     55.065     55.900      100.0%            1            1
                               table_range_force_count     101.5%      2.107      2.139      100.0%            1            1
                                   ld_prune_profile_25     101.5%    507.800    515.460      100.0%           94           94
                             matrix_table_entries_show     101.5%      2.376      2.411      100.0%            2            2
                                      join_p1000_p1000     101.5%      8.696      8.823      100.0%            1            1
                              table_scan_prev_non_null     101.3%     72.219     73.167      100.0%            1            1
                                        join_p1000_p10     101.3%     73.757     74.700      100.0%            1            1
                                            variant_qc     101.2%     10.006     10.128      100.0%            1            1
                         test_map_filter_region_memory     101.2%      2.015      2.039      100.0%          382          382
                                   sentinel_cpu_hash_2     101.0%     26.941     27.204      100.0%            1            1
                block_matrix_to_matrix_table_row_major     101.0%    236.016    238.277      100.0%            2            2
                 table_annotate_many_nested_dependence     100.9%      6.497      6.555      100.0%            1            1
                                         join_p100_p10     100.9%     12.675     12.784      100.0%            1            1
blockmatrix_write_from_entry_expr_range_mt_standardize     100.9%    157.964    159.308      100.0%            3            3
                        ndarray_matmul_int64_benchmark     100.8%      7.479      7.542      100.0%            1            1
                          table_scan_sum_1k_partitions     100.8%      5.494      5.535      100.0%            1            1
                               python_only_10k_combine     100.8%      5.723      5.766      100.0%            1            1
                                table_aggregate_linreg     100.5%     40.314     40.512      100.0%            1            1
                             linear_regression_rows_nd     100.4%     61.070     61.287      100.0%            8            8
                 shuffle_key_by_aggregate_bad_locality     100.4%    402.881    404.310      100.0%            4            4
                            ndarray_addition_benchmark     100.2%      1.883      1.888      100.0%            1            1
                                matrix_table_rows_show     100.2%      1.289      1.292      100.0%            1            1
                  matrix_table_filter_entries_unfilter     100.0%      7.809      7.812      100.0%            1            1
                          block_matrix_nested_multiply     100.0%   1800.000   1800.000      100.0%            1            1
                       matrix_table_rows_is_transition     100.0%      1.049      1.049      100.0%            1            1
                                     table_import_ints      99.9%     98.798     98.659      100.0%            1            1
                                     table_range_means      99.8%      3.182      3.175      100.0%            1            1
                                  table_import_strings      99.6%     32.218     32.102      100.0%            1            1
                                      compile_2k_merge      99.6%    224.423    223.552      100.0%            8            8
                       gnomad_coverage_stats_optimized      99.5%     28.035     27.885      100.0%            1            1
                               mt_localize_and_collect      99.4%     10.046      9.982      100.0%           29           29
                                       union_p100_p100      99.3%      4.028      4.000      100.0%            1            1
                                        join_p100_p100      99.3%      5.961      5.920      100.0%            1            1
                                      import_vcf_write      98.6%     98.833     97.421      100.0%            2            2
                     table_group_by_aggregate_unsorted      98.4%      6.652      6.547      100.0%            4            4
                 matrix_table_decode_and_count_just_gt      98.4%      4.668      4.592      100.0%            1            1
                                        join_p10_p1000      98.3%     70.711     69.503      100.0%            1            1
                       import_bgen_force_count_just_gp      98.2%    158.500    155.583      100.0%            4            4
                                  make_ndarray_bench_2      98.2%     16.075     15.779      100.0%            3            3
                         test_inner_join_region_memory      98.1%      3.550      3.482      100.0%          573          573
                              group_by_collect_per_row      97.8%      3.108      3.039      100.0%            1            1
   hwe_normalized_pca_blanczos_small_data_0_iterations      97.7%     20.504     20.035      100.0%            9            9
                                linear_regression_rows      97.6%     54.321     53.022       97.8%            3            3
                                  kyle_sex_specific_qc      97.5%      9.679      9.436      100.0%            1            1
                       table_aggregate_take_by_strings      97.5%     12.211     11.903      100.0%            1            1
                                     matrix_table_show      97.2%      1.762      1.713      100.0%            1            1
                                     genetics_pipeline      97.1%     98.606     95.791      100.0%            3            3
    variant_and_sample_qc_nested_with_filters_4_counts      96.8%     84.209     81.486      100.0%            1            1
                                            export_vcf      96.7%     59.689     57.710      100.0%            1            1
                                 write_range_table_p10      96.4%      6.814      6.569      100.0%            1            1
                       table_group_by_aggregate_sorted      96.4%      6.606      6.366      100.0%            4            4
                     matrix_table_call_stats_star_star      96.3%      7.701      7.417      100.0%            1            1
              table_annotate_many_nested_no_dependence      96.2%      2.472      2.377      100.0%            1            1
                         matrix_table_array_arithmetic      96.1%      9.598      9.220      100.0%            1            1
                     shuffle_key_rows_by_65k_byte_rows      96.0%     13.613     13.066      100.0%            2            2
                                   sentinel_cpu_hash_3      95.9%     29.006     27.828      100.0%            1            1
                                    hwe_normalized_pca      95.9%     36.776     35.271      100.0%            1            1
                                   full_combiner_chr22      95.7%    300.410    287.627      105.6%          121          128
                      test_head_and_tail_region_memory      95.7%      1.918      1.836      100.0%          382          382
                       matrix_table_many_aggs_col_wise      95.6%     20.882     19.957      100.0%            4            4
                     matrix_table_entries_table_no_key      95.5%     11.016     10.525      100.0%            1            1
                        matrix_table_aggregate_entries      95.5%      6.424      6.136      100.0%            1            1
                 table_aggregate_downsample_worst_case      94.9%     18.166     17.239      100.0%            1            1
                       matrix_table_many_aggs_row_wise      94.8%     13.809     13.089      100.0%            1            1
                         matrix_table_decode_and_count      94.6%      6.652      6.295      100.0%            1            1
                      table_aggregate_downsample_dense      94.6%     47.326     44.775      100.0%          256          256
                                 variant_and_sample_qc      93.7%     32.292     30.243      100.0%            2            2
                                 import_vcf_count_rows      93.6%     17.780     16.644      100.0%            1            1
                                 matrix_table_take_row      93.4%      1.585      1.481      100.0%            1            1
                                      write_profile_mt      93.1%     59.722     55.615      100.0%            2            2
                                       split_multi_hts      92.3%     33.493     30.922      100.0%            1            1
                    shuffle_key_rows_by_4096_byte_rows      91.7%      8.177      7.497      100.0%            2            2
                                        union_p10_p100      91.5%     12.784     11.692      100.0%            1            1
                                           concordance      90.8%     39.971     36.295      100.0%            2            2
                                shuffle_key_rows_by_mt      90.2%     27.706     24.982      100.0%            3            3
                               per_row_stats_star_star      90.0%      6.401      5.758      100.0%            1            1
                           matrix_table_filter_entries      88.2%      8.156      7.196      100.0%            1            1
           variant_and_sample_qc_nested_with_filters_4      87.5%     38.366     33.568      100.0%            1            1
                           read_decode_gnomad_coverage      87.0%      2.922      2.543      100.0%            1            1
                                  read_force_count_p10      86.5%      1.370      1.186      100.0%            1            1
  hwe_normalized_pca_blanczos_small_data_10_iterations      84.5%     56.633     47.859      100.0%           10           10
                            matrix_table_entries_table      84.2%     18.644     15.701      100.0%            2            2
                                 read_with_index_p1000      77.0%     27.749     21.353      100.0%            1            1
----------------------
Harmonic mean: 99.6%
Geometric mean: 99.8%
Arithmetic mean: 100.0%
Median:  100.8%
```

**Review by tpoterba — APPROVED** [review]

**Pull request merged**
