### PR TITLE
[hailctl] update dependencies on modify

### PR DESCRIPTION
**Pull request by danking**
CHANGELOG: Fix hailctl dataproc modify to install dependencies of the wheel file.

### CODE REVIEW

**Comment by johnc1231** [comment]
@danking Did you try running this?

**Comment by danking** [comment]
No, but its the same string I used to install hail dependencies for Terra's notebooks. I can run a test now

**Comment by johnc1231** [comment]
This is also failing the `hailctl` tests

**Comment by danking** [comment]
tested, it works.

**Comment by johnc1231** [comment]
Still failing `hailctl` tests though.

**Comment by danking** [comment]
bump

**Review by johnc1231 — APPROVED** [review]

**Pull request merged**
