### PR TITLE
[hail] Shade most of our bundled dependencies

### PR DESCRIPTION
**Pull request by danking**
Our public interface is python. The public interface of Spark that we use, AFAICT, does not depend on any non-Spark-defined classes. Ergo, we should hide away all our dependencies.

I intended to shade every bundled package except for breeze-natives, because I think we want to take that from the cluster (and we're willing to lock into Spark's version). `RandBasis` (a breeze class) takes as argument a random generator from `math3`, so I keep the Apache Commons Math3 library unbundled and not shaded. Everything else should now be shaded.

### CODE REVIEW

**Comment by tpoterba** [comment]
error in test java:
```
[[TestNGClassFinder]] Unable to read methods on class is.hail.relocated.com.indeed.util.varexport.servlet.ViewExportedVariablesServlet - unable to resolve class reference freemarker/template/ObjectWrapper
Exception in thread "main" java.lang.NoClassDefFoundError: freemarker/template/ObjectWrapper
```

**Comment by danking** [comment]
It passed the dataproc tests.

**Comment by danking** [comment]
I have no idea what this means and I'm so angry but whatever. https://github.com/indeedeng/util/blob/master/varexport/build.gradle#L19-L22

**Comment by danking** [comment]
ok maybe that fixes it? Testing locally doesn't seem to encounter the issue.

**Comment by danking** [comment]
OK, one more change to accommodate the shuffler.

**Comment by tpoterba** [comment]
failing shuffler tests with UnsatisfiedLinkError.

**Comment by danking** [comment]
ugh so this is really annoying. Shading libraries with native libraries doesn't work out of the box. The SO file that indeed ships has a symbol like this:
```
0000000000001440 T _Java_com_indeed_util_mmap_MMapBuffer_mmap
```
But after relocation, the java counterpart's package doesn't match the package you see above. Ergo, link error.

**Comment by danking** [comment]
OK, this should work. We leak indeed's namespace (i.e. its not shaded), but hopefully that's a pretty rare package.

**Comment by danking** [comment]
Somewhat surprising that no one has written a shade plugin that renames SO symbols 🤷 . That's clearly the correct answer here.

**Comment by danking** [comment]
heh the internet suggests that renaming symbols in an SO is so hard as to be impossible.

**Pull request merged**
