### PR TITLE
[hail] Memory-efficient scan

### PR DESCRIPTION
**Pull request by danking**
This adds `SpillingCollectIterator` which avoids holding more than 1000 aggregation results in memory at one time. We could do something that [listens for GC events](https://stackoverflow.com/questions/30041332/a-useful-metric-for-determining-when-the-jvm-is-about-to-get-into-memory-gc-trou) and spills data if there's high memory pressure. That seems a bit error prone and hard.

How should I pipe the size limit down to TableMapRows? The only workable solution I can think of is a HailContext setting. Maybe I should bite the bullet and respond to memory pressure? Either way this should get Laurent cooking with gas.


Spilling ten local files and then reading them in is probably in the noise of timings. 🎉

Master 0.2.14-4da055db5a7b
```ipython
In [1]: %%time  
   ...:  
   ...: import hail as hl 
   ...: ht = hl.utils.range_table(10000, n_partitions=10000) 
   ...: ht = ht.annotate(rank = hl.scan.count())._force_count()                                                                                                                                             
CPU times: user 1.45 s, sys: 333 ms, total: 1.78 s
Wall time: 24.6 s
In [3]: %%time  
   ...:  
   ...: import hail as hl 
   ...: ht = hl.utils.range_table(1000000, n_partitions=1000) 
   ...: ht = ht.annotate(rank = hl.scan.count())._force_count()                                                                                                                                             
CPU times: user 6.23 ms, sys: 1.96 ms, total: 8.19 ms
Wall time: 1.33 s
```
This branch:
```ipython
In [2]: %%time  
   ...:  
   ...: import hail as hl 
   ...: ht = hl.utils.range_table(10000, n_partitions=10000) 
   ...: ht = ht.annotate(rank = hl.scan.count())._force_count()                                                                                                                                                                                                                 
CPU times: user 1.41 s, sys: 313 ms, total: 1.72 s
Wall time: 25.2 s

In [3]: %%time 
   ...:  
   ...: import hail as hl 
   ...: ht = hl.utils.range_table(1000000, n_partitions=1000) 
   ...: ht = ht.annotate(rank = hl.scan.count())._force_count() 
   ...:  
   ...:                                                                                                                                                                                                                                                                         
CPU times: user 4.72 ms, sys: 1.82 ms, total: 6.53 ms
Wall time: 1.41 s
```

---

Minor implementation note: I did the rigamarole with `runJob` because I wasn't sure that using `synchronized` in a constructor was kosher and I'm also generally weary of Scala's constructor syntax.

### CODE REVIEW

**Comment by danking** [comment]
cc: @cseed

**Comment by tpoterba** [comment]
> this should get Laurent cooking with gas.

I rather think it's going to explode, but at least it won't be fizzling out before getting to the meat of densify!

**Comment by tpoterba** [comment]
Looks awesome on a preliminary glance.

**Comment by danking** [comment]
ack hold on gotta get ordering right

**Comment by danking** [comment]
blah a bit more complicated than I want it to be, I'll finish this tomorrow.

**Pull request closed without merging**
