### PR TITLE
Lower MatrixWrite

### LINKED ISSUE #5446: Lower MatrixWrite

### PR DESCRIPTION
**Pull request by tpoterba**
Fixes #5446

Stacked on #5774

### CODE REVIEW

**Comment by patrick-schultz** [comment]
Err... was I not supposed to approve a stacked PR?

**Comment by tpoterba** [comment]
you were the reviewer for the dependent PR, so you did fully approve the change. It went in as one commit instead of two, which saves the CI some cycles and slightly obfuscates the git history 🤷‍♂️

**Comment by tpoterba** [comment]
I think in general don't approve stacked PRs? We could maybe add support in CI for not merging this with the stacked label, that would be cool

**Comment by tpoterba** [comment]
oh wait, they both merged... that seems like a CI bug...

**Comment by tpoterba** [comment]
unless -- the dependent PR was fully rebased, and so the SHA of the merged master was identical! That's actually possible.

**Comment by danking** [comment]
I think CI might have a bug right now wrt merging two approved and passing branches :/

**Pull request merged**
