### PR TITLE
Fix pc relate test

### PR DESCRIPTION
**Pull request by danking**
You were right about the cache'ing. Thanks @jbloom22 !

### CODE REVIEW

**Comment by danking** [comment]
I lowered the tolerance

**Comment by tpoterba** [comment]
why do you need the cache?

**Comment by danking** [comment]
@tpoterba evaluates it once, thus fixing the randomness for the subsequent comparison.

**Comment by tpoterba** [comment]
If it's not giving the same result on multiple evaluations, we have a bug.

**Comment by tpoterba** [comment]
The reproducible randomness guarantee of the IR states that the same IR evaluated multiple times will produce the same result

**Comment by danking** [comment]
@jbloom22 ?

**Comment by danking** [comment]
closing because this is probably not the right answer

**Pull request closed without merging**
