### PR TITLE
[www/docs] Complete scrolling fix

### PR DESCRIPTION
**Pull request by akotlar**
This scraps the html/css solution in favor of a JS one.

### CODE REVIEW

**Comment by akotlar** [comment]
@danking this is ready to look at.

**Comment by akotlar** [comment]
>Can you help me understand why we can't set a very negative z-index on whatever element is creating the offset or use one of these shorter solutions?

Sure. These solutions don't work because they interfere with the layout of content. What you linked above works fine with 1 element, but not with adjacent elements. All of these solutions try to make up for the fact that the browser will position the element at the top of the browser (has no concept of non-0 offset). The javascript solution fixes this by introducing that non-0-offset.

  - I tried every permutation of these solutions, including every solution at the link you provided, in the original fix. They all interfere with layout in the presence of nested and adjacent modified elements. There is no z-index solution possible for all combinations, at least without JS (because you need adjacent elements to have descending ordered z-indices).

MathJax was handling scrolling at page load. If you remove that line MathJax will scroll the page whenever it detects a hash in the URL.

"Since typesetting usually changes the vertical dimensions of the page, if the URL contains an anchor position, then after the page is typeset, you may no longer be positioned at the correct position on the page. MathJax can reposition to that location after it completes its initial typesetting of the page. This value controls whether MathJax will reposition the browser to the #hash location from the page URL after typesetting for the page"

   *  https://docs.mathjax.org/en/v2.7-latest/options/hub.html

  

The reason we use history instead of say updating location.href is because there is no way to prevent the browser from scrolling to that location when you update that value. It's undefeatable, as mentioned in the comments.

**Comment by akotlar** [comment]
Regarding history and fake pages: I’m confused as to why fake pages would be used, since upon refresh that fake page wouldn’t correspond to a real page, but this shouldn’t interfere. The behavior without this solution should be the same: the url is updated with a hash. If you’ve noticed a concrete issue, please share it, because I may not understand the specific use (e.g. RTD). Haven’t seen any issues in testing.

**Comment by danking** [comment]
OK, so the current solution addresses the problem, but:
- if MathJax changes the vertical layout of the page, we might have scrolled too far or not far enough to have the anchor located just below the header
- if we navigate to a new URL using any means other than clicking on an anchor tag, our history will have the URL with the special hash

**Comment by danking** [comment]
I cannot point to a specific bad behavior. My general sense of the docs is of an ever increasing pile of code that is too hard to reason about.

When something breaks or we want to add something new, we try several different things until one of them works (at least well enough), we commit that, and don't think about it until something new breaks.

I have no better solution, so I suppose we should go with this, even though the situation in the presence of MathJax seems broken.

**Comment by akotlar** [comment]
> if MathJax changes the vertical layout of the page, we might have scrolled too far or not far enough to have the anchor located just below the header

I haven't seen the issue in practice, but it would be better to listen to mathjaxj unload. Anchor tags / clicks of course wouldn't be affected.

> if we navigate to a new URL using any means other than clicking on an anchor tag, our history will have the URL with the special hash

I don't think there's anything special about the hash; without this solution clicking on an anchor tag should produce exactly the same behavior (a #id appended).

**Comment by akotlar** [comment]
@danking should address point 1

**Pull request merged**
