### PR TITLE
[k8s] policy/v1beta1/PodDisruptionBudget => policy/v1/...

### PR DESCRIPTION
**Pull request by danking**

### CODE REVIEW

**Comment by danking** [comment]
Seen in a deploy:
```
Warning: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget

```

**Comment by daniel-goldstein** [comment]
Looks like an issue with AKS support for the reosurce?

**Comment by danking** [comment]
Mmm. We should upgrade AKS to 1.21.x. I'll address this after March 28th though.

**Comment by danking** [comment]
WIP, to avoid merging while azure isn't required.

**Comment by daniel-goldstein** [comment]
I'm upgrading Azure currently to 1.21.9, so this should start to pass hopefully

**Review by daniel-goldstein — APPROVED** [review]
Not worth beating out qb28 PRs but this works now that I've upgraded AKS

**Pull request merged**
