### PR TITLE
Added an option to annotate all variants (default false) to filter_al…

### PR DESCRIPTION
**Pull request by lfrancioli**
…leles

Note: The previous behavior was to always annotate all variants, regardless of whether an allele was filtered at this variant or not.

### CODE REVIEW

**Comment by tpoterba** [comment]
This behavior can produce type errors, I think

**Comment by lfrancioli** [comment]
ah, you're totally right! This needs more thoughts :(

**Comment by tpoterba** [comment]
Can you give an example where you don't want to annotate variants where an allele wasn't filtered?

**Comment by lfrancioli** [comment]
It was really for performance: we want to remove the filtered allele(s) from R, A and G-based annotations. Now for the gnomAD VDS there are ~ 40 of these.

**Comment by tpoterba** [comment]
I'm not sure this will make such a performance difference in the common case -- the genotype-level downcode/subset operation will dominate runtime

**Comment by lfrancioli** [comment]
Fair enough. I'm happy to close the issue given that it's not trivial with respect to annotations and might not give a large gain.

**Comment by lfrancioli** [comment]
so just to make it more concrete, it's ~40 stmts like:
`va.info.AC_AFR = aIndices[1:].map(i => va.info.AC_AFR[i - 1])`

a few are worse:
`va.info.GC_AMR = let removed_alleles = range(1, v.nAltAlleles + 1).filter(i => !aIndices.toSet.contains(i)).toSet in
range(va.info.GC_AMR.size).filter(i => !removed_alleles.contains(gtj(i)) && !removed_alleles.contains(gtk(i)))`

And most of the 250M variants in gnomad are bi-allelic

**Pull request closed without merging**
