### PR TITLE
Pass authorisation token to Query Batch backend

### PR DESCRIPTION
**Pull request by vladsaveliev**
Similar to https://github.com/hail-is/hail/pull/11435, adding `token` parameter for `init_batch` as well.

### CODE REVIEW

**Review by danking — APPROVED** [review]

**Comment by vladsaveliev** [comment]
Thanks for approving @danking!

(Note that I don't have permissions to merge PRs)

**Comment by vladsaveliev** [comment]
I can't see the test logs though and what is failing exactly :(

**Comment by danking** [comment]
I'm pretty sure this is due to the database getting overloaded by concurrent PRs. I'm gonna retry the builds.

**Comment by danking** [comment]
We separately need a better story for preventing PRs from starving one another of db resources.

**Pull request merged**
