### PR TITLE
prototype experimental.define_function

### PR DESCRIPTION
**Pull request by cseed**
@chrisvittal your functions, sir:

```
        f = hl.experimental.define_function(
            lambda a, b: (a + 7) * b, hl.tint32, hl.tint32)
        self.assertEqual(hl.eval(f(1, 3)), 24)

```

### CODE REVIEW

**Comment by chrisvittal** [comment]
When I attempt to rewrite `transform` to use a function, I'm getting a parser error

```
is.hail.utils.HailException: no conversion found for __uid_1(struct{locus: locus<GRCh38>, alleles: array<str>, rsid: str, qual: float64, filters: set<str>, info: struct{BaseQRankSum: float64, ClippingRankSum: float64, DP: int32, END: int32, ExcessHet: float64, MQ: float64, MQRankSum: float64, MQ_DP: int32, QUALapprox: int32, RAW_MQ: float64, ReadPosRankSum: float64, VarDP: int32}, __entries: array<struct{AD: array<int32>, DP: int32, GQ: int32, GT: call, MIN_DP: int32, PGT: call, PID: str, PL: array<int32>, SB: array<int32>}>})
	at is.hail.utils.ErrorHandling$class.fatal(ErrorHandling.scala:9)
	at is.hail.utils.package$.fatal(package.scala:26)
	at is.hail.expr.ir.package$.invoke(package.scala:76)
	at is.hail.expr.ir.IRParser$.ir_value_expr_1(Parser.scala:751)
	at is.hail.expr.ir.IRParser$.ir_value_expr(Parser.scala:517)
	at is.hail.expr.ir.IRParser$.ir_value_expr_1(Parser.scala:718)
	at is.hail.expr.ir.IRParser$.ir_value_expr(Parser.scala:517)
	at is.hail.expr.ir.IRParser$.named_value_ir(Parser.scala:500)
	at is.hail.expr.ir.IRParser$$anonfun$named_value_irs$1.apply(Parser.scala:495)
	at is.hail.expr.ir.IRParser$$anonfun$named_value_irs$1.apply(Parser.scala:495)
	at is.hail.expr.ir.IRParser$.repUntil(Parser.scala:282)
	at is.hail.expr.ir.IRParser$.named_value_irs(Parser.scala:495)
	at is.hail.expr.ir.IRParser$.ir_value_expr_1(Parser.scala:714)
	at is.hail.expr.ir.IRParser$.ir_value_expr(Parser.scala:517)
	at is.hail.expr.ir.IRParser$.table_ir_1(Parser.scala:943)
	at is.hail.expr.ir.IRParser$.table_ir(Parser.scala:850)
	at is.hail.expr.ir.IRParser$.table_ir_1(Parser.scala:942)
	at is.hail.expr.ir.IRParser$.table_ir(Parser.scala:850)
	at is.hail.expr.ir.IRParser$$anonfun$table_ir_children$1.apply(Parser.scala:846)
	at is.hail.expr.ir.IRParser$$anonfun$table_ir_children$1.apply(Parser.scala:846)
	at is.hail.expr.ir.IRParser$.repUntil(Parser.scala:282)
	at is.hail.expr.ir.IRParser$.table_ir_children(Parser.scala:846)
	at is.hail.expr.ir.IRParser$.table_ir_1(Parser.scala:935)
	at is.hail.expr.ir.IRParser$.table_ir(Parser.scala:850)
	at is.hail.expr.ir.IRParser$.table_ir_1(Parser.scala:942)
	at is.hail.expr.ir.IRParser$.table_ir(Parser.scala:850)
	at is.hail.expr.ir.IRParser$.table_ir_1(Parser.scala:942)
	at is.hail.expr.ir.IRParser$.table_ir(Parser.scala:850)
	at is.hail.expr.ir.IRParser$.table_ir_1(Parser.scala:946)
	at is.hail.expr.ir.IRParser$.table_ir(Parser.scala:850)
	at is.hail.expr.ir.IRParser$.table_ir_1(Parser.scala:946)
	at is.hail.expr.ir.IRParser$.table_ir(Parser.scala:850)
	at is.hail.expr.ir.IRParser$.table_ir_1(Parser.scala:942)
	at is.hail.expr.ir.IRParser$.table_ir(Parser.scala:850)
	at is.hail.expr.ir.IRParser$.table_ir_1(Parser.scala:942)
	at is.hail.expr.ir.IRParser$.table_ir(Parser.scala:850)
	at is.hail.expr.ir.IRParser$.matrix_ir_1(Parser.scala:1112)
	at is.hail.expr.ir.IRParser$.matrix_ir(Parser.scala:999)
	at is.hail.expr.ir.IRParser$.ir_value_expr_1(Parser.scala:806)
	at is.hail.expr.ir.IRParser$.ir_value_expr(Parser.scala:517)
	at is.hail.expr.ir.IRParser$$anonfun$parse_value_ir$2.apply(Parser.scala:1192)
	at is.hail.expr.ir.IRParser$$anonfun$parse_value_ir$2.apply(Parser.scala:1192)
	at is.hail.expr.ir.IRParser$.parse(Parser.scala:1186)
	at is.hail.expr.ir.IRParser$.parse_value_ir(Parser.scala:1192)
	at is.hail.expr.ir.IRParser$.parse_value_ir(Parser.scala:1191)
	at is.hail.expr.ir.IRParser.parse_value_ir(Parser.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
```

My updated code is at https://github.com/chrisvittal/hail/commit/92d18b7c5e28db82f2502980b44d48b730d8f000

**Comment by cseed** [comment]
This is a type error: your input argument doesn't match the declared type of the function.  Try `assert transform_row_type == mt.row.dtype` before the application of `transform_row_f`.  I'll beef up the error reporting of my define_function prototype so the error gets caught before hitting the JVM.

**Comment by chrisvittal** [comment]
It does though. That assertion returns true.

**Comment by cseed** [comment]
I don't see an assert in the linked code.

Either way, I'll try to look at this tonight or after my talk in the morning.

**Comment by cseed** [comment]
What's `mt.row._parsable_string()`?  The issue here might be missingness.  The types coming from Python will never be required.

**Comment by chrisvittal** [comment]
```
# t is the localized table, imported from a vcf with array_elements_missing=True
# c is hail.experimental.vcf_combiner
In [3]: t.row.dtype._parsable_string()
Out[3]: 'Struct{locus:Locus(GRCh38),alleles:Array[String],rsid:String,qual:Float64,filters:Set[String],info:Struct{BaseQRankSum:Float64,ClippingRankSum:Float64,DP:Int32,END:Int32,ExcessHet:Float64,MQ:Float64,MQRankSum:Float64,MQ_DP:Int32,QUALapprox:Int32,RAW_MQ:Float64,ReadPosRankSum:Float64,VarDP:Int32},__entries:Array[Struct{AD:Array[Int32],DP:Int32,GQ:Int32,GT:Call,MIN_DP:Int32,PGT:Call,PID:String,PL:Array[Int32],SB:Array[Int32]}]}'

In [4]: c.transform_row_type._parsable_string()
Out[4]: 'Struct{locus:Locus(GRCh38),alleles:Array[String],rsid:String,qual:Float64,filters:Set[String],info:Struct{BaseQRankSum:Float64,ClippingRankSum:Float64,DP:Int32,END:Int32,ExcessHet:Float64,MQ:Float64,MQRankSum:Float64,MQ_DP:Int32,QUALapprox:Int32,RAW_MQ:Float64,ReadPosRankSum:Float64,VarDP:Int32},__entries:Array[Struct{AD:Array[Int32],DP:Int32,GQ:Int32,GT:Call,MIN_DP:Int32,PGT:Call,PID:String,PL:Array[Int32],SB:Array[Int32]}]}'

In [5]: c.transform_row_type._parsable_string() == t.row.dtype._parsable_string()
Out[5]: True
```

**Comment by chrisvittal** [comment]
I am still getting the same error when I take the type explicitly from the table I am trying to transform.

Updated code is here:
https://github.com/chrisvittal/hail/blob/404cbd2b3255fc58656801febccce6ed98e594b9/hail/python/hail/experimental/vcf_combiner.py#L13-L59

**Pull request merged**
