### PR TITLE
[query] Add StreamZipJoinProducers node to zip join streams defined by an IR function

### PR DESCRIPTION
**Pull request by tpoterba**
This will be used to merge GVCFs in O(1) IR.

WIP because I want to test end-to-end with the GVCF partition reader piece.

### CODE REVIEW

**Comment by danking** [comment]
one lint:
```
/usr/local/lib/python3.7/dist-packages/hail/ir/ir.py:1345:1: E302 expected 2 blank lines, found 1
```

**Comment by danking** [comment]
@tpoterba Should this be assigned to someone?

**Comment by tpoterba** [comment]
I definitely don't love the code duplication, but it's also not super easy to abstract.

**Comment by tpoterba** [comment]
current status -- I didn't have a chance to debug what went wrong when I abstracted out shared code between the two implementations. Can either debug that, or go back to the working earlier commit and try from there.

**Comment by tpoterba** [comment]
[d45cad3](https://github.com/hail-is/hail/pull/12904/commits/d45cad3f222ef4594fab10e95faf7eda64fa383b) is the working earlier version, I think

**Comment by chrisvittal** [comment]
closing in favor of my own PR

**Comment by danking** [comment]
link: https://github.com/hail-is/hail/pull/13222

**Pull request closed without merging**
