### PR TITLE
[gke] optimize utilization autoscaling and shrink nodes

### PR DESCRIPTION
**Pull request by danking**
I need to get GKE costs down further. The driver is now 3 CPU anyway.

@daniel-goldstein, I am not sure how to modify the Azure terraform. It appears this
is controlled by a variable which is already set to a 4 core machine?

### CODE REVIEW

**Comment by danking** [comment]
Obviously, we'll need to apply this PR by hand.

**Comment by daniel-goldstein** [comment]
Screen Shot 2022-06-29 at 5 17 43 PM
Not confusing at all

**Review by daniel-goldstein — DISMISSED** [review]
Should be `Standard_D3_v2`.

**Comment by danking** [comment]
🤦

**Comment by danking** [comment]
I could get behind D0, D1, D2, D3.

**Review by daniel-goldstein — APPROVED** [review]
Will need to let the AUS folks know. How do you want to handle the drain switch?

**Comment by danking** [comment]
I'll switch the nodes tomorrow morning. My plan was to follow the kubernetes-operations.md file. Manually managed for Google and the second section for Azure.

**Pull request merged**
