### PR TITLE
added drop_{rows, cols} to api2.

### PR DESCRIPTION
**Pull request by cseed**

### CODE REVIEW

**Comment by tpoterba** [comment]
I was going to suggest we leave this out for 0.2. With better-optimized tables, there will be very little reason to have one-dimensional matrices.

**Comment by tpoterba** [comment]
Instead of drop_samples, one should just do rows_table()!

**Comment by cseed** [comment]
I'm obviously sympathetic to this (I've even argued matrix should not have row/col annotations at all!)  But I have a few questions about how this will work:

The main interface problem I see is that there are naturally columnless matrices in our domain (sites files).  This PR was motivated by some code that Konrad sent me.  Are we going to have two versions of VEP and export_vcf, for example?

Second, it seems we can have either interface purity or performance in the short term.  I loosely think the latter is better (I would) so we can productively move people off 0.1 even if that means the interface is less stable (e.g. eventually we'll deprecate/remove the drop functions).  I want to say I can be convinced otherwise, but changing a range join to a table shuffle seems like a non-starter.

**Comment by tpoterba** [comment]
Alright, I'm OK with that. Let's see if we can remove these before 0.2 is released. If not, that's fine too.

**Pull request merged**
