### PR TITLE
[misc] Remove wheel dependence on `setuptools`

### LINKED ISSUE #14630: Installing from PyPI leads to a broken install
### What happened?

I installed from PyPI and obtained hail 0.2.132

I made sure I used a completely clean environment with nothing in it (using pixi). 

When I did 

```
import hail
```

I got this error:

```
>>> import hail
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/srinivas/test/.pixi/envs/default/lib/python3.12/site-packages/hail/__init__.py", line 40, in <module>
    from hail.utils import (
  File "/Users/srinivas/test/.pixi/envs/default/lib/python3.12/site-packages/hail/utils/__init__.py", line 4, in <module>
    from .hadoop_utils import (
  File "/Users/srinivas/test/.pixi/envs/default/lib/python3.12/site-packages/hail/utils/hadoop_utils.py", line 7, in <module>
    from hail.fs.hadoop_fs import HadoopFS
  File "/Users/srinivas/test/.pixi/envs/default/lib/python3.12/site-packages/hail/fs/hadoop_fs.py", line 8, in <module>
    from hailtop.fs.fs import FS
  File "/Users/srinivas/test/.pixi/envs/default/lib/python3.12/site-packages/hailtop/fs/__init__.py", line 1, in <module>
    from .fs_utils import (
  File "/Users/srinivas/test/.pixi/envs/default/lib/python3.12/site-packages/hailtop/fs/fs_utils.py", line 4, in <module>
    from hailtop.aiocloud.aiogoogle import GCSRequesterPaysConfiguration
  File "/Users/srinivas/test/.pixi/envs/default/lib/python3.12/site-packages/hailtop/aiocloud/aiogoogle/__init__.py", line 1, in <module>
    from .client import (
  File "/Users/srinivas/test/.pixi/envs/default/lib/python3.12/site-packages/hailtop/aiocloud/aiogoogle/client/__init__.py", line 8, in <module>
    from .storage_client import (
  File "/Users/srinivas/test/.pixi/envs/default/lib/python3.12/site-packages/hailtop/aiocloud/aiogoogle/client/storage_client.py", line 14, in <module>
    from hailtop.aiotools import FeedableAsyncIterable, WriteBuffer
  File "/Users/srinivas/test/.pixi/envs/default/lib/python3.12/site-packages/hailtop/aiotools/__init__.py", line 1, in <module>
    from .fs import (
  File "/Users/srinivas/test/.pixi/envs/default/lib/python3.12/site-packages/hailtop/aiotools/fs/__init__.py", line 1, in <module>
    from .copier import Copier, CopyReport, SourceCopier, SourceReport, Transfer, TransferReport
  File "/Users/srinivas/test/.pixi/envs/default/lib/python3.12/site-packages/hailtop/aiotools/fs/copier.py", line 7, in <module>
    import humanize
  File "/Users/srinivas/test/.pixi/envs/default/lib/python3.12/site-packages/humanize/__init__.py", line 1, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

```

I think this is largely because hail requires an ancient version of humanize (v1 vs v4)

In any case, the wheel on PyPI is broken and un-importable. 

There are other issues stemming from the underlying issue that there is no clear description of requirements and dependencies. 

### Version

0.2.132

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ehigham**
`hail` had a transitive dependency on `setuptools` via an ancient version of `humanize` that's removed by upgrading to the latest major revision. 
Bump `humanize` to major revision `4` and regenerate lock files.

Fixes #14630

### CODE REVIEW

**Comment by ehigham** [comment]
Tested by installing wheel in clean venv, importing and running basic hail commands

**Review by patrick-schultz — CHANGES_REQUESTED** [review]
I'm confused. You say this removes our dependence on setuptools, but I only see version bumps. Can you explain how this fixes the bug reported in #14630?

Also, it would be helpful to record for history what you ran to update all the `pinned-requirements.txt` files.

**Comment by ehigham** [comment]
Description updated.

> Also, it would be helpful to record for history what you ran to update all the pinned-requirements.txt files.

```bash
$ make generate-pip-lockfiles
```

**Review by patrick-schultz — APPROVED** [review]
Thanks!

**Review by iris-garden — APPROVED** [review]
Reproduced original error by building a wheel locally off of `main` and installing it into a new miniconda env without `setuptools`:

```bash
make -C hail shadowJar wheel HAIL_RELEASE_MODE=1
yes | conda create -n hail-test python=3.9
conda activate hail-test
pip uninstall setuptools
pip install hail/build/deploy/dist/hail-0.2.132-py3-none-any.whl
python -c "import hail"
```

Then ran the same commands on this branch, and confirmed there was no error.

Thanks for fixing this!

**Pull request merged**
