### PR TITLE
fix ci

### PR DESCRIPTION
**Pull request by danking**

### CODE REVIEW

**Comment by danking** [comment]
CI could not talk to GitHub due to this.

**Comment by tpoterba** [comment]
informative commit messages please!

**Comment by danking** [comment]
I added one when I force merged: https://github.com/hail-is/hail/commit/f5e1dd793ae1e936faeb121ab75b5335f93e04b7

**Comment by tpoterba** [comment]
ah, ok. It's nice to have it in the first line though, which makes searching a little easier

**Pull request merged**
