### PR TITLE
[batch] search help for batches, batch jobs

### PR DESCRIPTION
**Pull request by cseed**
Add an expandable element just below the search box.

Screen shots, unexpanded:

Screen Shot 2019-12-23 at 4 24 18 PM

And expanded:

Screen Shot 2019-12-23 at 4 24 41 PM

@akotlar A CSS thing I couldn't figure out, if you have any ideas: I wanted the width of the expanded help to be 75% the width of the table below it, but `max-width: 75%` doesn't work.  For now, I just set the max-width: 450px, which is 75% of the min-width of the table (now 600px).

### CODE REVIEW

**Comment by akotlar** [comment]
What happens if you set expand-content to “display: flex;”?

**Comment by cseed** [comment]
@akotlar will try and report back.  Thanks!

**Comment by akotlar** [comment]
I have a better solution, will PR

**Comment by akotlar** [comment]
I don't think this is possible without JS, if I understand what you want. The container will grow to the size of its largest element by default. If the largest element is the table, then max-width: 75% does the appropriate thing. If the largest element is your dropdown (because the Note text is long say), then the width of the dropdown will dominate. Using JS you can sample the table's width, and set the dropdown's width directly.

However, I think a more elegant solution is to set the width on the parent container (the outer flex-col-align-right) based on the size of the window, have the table stretch to fit that, and set 75% on the dropdown. I'll PR that, see if you like it.

Also no need for `border-spacing: 2px`, that is the default.

**Pull request merged**
