### PR TITLE
[batch] Allow python jobs to have file resources too

### PR DESCRIPTION
**Pull request by daniel-goldstein**
I feel like `ofile` semantics should apply the same to bash and python jobs. I don't believe this is a breaking change since `j.ofile` didn't really mean anything usable until now for python jobs IIUC.

### CODE REVIEW

**Comment by jigold** [comment]
I think I'm good with this change, but I just want to make sure my reasoning is the same as yours. In our "language" `j.ofile` is implied to be a temporary automatically localized / delocalized file. Doesn't matter whether it's from bash, c++, R, Python that wants to write / read from that file. I don't think there is anything special about PythonJobs that we'd want to reserve the `__getitem__` semantics for. Does this seem right?

**Review by jigold — APPROVED** [review]
Nice change!

**Comment by jigold** [comment]
Can you add a CHANGELOG comment somewhere?

**Comment by danking** [comment]
Ah this is really nice, I have wanted this for a while.

**Pull request merged**
