### PR TITLE
create hailtop module, update hail package setup.py

### PR DESCRIPTION
**Pull request by cseed**
I called it `hailtop`.

Next, I'll PR to put gear and batch_client in hailtop and then I think @johnc1231 will be unblocked on `hailctl batch`.

### CODE REVIEW

**Comment by cseed** [comment]
@tpoterba Is there a way to test the pip package still works?

**Comment by tpoterba** [comment]
`make install-wheel` and then `PYTHONPATH="" python -c "import hail; hail.init()"

**Comment by tpoterba** [comment]
you need to fix up some makefile logic

**Comment by cseed** [comment]
Thanks!  Yep, I just did.

**Comment by cseed** [comment]
`make install-wheel` changes my local environment?

**Comment by tpoterba** [comment]
no, but if you have PYTHONPATH set, it could override the generated package.

**Comment by cseed** [comment]
Wait, how's that?  Looks like it runs `pip uninstall hail ... install hail`.

**Comment by tpoterba** [comment]
I used to have PYTHONPATH set to `~/hail/hail/python` in my ~/.profile. This supercedes system package

**Comment by cseed** [comment]
> make install-wheel and then PYTHONPATH="" python -c "import hail; hail.init()"

Should this be an automated test?

**Comment by tpoterba** [comment]
I think we should use the wheel as the artifact passed around in build.yaml, then the distribution goes through the full suite!

**Comment by cseed** [comment]
Oh, yes, very nice.

**Pull request merged**
