### PR TITLE
[vcf-combiner] Miscellaneous Updates

### PR DESCRIPTION
**Pull request by chrisvittal**
These changes start moving the combiner away from being a gnomAD v3
specific application and into being a more general application.

The most exciting feature is the new interval calculator. Which creates
even intervals that can be used to repartition the data set.

### CODE REVIEW

**Comment by iitalics** [comment]
this breaks `run_combiner.py` right?

**Comment by chrisvittal** [comment]
Correct. Removed. Good catch.

**Comment by akotlar** [comment]
And drive_combiner.py

**Comment by iitalics** [comment]
I think `drive_combiner.py` is still fine

**Comment by chrisvittal** [comment]
drive_combiner doesn't use the removed functions.

**Comment by akotlar** [comment]
yes, but it does use modified functionality (namely info_to_keep is now potentially different).

**Comment by chrisvittal** [comment]
The only place outside of tests where `combine_gvcfs` is called is `drive_combiner`. And no user would have had the opportunity to use the old parameter, which was a workaround for a bug in GATK that's no longer relevant with the way the combiner output is used by downstream. Also this is still _highly experimental_ functionality.

**Pull request merged**
