### PR TITLE
[batch] refactor how jobs are submitted in batches

### PR DESCRIPTION
**Pull request by jigold**

### CODE REVIEW

**Comment by jigold** [comment]
This requires a database change so we should coordinate when this gets approved with @konradjk . I'm going to try updating the db by hand so we don't lose all of the data. But that may fail since I've never done it before.

FYI @danking

**Comment by konradjk** [comment]
I'm good for now!

**Comment by danking** [comment]
I looked at all the changes when reviewing the next PR.

**Comment by akotlar** [comment]
It would help next time to get a description. 

If I understand, state "closed" really means "batch and all related jobs have been submitted", so that that batch is no longer reentrant, and state transitions (complete/failed) are only allowed if this has been set. If so that sounds about right.

**Comment by jigold** [comment]
It means the user cannot hit the endpoint `/batches/{batch_id}/jobs/create` for that batch.

**Comment by akotlar** [comment]
Also prevents bookkeeping of state success and cancelled, and transition to "complete" right?

https://github.com/hail-is/hail/pull/6479/files#diff-379bcd812e1e6732be3f7d9ea9599d34R662

**Comment by jigold** [comment]
exactly

**Comment by jigold** [comment]
See #6490

**Pull request merged**
