### PR TITLE
[batch] Add MySQL support for Jobs table

### PR DESCRIPTION
**Pull request by jigold**
@cseed There are a lot of things in here that I didn't know exactly what to do, so I just got something working. You can't have async __init__ methods. Hence the work-around with `create`. Not sure what the SQL schema we want is. How to get the database set up for testing. Get it working on cloud...

### CODE REVIEW

**Comment by akotlar** [comment]
@jigold Your approach (a Db factory method) seems correct.

Here is an alternative implementation (https://github.com/kchmck/pyasyncinit), that enables the following

```
from asyncinit import asyncinit

@asyncinit
class MyClass:
    async def __init__(self, param):
        self.val = await self.deferredFn(param)

obj = await MyClass(42)
```

**Comment by jigold** [comment]
cool -- I'll test that out. IntelliJ kept telling me that wouldn't work, but maybe it's wrong.

**Comment by jigold** [comment]
I didn't read your comment carefully enough. Do we want to have all of these dependencies for our project? This is a more general question.

**Comment by jigold** [comment]
Depends on #5563

**Comment by akotlar** [comment]
@jigold If the concern is number of third party dependencies, I don’t really have an answer (number of third party dependencies last which productivity drops over some timespan). This library is something like 20 lines long, they just wrap __new__ and __init__ to make that awaitable. 

I also think your approach is fine!

**Comment by jigold** [comment]
Closing for now until I get the database in the cloud working!

**Pull request closed without merging**
