### PR TITLE
[hail] Teach MatrixTable how to HTML

### PR DESCRIPTION
**Pull request by danking**
stacks on https://github.com/hail-is/hail/pull/5666

Teaches Matrix Tables how to HTML

Screen Shot 2019-03-22 at 3 36 44 PM
Screen Shot 2019-03-22 at 3 36 37 PM
Screen Shot 2019-03-22 at 3 36 29 PM
Screen Shot 2019-03-22 at 3 36 34 PM

### CODE REVIEW

**Comment by danking** [comment]
kind of curious what @konradjk will think of this

**Comment by konradjk** [comment]
What happens if there are column fields?

**Comment by tpoterba** [comment]
this doesn't show column fields. I think show should treat both scopes symmetrically.

**Comment by danking** [comment]
By default neither column nor row fields are displayed. PR's welcome that add an option to display them with the table header :)

**Comment by tpoterba** [comment]
oh, OK, that is symmetric

**Comment by danking** [comment]
to be clear, there is an option to display row fields, but it defaults to `False`.

There's a lot of visual noise if you show both.

**Pull request merged**
