### PR TITLE
convert split_multi

### PR DESCRIPTION
**Pull request by danking**

### CODE REVIEW

**Comment by danking** [comment]
I think the difficult was mostly my ignorance of this part of the code! Glad I was forced to hack it.

**Comment by konradjk** [comment]
What about generic `split_multi`?

**Comment by danking** [comment]
@konradjk much harder due to the magic `aIndex` binding that is placed into the scope. Cotton is thinking about how to handle these situations.

**Comment by konradjk** [comment]
Oh I see. This is still all in strings. Ok, carry on

**Pull request merged**
