### PR TITLE
[datasets] remove gnomad_annotation_pext

### PR DESCRIPTION
**Pull request by danking**
This dataset was incorrectly written as an MT. gnomAD team is working on a fix. Until then,
we will remove it from the annotation db.

fyi @pwc2

### CODE REVIEW

**Comment by pwc2** [comment]
ah sorry I missed this! I made the changes earlier but hadn't created a PR yet, sorry for the extra work

**Comment by danking** [comment]
No worries!

**Comment by danking** [comment]
bump for approval, I fixed the lint error

**Review by tpoterba — APPROVED** [review]

**Comment by tpoterba** [comment]
whoops, didn't realize this was assigned to me 🤦

**Pull request merged**
