### PR TITLE
[hail] Interactive widget for Table/MatrixTable describe

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by tpoterba** [comment]
image

**Comment by akotlar** [comment]
Really cool, nice work!

**Comment by akotlar** [comment]
Why is the entirety of table.scala diff?

**Comment by tpoterba** [comment]
wtf...

**Comment by tpoterba** [comment]
Is this a git bug?
```
$ cp src/main/scala/is/hail/table/Table.scala /tmp/table1.scala
$ gco interactive-describe-2
Switched to branch 'interactive-describe-2'
Your branch is up to date with 'origin/interactive-describe-2'.
$ cp src/main/scala/is/hail/table/Table.scala /tmp/table2.scala
$ diff /tmp/table1.scala /tmp/table2.scala
```

**Comment by akotlar** [comment]
On mobile, but could be mode change?

**Comment by tpoterba** [comment]
they have the same md5 as well.

**Comment by tpoterba** [comment]
OH! this is a file in the OLD src root.

**Comment by tpoterba** [comment]
(shame on me for suspecting a git bug)

**Comment by akotlar** [comment]
> OH! this is a file in the OLD src root.

Linus is never wrong

**Comment by akotlar** [comment]
I’ve seen this/used it, so happy to approve

**Comment by tpoterba** [comment]
yes, sure. I'll ask Kumar for more feedback tomorrow.

**Pull request merged**
