### PR TITLE
Revert "Cpp5 - support for Scala-generated C++ (#4211)"

### PR DESCRIPTION
**Pull request by danking**
This reverts commit a286990cfcf8877dd597f838d72bfe74b83fcbb8.

### CODE REVIEW

**Comment by danking** [comment]
cc: @cseed @rcownie @catoverdrive 

Amanda saw this error with these changes:

```
amwang: fyi, this is the error the executor is seeing on a cluster with that jar:

ERROR: dlopen("/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1535651898654_0001/container_1535651898654_0001_01_000002/tmp/libhail8271834084559267793.so"): /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1535651898654_0001/container_1535651898654_0001_01_000002/tmp/libhail8271834084559267793.so)
FATAL: caught exception java.lang.UnsatisfiedLinkError: /hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1535651898654_0001/container_1535651898654_0001_01_000002/tmp/libhail8271834084559267793.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1535651898654_0001/container_1535651898654_0001_01_000002/tmp/libhail8271834084559267793.so)
java.lang.UnsatisfiedLinkError: /hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1535651898654_0001/container_1535651898654_0001_01_000002/tmp/libhail8271834084559267793.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1535651898654_0001/container_1535651898654_0001_01_000002/tmp/libhail8271834084559267793.so)
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
    at java.lang.Runtime.load0(Runtime.java:809)
    at java.lang.System.load(System.java:1086)
    at is.hail.nativecode.NativeCode.<clinit>(NativeCode.java:27)
    at is.hail.nativecode.NativeBase.<init>(NativeBase.scala:22)
    at is.hail.annotations.Region.<init>(Region.scala:33)
    at is.hail.annotations.Region$.apply(Region.scala:15)
    at is.hail.rvd.RVDContext$.default(RVDContext.scala:8)
    at is.hail.rvd.package$RVDContextIsPointed$.point(package.scala:8)
    at is.hail.rvd.package$RVDContextIsPointed$.point(package.scala:6)
    at is.hail.utils.package$.point(package.scala:593)
    at is.hail.sparkextras.ContextRDD$$anonfun$apply$2.apply(ContextRDD.scala:17)
    at is.hail.sparkextras.ContextRDD$$anonfun$apply$2.apply(ContextRDD.scala:17)
    at is.hail.sparkextras.ContextRDD.is$hail$sparkextras$ContextRDD$$sparkManagedContext(ContextRDD.scala:129)
    at is.hail.sparkextras.ContextRDD$$anonfun$run$1.apply(ContextRDD.scala:138)
    at is.hail.sparkextras.ContextRDD$$anonfun$run$1.apply(ContextRDD.scala:137)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:797)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:797)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
    at org.apache.spark.scheduler.Task.run(Task.scala:108)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Daniel King: JAR and ZIP are both deleted from google storage. for the record the bad SHA was 5702f5c6b299
```

A discuss user [is seeing that the JVM crashes when he tries to use hail](http://discuss.hail.is/t/gcp-py4jnetworkerror-answer-from-java-side-is-empty/630):

```
hl.init()
mt = hl.read_matrix_table('gs://hail-datasets/hail-data/1000_genomes_phase3_autosomes.GRCh37.mt')
mt.describe() ...
mt.rsid.show(5)
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1035, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 883, in send_command
    response = connection.send_command(command)
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1040, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving

```

**Comment by danking** [comment]
Correct.

**Comment by danking** [comment]
We need tests that actually run on dataproc.

**Comment by catoverdrive** [comment]
I wonder if we can fix this by kicking the dataproc image version that cloudtools is using up to `1.2-deb9`?

**Comment by danking** [comment]
Fixing with a change to dataproc image version requires a cloud tools upgrade form all our users. Perhaps we should start a new latest-hash file and push a cloud tools update that looks there and uses `1.2-deb9`?

**Pull request merged**
