### PR TITLE
[hail] use val for IndexedRVDSpec partitioner

### PR DESCRIPTION
**Pull request by chrisvittal**
When using indexed reads, we were creating a new partitioner for every
partiton in tmpPartitioner. It was not good.

### CODE REVIEW

**Comment by tpoterba** [comment]
oof, this is bad enough we might want to do yet another release

**Comment by chrisvittal** [comment]
You have no idea. I went from waiting over an hour for a stage to begin to fast enough.

**Comment by chrisvittal** [comment]
This uses an undocumented feature. It can wait for a little while.

**Comment by tpoterba** [comment]
oh, phew, it's only on readIndexed

**Comment by chrisvittal** [comment]
Yeah.

**Comment by chrisvittal** [comment]
This benchmark is in some ways bad. The real problem is in the compiler/orchestration, not in any execution. I feel like we need a `_do_nothing()` that doesn't execute any code, but runs a pipeline through everything in the compiler and stops short before anything that would submit a spark job.

**Comment by tpoterba** [comment]
yeah, I agree. But we can also get that effect by having tiny data but big pipelines

**Pull request merged**
