### PR TITLE
Add py4j to path using pattern matching rather than hardcoded version

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by jbloom22** [comment]
Change to `echo $SPARK_HOME/python/lib/py4j*-src.zip`

**Comment by jbloom22** [comment]
I'm having second thoughts on echo. let's let @danking tie break.

**Comment by danking** [comment]
👍

Either way seems fine to me. Slight preference for `echo` because it's a shell built-in, so no external executables are invoked. AFAICT, [a POSIX-compliant shell](http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html) will do what we want. If there is more than one py4j in that directory things will definitely break. AFAIK, more than one py4j in that directory is an error, correct? If not, we could do something like `$(ls ... | tr '\n' ':')` to list all of them.

**Comment by tpoterba** [comment]
Should be only one.

**Pull request merged**
