### PR TITLE
[batch] Check for case sensitive billing project names

### PR DESCRIPTION
**Pull request by jigold**
This is a mitigation and does not solve the issue where we have existing duplicated billing project names. I'm not entirely sure adding BINARY in front of the search value is correct, but I was going off of this post. Apparently, if you use `BINARY name = %s` instead of `name = BINARY %s`, then you pay a performance hit because you cannot use the index any longer.

https://stackoverflow.com/questions/5629111/how-can-i-make-sql-case-sensitive-string-comparison-on-mysql

### CODE REVIEW

**Review by danking — CHANGES_REQUESTED** [review]
I'm pretty sure this will prevent us from using the index with any of these where conditions. It seems like fixing the tables themselves is the right move, yeah?

**Comment by danking** [comment]
I like the tests

**Comment by jigold** [comment]
Let me do some experiments and see whether there is a performance cost. The third post down seemed to think the way I wrote it there shouldn't be a performance penalty and it should still use the index. I'm not sure whether I believe that.

**Comment by jigold** [comment]
I think I should try writing the full correct solution with the correct collation type and see how painful it will be.

**Comment by jigold** [comment]
I'm going to close this in favor of solving it a better way now that the job regions PR is basically done.

**Pull request closed without merging**
