### PR TITLE
Implemented TDT

### PR DESCRIPTION
**Pull request by JKosmicki**
Implemented the transmission disequilibrium test (TDT) in hail.  TDT tests for variants that are inherited more or less than what would be expected by chance (i.e., 50%).

### CODE REVIEW

**Comment by danking** [comment]
Hey @JKosmicki,

Your branch has diverged from master a fair bit at this point. I can get this PR moving again if you do two simple things for me:

 - rebase your commit on hail-is's master
 - apply a patch I created, which fixes some compile errors.


If you don't already have a remote (you can list remotes with `git remote -v`) for `hail-is/hail`, let's create one:
```bash
git remote add hi https://github.com/hail-is/hail.git
```
I'll refer to this remote as `hi` from now on. If you already had a remote for `hail-is/hail` then substitute its name below for `hi`.

First, we rebase to get the latest code from `hail-is/hail`'s `master` branch
```bash
git fetch hi
git rebase hi/master tdt
```

And now we download [this `.patch` file](https://github.com/danking/hail/commit/6ea3d77684596abf171920e014c2aedd2a209f9c.patch) and apply it to the `tdt` branch:

```bash
git am the/path/to/that/file/you/downloaded.patch
```

**Comment by JKosmicki** [comment]
Thank you for the clear and easy-to-follow instructions!  I've rebased my commit and applied your patch.  What do I need to do now?

**Comment by danking** [comment]
@JKosmicki, @tpoterba Is going to take a look and perhaps request some edits before merge. Thanks for rebasing!

**Comment by JKosmicki** [comment]
Glad that fixed some of the issues; thanks so much for your help!

**Comment by tpoterba** [comment]
I've got some changes I think we should make.  I need to think about the best way to organize them, so I'll give you some concrete suggestions tomorrow

**Comment by danking** [comment]
@tpoterba ping

**Comment by tpoterba** [comment]
Yeah, sorry about this.  I've been working on de novo stuff on the side and am really unhappy about the current trio abstraction (pasting a bunch of code in from Mendel errors).  I'll review as it is now, though, so we can get this in.

**Comment by danking** [comment]
@tpoterba That sounds great! Thanks

**Comment by danking** [comment]
Closing, conversation moved to PR 1044

**Pull request closed without merging**
