### PR TITLE
[Github] Security impact field in templates

### PR DESCRIPTION
**Pull request by cjllanwarne**
For feedback - a couple of potential templates for capturing security impacts at either the issue or PR level.

### CODE REVIEW

**Review by iris-garden — CHANGES_REQUESTED** [review]
Looks good! Noticed one problem with the Issue template, but aside from that, my only feedback is:

I don't know if it makes the most sense to me to have both Issues and PRs capture this information. Issues can get outdated somewhat easily if the nature of the work being done ends up changing in the process of doing it. Also, there are some cases where it makes sense to have multiple PRs per Issue, where each might have different security implications. Since cases exist where it only makes sense to put this information in the PR description, and I'm not sure there are cases where it only makes sense to put it in an Issue, and for the sake of consistency, I would prefer to just use the PR description. Happy to be overruled if the rest of the team finds having the option to put it in Issues helpful, though!

Also this is definitely outside the scope of this PR, but maybe we could create a custom GitHub Action (similar to [this](https://github.com/kentaro-m/task-completed-checker-action)) to check that at least one of these boxes is checked off before allowing a merge, so it's not just up to the reviewers to catch that.

**Comment by cjllanwarne** [comment]
@iris-garden I think you make great points! And I agree, across many PRs we probably do want to be analyzing the security impacts at every stage, not just as a one-off "when we're done it will be X" analysis in the ticket... So I guess in my mind the _only_ real reason for using the issue-level review would be for tracking the impact of non-code changes (like configuration updates to production). I will try to make the templates reflect that distinction

**Review by patrick-schultz — APPROVED** [review]
Thanks for adding these Chris. Nice and simple, and we can always tweak later after we've spent some time with them.

**Review by iris-garden — APPROVED** [review]
Looks good, thanks for making those changes!

**Pull request merged**
