### PR TITLE
Added MutableGenotype, MutableGenotypeStreamIterator, test

### PR DESCRIPTION
**Pull request by jbloom22**

### CODE REVIEW

**Comment by cseed** [comment]
Great.  Looking forward to getting this plugged in.

**Comment by tpoterba** [comment]
but where are the pretty plots this time? ☹️

**Comment by jbloom22** [comment]
Sorry @tpoterba , there's still more work to do to integrate this throughout Hail without tests failing. That's the next step!

**Comment by tpoterba** [comment]
ahhh that's ok, I'm just excited!

**Comment by jbloom22** [comment]
@cseed this code in GenericGenotype is not in MutableGenotype.  Do you think it belongs in read? Seems like it will hit (relative) performance more significantly in the mutable case.

```
  require(unboxedGT >= -1, s"invalid _gt value: $unboxedGT")
  require(unboxedDP >= -1, s"invalid _dp value: $unboxedDP")

  if (isDosage) {
    require(unboxedGQ == -1)
    if (unboxedPX == null)
      require(unboxedGT == -1)
    else {
      require(unboxedPX.sum == 32768)
      require(unboxedGT == Genotype.gtFromLinear(unboxedPX).getOrElse(-1))
    }
  }
```

**Pull request merged**
