### PR TITLE
Unkeyed option for PC relate

### PR DESCRIPTION
**Pull request by konradjk**
In order to enable use on pre-emptibles

### CODE REVIEW

**Comment by tpoterba** [comment]
I'm pretty sure just doing a `key_by()` on the result has the same semantics

**Comment by danking** [comment]
I think Tim is right and that seems better than an undocumented hidden option, though I admit it's about as undocumented and hidden.

**Comment by konradjk** [comment]
Yes, agreed. I thought the key_by with a fk join might be messing with it a bit, but you're probably right

**Comment by tpoterba** [comment]
the lookups are in a literal, not a table 👍

**Pull request closed without merging**
