### PR TITLE
Added new functions on Array and Set

### PR DESCRIPTION
**Pull request by lfrancioli**
- Array: append, extend
- Set: add, union, difference, intersection, issubset

### CODE REVIEW

**Comment by jbloom22** [comment]
Recommended changes to doc strings (I had an issue making PR against yours in browser, so just cut and paste in your code if you agree with changes):

```
  registerMethod("append", (a: IndexedSeq[Any], b: Any) => a :+ b, "Returns the result of adding the element `b` to the end of Array `a`.")(arrayHr(TTHr), TTHr, arrayHr(TTHr))
  registerMethod("extend", (a: IndexedSeq[Any], b: IndexedSeq[Any]) => a ++ b, "Returns the concatenation of Array `a` and Array `b`.")(arrayHr(TTHr), arrayHr(TTHr), arrayHr(TTHr))

  registerMethod("add", (a: Set[Any], b: Any) => a + b, "Returns the result of adding the element `b` to Set `a`.")(setHr(TTHr), TTHr, setHr(TTHr))
  registerMethod("union", (a: Set[Any], b: Set[Any]) => a ++ b, "Returns the union of Sets `a` and `b`.")(setHr(TTHr), setHr(TTHr), setHr(TTHr))
  registerMethod("intersection", (a: Set[Any], b: Set[Any]) => a & b, "Returns the intersection of Sets `a` and `b`.")(setHr(TTHr), setHr(TTHr), setHr(TTHr))
  registerMethod("difference", (a: Set[Any], b: Set[Any]) => a &~ b, "Returns the elements of Set `a` that are not in Set `b`.")(setHr(TTHr), setHr(TTHr), setHr(TTHr))
  registerMethod("issubset", (a: Set[Any], b: Set[Any]) => a.subsetOf(b), "Returns true if Set `a` is a subset of Set `b`.")(setHr(TTHr), setHr(TTHr), boolHr)
```

**Comment by jbloom22** [comment]
I prefer "subsetOf" to "issubset".

**Comment by lfrancioli** [comment]
These are the python names...

**Comment by jbloom22** [comment]
Yes, but the rest of the expression language is camel-case Scala, not Python.
https://hail.is/hail/types.html

We've discussed switching to Python for consistency, but that's not where things stand now. @tpoterba thoughts?

**Comment by lfrancioli** [comment]
Fair  point! Either way is fine by me obviously :)

**Comment by tpoterba** [comment]
Things aren't really consistent, so there's no clear pattern to follow.  I'm happy to mimic python set/list functionality

**Comment by lfrancioli** [comment]
OK, I've changed the doc strings (thanks Jon for the better ones!) I've left `issubset` for now but again, I have no strong opinion. Just copied the python cause it seems like it's the way things are moving ;)

**Comment by jbloom22** [comment]
@lfrancioli look at the built docs (under TeamCity, artifacts, index):
https://ci.hail.is/repository/download/HailSourceCode_HailMainline_BuildDocs/9716:id/www/hail/types.html#set-t

There is an issue of variable naming: your a is implicit (not named), and your b is our a.

So for example:
```
add(a: T): Set[T] – Returns the result of adding the element b to Set a.
```

**Comment by jbloom22** [comment]
Look over this correction:
```
  registerMethod("append", (a: IndexedSeq[Any], b: Any) => a :+ b, "Returns the result of adding the element `a` to the end of this Array.")(arrayHr(TTHr), TTHr, arrayHr(TTHr))
  registerMethod("extend", (a: IndexedSeq[Any], b: IndexedSeq[Any]) => a ++ b, "Returns the concatenation of this Array followed by Array `a`.")(arrayHr(TTHr), arrayHr(TTHr), arrayHr(TTHr))

  registerMethod("add", (a: Set[Any], b: Any) => a + b, "Returns the result of adding the element `a` to this Set.")(setHr(TTHr), TTHr, setHr(TTHr))
  registerMethod("union", (a: Set[Any], b: Set[Any]) => a ++ b, "Returns the union of this Set and Set `a`.")(setHr(TTHr), setHr(TTHr), setHr(TTHr))
  registerMethod("intersection", (a: Set[Any], b: Set[Any]) => a & b, "Returns the intersection of this Set and Set `a`.")(setHr(TTHr), setHr(TTHr), setHr(TTHr))
  registerMethod("difference", (a: Set[Any], b: Set[Any]) => a &~ b, "Returns the elements of this Set that are not in Set `a`.")(setHr(TTHr), setHr(TTHr), setHr(TTHr))
  registerMethod("issubset", (a: Set[Any], b: Set[Any]) => a.subsetOf(b), "Returns true if this Set is a subset of Set `a`.")(setHr(TTHr), setHr(TTHr), boolHr)
```

**Pull request merged**
