### PR TITLE
Add TableCollect IR node

### PR DESCRIPTION
**Pull request by tpoterba**
Builds on #4912

### CODE REVIEW

**Comment by catoverdrive** [comment]
@tpoterba @jbloom22 I've reviewed this PR but haven't approved it because I was waiting for the other one to go in. If someone pings me when it does, I'm happy to approve.

**Comment by tpoterba** [comment]
ready for review

**Comment by tpoterba** [comment]
see the comment - Arcturus approved but was waiting on dependent PR.

**Comment by cseed** [comment]
bump as I want to use this

**Comment by tpoterba** [comment]
@cseed - Arcturus approved when it was stacked before going on vacation.

You can approve + merge if you want it in

**Comment by cseed** [comment]
Done!

**Pull request merged**
