### PR TITLE
[site] install section, hero content updates

### PR DESCRIPTION
**Pull request by akotlar**
Adds the side-by-side clickable code block, some styling changes (fix view width to 2048px on wider displays), and the install section.

Stacked on #8848

### CODE REVIEW

**Comment by danking** [comment]
Ah, I commented on both PRs by accident. In the future, keeping each PR to a single commit can help the reviewer identify the right changes to review for stacked PRs.

**Comment by akotlar** [comment]
> Ah, I commented on both PRs by accident. My bad, sorry! In the future, keeping each PR to a single commit can help the reviewer identify the right changes to review for stacked PRs.

Please clarify. Unless I misunderstand, 1 commit per PR isn’t something that we currently hold ourselves to. For instance the PR you issued for site deploy has something like 10 commits. Maybe we can specify this in a design doc, much like John and you did with the PR message? This would be a useful place to specify related issues, like settling on rebasing vs merging. 

My understanding of our use of the stacked label is that the dependent PR isn’t meant to be reviewed until the child is merged.

**Comment by danking** [comment]
I don't think we have a clear policy on this. When I'm making stacked changes, I use one-commit per PR so that they can be reviewed independently. You're welcome to take either approach.

**Comment by akotlar** [comment]
> Minor comments. Is this deployed anywhere so I can take a look?

http://34.207.246.132 has the latest, which is this PR + the tutorial page.

**Comment by tpoterba** [comment]
> I think the policy we've been roughly sticking to on the compilers team is that people don't need to make one commit per PR, but also shouldn't expect that stacked PRs are reviewed until the parent goes in.

**Comment by akotlar** [comment]
I can dev deploy it as well

**Comment by danking** [comment]
Sounds good, my apologies for misunderstanding compiler's team norms.

**Comment by akotlar** [comment]
I'm just going to close the other PR so that we get the overall in (I think here you've approved both the dependent PR and the stacked content)

**Comment by danking** [comment]
👍

**Pull request merged**
