### PR TITLE
fix rendering of tutorial docs

### PR DESCRIPTION
**Pull request by tpoterba**
Fixes this:

image

### CODE REVIEW

**Comment by jigold** [comment]
I tried to see if the rendering was fixed on the CI, and it isn't. Maybe a problem with the CI being out of date?

**Comment by tpoterba** [comment]
huh... someone changed the artifacts page so that the docs aren't clickable.

https://storage.googleapis.com/hail-ci-0-1/ci/d3a72374f64c5e6e2fe2b5e108e2a0c74ec80aa4/3283f61b4134a695142294e880cb31e97dd0acbe/artifacts/www/docs/0.2/tutorials/01-genome-wide-association-study.html#Importing-data-from-VCF

**Comment by jigold** [comment]
How did you get to that page? I clicked on Tutorials link in the body of the home page and got an old version.

**Comment by tpoterba** [comment]
I manually edited the URL. I also clicked the tutorials link at first and realized it linked directly to www.hail.is

**Comment by tpoterba** [comment]
I'll PR a fix to the artifacts page that exposes the docs directly

**Pull request merged**
