### PR TITLE
add test for exporting sparse matrix

### LINKED ISSUE #5500: [hail] test exportRectangles with sparsified & filtered blocks
@daniel-goldstein, I'm vaguely worried given that the tests didn't fail on your PR the other day. Let's get a simple test that filters and/or sparsifies a block and then exports.

### PR DESCRIPTION
**Pull request by daniel-goldstein**
Updated incorrect doc and added test to verify that if you try to export a sparse block it writes a file of zeros. resolves #5500

### CODE REVIEW

**Comment by daniel-goldstein** [comment]
`sparsify_rectangles` is doing the bounds correctly but is semantically different from `export_rectangles` in a subtle way. `sparsify_rectangles` drops *blocks* that are disjoint from all the given rectangles, while `export_rectangles` actually gives you the rectangles you wanted. So because `[0, 3, 0, 2]` intersects the bottom left quadrant, 13 and 14 are not dropped. The docs were incorrect because this behavior assumes a block size of 2 (which I fixed in this PR). `sparsify_blocks` seems to me like a more appropriate name for the method.

Also, the docs on `export_rectangles` are outdated and don’t reflect my previous PR this one is based on. I assumed doc rebuilds were automated.

**Comment by konradjk** [comment]
Ah ok, I certainly agree then, that `sparsify_blocks` is a more appropriate name, and this should be documented explicitly. It makes me a little bit uncomfortable that the output depends on the block_size parameter that's not set in this function (I understand why that is, it's just a little odd).

**Comment by jbloom22** [comment]
Note the BlockMatrix top matter says:
```
Block-sparse matrices may be created with sparsify_band(), sparsify_rectangles(), sparsify_row_intervals(), and sparsify_triangle().
```
The name consistently says the form of the regain one is conceptually sparsifying to. Ny this convention, `sparsify_blocks` would be the name of a command that takes a list of BlockMatrix blocks to keep. That command doesn't exist, but renaming sparsify_rectangles to sparsify_blocks would very inconsistent.

**Comment by daniel-goldstein** [comment]
You're right, when considering the other methods it doesn't make sense to rename any one of them `sparsify_blocks`. Maybe `sparsify_by_*` would provide the necessary clarification if applied consistently across the board.

**Comment by jbloom22** [comment]
I was thinking `sparsity_to_*`

**Comment by daniel-goldstein** [comment]
I will make the sparsifying rename/doc update a separate PR. @konradjk I also added another test along the same vein but for a matrix that has been filtered for a subset of rows and columns.

**Pull request merged**
