### PR TITLE
Rename Expression.value to Expression.eval()

### LINKED ISSUE #4364: Rename Expression.value => Expression.eval()

### PR DESCRIPTION
**Pull request by tpoterba**
fixes #4364

### CODE REVIEW

**Comment by cseed** [comment]
Just asking: is `hl.eval(x)` more natural than `x.eval()`?

**Comment by cseed** [comment]
Compare:

```
>>> eval('5')
5

```

**Comment by tpoterba** [comment]
I'm fine with that too

**Comment by patrick-schultz** [comment]
I do find `eval(expr)` much more natural that `expr.eval()`. I'm okay with approving as is, but my vote is for the former.

**Comment by tpoterba** [comment]
The one case where this is much less natural is globals:

`hl.eval(mt.globals.foo)`

**Comment by tpoterba** [comment]
so, should I make the change? I am totally fine with that

**Comment by tpoterba** [comment]
and we can add a `get_globals()` or something which does `hl.eval(globals)`

**Comment by patrick-schultz** [comment]
Sorry, I was just giving this some more thought. I like making the change and finding some more comfortable alternative for globals. What about making `show()` work for gloabls too?

**Comment by cseed** [comment]
Yeah, that's probably the case that motivated `.value`.  I say make it.  Yeah, I like `get_globals()` or `globals_value()` or something.

**Comment by tpoterba** [comment]
show works for expressions!

**Comment by tpoterba** [comment]
I have to say, this find/replace was _much_ harder than the last!

**Pull request merged**
