### PR TITLE
added div (floor division // in Python), made % consistent w Python

### PR DESCRIPTION
**Pull request by jbloom22**
- updated docs
- added tests

### CODE REVIEW

**Comment by jbloom22** [comment]
After hand coding them, I then found the floorDiv and floorMod functions in java math so switched to those.

@danking, with div method, do you see a way to use `//` as an operator instead? I couldn't figure out if/how to tell Java to prioritize it on the same level as `/`?

Also, because the definitions are different for int/long and float/double, am I correct that I can't make use of the numeric types as written?

**Comment by jbloom22** [comment]
@danking also, math.floor converts Float to Double, so `a // b` of floats will return Double.  I could add .toFloat after, or search for another implementation

**Comment by danking** [comment]
`toFloat` is probably most appropriate.

**Comment by danking** [comment]
Also, yes, the `registerNumeric` would require some sort of polymorphic implementation, which this is not.

**Pull request merged**
