### PR TITLE
[hail] (StagedAggs) some staged aggregators

### LINKED ISSUE #6849: min/max are wrong
Issue known by several members of the dev team now -- if the first element combined is nan, the result is non-deterministically wrong (depends on the associativity of agg combination on the master)

### PR DESCRIPTION
**Pull request by iitalics**
- [x] Min
- [x] Max
- [x] Product
- [x] use tim's `nan{min,max}` implementation

i'm thinking that i should create an abstraction that encompasses all of these, since they are very similar

fixes #6849 
will pass ci when #6861 is merged

### CODE REVIEW

**Comment by tpoterba** [comment]
very nice!

Since you destroyed your 3 (plus a bonus sum) already, do you want to take one of the slightly trickier ones, like `collect`?

**Comment by iitalics** [comment]
sure, i could give it a shot

**Comment by iitalics** [comment]
hm. python test is failing because max can't handle float32's, but the code i based it off of (`SumAggregator`) 
only handled int64 and float64. 

should i insert cases to handle each kind of number?

also should i assign someone in particular to this or choose randomly from the scorecard?

**Comment by tpoterba** [comment]
> should i insert cases to handle each kind of number?

yeah, this is probably right for min and max.

**Comment by tpoterba** [comment]
and I think assign Arcturus to this one -- they should have a first look at everyone's agg conversions

**Comment by catoverdrive** [comment]
@iitalics in the future, when you finish making changes you should dismiss the review---that will let the reviewer know that it's ready for another look and make it show up correctly as "review required" instead of "changes requested" so that scorecard/ci/etc handle it correctly. Sorry for missing this!

**Comment by tpoterba** [comment]
Reassigned to me.

**Comment by tpoterba** [comment]
needs a bump.

There's also a weird failure in the tutorial docs - seems like something is generating an `inf` that Python doesn't expect

**Comment by iitalics** [comment]
any idea how i can reproduce this locally?

**Comment by tpoterba** [comment]
yep, run `./gradlew makeDocs`

It could be somehow related to another random failure (no space left on device)

**Comment by tpoterba** [comment]
If you wait until #6847 goes in, there's a function you can easily call for the combiner.

**Comment by iitalics** [comment]
`test_summarize_run` is segfaulting on the CI server, but it runs fine for me locally (in fact, I can run all of `test_expr.py` with no failures). can somebody else try cloning this branch and running tests locally?

**Pull request merged**
