### PR TITLE
Extend Python methods that print to take arbitrary handler functions

### LINKED ISSUE #4299: Save the screen printout from ht.show() to a logger file
I'd like to be able to save the screen printout from ht.show() in a logger file for recordkeeping purposes.

### PR DESCRIPTION
**Pull request by tpoterba**
fixes #4299

### CODE REVIEW

**Comment by tpoterba** [comment]
where? everywhere?

**Comment by tpoterba** [comment]
I'll add a how to

**Comment by jbloom22** [comment]
ok, with this or separately?

**Comment by tpoterba** [comment]
doing it now

**Comment by jbloom22** [comment]
Cool, will look once it builds

**Comment by gtiao** [comment]
Hooray! Thanks for the fast turnaround, guys!

**Comment by jbloom22** [comment]
@danking any idea why the artifacts aren't visible?

**Comment by danking** [comment]
ah. the artifacts are no longer in `artifacts`. they're in `artifacts/hail`, so the CI doesn't see them.

**Pull request merged**
