### PR TITLE
[testing] Disable scheduler tests

### PR DESCRIPTION
**Pull request by tpoterba**
How do I make these pass on my machine? Maybe it's hitting ports in use?

### CODE REVIEW

**Comment by cseed** [comment]
How are you running the tests?  We have the following in `hail/testng.xml`:

```
<suite name="SuiteAll" verbose="1">
    <test name="TestAll">  
        <packages>  
          <package name="is.hail.*">
            <exclude name="is.hail.scheduler"></exclude>
            <exclude name="is.hail.backend.distributed"></exclude>
	  </package>
        </packages>
    </test>
</suite>
```

These tests are explicitly executed by `scheduler/testng.xml`.

**Comment by tpoterba** [comment]
`gradle test` runs the scheduler tests

**Comment by cseed** [comment]
Then we should exclude them in gradle test, too.  These are being run in the `test_scheduler` step of the build process.

**Comment by tpoterba** [comment]
yeah, figured that out after your comment. 

I'm a bit bothered by the differences between the build.yaml and the local development process. the build.yaml should be the single source of truth, but it's not in a form that's easy to look to for local testing.

**Pull request closed without merging**
