### PR TITLE
[ci] Also push to new_docker_prefix if present as part of AR migration

### PR DESCRIPTION
**Pull request by daniel-goldstein**
Stacked on #12210, this alters `build.py` to push images to `docker_prefix` and to `new_docker_prefix` if present in the global config. This will make sure that when we switch `docker_prefix` to the new Artifact Registry that any in-use images are ready to go.

Once we are ready to switch over, we can
1. change `docker_prefix` to the new AR in the global-config
2. remove `new_docker_prefix` from the global-config
3. Revert this change

### CODE REVIEW

**Comment by daniel-goldstein** [comment]
Tested by running `hailctl dev deploy -b hail-is/hail:main -s git_make_bash_image` against a CI in my namespace and seeing that it succeeded and pushed an image [here](https://console.cloud.google.com/artifacts/docker/hail-vdc/us/hail/ci-intermediate?project=hail-vdc)

**Comment by jigold** [comment]
Before we merge this, I'd like to have the new Artifact Registry in hail-vdc setup and have configured a cloud run job for the cleanup script. I think a daily run is good enough. https://github.com/GoogleCloudPlatform/gcr-cleaner/blob/main/docs/deploy-cloud-run.md

**Comment by jigold** [comment]
I used filters for the following images when I've run the Azure cleanup script, but we should double check these make sense still in light of changing how we use "cache" and there aren't any additional images or ones that we don't want to delete that are in this list:

```
  --filter 'auth:.*' \
  --filter 'ci-intermediate:.*' \
  --filter 'ci-utils:.*' \
  --filter 'base:.*' \
  --filter 'base_spark_3_2:.*' \
  --filter 'batch:.*' \
  --filter 'batch-driver-nginx:.*' \
  --filter 'batch-worker:.*' \
  --filter 'benchmark:.*' \
  --filter 'blog_nginx:.*' \
  --filter 'ci:.*' \
  --filter 'ci-utils:.*' \
  --filter 'create_certs_image:.*' \
  --filter 'echo:.*' \
  --filter 'grafana:.*' \
  --filter 'hail-base:.*' \
  --filter 'hail-build:.*' \
  --filter 'hail-buildkit:.*' \
  --filter 'hail-run:.*' \
  --filter 'hail-run-tests:.*' \
  --filter 'hail-pip-installed-python37:.*' \
  --filter 'hail-pip-installed-python38:.*' \
  --filter 'hail-ubuntu:.*' \
  --filter 'memory:.*' \
  --filter 'monitoring:.*' \
  --filter 'notebook:.*' \
  --filter 'notebook_nginx:.*' \
  --filter 'prometheus:.*' \
  --filter 'service-base:.*' \
  --filter 'service-java-run-base:.*' \
  --filter 'test-ci:.*' \
  --filter 'test-monitoring:.*' \
  --filter 'test-benchmark:.*' \
  --filter 'website:.*' \
```

**Comment by daniel-goldstein** [comment]
Sounds good, I'll get this set up

**Comment by jigold** [comment]
One last thing -- do we need to change the Makefiles at all?

**Comment by daniel-goldstein** [comment]
Closing as this is not necessary.

**Pull request closed without merging**
