### PR TITLE
Staged aggs 1

### PR DESCRIPTION
**Pull request by patrick-schultz**
This is the first broken off piece of @catoverdrive's PR #6518. Staged on #6501 (only look at last commit).

### CODE REVIEW

**Comment by tpoterba** [comment]
I'll take this - I have more context.

**Comment by patrick-schultz** [comment]
Thanks Tim! Want to take the rest of the stack too?

**Comment by tpoterba** [comment]
oops, missed your comment -- yes I'll take the stack.

**Comment by tpoterba** [comment]
Needs rebase, then ready to go.

**Pull request merged**
