### PR TITLE
release 0.2.74

### PR DESCRIPTION
**Pull request by danking**
@jigold @tpoterba

### CODE REVIEW

**Comment by johnc1231** [comment]
#10695 Fixed bug in `hl.experimental.loop` causing incorrect results when loop state contained pointers.

**Comment by danking** [comment]
Done

**Comment by jigold** [comment]
Looks fine with me. Approving and putting the WIP tag on.

**Review by jigold — APPROVED** [review]

**Review by tpoterba — APPROVED** [review]

**Review by tpoterba — DISMISSED** [review]
oops. needs version change in makefile

**Comment by danking** [comment]
done

**Pull request merged**
