### PR TITLE
[build] time jar modification

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by tpoterba** [comment]
er, can't time like this in make

**Comment by tpoterba** [comment]
why did this pass? um...

**Comment by danking** [comment]
The shadow jar file was newer than its dependencies so Make assumed it was good to go. The Make-Way TM would be to make the output of gradle an intermediate step which is then copied to a new file by the jar modification.

**Review by danking — CHANGES_REQUESTED** [review]
xxx

**Review by danking — APPROVED** [review]

**Comment by tpoterba** [comment]
I never fixed this

**Pull request closed without merging**
