### PR TITLE
[batch] use one global deployment

### PR DESCRIPTION
**Pull request by danking**

### CODE REVIEW

**Comment by danking** [comment]
I'll verify in a namespace once the tests verify that this isn't completely insane.

**Comment by danking** [comment]
Actually I just went ahead and looked at this PR to make sure highcpus were indeed highcpus. They are!
Screen Shot 2021-12-09 at 11 56 56 AM

I also grabbed all the VM details and all the things that should be different (vm name, Nic name, etc.) are different. The userData is myseriously null, but its null for every VM in Azure currently (other PRs, namespaces, and default)

```
  {
    "additionalCapabilities": null,
    "applicationProfile": null,
    "availabilitySet": null,
    "billingProfile": {
      "maxPrice": -1.0
    },
    "capacityReservation": null,
    "diagnosticsProfile": null,
    "evictionPolicy": "Delete",
    "extendedLocation": null,
    "extensionsTimeBudget": null,
    "hardwareProfile": {
      "vmSize": "Standard_F16s_v2",
      "vmSizeProperties": null
    },
    "host": null,
    "hostGroup": null,
    "id": "/subscriptions/22cd45fe-f996-4c51-af67-ef329d977519/resourceGroups/dgoldste/providers/Microsoft.Compute/virtualMachines/batch-worker-pr-11144-default-nbthv8fduvd6-highcpu-robv5",
    "identity": {
      "principalId": null,
      "tenantId": null,
      "type": "UserAssigned",
      "userAssignedIdentities": {
        "/subscriptions/22cd45fe-f996-4c51-af67-ef329d977519/resourceGroups/dgoldste/providers/Microsoft.ManagedIdentity/userAssignedIdentities/batch-worker": {
          "clientId": "890af904-42f1-4136-810a-c52f4e132c6b",
          "principalId": "b952a3bb-1091-4f11-803b-9d5199219a27"
        }
      }
    },
    "instanceView": null,
    "licenseType": null,
    "location": "eastus",
    "name": "batch-worker-pr-11144-default-nbthv8fduvd6-highcpu-robv5",
    "networkProfile": {
      "networkApiVersion": null,
      "networkInterfaceConfigurations": null,
      "networkInterfaces": [
        {
          "deleteOption": "Delete",
          "id": "/subscriptions/22cd45fe-f996-4c51-af67-ef329d977519/resourceGroups/dgoldste/providers/Microsoft.Network/networkInterfaces/batch-worker-pr-11144-default-nbthv8fduvd6-highcpu-robv5-nic",
          "primary": null,
          "resourceGroup": "dgoldste"
        }
      ]
    },
    "osProfile": {
      "adminPassword": null,
      "adminUsername": "batch-worker",
      "allowExtensionOperations": true,
      "computerName": "batch-worker-pr-11144-default-nbthv8fduvd6-highcpu-robv5",
      "customData": null,
      "linuxConfiguration": {
        "disablePasswordAuthentication": true,
        "patchSettings": {
          "assessmentMode": "ImageDefault",
          "patchMode": "ImageDefault"
        },
        "provisionVmAgent": true,
        "ssh": {
          "publicKeys": [
            {
              "keyData": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDKC9kZBCsWb78yJ1zcdhmrYEmjNEOaJN5RGuMBuoszUXGGOCJMFi6jMTgSVjTql90NchA0tWXAuooVLV++f8WIOwpP7TY1YzN1XCREyk8jKOMrIdCc22ueJlNvxmFfJhdDKBCy0eThWN2qFxQJ4p9SvzGlMd2r3nBy95v9f8WgkN8M/HTDwTsFafNT0arvHnmUY6rFHxQE9TgTRlH1/sZ7mMxzmVZ8NKI/wIXTkv53TbylBYbvkEXyVFl3OBj1MUvo17v99LGdQNFcAiWR/pRsDvXY415FzootwShgQpmvuPLP7buTqVcrRnwRr2hZcpaydOyEaErYsuEPiot0RPrvsIXSkSI4NlIbqO2i4gjfF8FwpDzyY0WtAvUbsY8dKxWXzcIWtQzUyYeqJq1R0Yh8p3ijmLgrkpAJTI/Lz8WT2foUFg7gYQwc9xbFN6aQzQwUQ0Y8s0DDvQqnbby12IXXHI+rjuh1TH8lIRPw/UsFInJn3WS1MBp4FRiXwRs9EwVhfeb+b8Z5rnaQ3RrmM8SY0kjg0i05rkMkygEnPuSec6qKYREHW8n4wbYQNhJvDW9RhUIGnzn3IQRJB57bOZ8xwPkZ97PM0WGsCMWwupSOuEk/NsFe69cZwbElYZJeqeA/bKKsmRsJ/tjzyYMLUlj4L++4GQIwPHgtjmQ9kUEeaw== dgoldste@wmce3-cb7\n",
              "path": "/home/batch-worker/.ssh/authorized_keys"
            }
          ]
        }
      },
      "requireGuestProvisionSignal": true,
      "secrets": [],
      "windowsConfiguration": null
    },
    "plan": null,
    "platformFaultDomain": null,
    "priority": "Spot",
    "provisioningState": "Succeeded",
    "proximityPlacementGroup": null,
    "resourceGroup": "dgoldste",
    "resources": null,
    "scheduledEventsProfile": null,
    "securityProfile": null,
    "storageProfile": {
      "dataDisks": [
        {
          "caching": "None",
          "createOption": "Empty",
          "deleteOption": "Delete",
          "detachOption": null,
          "diskIopsReadWrite": null,
          "diskMBpsReadWrite": null,
          "diskSizeGb": 375,
          "image": null,
          "lun": 2,
          "managedDisk": {
            "diskEncryptionSet": null,
            "id": "/subscriptions/22cd45fe-f996-4c51-af67-ef329d977519/resourceGroups/dgoldste/providers/Microsoft.Compute/disks/batch-worker-pr-11144-default-nbthv8fduvd6-highcpu-robv5-data",
            "resourceGroup": "dgoldste",
            "storageAccountType": "Standard_LRS"
          },
          "name": "batch-worker-pr-11144-default-nbthv8fduvd6-highcpu-robv5-data",
          "toBeDetached": false,
          "vhd": null,
          "writeAcceleratorEnabled": null
        }
      ],
      "imageReference": {
        "exactVersion": "0.0.12",
        "id": "/subscriptions/22cd45fe-f996-4c51-af67-ef329d977519/resourceGroups/dgoldste/providers/Microsoft.Compute/galleries/dgoldste_batch/images/batch-worker/versions/0.0.12",
        "offer": null,
        "publisher": null,
        "resourceGroup": "dgoldste",
        "sharedGalleryImageId": null,
        "sku": null,
        "version": null
      },
      "osDisk": {
        "caching": "ReadOnly",
        "createOption": "FromImage",
        "deleteOption": "Delete",
        "diffDiskSettings": null,
        "diskSizeGb": 30,
        "encryptionSettings": null,
        "image": null,
        "managedDisk": {
          "diskEncryptionSet": null,
          "id": "/subscriptions/22cd45fe-f996-4c51-af67-ef329d977519/resourceGroups/dgoldste/providers/Microsoft.Compute/disks/batch-worker-pr-11144-default-nbthv8fduvd6-highcpu-robv5-os",
          "resourceGroup": "dgoldste",
          "storageAccountType": "Standard_LRS"
        },
        "name": "batch-worker-pr-11144-default-nbthv8fduvd6-highcpu-robv5-os",
        "osType": "Linux",
        "vhd": null,
        "writeAcceleratorEnabled": null
      }
    },
    "tags": {
      "batch-worker": "1",
      "namespace": "pr-11144-default-nbthv8fduvd6"
    },
    "type": "Microsoft.Compute/virtualMachines",
    "userData": null,
    "virtualMachineScaleSet": null,
    "vmId": "4eaaa3a5-69ce-4eb0-ba8c-266bd66c821e",
    "zones": null
  },
  {
    "additionalCapabilities": null,
    "applicationProfile": null,
    "availabilitySet": null,
    "billingProfile": {
      "maxPrice": -1.0
    },
    "capacityReservation": null,
    "diagnosticsProfile": null,
    "evictionPolicy": "Delete",
    "extendedLocation": null,
    "extensionsTimeBudget": null,
    "hardwareProfile": {
      "vmSize": "Standard_E4d_v4",
      "vmSizeProperties": null
    },
    "host": null,
    "hostGroup": null,
    "id": "/subscriptions/22cd45fe-f996-4c51-af67-ef329d977519/resourceGroups/dgoldste/providers/Microsoft.Compute/virtualMachines/batch-worker-pr-11144-default-nbthv8fduvd6-highmem-13t6m",
    "identity": {
      "principalId": null,
      "tenantId": null,
      "type": "UserAssigned",
      "userAssignedIdentities": {
        "/subscriptions/22cd45fe-f996-4c51-af67-ef329d977519/resourceGroups/dgoldste/providers/Microsoft.ManagedIdentity/userAssignedIdentities/batch-worker": {
          "clientId": "890af904-42f1-4136-810a-c52f4e132c6b",
          "principalId": "b952a3bb-1091-4f11-803b-9d5199219a27"
        }
      }
    },
    "instanceView": null,
    "licenseType": null,
    "location": "eastus",
    "name": "batch-worker-pr-11144-default-nbthv8fduvd6-highmem-13t6m",
    "networkProfile": {
      "networkApiVersion": null,
      "networkInterfaceConfigurations": null,
      "networkInterfaces": [
        {
          "deleteOption": "Delete",
          "id": "/subscriptions/22cd45fe-f996-4c51-af67-ef329d977519/resourceGroups/dgoldste/providers/Microsoft.Network/networkInterfaces/batch-worker-pr-11144-default-nbthv8fduvd6-highmem-13t6m-nic",
          "primary": null,
          "resourceGroup": "dgoldste"
        }
      ]
    },
    "osProfile": {
      "adminPassword": null,
      "adminUsername": "batch-worker",
      "allowExtensionOperations": true,
      "computerName": "batch-worker-pr-11144-default-nbthv8fduvd6-highmem-13t6m",
      "customData": null,
      "linuxConfiguration": {
        "disablePasswordAuthentication": true,
        "patchSettings": {
          "assessmentMode": "ImageDefault",
          "patchMode": "ImageDefault"
        },
        "provisionVmAgent": true,
        "ssh": {
          "publicKeys": [
            {
              "keyData": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDKC9kZBCsWb78yJ1zcdhmrYEmjNEOaJN5RGuMBuoszUXGGOCJMFi6jMTgSVjTql90NchA0tWXAuooVLV++f8WIOwpP7TY1YzN1XCREyk8jKOMrIdCc22ueJlNvxmFfJhdDKBCy0eThWN2qFxQJ4p9SvzGlMd2r3nBy95v9f8WgkN8M/HTDwTsFafNT0arvHnmUY6rFHxQE9TgTRlH1/sZ7mMxzmVZ8NKI/wIXTkv53TbylBYbvkEXyVFl3OBj1MUvo17v99LGdQNFcAiWR/pRsDvXY415FzootwShgQpmvuPLP7buTqVcrRnwRr2hZcpaydOyEaErYsuEPiot0RPrvsIXSkSI4NlIbqO2i4gjfF8FwpDzyY0WtAvUbsY8dKxWXzcIWtQzUyYeqJq1R0Yh8p3ijmLgrkpAJTI/Lz8WT2foUFg7gYQwc9xbFN6aQzQwUQ0Y8s0DDvQqnbby12IXXHI+rjuh1TH8lIRPw/UsFInJn3WS1MBp4FRiXwRs9EwVhfeb+b8Z5rnaQ3RrmM8SY0kjg0i05rkMkygEnPuSec6qKYREHW8n4wbYQNhJvDW9RhUIGnzn3IQRJB57bOZ8xwPkZ97PM0WGsCMWwupSOuEk/NsFe69cZwbElYZJeqeA/bKKsmRsJ/tjzyYMLUlj4L++4GQIwPHgtjmQ9kUEeaw== dgoldste@wmce3-cb7\n",
              "path": "/home/batch-worker/.ssh/authorized_keys"
            }
          ]
        }
      },
      "requireGuestProvisionSignal": true,
      "secrets": [],
      "windowsConfiguration": null
    },
    "plan": null,
    "platformFaultDomain": null,
    "priority": "Spot",
    "provisioningState": "Succeeded",
    "proximityPlacementGroup": null,
    "resourceGroup": "dgoldste",
    "resources": null,
    "scheduledEventsProfile": null,
    "securityProfile": null,
    "storageProfile": {
      "dataDisks": [],
      "imageReference": {
        "exactVersion": "0.0.12",
        "id": "/subscriptions/22cd45fe-f996-4c51-af67-ef329d977519/resourceGroups/dgoldste/providers/Microsoft.Compute/galleries/dgoldste_batch/images/batch-worker/versions/0.0.12",
        "offer": null,
        "publisher": null,
        "resourceGroup": "dgoldste",
        "sharedGalleryImageId": null,
        "sku": null,
        "version": null
      },
      "osDisk": {
        "caching": "ReadOnly",
        "createOption": "FromImage",
        "deleteOption": "Delete",
        "diffDiskSettings": null,
        "diskSizeGb": 30,
        "encryptionSettings": null,
        "image": null,
        "managedDisk": {
          "diskEncryptionSet": null,
          "id": "/subscriptions/22cd45fe-f996-4c51-af67-ef329d977519/resourceGroups/dgoldste/providers/Microsoft.Compute/disks/batch-worker-pr-11144-default-nbthv8fduvd6-highmem-13t6m-os",
          "resourceGroup": "dgoldste",
          "storageAccountType": "Standard_LRS"
        },
        "name": "batch-worker-pr-11144-default-nbthv8fduvd6-highmem-13t6m-os",
        "osType": "Linux",
        "vhd": null,
        "writeAcceleratorEnabled": null
      }
    },
    "tags": {
      "batch-worker": "1",
      "namespace": "pr-11144-default-nbthv8fduvd6"
    },
    "type": "Microsoft.Compute/virtualMachines",
    "userData": null,
    "virtualMachineScaleSet": null,
    "vmId": "2612958c-ef4e-4678-8482-29726290ae20",
    "zones": null
  },
  {
    "additionalCapabilities": null,
    "applicationProfile": null,
    "availabilitySet": null,
    "billingProfile": {
      "maxPrice": -1.0
    },
    "capacityReservation": null,
    "diagnosticsProfile": null,
    "evictionPolicy": "Delete",
    "extendedLocation": null,
    "extensionsTimeBudget": null,
    "hardwareProfile": {
      "vmSize": "Standard_D16d_v4",
      "vmSizeProperties": null
    },
    "host": null,
    "hostGroup": null,
    "id": "/subscriptions/22cd45fe-f996-4c51-af67-ef329d977519/resourceGroups/dgoldste/providers/Microsoft.Compute/virtualMachines/batch-worker-pr-11144-default-nbthv8fduvd6-standard-i4sun",
    "identity": {
      "principalId": null,
      "tenantId": null,
      "type": "UserAssigned",
      "userAssignedIdentities": {
        "/subscriptions/22cd45fe-f996-4c51-af67-ef329d977519/resourceGroups/dgoldste/providers/Microsoft.ManagedIdentity/userAssignedIdentities/batch-worker": {
          "clientId": "890af904-42f1-4136-810a-c52f4e132c6b",
          "principalId": "b952a3bb-1091-4f11-803b-9d5199219a27"
        }
      }
    },
    "instanceView": null,
    "licenseType": null,
    "location": "eastus",
    "name": "batch-worker-pr-11144-default-nbthv8fduvd6-standard-i4sun",
    "networkProfile": {
      "networkApiVersion": null,
      "networkInterfaceConfigurations": null,
      "networkInterfaces": [
        {
          "deleteOption": "Delete",
          "id": "/subscriptions/22cd45fe-f996-4c51-af67-ef329d977519/resourceGroups/dgoldste/providers/Microsoft.Network/networkInterfaces/batch-worker-pr-11144-default-nbthv8fduvd6-standard-i4sun-nic",
          "primary": null,
          "resourceGroup": "dgoldste"
        }
      ]
    },
    "osProfile": {
      "adminPassword": null,
      "adminUsername": "batch-worker",
      "allowExtensionOperations": true,
      "computerName": "batch-worker-pr-11144-default-nbthv8fduvd6-standard-i4sun",
      "customData": null,
      "linuxConfiguration": {
        "disablePasswordAuthentication": true,
        "patchSettings": {
          "assessmentMode": "ImageDefault",
          "patchMode": "ImageDefault"
        },
        "provisionVmAgent": true,
        "ssh": {
          "publicKeys": [
            {
              "keyData": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDKC9kZBCsWb78yJ1zcdhmrYEmjNEOaJN5RGuMBuoszUXGGOCJMFi6jMTgSVjTql90NchA0tWXAuooVLV++f8WIOwpP7TY1YzN1XCREyk8jKOMrIdCc22ueJlNvxmFfJhdDKBCy0eThWN2qFxQJ4p9SvzGlMd2r3nBy95v9f8WgkN8M/HTDwTsFafNT0arvHnmUY6rFHxQE9TgTRlH1/sZ7mMxzmVZ8NKI/wIXTkv53TbylBYbvkEXyVFl3OBj1MUvo17v99LGdQNFcAiWR/pRsDvXY415FzootwShgQpmvuPLP7buTqVcrRnwRr2hZcpaydOyEaErYsuEPiot0RPrvsIXSkSI4NlIbqO2i4gjfF8FwpDzyY0WtAvUbsY8dKxWXzcIWtQzUyYeqJq1R0Yh8p3ijmLgrkpAJTI/Lz8WT2foUFg7gYQwc9xbFN6aQzQwUQ0Y8s0DDvQqnbby12IXXHI+rjuh1TH8lIRPw/UsFInJn3WS1MBp4FRiXwRs9EwVhfeb+b8Z5rnaQ3RrmM8SY0kjg0i05rkMkygEnPuSec6qKYREHW8n4wbYQNhJvDW9RhUIGnzn3IQRJB57bOZ8xwPkZ97PM0WGsCMWwupSOuEk/NsFe69cZwbElYZJeqeA/bKKsmRsJ/tjzyYMLUlj4L++4GQIwPHgtjmQ9kUEeaw== dgoldste@wmce3-cb7\n",
              "path": "/home/batch-worker/.ssh/authorized_keys"
            }
          ]
        }
      },
      "requireGuestProvisionSignal": true,
      "secrets": [],
      "windowsConfiguration": null
    },
    "plan": null,
    "platformFaultDomain": null,
    "priority": "Spot",
    "provisioningState": "Succeeded",
    "proximityPlacementGroup": null,
    "resourceGroup": "dgoldste",
    "resources": null,
    "scheduledEventsProfile": null,
    "securityProfile": null,
    "storageProfile": {
      "dataDisks": [],
      "imageReference": {
        "exactVersion": "0.0.12",
        "id": "/subscriptions/22cd45fe-f996-4c51-af67-ef329d977519/resourceGroups/dgoldste/providers/Microsoft.Compute/galleries/dgoldste_batch/images/batch-worker/versions/0.0.12",
        "offer": null,
        "publisher": null,
        "resourceGroup": "dgoldste",
        "sharedGalleryImageId": null,
        "sku": null,
        "version": null
      },
      "osDisk": {
        "caching": "ReadOnly",
        "createOption": "FromImage",
        "deleteOption": "Delete",
        "diffDiskSettings": null,
        "diskSizeGb": 30,
        "encryptionSettings": null,
        "image": null,
        "managedDisk": {
          "diskEncryptionSet": null,
          "id": "/subscriptions/22cd45fe-f996-4c51-af67-ef329d977519/resourceGroups/dgoldste/providers/Microsoft.Compute/disks/batch-worker-pr-11144-default-nbthv8fduvd6-standard-i4sun-os",
          "resourceGroup": "dgoldste",
          "storageAccountType": "Standard_LRS"
        },
        "name": "batch-worker-pr-11144-default-nbthv8fduvd6-standard-i4sun-os",
        "osType": "Linux",
        "vhd": null,
        "writeAcceleratorEnabled": null
      }
    },
    "tags": {
      "batch-worker": "1",
      "namespace": "pr-11144-default-nbthv8fduvd6"
    },
    "type": "Microsoft.Compute/virtualMachines",
    "userData": null,
    "virtualMachineScaleSet": null,
    "vmId": "13ddde82-50c6-4b61-af8b-c651eba9a674",
    "zones": null
  }
```

**Comment by danking** [comment]
I saved screenshots of the VM detail pages as well if we want to inspect those.

**Comment by danking** [comment]
Mysterious that we created 16 cores for default and highcpu but 4 cores for highmem? I've noticed before that the standing workers take quite a while to start up and if there's a ready job the scale system will produce a 16 core node instead of a 4 core node even if there is no standing worker.

**Comment by jigold** [comment]
This still seems absolutely crazy to me, but let's put it in production and see if the tests fail.

**Comment by danking** [comment]
I will accept your approval any time 😉

**Review by jigold — APPROVED** [review]

**Pull request merged**
