### PR TITLE
[copy] Expandvars in file path names

### PR DESCRIPTION
**Pull request by jigold**
For my SAIGE implementation, it would be nice to be able to use the `{BATCH_TMPDIR}` environment variable within a file name so that I can give user-specified file path names for output files to write that can be used downstream in globs when importing temporary files in Hail without having to localize all of the files (could be 4K+ files). I also thought this could solve Konrad's region bucket request where we copy data from a region-specific location.

### CODE REVIEW

**Review by daniel-goldstein — DISMISSED** [review]

**Comment by jigold** [comment]
I made a change.

**Review by danking — CHANGES_REQUESTED** [review]
This change gives me very strong heebie jeebies. It means that I, the user, cannot prevent environment substitution and, moreover, would get environment substitution when I *think* I've prevented environment substitution. In particular, if I wrote this, the presence of the `'` makes me think that the `$def` will not be replaced. Indeed, the shell won't replace it, but `hailtop.aiotools.copy` *will*.

```
python3 -m hailtop.aiotools.copy ... '[{"from":"gs://bucket/abc$def", "to":"gs://bucket/abc$def"}]'
```

I think this behavior should be off by default and only enabled by an explicit flag like `--substitute-environment-variables`.

**Comment by daniel-goldstein** [comment]
Good point, I didn't consider that. It's a shame that the copy step is not instea more programmable. Like if the copy step was just another shell script then the client could do environment substitution at the shell level and not inside aiotools

**Comment by jigold** [comment]
Then I'll close it and come up with another solution for SAIGE

**Pull request closed without merging**
