### PR TITLE
[notebook2] mount gsa key secret

### PR DESCRIPTION
**Pull request by akotlar**
Allows the notebook container to have access to the user's gsa secret key, a necessary step in mounting the user's bucket.

I modified `delete_worker_pod` to exclude the  V1DeleteOptions, because the signature appears to have changed, and no options were actually provided.

```sh
  File "notebook/notebook.py", line 443, in delete_worker_pod
    kube.client.V1DeleteOptions())
TypeError: delete_namespaced_pod() takes 3 positional arguments but 4 were given
```

Will double check that I have necessary permissions: its the case when running on local, but I think I will need to update vdc to provide broad secret read access for notebook for this to work on the cluster. Checking now

cc @cseed, @danking, @jigold

### CODE REVIEW

**Comment by akotlar** [comment]
In-cluster I have the ability to create a pod, including the secret, which is slightly surprising to me. Does the ability create a pod give ability to mount any secret? Surely not. At the same time, my rbac for notebook clearly defines the only secret it can access:

These pods are bound to the user's service account. Interestingly I also don't appear to need to give that service account permission to read the mounted secret. This makes sense to me: the container should be able to access anything on its file system. The notebook leader defines what that is.

cc @cseed, thought you may want to know.

The following was from a manual in-cluster test:
Screenshot 2019-04-02 15 55 39

**Comment by cseed** [comment]
My guess is the launched pod is the one accessing the secret, with its service account.  You could check this by removing the user can read secret binding and try launching a pod.

**Comment by danking** [comment]
nb, from [Authorization Overview](https://kubernetes.io/docs/reference/access-authn-authz/authorization/):

> Caution: System administrators, use care when granting access to pod creation. A user granted permission to create pods (or controllers that create pods) in the namespace can: read all secrets in the namespace; read all config maps in the namespace; and impersonate any service account in the namespace and take any action the account could take. This applies regardless of authorization mode.

Permission to create a pod gives you permission to mount any secrets in said namespace. Pod creation is a dangerous and powerful permission.

See this [recently closed ticket on k8s](https://github.com/kubernetes/kubernetes/issues/4957).

[An issue from June 2018](https://github.com/kubernetes/community/pull/1604) notes this is an issue for multi-tenant clusters. The k8s maintainers don't have bandwidth to iterate on a solution right now.

**Comment by akotlar** [comment]
> nb, from [Authorization Overview](https://kubernetes.io/docs/reference/access-authn-authz/authorization/):
> 
> > Caution: System administrators, use care when granting access to pod creation. A user granted permission to create pods (or controllers that create pods) in the namespace can: read all secrets in the namespace; read all config maps in the namespace; and impersonate any service account in the namespace and take any action the account could take. This applies regardless of authorization mode.
> 
> Permission to create a pod gives you permission to mount any secrets in said namespace. Pod creation is a dangerous and powerful permission.
> 
> See this [recently closed ticket on k8s](https://github.com/kubernetes/kubernetes/issues/4957).
> 
> [An issue from June 2018](https://github.com/kubernetes/community/pull/1604) notes this is an issue for multi-tenant clusters. The k8s maintainers don't have bandwidth to iterate on a solution right now.

Thanks, yeah, I shared this with Cotton yesterday. We need to be careful seems to be the conclusion.

**Comment by danking** [comment]
I think the takeaway is: notebook's ability to create pods makes it a security risk, so we gotta treat all this code with care.

**Comment by akotlar** [comment]
@danking, @cseed An alternative: [as mentioned in the ticket Dan linked] the acl boundary for pod creation is a namespace. If we scope all user resources to their namespace, and during user resource creation give notebook create pod permissions in the users namespace, and also remove create pod permissions in the default namespace, we reduce the likelihood that a compromised notebook leader could expose user secrets and other data.

**Comment by danking** [comment]
agree strongly with notebook-leader not creating notebook pods in the default namespace

**Comment by cseed** [comment]
Thanks Dan.

I don't think there's a problem, we just need to make sure anyone who has pod create has a dedicated namespace to create pods in (like batch-pods) and only had pod create in that namespace.  Yes, we should do the same for notebook.

 > An issue from June 2018 notes this is an issue for multi-tenant clusters

Still reading this, but I will note, we are not a multi-tenant cluster.  We are a single-tenant cluster running a multi-tenant application.  In particular, our users are not themselve kubernetes clients.  We run things on their behalf in the same way, say, a web site running on a unix host but implementing multiple user accounts.  There is one (or a few) accounts on the host, but many accounts in the application.

**Pull request merged**
