### PR TITLE
removed api1

### PR DESCRIPTION
**Pull request by cseed**
Still need to fix the doc tests.  Just getting it up on the board.

builds on: https://github.com/hail-is/hail/pull/2824

removed hail2
moved hail2 => hail
moved api2 => hail
scala + python tests passing, docs still need some work

### CODE REVIEW

**Comment by cseed** [comment]
> +707 −10,251 

F-yeah.

**Comment by cseed** [comment]
> +1,162 −12,318 

Mwahahaha.

**Comment by cseed** [comment]
Note to self: to port doctest_setup.py, need: 
 - sample_rows (https://github.com/hail-is/hail/pull/2819)
 - ld_prune (https://github.com/hail-is/hail/pull/2830)
 - interval joins
 - joins with product=True

**Comment by cseed** [comment]
@tpoterba I fiat assigned you, let me know if you want me to spin the wheel of review fortune instead.

doctest_setup.py has these four lines commented out:

````
# geneskt = methods.import_interval_list('data/genes.interval_list')
# genekt = methods.import_interval_list('data/gene.interval_list')
# ds = ds.annotate_rows(genes = ???)
# ds = ds.annotate_rows(gene = genekt[ds.v.locus()])
```

which will be used by the skat tests/docs (https://github.com/hail-is/hail/pull/2812) and maybe some burden tests/examples?  They require interval joins (@patrick-schultz is working on that) and product=True (I will make a separate PR).  But since things are working now, I thought I'd try to get this in first.

**Comment by tpoterba** [comment]
Beautiful!!! will look tomorrow

**Comment by tpoterba** [comment]
tutorial got you

**Comment by cseed** [comment]
Yep, just pushed fixes.

**Comment by tpoterba** [comment]
let's also not forget Konrad gets to push the merge button when it's ready!

**Comment by konradjk** [comment]
To clarify, that :-1: is my finger hovering over the button. Not a thumbs down

**Comment by cseed** [comment]
What's the review plan for this?  Rebase is looking increasingly painful.

**Comment by tpoterba** [comment]
Ah, sorry. I'll review today

**Pull request merged**
