### PR TITLE
New group_by().aggregate_*() interface

### PR DESCRIPTION
**Pull request by jigold**
- Added `aggregate_rows`, `aggregate_cols`, `aggregate_entries`, `result` to a GroupedMatrixTable
- Made `aggregate()` an alias for `aggregate_entries().result()`
- Fixed MatrixAggregateColsByKey to do the initOp once per new column rather than once per old column.

Addresses #4022

### CODE REVIEW

**Comment by cseed** [comment]
I very much like the interface.  :+1:

**Comment by jigold** [comment]
@konradjk This isn't a breaking change. We're keeping the current interface as an alias to `aggregate_entries().result()`.

**Comment by konradjk** [comment]
Ah - I saw that in your example, but I was thinking `group_cols_by().aggregate()` without thinking that you probably made a corresponding one for that. My bad.

**Comment by jigold** [comment]
Closing until I get a chance to work on this again.

**Pull request closed without merging**
