### PR TITLE
Towards fullgeneric 6: rowstore codec

### PR DESCRIPTION
**Pull request by cseed**
builds on: https://github.com/hail-is/hail/pull/2081

profile225 is now 10% larger (instead of ~4x) than the 0.1 VDS or VCF:

```
$ ls -lh profile225.vcf.bgz
 ... 2.0G ... profile225.vcf.bgz
$ du -sh profile225.vds
2.2G	profile225.vds
```

import_vcf/write is still slower than 0.1.  I'm not quite sure why.

### CODE REVIEW

**Comment by tpoterba** [comment]
```
577M	ExAC_table.kt (Parquet)
885M	ExAC_rowstore.kt (pre-this-change)
651M	ExAC_rowstore.kt (this change)
```

However, read/count took about 1.5s pre-change, and 6.5s now

**Comment by cseed** [comment]
Yeah, OK, this isn't great.  Do you have exac sites file snippet you're using somewhere?  I clearly need to start doing more systematic benchmarking.

**Comment by tpoterba** [comment]
I think this is the TSV from the public release, so I'll put it on a bucket.

**Comment by cseed** [comment]
I think given the performance I'll need to take another try at this.

**Comment by cseed** [comment]
Needed by https://github.com/hail-is/hail/pull/2097

Will address performance once Row is gone and we're pure unsafe.

**Pull request closed without merging**
