### PR TITLE
[bugfix] Allow pip uninstall to fail

### PR DESCRIPTION
**Pull request by chrisvittal**

### CODE REVIEW

**Comment by tpoterba** [comment]
This exits with 0 for me:
image

**Comment by chrisvittal** [comment]
exits with 1 for me

**Comment by danking** [comment]
Also exits 0 for me, but seems a fine change.

**Comment by chrisvittal** [comment]
This changed in between version `9` which ubuntu 18.10 ships and current pip. I think this is still a good change as older pip should be fine for building.

**Comment by tpoterba** [comment]
ahh, sure. I'm fine with it, just trying to understand what happened to draw your attention :)

**Comment by chrisvittal** [comment]
Trying to do dev install deploy.

**Comment by tpoterba** [comment]
nice! Let me know how it goes... I don't think anyone else has tried yet 😉

**Pull request merged**
