### PR TITLE
Use nosetests in gradle

### PR DESCRIPTION
**Pull request by tpoterba**
generate coverage reports

### CODE REVIEW

**Comment by patrick-schultz** [comment]
It looks like nose is a dead project. There's nose2, but judging by https://www.reddit.com/r/Python/comments/50nqlp/is_nose_still_relevant_how_about_unittest/ it isn't very widely used. Pytest seems to be most popular, and it has a coverage plugin https://pypi.python.org/pypi/pytest-cov. But if nose is working, maybe it's fine to go with it for now.

**Comment by tpoterba** [comment]
yeah, I saw that. Not quite sure what to think -- nose seems to do what we need for now, so maybe we don't need a highly maintained testing framework?

At least in the short term, this seems OK to me. I'll spend some time looking into pytest though.

**Comment by danking** [comment]
This seems fine now (the alternative is to continue using unittest which seems not loved for some reason?). I'll echo patrick that I would prefer we live on a test framework that's maintained. [nose2](http://nose2.readthedocs.io/en/latest/) seems to be a maintained project, but that reddit thread is hot for `pytest`.

**Comment by tpoterba** [comment]
after about an hour of poking around last night, I'm happy to go with pytest.

**Pull request merged**
