### PR TITLE
converted filter intervals to relational function

### PR DESCRIPTION
**Pull request by cseed**

### CODE REVIEW

**Comment by tpoterba** [comment]
This will prevent optimization around the filter intervals. Given the prevalence of filter intervals in the biggest, baddest pipelines, this is a concern/.

**Comment by cseed** [comment]
Agreed.  I'd like to get this in as is for the service support but I'll make another pass and add Matrix/TableFilterInterval nodes that interacts nicely with pruning, etc.

**Comment by tpoterba** [comment]
ok, sounds good

**Comment by tpoterba** [comment]
(or someone else can do that)

**Comment by cseed** [comment]
Can I bump the priority on reviewing this (e.g. get it in on Tue?)  A few other waiting PRs are stacked on top of it.

**Comment by akotlar** [comment]
Working on it.

Gradle/Scala tests pass. Python (Python 3.6.7) also probably pass, I encountered a missing R library error on 501, will re-run in the morning with it installed.

Need to better understand the context of the changes, and whether any additional tests needed to cover them.

**Pull request merged**
