### PR TITLE
[query] Appropriately set requiredness in `registerCode`

### PR DESCRIPTION
**Pull request by tpoterba**
Also fix HWE and Hardy-Weinberg return types.

### CODE REVIEW

**Comment by akotlar** [comment]
'HailException: Required field cannot be missing: PCStruct{PL:PCArray[+PInt32],__uid_1086:+PFloat64}, 1'

**Comment by tpoterba** [comment]
test failures were caused by PType inference bugs that are now fixed

**Comment by akotlar** [comment]
Could you point me to the fix?

**Comment by tpoterba** [comment]
it was #8311

**Pull request merged**
