### PR TITLE
Add support for embedded HTML in CI index page

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by tpoterba** [comment]
This is part 1 of a 2-stage commit to embed all the project logs directly in the index page.

**Comment by tpoterba** [comment]
and we should eventually template but this is OK for now I think

**Comment by danking** [comment]
@tpoterba why would these not go on the artifacts index page? It seems odd to couple the CI directly to the artifact structure of `hail-is/hail` when there's an equally simple alternative.

**Comment by tpoterba** [comment]
the extra click is a big disadvantage

**Comment by tpoterba** [comment]
we can get the same generality via templating, but that requires a bit more infrastructure and want to get this change in

**Comment by tpoterba** [comment]
the artifacts page has the same problem - testing multiple projects means you have to encode the full set of information somewhere...

**Comment by tpoterba** [comment]
also - the artifacts index page is currently generated by `hail/hail-ci-build.sh`. This seems like a violation of the level of abstraction, and don't immediately see how to resolve that

**Comment by tpoterba** [comment]
however, I'd be happy to move all this stuff to the generated html there, and import that here.

I don't see much of a difference

**Comment by danking** [comment]
Once we fold in cloud tools, the CI will only be testing hail-is/hail, so all these questions of coupling between CI and hail-is/hail are moot. (Currently, these changes will introduce a few broken object links to the cloud tools repo. Which is mostly untidy rather than bad in anyway.)

I created `artifacts/index.html` to work around a GCS limitation. Serving a bucket directly doesn't generate an `ls -l` style index.html for directories. nginx and apache are happy to do this.

There are two layers:

 - ci's "job" information (a log and a directory of artifacts)
 - project-specific artifacts

I think the friction is caused by CI & batch lacking a way to express a DAG of jobs. We've hacked this on via background processes, but now the ci's "job" page doesn't neatly correspond to one process log.

Cotton's proposed batch DAG (& CI's use of it) resolves this by restoring the separation of "job" (or, now, "jobs") information and artifacts (which are truly just artifacts).

All that said, if this makes your life easier, I don't mind the mild ugliness on cloud tools while we wait for batch DAG to land. Let me know and I'll approve.

**Pull request merged**
