### PR TITLE
Fix link to LeveneHaldane.pdf in FunctionRegistry

### PR DESCRIPTION
**Pull request by jbloom22**

### CODE REVIEW

**Comment by danking** [comment]
@jigold is there a way to link to this PDF by name rather than by path?

**Comment by jigold** [comment]
Two options:

1. Add the file path to `html_extra_path` in `conf.py` and then the file will be in the docs directory upon building

2. Make a new directory in `python/hail/docs/`, move the PDF file and image files there, and then add the new directory path to `html_extra_path` in `conf.py`.

**Comment by danking** [comment]
#2 sounds right to me. In general, each version of the docs (right now, just `devel` and `0.1`) needs it's own version of all assets (including the Levene-Haldane pdf).

**Comment by jbloom22** [comment]
Closing in favor of #2205

**Pull request closed without merging**
