### PR TITLE
[batch] Fix duration on the UI by using time_created

### PR DESCRIPTION
**Pull request by daniel-goldstein**

### CODE REVIEW

**Review by jigold — APPROVED** [review]

**Comment by illusional** [comment]
Hey @daniel-goldstein, just checking what caused this issue. Was it the open-batches PR, or prior to the 100 release?

**Comment by jigold** [comment]
It was the open batches PR.

**Comment by illusional** [comment]
Thanks @jigold! Will make sure to collect them as a pair :)

**Comment by daniel-goldstein** [comment]
It was the open batches PR. From that point on, a batch is never "closed", it is either running or complete. So places that use time_closed are better off using time_created

**Comment by daniel-goldstein** [comment]
Oops, should have refreshed to see the new comments before I commented :)

**Pull request merged**
