### PR TITLE
rename_samples now takes a dict instead of a file.

### PR DESCRIPTION
**Pull request by cseed**
Added KeyTable.collect()
Default key_names to [].

### CODE REVIEW

**Comment by cseed** [comment]
I'll make a quick Discuss post when this goes in.

Here is a quick example of renaming as before with a mapping file:

```
        m2 = {r._0: r._1 for r in hc.import_keytable(test_resources + '/sample2_rename.tsv',
                                                     config=TextTableConfig(noheader=True))
              .collect()}
        self.assertEqual(sample2.join(sample2.rename_samples(m2))
                         .count()['nSamples'], 200)
```

**Comment by cseed** [comment]
@danking Any idea why this is failing?  On the CI I'm seeing:

 > Failed to perform checkout on agent: Cannot find commit 8955cc391e0e811ecb3a5325a82dff96eb3a0824

**Comment by danking** [comment]
@cseed that can happen if you force push over an old commit that's building. In my experience, team city will eventually rebuild with the latest commit. What happened this time?

**Comment by cseed** [comment]
I think that's exactly what happened.  It rebuilt on its own accord and eventually turned green.  Thanks!

**Pull request merged**
