### PR TITLE
[batch,ci,pipeline] remove batch from build.yaml and tests

### PR DESCRIPTION
**Pull request by jigold**
Stacked on #7466

### CODE REVIEW

**Comment by cseed** [comment]
Can we remove `batch/`, too?!

**Comment by jigold** [comment]
I wanted to remove /batch in a different PR so it was clear what additional changes there were besides `rm /batch`. I can make it a separate commit though and that should fulfill the same purpose.

**Comment by cseed** [comment]
> I wanted to remove /batch in a different PR so it was clear what additional changes there were besides rm /batch

Smart.  Disregard my suggestion.

**Comment by cseed** [comment]
No longer stacked, needs rebase.

**Pull request merged**
