### PR TITLE
[query] Add a persist to improve performance of blanczos_pca

### PR DESCRIPTION
**Pull request by johnc1231**

### CODE REVIEW

**Comment by tpoterba** [comment]
What's the difference in the benchmark?

**Comment by tpoterba** [comment]
(nice to have it on the PR as a historical record)

**Comment by johnc1231** [comment]
Sure, I can add that. Just on my laptop?

**Comment by tpoterba** [comment]
Yeah, laptop should be fine.

**Comment by johnc1231** [comment]
Before change:

```
{"config": {"cores": 1, "version": "0.2.57-e20c00f05c78", "timestamp": "2020-09-24 08:27:24.863298", "system": "darwin"}, "benchmarks": [{"name": "hwe_normalized_pca_blanczos_small_data_10_iterations", "failed": false, "timed_out": false, "times": [54.736854666000006, 46.213391341000005, 52.75462794499998]}]}
```

After change: 

```
{"config": {"cores": 1, "version": "0.2.57-c013f70fe868", "timestamp": "2020-09-24 08:32:23.991129", "system": "darwin"}, "benchmarks": [{"name": "hwe_normalized_pca_blanczos_small_data_10_iterations", "failed": false, "timed_out": false, "times": [28.998368115000005, 40.65512770199999, 28.816323178000005]}]}
```

Obvious improvement, nearly 2x.

**Review by tpoterba — APPROVED** [review]

**Pull request merged**
