### PR TITLE
[docker] add Boto3 dependency

### PR DESCRIPTION
**Pull request by cseed**
boto3 is the AWS Python client library.  This is for the upcoming S3AsyncFS.  FYI @tpoterba I also added it to the hail package requirements file because it will be exposed via `hailctl cp ...`, etc.

### CODE REVIEW

**Comment by cseed** [comment]
Looks like there is a version conflict on setuptools.  I'm investigating.  However, it looks like we're not pinning in our requirements file:

 > setuptools>=38.6.0

Do you know if there is a reason for that?

**Comment by danking** [comment]
For `hail` we’ve tried to be flexible, but We can move the lower bound or add an upper bound if necessary. I’d this is services stuff that’s just a mistake, definitely pin if you’d like.

**Comment by cseed** [comment]
The failure doesn't appear to be related to my changes.  Installing the docker requirements, which has `setuptools>=38.6.0`, is trying to upgrade to the latest setuptools (56.0.0).  Another dependency might be forcing the upgrade.  However, setuptools was installed via apt, not pip, and that is causing this:

```
  Attempting uninstall: setuptools
    Found existing installation: setuptools 45.2.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'setuptools'. No files were found to uninstall.
```

So there's two things I don't understand.  I'll keep investigating.  I glad I PRed this separately!

**Review by danking — APPROVED** [review]
No objections, I'm good with however you solve the setup tools thing

**Comment by cseed** [comment]
The setuptools thing was actually a red herring, that error isn't fatal, and there was a version conflict elsewhere.  I upgraded urllib3 and requests to resolve.

**Pull request merged**
