### PR TITLE
Feature/update nirvana support

### PR DESCRIPTION
**Pull request by shulik7**
Add the support for latest Nirvana release

### CODE REVIEW

**Comment by tpoterba** [comment]
@jbloom22 can you review this? You know most about Nirvana interop.

Also, how do we get it integrated into cloudtools?

**Comment by jbloom22** [comment]
Closing while updates are made.

**Comment by shulik7** [comment]
We just updated Nirvana public repository with the bugfix being merged with develop branch. (https://github.com/Illumina/Nirvana/tree/develop). I just realized that the supplementary annotation data haven't been updated (regenerated) yet, so no need to update the JSON schema in Nirvana.scala. This feature branch is good for testing current version of Nirvana (develop branch) and supplementary files.

**Comment by jbloom22** [comment]
Great! So here's what the docs look like now:
https://hail.is/docs/devel/methods/genetics.html#hail.methods.nirvana

Here's the Python source:
https://github.com/hail-is/hail/blob/master/python/hail/methods/qc.py

You can see the built docs of this PR by clicking on Details next to the 2.2.0 test, and then clicking on Docs, e.g.:
https://ci.hail.is/viewLog.html?buildId=63354&buildTypeId=HailSourceCode_PRsOnly_HailTestJarSpark220&tab=report_project8_Docs

I'd appreciate if you could:
- ensure the docs are still accurate and add information on what version(s) of Nirvana is compatible.
- update the schema in the documentation to match your changes in Scala
- try running the same pipeline with a few block sizes to see whether its reasonable to reduce the default block size so that users will get more parallelism by default. I suspect a user with a 1 million variant VCF would prefer running 100 cores with 10k variants each to 2 cores with 500k variants each. I'd be surprised if the per-block overhead is so high to outweigh the benefit.

**Comment by shulik7** [comment]
@jbloom22 We lost our AWS EC2 instance I used for performance testing previously. I tried to build HAIL on our cluster, but was out of luck due to some Python issues. We just get another EC2 instance very recently and I haven't had a chance to test the block size yet.

One thing I want to mention is that every Nirvana process will spend several seconds on reading the Cache file and Nirvana can process 10k+ variants per second (on my laptop). Let's say it takes 5 seconds to read the Cache and the annotation speed is 10k variants/s. For 1 million variants, it would take 5*2 + 500/10 = 60 seconds to annotate with a blockSize of 500K. When the blockSize set to 10K, the estimated time would be 5*100 + 1 = 501 seconds. So Nirvana prefers larger chunks of data due to the overhead of loading Cache file and relatively faster annotation speed.

**Comment by shulik7** [comment]
@jbloom22 That would be great. We have made Nirvana even faster recently. Also we are working on reduce the overhead (i.e. time used to load the Cache) for each Nirvana process.  I will test on the best blockSize again when this is done.

**Pull request merged**
