### PR TITLE
[hail/ptypes] refactor getNestedElementPTypes

### PR DESCRIPTION
**Pull request by akotlar**
Makes the unification functionality work for non-canonical ptypes.

### CODE REVIEW

**Comment by akotlar** [comment]
Not sure the best way to handle this. My goal was to not have to match on ptype, if I have on companion type I think I will need to do that. I could also just keep organization as is, and call ptype.copy instead of the canonical constructors

**Comment by tpoterba** [comment]
> Not sure the best way to handle this. My goal was to not have to match on ptype, if I have on companion type I think I will need to do that. I could also just keep organization as is, and call ptype.copy instead of the canonical constructors

I'm pretty sure you can't do this right without matching. I think we should add a non-canonical array and non-canonical struct (both unused in mainline code) to motivate some of these designs.

**Comment by akotlar** [comment]
I'm not sure why this PR wouldn't work (besides the slight awkwardness of calling on one element of the collection, but this is already done in effect in the current getNested, because we match on ptypes.head), but if matching is the way to go, I think we should call ptype.head.copy() in each match arm

ex:

```scala
case x: PStreamable => {
        val elementType = getNestedElementPTypesOfSameType(ptypes.map(_.asInstanceOf[PStreamable].elementType))
        x.copyStreamable(elementType, ptypes.forall(_.required))
      }
```

to

```scala
case x: PStreamable => {
        val elementType = getNestedElementPTypesOfSameType(ptypes.map(_.asInstanceOf[PStreamable].elementType))
        x.copy(elementType, ptypes.forall(_.required))
      }
```

**Comment by tpoterba** [comment]
sorry, I didn't quite understand your last comment.

Suppose we have a `PFixedLengthArray(length: Int, element: PType, required: Boolean)`

We need an algorithm that will have the following properties:
```
unify(
  PCanonicalArray(PInt32Required, true),
  PFixedLengthArray(1, PInt32Required, false))
returns PCanonicalArray(PInt32Required, false)
```

```
unify(
  PFixedLengthArray(1, PInt32Required, false))
  PCanonicalArray(PInt32Required, true),
returns PCanonicalArray(PInt32Required, false)
```

```
unify(
  PFixedLengthArray(1, PInt32Required, false),
  PFixedLengthArray(1, PInt32Required, true))
returns PFixedLengthArray(1, PInt32Required, false)
```

calling something on the head is wrong, as is matching on the head alone. This is going to be a complicated thing, and I want all the logic (at least for each interface like PArray) in the same place.

**Comment by akotlar** [comment]
Thanks Tim, that clarifies.

**Comment by akotlar** [comment]
I had believed we would only want to unify members of the same physical type, which this will not do. I will leave open to implement the change you proposed, but flip to wip

**Comment by akotlar** [comment]
I think this can be solved by implementing canonical on each concrete implementation, and then calling that on each element in the ptypes Seq. We match on ptypes.head.virtualType (or directly on the PType abstract classes), or use the strategy found in this PR. This would give the behavior you’re after.

**Comment by tpoterba** [comment]
> I had believed we would only want to unify members of the same physical type, which this will not do. I will leave open to implement the change you proposed, but flip to wip

yeah, we need to unify different physical representations of the same virtual type, which means there are no restrictions on what we have to be able to unify. Doing this right will require some complexity. We may need some new abstractions.

**Comment by akotlar** [comment]
This won't be merged in anything like the present state

**Comment by tpoterba** [comment]
The current design also totally supports our initial goal of no requiredness on vtype.

**Pull request closed without merging**
