### PR TITLE
update citation section

### PR DESCRIPTION
**Pull request by danking**
cc: @cseed @jbloom22

### CODE REVIEW

**Comment by jbloom22** [comment]
Looks great to me, but Cotton should have a look too.

**Comment by cseed** [comment]
It would be nice if the versions always point to the current version, but I don't quite know how to manage that in the README.

In spite of the Keras example, I object to being the only one listed here.

**Comment by danking** [comment]
re: latest version, it's not too bad to add it to the checklist. However the DOI link *does* always point to the latest.

**Comment by cseed** [comment]
I guess I was afraid of somebody copying and pasting from the README.  But if they're going to do that, they're not going to get right version anyway.

You don't know the release hash until it goes in, which is annoying.

**Comment by danking** [comment]
@cseed got you covered, from a JAR install:
```
In [3]: print(hl.cite_hail_bibtex())                                                                                                         

@misc{Hail,
  author = {Hail Team},
  title = {Hail},
  howpublished = {\url{https://github.com/hail-is/hail/commit/8269129095ea}}
}
```
from pip:
```
In [3]: print(hl.cite_hail_bibtex())                                                                                                         

@misc{Hail,
  author = {Hail Team},
  title = {Hail},
  howpublished = {\url{https://github.com/hail-is/hail/releases/tag/0.2.13}}
}

In [4]: print(hl.cite_hail())                                                                                                                
Hail Team. Hail 0.2.13-81ab564db2b4. https://github.com/hail-is/hail/releases/tag/0.2.13.
```

**Comment by cseed** [comment]
Thanks, @danking, very nice work.

**Pull request merged**
