### PR TITLE
[notebook] add workshop index page

### PR DESCRIPTION
**Pull request by cseed**
Summary of changes:
 - add a / index page to the workshop service with some chipper content.  FYI @tpoterba, feel free to change if you don't like.
 - make csrf token session-based
 - add common render_template function to web_common that handles csrf and jinja2 rendering.  This is necessary because the header has a logout button (potentially) so every page needs make sure the csrf is set.
 - added a toplevel make check target
 - fixed a forwarding bug: Host: $updated_host needs to get set when proxying to the notebook itself or you get cross-origin errors in the notebook

Things I have left to do:
 - make the notebook non-clickable when it isn't ready
 - write up a UI testing playbook
 - link to notebook/workshop-admin somewhere

### CODE REVIEW

**Comment by akotlar** [comment]
Notebook2 link should be changed to redirect to notebook 1. 
Screen Shot 2019-09-27 at 7 42 30 PM

**Comment by cseed** [comment]
> I'm seeing issues creating notebooks (500)

I can't reproduce this.  Can you give me more details?  Where are you running it?  Note, my namespace is running a different branch that I'm working on (e.g. the menu stuff which doesn't include these changes.)

 > reaching CI and Batch (502)

Is this in my namespace?  I don't have CI or Batch deployed.  Let me know if you want to test it there and I'll spin up this branch.  Is it not working in your namespace?

 > Notebook2 link should be changed to redirect to notebook 1.

There should be no notebook2 links.  I just grepped through the entire codebase, I didn't find anything.  We're not asking for notebook2 certs anymore.  Notebook2 is dead, long live notebook.  Nobody is using it besides us, so I don't see any need for maintaining backward compatibility.  In particular, if/when we make this more widely available, there shouldn't be anything2.

**Comment by akotlar** [comment]
> There should be no notebook2 links. I just grepped through the entire codebase, I didn't find anything. We're not asking for notebook2 certs anymore. Notebook2 is dead, long live notebook. Nobody is using it besides us, so I don't see any need for maintaining backward compatibility. In particular, if/when we make this more widely available, there shouldn't be anything2.

I just mean we should have a gateway/router redirect

**Comment by cseed** [comment]
Ah.  This has nothing to do with notebook2.  We have a wildcard DNS entry for *.hail.is so we don't have to modify DNS every time we add/remove a service.  However, Let's Encrypt didn't support wildcard certificates when I wrote that code.  So anything.hail.is will get a cert error.  To fix this we either need to get a wildcard cert or fix the subdomains we use in DNS.

**Comment by cseed** [comment]
I created an issue for it: https://github.com/hail-is/hail/issues/7159

**Comment by akotlar** [comment]
> I created an issue for it: #7159

Nice, thank you

**Comment by akotlar** [comment]
> I can't reproduce this. Can you give me more details? Where are you running it? Note, my namespace is running a different branch that I'm working on (e.g. the menu stuff which doesn't include these changes.)

Makes sense. Could you update the branch in your namespace? If not I can check tomorrow in mine.

> Is this in my namespace? I don't have CI or Batch deployed. Let me know if you want to test it there and I'll spin up this branch. Is it not working in your namespace?

Got it. It's just that these changes affect CI and Batch, so I would like to quickly glance at a working example. Again, can do this tomorrow in my namespace. Not entirely comfortable with dev deploy yet, so want to try it when I'm less tired.

Sounds like this will go in tomorrow

**Comment by cseed** [comment]
This branch, notebook, ci and batch are deployed in my namespace now.  Note, batch is tested pretty well, and we test CI comes up (which is about all you can do in a dev deploy).

**Comment by akotlar** [comment]
Hm, batch works, ci gives 404. https://internal.hail.is/cseed/notebook/notebook is stil 500'ing when I click on create notebook, even after hard refresh.

**Comment by akotlar** [comment]
The error, some resources are missing. 

```sh
{"levelname": "ERROR", "asctime": "2019-09-29 03:43:05,260", "filename": "web_protocol.py", "funcNameAndLine": "log_exception:355", "message": "Error handling request", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/aiohttp/web_protocol.py\", line 418, in start\n    resp = await task\n  File \"/usr/local/lib/python3.6/dist-packages/aiohttp/web_app.py\", line 458, in _handle\n    resp = await handler(request)\n  File \"/usr/local/lib/python3.6/dist-packages/aiohttp/web_middlewares.py\", line 119, in impl\n    return await handler(request)\n  File \"/usr/local/lib/python3.6/dist-packages/aiohttp/web_middlewares.py\", line 119, in impl\n    return await handler(request)\n  File \"/usr/local/lib/python3.6/dist-packages/aiohttp/web_middlewares.py\", line 119, in impl\n    return await handler(request)\n  File \"/usr/local/lib/python3.6/dist-packages/aiohttp_session/__init__.py\", line 152, in factory\n    response = await handler(request)\n  File \"/usr/local/lib/python3.6/dist-packages/gear/csrf.py\", line 20, in wrapped\n    return await fun(request, *args, **kwargs)\n  File \"/usr/local/lib/python3.6/dist-packages/gear/auth.py\", line 77, in wrapped\n    return await fun(request, userdata, *args, **kwargs)\n  File \"/usr/local/lib/python3.6/dist-packages/notebook/notebook.py\", line 417, in post_notebook\n    return await _post_notebook('notebook', request, userdata)\n  File \"/usr/local/lib/python3.6/dist-packages/notebook/notebook.py\", line 278, in _post_notebook\n    pod = await start_pod(k8s, service, userdata, notebook_token, jupyter_token)\n  File \"/usr/local/lib/python3.6/dist-packages/notebook/notebook.py\", line 167, in start_pod\n    _request_timeout=KUBERNETES_TIMEOUT_IN_SECONDS)\n  File \"/usr/local/lib/python3.6/dist-packages/kubernetes_asyncio/client/api_client.py\", line 166, in __call_api\n    _request_timeout=_request_timeout)\n  File \"/usr/local/lib/python3.6/dist-packages/kubernetes_asyncio/client/rest.py\", line 230, in POST\n    body=body))\n  File \"/usr/local/lib/python3.6/dist-packages/kubernetes_asyncio/client/rest.py\", line 181, in request\n    raise ApiException(http_resp=r)\nkubernetes_asyncio.client.rest.ApiException: (422)\nReason: Unprocessable Entity\nHTTP response headers: <CIMultiDictProxy('Audit-Id': '16158e81-8543-457e-8bea-5d5e1a8c39f3', 'Content-Type': 'application/json', 'Date': 'Sun, 29 Sep 2019 03:43:05 GMT', 'Content-Length': '901')>\nHTTP response body: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Pod \\\"notebook-worker-9z6tg\\\" is invalid: [spec.volumes[1].secret.secretName: Required value, spec.volumes[2].secret.secretName: Required value, spec.containers[0].volumeMounts[1].name: Not found: \\\"gsa-key\\\", spec.containers[0].volumeMounts[2].name: Not found: \\\"user-tokens\\\"]\",\"reason\":\"Invalid\",\"details\":{\"name\":\"notebook-worker-9z6tg\",\"kind\":\"Pod\",\"causes\":[{\"reason\":\"FieldValueRequired\",\"message\":\"Required value\",\"field\":\"spec.volumes[1].secret.secretName\"},{\"reason\":\"FieldValueRequired\",\"message\":\"Required value\",\"field\":\"spec.volumes[2].secret.secretName\"},{\"reason\":\"FieldValueNotFound\",\"message\":\"Not found: \\\"gsa-key\\\"\",\"field\":\"spec.containers[0].volumeMounts[1].name\"},{\"reason\":\"FieldValueNotFound\",\"message\":\"Not found: \\\"user-tokens\\\"\",\"field\":\"spec.containers[0].volumeMounts[2].name\"}]},\"code\":422}\n\n"}
```

**Comment by cseed** [comment]
You need a trailing slash.  Your PR to fix this hasn't gone in yet.

**Comment by cseed** [comment]
Ah, yeah, your account in my namespace isn't real enough to launch a notebook.  Works fine for me.

**Comment by akotlar** [comment]
Got it, that solves the ci issue, should we add a trailing slash to the link?

**Comment by akotlar** [comment]
> Ah, yeah, your account in my namespace isn't real enough to launch a notebook. Works fine for me.

Sounds good

**Comment by cseed** [comment]
Oops, sorry, your PR was for the monitoring namespace.  I see the problem, CI doesn't have a route for `''`.  I'll push a fix.

**Comment by akotlar** [comment]
> Oops, sorry, your PR was for the monitoring namespace. I see the problem, CI doesn't have a route for `''`. I'll push a fix.

Yeah, monitoring, thought you meant it was a similar issue (exact route not matching).

**Comment by cseed** [comment]
OK, fixed and deployed.  It works now.

**Comment by akotlar** [comment]
confirmed, nice

**Pull request merged**
