### PR TITLE
Refactor Python IR to reduce code duplication and complexity

### PR DESCRIPTION
**Pull request by tpoterba**
Contains one piece of a fix for #5262

This refactor was initially undertaken to resolve the above issue, which
manifested due to the nested stack frames created by the IR renderer.

### CODE REVIEW

**Comment by tpoterba** [comment]
oh god this is huge

**Comment by tpoterba** [comment]
Arcturus has volunteered as tribute

**Comment by catoverdrive** [comment]
@tpoterba This looks pretty reasonable and I'm happy to approve once it's rebased etc. The one thing I'd be a little curious to see is if and how this PR affects the overhead of constructing and passing large IRs in Python, which I think @chrisvittal is seeing some slowness in?

**Comment by tpoterba** [comment]
it's actually a bit slower (2x) than using f-strings. I could serialize a million-node IR tree in 100ms, though, so I don't think this is the limiting factor compared to the optimization in the backend.

**Comment by catoverdrive** [comment]
I think Chris mentioned that he was seeing something slow on the python end of things (pre-serialization), although I don't entirely remember what the issue was. @chrisvittal?

**Comment by chrisvittal** [comment]
For ~1500 joint caller inputs, on what was a frankenbranch (I merged a bunch of stuff together, haven't pushed it). I saw that IR construction in python took around a minute. I'm not entirely sure where the time was being spent though. Also 1 minute is nothing compared to the amount of time we spend actually joint calling.

Anyways, `run_combiner.py`
```python3
def run_combiner(sample_list, json, out_path, tmp_path, summary_path=None, overwrite=False):
    # make the temp path a directory, no matter what
    tmp_path += f'/combiner-temporary/{uuid.uuid4()}/'
    vcfs = [comb.transform_one(vcf)
            for vcf in hl.import_vcfs(sample_list, json, array_elements_required=False)]
    combined = [comb.combine_gvcfs(mts) for mts in chunks(vcfs, MAX_COMBINER_LENGTH)]
    if len(combined) == 1:
        combined[0].write(out_path, overwrite=overwrite)
    else:
        hl.utils.java.info(f'Writing combiner temporary files to: {tmp_path}')
        ... # do more, but this stage isn't huge yet so :man_shrugging: 
```
Relevant log:
```
2019-03-01 22:09:20 DAGScheduler: INFO: Job 0 finished: collect at LoadVCF.scala:1295, took 88.076400 s
2019-03-01 22:10:19 Hail: INFO: Writing combiner temporary files to: gs://cdv-hail/combiner/tmp//combiner-temporary/dc741728-fdfd-49d9-a66e-94bd7b541879/
```
Stage zero is tabix reading `sc.parallelize`. The next line is the logging line that I added, almost a minute apart. After that it's 30 seconds for the Optimizer and Lowerer and (printing hundreds of thousands of lines of IR).

**Comment by chrisvittal** [comment]
Basically PyObject initialization is slow and sad. :crying_cat_face:

**Comment by tpoterba** [comment]
are you sure that's what it is? I think it's more likely that the work done on MatrixTable class construction is the slow bit here.

**Comment by tpoterba** [comment]
This iteration also uses an extremely slow py4j protocol
```
    return [MatrixTable._from_java(jmir) for jmir in jmirs]

```

**Comment by chrisvittal** [comment]
That could be it. If you have time, I'd like to see what we could do about it, but not here of course.

**Pull request merged**
