### PR TITLE
rewrite hl.agg.hist in python

### PR DESCRIPTION
**Pull request by catoverdrive**
Histograms are basically a group_by on the bin index. The implementation is a tad more complex than I would have hoped, but I think it will be nice to not have to maintain an extra aggregator.

(Actually, I think if we break apart the array elements aggregator interface in the right way, hl.agg.hist might be written pretty naturally in terms of that. But that may need to wait until the old aggregators are gone.)

### CODE REVIEW

**Comment by tpoterba** [comment]
this is pretty cool though

**Comment by catoverdrive** [comment]
I registered the functions inside and outside the actual aggregation to bring the IR size all the way down to about what it was before. It was maybe 140 before I did that, 30 of which belonged to the string concatenation in the error messages :(. 

This also hit a bug that I'm fixing in #6740, so it won't be able to go in before that does.

**Comment by catoverdrive** [comment]
So this is failing the `test_aggregators_hist_neg0` test, which asserts that a value of -0.0 falls outside of the bins for `[0, 2, 4, 6, 8, 10]`. I really don't see why this is the desired behavior, but this is how it stands as the fix to #5846. I can pretty easily fix this to use `compare` instead of `<=`, but I'd instead like to fix the test so that we consider -0.0 to be in the bin [0.0, 2.0). 

@tpoterba @chrisvittal

**Comment by tpoterba** [comment]
the real problem with #5846 was that -0.0 threw an exception! Treating it as 0 seems fine.

**Pull request merged**
