### PR TITLE
modify hail-jupyter image so jupyter can be invoked directory

### PR DESCRIPTION
**Pull request by cseed**
for use by new notebook server

Let's make sure this is working in the test setup before we merge it.

### CODE REVIEW

**Comment by akotlar** [comment]
It doesn't seem like headless mode is in effect, at least in the most recent published image. Will grab this and play around with it.

Tested Dan's image in app.hail.is, seems to work, except for all of the .js/.css resources; first guess is SSL, but it's clearly a diff issue. I can't connect to your workers, can to his.

Will update in a bit.

Yours:
(notebook) alexkotlar:~/projects/hail-clone/notebook-api:$ k logs notebook-worker-5xq2w -f
[I 21:29:01.483 NotebookApp] Writing notebook server cookie secret to /home/jovian/.local/share/jupyter/runtime/notebook_cookie_secret
[I 21:29:03.742 NotebookApp] Serving notebooks from local directory: /home/jovian
[I 21:29:03.743 NotebookApp] The Jupyter Notebook is running at:
[I 21:29:03.743 NotebookApp] http://localhost:8888/instance/notebook-worker-service-qzppk/?token=...
[I 21:29:03.743 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 21:29:03.750 NotebookApp] No web browser found: could not locate runnable browser.


Dan’s
[I 21:44:38.439 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[I 21:44:38.808 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 21:44:38.898 NotebookApp] Jupyter-Spark enabled!
[I 21:44:38.942 NotebookApp] JupyterLab extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 21:44:38.942 NotebookApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 21:44:38.945 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 21:44:38.945 NotebookApp] The Jupyter Notebook is running at:
[I 21:44:38.946 NotebookApp] http://(notebook-worker-v7fr4 or 127.0.0.1):8888/instance/notebook-worker-service-sv5jl/?token=...
[I 21:44:38.946 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 21:44:55.324 NotebookApp] 302 GET /instance/notebook-worker-service-sv5jl/?access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik16YzNRekpFUXpWRk5VSXdPRE0yTmpJMFF6VkZPVVk1TkRZME9UZzJOa00xUkRBek1ERTJOZyJ9.eyJpc3MiOiJodHRwczovL2hhaWwuYXV0aDAuY29tLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTEwNzI2NTIxOTIxMjQ5NDQzNzYwIiwiYXVkIjpbImhhaWwiLCJodHRwczovL2hhaWwuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTU0OTIzMDI2MSwiZXhwIjoxNTQ5MjM3NDYxLCJhenAiOiJURDc4azIzQ2NkTTRwTVdvWVp3WXdLSmJRUEJqMDZqWSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUifQ.p3HjkP5t3xrGMGOG8kkCocRCg6BRSrGiO_ymwjqQt-omgk55KnObZCJXFX20BM6n6azzNvF_8EpruB3iSRAFiuhwVvHyabwvRpSZAy3giOpYyxgnj4mPlphdAF9c0yduIU-VpLA6ifaqF9Tj69pfMlFfdjo5ku1tkJnRIkysWYB58bXCqRp9dYSYxZZ45X52YOoP_VrnyyIWX4AvZnp-1Cy9nssFV6l6j2PJmvqkMPLR0suS-lR6NK6PMRRiOessKZy3SXwLJv1oLhJW7qFFEb8kP9pG7zoW0v-TpP9f-XBH0UE9WNaIyur0QOU80qsUa7CmjMdLoi7klDBqdfx-Mg&token=ef8707c52ba1439e9b7ebf78e136075d (10.32.13.94) 0.85ms
alexkotlar:~/projects/hail/web/packages/web-client:$

**Comment by cseed** [comment]
I don't think the browser error should pose a problem, it just failed to open a browser.  Jupyter should still be running.  I run it with `--no-browser`.  I'm not sure how Dan's image managed that without the option, I will investigate.

You can't connect to my image because it is binding localhost.  You can pass `--ip 0.0.0.0` or I can figure out how Dan's image is doing it.

**Comment by cseed** [comment]
Yeah, can you invoke with `--no-browser` and `--ip 0.0.0.0`?  I think that will fix it and (at the moment) seem easier than pushing another image.

**Comment by akotlar** [comment]
@cseed All set!

**Pull request merged**
