### PR TITLE
Re-enabled -Xfatal-warnings.

### PR DESCRIPTION
**Pull request by cseed**
Removed	   local argument to HailContext constructor.

### CODE REVIEW

**Comment by cseed** [comment]
Thanks!  Now I just need to debug the "JVM crashed".  Yay, me.

**Comment by danking** [comment]
@cseed bump

**Comment by danking** [comment]
@cseed perhaps you should delegate  this to someone else to debug?

**Comment by cseed** [comment]
Will revisit.

**Pull request closed without merging**
