### PR TITLE
Add package tests to hail.methods

### PR DESCRIPTION
**Pull request by tpoterba**
Somewhat stubby.

Dependent on #2578

### CODE REVIEW

**Comment by tpoterba** [comment]
The point of this PR was to just build up a shell we can add to, not to fully move the tests over yet. There's more functionality we have to add to Hail2 first.

**Comment by tpoterba** [comment]
Good comment though, and it's definitely on the list!

**Comment by danking** [comment]
split_multi takes three arguments, apparently?

**Comment by tpoterba** [comment]
I think Cotton's PR changed it under me

**Comment by tpoterba** [comment]
Should be split_multi_hts now?

**Pull request merged**
