### PR TITLE
[hail] coalesce

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by konradjk** [comment]
Hmm, I realized one problem with this - the error message will return that of coalesce rather than or_else and might be a little confusing.

**Comment by tpoterba** [comment]
yeah, I realized that and don't mind. Good for people to know it's just an alias, since coalesce is more generala.

**Comment by konradjk** [comment]
Yeah but it would really mess with debugging. I think probably still worth keeping the `unify_exprs` and `TypeError` lines (it'll be a little redundant, but it's just type checking so shouldn't be slow)

**Comment by tpoterba** [comment]
done

**Pull request merged**
