### PR TITLE
Added set_va_attributes to expose setting Field attributes

### PR DESCRIPTION
**Pull request by lfrancioli**
Needed to output correct VCF Header
In addition:
- Annotations generated using annotate_alleles_expr now have 'Number=A'
- VEP now parses the Description when using csq=True option (required to know the fields stored in the  |-delimited field)
- VEP annotations with csq=True option is now of type Array[String]. (how it should be)

### CODE REVIEW

**Comment by jbloom22** [comment]
Add test please.

**Comment by lfrancioli** [comment]
Just added tests, @jbloom22 !

**Comment by jbloom22** [comment]
There are some tiny formatting issues and typos, but the main thing is to add an short examples section in docs that makes clear what this is useful for.  I'd put one example for INFO field and one for FORMAT field.

For other commands for format, like:
https://hail.is/hail/hail.VariantDataset.html#hail.VariantDataset.pca

**Comment by lfrancioli** [comment]
Done @jbloom22 !

**Comment by jbloom22** [comment]
@lfrancioli is adding Set and Array methods that will clean up the example in another PR, and then planning to modify this one to have the following behavior:
```
Reposting here after (a) discussions with Konrad and (b) a quick look at the code. And I think that it'd make more sense to handle the filters (va.filters) this way:
- If no filtering was applied => NA: Set[String]. When exported to VCF => .
- If filtering was applied but variant wasn't filtered => Set(). When exported to VCF => PASS
- If filtered => Set containing the filter names (current behavior). When exported to VCF, current behavior.
```
Closing for now.

**Pull request closed without merging**
