### PR TITLE
[docker][batch] Switch to Python 3.7

### PR DESCRIPTION
**Pull request by jigold**

### CODE REVIEW

**Comment by johnc1231** [comment]
This doesn't affect hail at all right? Because hail only supports up to 3.7

**Comment by jigold** [comment]
Why does Hail only support up to 3.7?

**Comment by tpoterba** [comment]
pyspark doesnt' support 3.8

**Comment by jigold** [comment]
ok

**Comment by jigold** [comment]
I confirmed the python3 alias works:

```
(base) wmecc-475:batch jigold$ docker run -it gcr.io/hail-vdc/ci-intermediate:vta9lvmzyu3t /bin/bash
root@45326d721af1:/# python3
Python 3.7.5 (default, Nov  7 2019, 10:50:52)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by jigold** [comment]
Stacked on #8437

**Comment by danking** [comment]
PySpark supports 3.8 https://github.com/apache/spark/blob/master/python/setup.py#L227

**Comment by jigold** [comment]
> /hail/backend/hail-all-spark.jar'

Where does backend come from? Also, that file has a shebang '/opt/conda/default/bin/python3'

**Comment by jigold** [comment]
Looks like it just got changed.

**Comment by jigold** [comment]
The CI tests were failing due to not enough disk space on the workers. I increased the size to 20 GB, but this requires a migration. I'll need to setup a VM with the ability to deploy to have this new image pre-built. The last time I did a migration from the VM, it took a long time to deploy despite pre-caching the image, so I'll want to build a new VM with more cores to see if that helps. We should wait until after Konrad's jobs are done to do this.

**Comment by danking** [comment]
I just built the image using dev deploy of this branch to check its size and it's only grown by 8MB. What else is causing disk usage growth?

```
# docker image ls gcr.io/hail-vdc/ci-intermediate:anrd6xyjsrnd
REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
gcr.io/hail-vdc/ci-intermediate   anrd6xyjsrnd        2a479e5a34c4        53 seconds ago      363MB
# docker image ls gcr.io/hail-vdc/batch-worker:g76daybmi5g1                                                                              
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
gcr.io/hail-vdc/batch-worker   g76daybmi5g1        6782b39e4d31        45 hours ago        355MB
```

**Comment by jigold** [comment]
It's able to use the prebuilt image before. Now, base:latest in GCR diverges from the 3.7 version, so it has to build the context from scratch

**Comment by jigold** [comment]
I'm not sure why this is still failing. It looks like the CI jobs are all succeeding, but the last jobs in the batch aren't getting scheduled. Building the base image on the worker is taking 2 minutes 25 seconds.

**Comment by jigold** [comment]
ok. Figured it out. The issue is that the build of the new image finally succeeded after 18 minutes, but the test timed out and batch must have been shut down already.

**Comment by jigold** [comment]
The first image being built is just ubuntu and not the base image.

**Comment by jigold** [comment]
I think the thing to do is to increase the time for test_ci to 30 minutes.

**Comment by jigold** [comment]
@danking This is finally passing. I had to change the test_ci to timeout after 30 minutes. Do you want to do the migration? If not, then I'll figure out how to try and make a faster VM later today.

**Comment by danking** [comment]
I'll handle it.

**Pull request merged**
