### PR TITLE
[release] update changelog for 0.2.103

### PR DESCRIPTION
**Pull request by jigold**

### CODE REVIEW

**Comment by tpoterba** [comment]
(hail#12305): Fixed a rare crash reading tables/matrixtables with _intervals

**Review by tpoterba — DISMISSED** [review]

**Comment by tpoterba** [comment]
marked as WIP to make PR to delete stray compiler println

**Comment by tpoterba** [comment]
#12348

**Comment by danking** [comment]
I removed WIP. Should merge soon!

**Review by daniel-goldstein — APPROVED** [review]

**Pull request merged**
