### PR TITLE
[batch2] Don't generate broken links to log/status for pending jobs

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by jigold** [comment]
@cseed Should the behavior of the logs be to not have a link if the job is ready or pending or to report None? Right now, we report None for `status` if it's ready or pending and have a web.HTTPNotFound error for logs when it's pending or ready. I think we should have it be consistent between logs and status and I think having no links in the ready and pending case is clearer.

**Comment by cseed** [comment]
So I think we should fix this is in a slightly different way.  First, I want to unify the log and status page.  Second, I want the status to actually include the whole job configuration, of which status is just a sub-field, so you can look at detail to what you submitted.  Then it would make sense for these links to always be present.

That said, they obviously shouldn't be broken.  Instead of 404, we should just say "job is pending, no logs" or wahtever.

Let me make pass on the batch2 UI and then revisit this, OK?

**Comment by tpoterba** [comment]
should this be closed?

**Comment by jigold** [comment]
Yes

**Comment by jigold** [comment]
#7530 Should fix this

**Pull request closed without merging**
