### PR TITLE
Add Long signature for sum aggregator over integral types

### LINKED ISSUE #900: sum should preserve the input type, not promote everything to doubles

### PR DESCRIPTION
**Pull request by tpoterba**
Fixes #900

### CODE REVIEW

**Comment by jbloom22** [comment]
By using Double and converting to Long:
1) there may be off-by-one errors from what is expected (both 0.99999999 and -0.99999999 go to 0)
2) you can only represent up to 2^53 = 9e15 exactly, rather than 2^63:
https://en.wikipedia.org/wiki/Double-precision_floating-point_format#IEEE_754_double-precision_binary_floating-point_format:_binary64

So question is whether to create a Long version of aggregator for both Int and Long, analogous to Double for Float and Double.

**Comment by jbloom22** [comment]
Actually, rounding won't be an issue so long as you're adding ints and stay in mantissa range.  (2) is still an issue if folks expect Long range

**Comment by tpoterba** [comment]
@jigold any concerns with this PR as it is?

**Comment by tpoterba** [comment]
There are already tests that sum integers, and all of them still work!

**Comment by cseed** [comment]
This is obviated by my imminent aggregator registry changes.  The L suffix change should be a separate PR.  I'll integrate the tests into my branch.

**Pull request closed without merging**
