### PR TITLE
[batch] increment worker instance version

### PR DESCRIPTION
**Pull request by danking**
https://github.com/hail-is/hail/commit/1940547d35ddddb084ad52684e36153c1e03a331 should have incremented the worker version. New QoB logging is incompatible with old workers.

### CODE REVIEW

**Comment by danking** [comment]
For posterity, the Zulip thread where we diagnosed the issue: https://hail.zulipchat.com/#narrow/stream/278688-grafana/topic/batch/near/354939744

**Review by daniel-goldstein — APPROVED** [review]

**Comment by danking** [comment]
I'll retry, but Azure is doing something weird right now:
```
FAILED
_____________________ test_pool_highcpu_instance_cheapest ______________________

client = <hailtop.batch_client.client.BatchClient object at 0x7f97f907d690>

    def test_pool_highcpu_instance_cheapest(client: BatchClient):
        bb = create_batch(client)
        resources = {'cpu': '0.25', 'memory': '50Mi'}
        j = bb.create_job(DOCKER_ROOT_IMAGE, ['true'], resources=resources)
        b = bb.submit()
        status = j.wait()
        assert status['state'] == 'Success', str((status, b.debug_info()))
>       assert 'highcpu' in status['status']['worker'], str((status, b.debug_info()))
E       AssertionError: ({'batch_id': 74, 'job_id': 1, 'name': None, 'user': 'test', 'billing_project': 'test', 'state': 'Success', 'exit_code': 0, 'duration': 609, 'cost': 1.1510333711392028e-06, 'msec_mcpu': 0, 'status': {'version': 5, 'worker': 'batch-worker-pr-12955-default-rrlcxki12v8r-standard-0e2wl', 'batch_id': 74, 'job_id': 1, 'attempt_id': 'gAaTm8', 'user': 'test', 'state': 'succeeded', 'format_version': 7, 'resources': [{'name': 'az/vm/Standard_D8ds_v4/spot/eastus/1682899200000', 'quantity': 32}, {'name': 'az/disk/E4_LRS/eastus/1546300800000', 'quantity': 1024}, {'name': 'az/ip-fee/1024/2021-12-01', 'quantity': 32}, {'name': 'az/service-fee/2021-12-01', 'quantity': 250}], 'region': 'eastus', 'start_time': 1682966178997, 'end_time': 1682966179606, 'container_statuses': {'main': {'name': 'batch-74-job-1-main', 'state': 'succeeded', 'timing': {'pulling': {'start_time': 1682966179035, 'finish_time': 1682966179224, 'duration': 189}, 'setting up overlay': {'start_time': 1682966179224, 'finish_time': 1682966179253, 'duration': 29}, 'setting up network': {'start_time': 1682966179253, 'finish_time': 1682966179253, 'duration': 0}, 'running': {'start_time': 1682966179253, 'finish_time': 1682966179340, 'duration': 87}, 'uploading_log': {'start_time': 1682966179340, 'finish_time': 1682966179361, 'duration': 21}, 'uploading_resource_usage': {'start_time': 1682966179361, 'finish_time': 1682966179407, 'duration': 46}}, 'container_status': {'started_at': 1682966179253, 'finished_at': 1682966179340, 'state': 'finished', 'exit_code': 0, 'out_of_memory': False}}}, 'timing': {'setup_io': {'start_time': 1682966178998, 'finish_time': 1682966178999, 'duration': 1}, 'configuring xfsquota': {'start_time': 1682966178999, 'finish_time': 1682966179035, 'duration': 36}, 'populating secrets': {'start_time': 1682966179035, 'finish_time': 1682966179035, 'duration': 0}, 'adding cloudfuse support': {'start_time': 1682966179035, 'finish_time': 1682966179035, 'duration': 0}, 'post-job finally block': {'start_time': 1682966179578}}}, 'spec': {'always_copy_output': False, 'job_id': 1, 'process': {'command': ['true'], 'image': 'haildev.azurecr.io/ubuntu:20.04', 'mount_docker_socket': False, 'type': 'docker'}, 'resources': {'req_cpu': '0.25', 'req_memory': '50Mi', 'req_storage': '0Gi', 'cores_mcpu': 250, 'memory_bytes': 1073741824, 'storage_gib': 0, 'preemptible': True}, 'secrets': [{'namespace': 'pr-12955-default-rrlcxki12v8r', 'name': 'test-gsa-key', 'mount_path': '/gsa-key', 'mount_in_copy': True}], 'env': [{'name': 'AZURE_APPLICATION_CREDENTIALS', 'value': '/gsa-key/key.json'}]}}, {'status': {'id': 74, 'user': 'test', 'billing_project': 'test', 'token': 'tiQog0l-k0Xp2TkavWlV37Xy9FWcC1530EtCMRfg8XQ', 'state': 'success', 'complete': True, 'closed': True, 'n_jobs': 1, 'n_completed': 1, 'n_succeeded': 1, 'n_failed': 0, 'n_cancelled': 0, 'time_created': '2023-05-01T18:36:18Z', 'time_closed': None, 'time_completed': '2023-05-01T18:36:19Z', 'duration': 'a second', 'msec_mcpu': 0, 'cost': 1.1510333711392028e-06, 'attributes': {'name': 'test_pool_highcpu_instance_cheapest'}}, 'jobs': [{'log': {'main': ''}, 'status': {'batch_id': 74, 'job_id': 1, 'name': None, 'user': 'test', 'billing_project': 'test', 'state': 'Success', 'exit_code': 0, 'duration': 609, 'cost': 1.1510333711392028e-06, 'msec_mcpu': 0, 'status': {'version': 5, 'worker': 'batch-worker-pr-12955-default-rrlcxki12v8r-standard-0e2wl', 'batch_id': 74, 'job_id': 1, 'attempt_id': 'gAaTm8', 'user': 'test', 'state': 'succeeded', 'format_version': 7, 'resources': [{'name': 'az/vm/Standard_D8ds_v4/spot/eastus/1682899200000', 'quantity': 32}, {'name': 'az/disk/E4_LRS/eastus/1546300800000', 'quantity': 1024}, {'name': 'az/ip-fee/1024/2021-12-01', 'quantity': 32}, {'name': 'az/service-fee/2021-12-01', 'quantity': 250}], 'region': 'eastus', 'start_time': 1682966178997, 'end_time': 1682966179606, 'container_statuses': {'main': {'name': 'batch-74-job-1-main', 'state': 'succeeded', 'timing': {'pulling': {'start_time': 1682966179035, 'finish_time': 1682966179224, 'duration': 189}, 'setting up overlay': {'start_time': 1682966179224, 'finish_time': 1682966179253, 'duration': 29}, 'setting up network': {'start_time': 1682966179253, 'finish_time': 1682966179253, 'duration': 0}, 'running': {'start_time': 1682966179253, 'finish_time': 1682966179340, 'duration': 87}, 'uploading_log': {'start_time': 1682966179340, 'finish_time': 1682966179361, 'duration': 21}, 'uploading_resource_usage': {'start_time': 1682966179361, 'finish_time': 1682966179407, 'duration': 46}}, 'container_status': {'started_at': 1682966179253, 'finished_at': 1682966179340, 'state': 'finished', 'exit_code': 0, 'out_of_memory': False}}}, 'timing': {'setup_io': {'start_time': 1682966178998, 'finish_time': 1682966178999, 'duration': 1}, 'configuring xfsquota': {'start_time': 1682966178999, 'finish_time': 1682966179035, 'duration': 36}, 'populating secrets': {'start_time': 1682966179035, 'finish_time': 1682966179035, 'duration': 0}, 'adding cloudfuse support': {'start_time': 1682966179035, 'finish_time': 1682966179035, 'duration': 0}, 'post-job finally block': {'start_time': 1682966179578}}}, 'spec': {'always_copy_output': False, 'job_id': 1, 'process': {'command': ['true'], 'image': 'haildev.azurecr.io/ubuntu:20.04', 'mount_docker_socket': False, 'type': 'docker'}, 'resources': {'req_cpu': '0.25', 'req_memory': '50Mi', 'req_storage': '0Gi', 'cores_mcpu': 250, 'memory_bytes': 1073741824, 'storage_gib': 0, 'preemptible': True}, 'secrets': [{'namespace': 'pr-12955-default-rrlcxki12v8r', 'name': 'test-gsa-key', 'mount_path': '/gsa-key', 'mount_in_copy': True}], 'env': [{'name': 'AZURE_APPLICATION_CREDENTIALS', 'value': '/gsa-key/key.json'}]}}}]})
E       assert 'highcpu' in 'batch-worker-pr-12955-default-rrlcxki12v8r-standard-0e2wl'

```

**Comment by daniel-goldstein** [comment]
@danking It's May 1st, any chance that the calculus changed on cheapest option for that spec?

**Comment by danking** [comment]
We really need a page that displays the current status of resources

**Comment by danking** [comment]
Spot cores indeed got cheaper:
```
| az/vm/Standard_D8ds_v4/spot/eastus/1680307200000    |  0.00000000004422498914930556 |       52602 |               52602 |
| az/vm/Standard_D8ds_v4/spot/eastus/1682899200000    |  0.00000000003538601345486111 |       52640 |               52640 |
```

**Comment by danking** [comment]
Spot F's got more expensive but still cheaper than D's.
```
| az/vm/Standard_F8s_v2/spot/eastus/1680307200000    | 0.000000000016796061197916665 |       52629 |               52629 |
| az/vm/Standard_F8s_v2/spot/eastus/1682899200000    |  0.00000000001763156467013889 |       52667 |               52667 |
```

**Pull request merged**
