### PR TITLE
Web PR 1

### PR DESCRIPTION
**Pull request by akotlar**
First of several web-related commits.

Simply adds Lerna to manage (from future PRs) web apps and related micro services, as a monorepo. Deduplicate dependencies, install using a single command.

The package.lock file is the majority of LOC, and it's automatically generated by npm install for a given package.json at a given point in time. We should commit these to ensure that subsequent npm install commands generated the same dependency tree. I think we should assume that this file is correct for the moment.

https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

Lerna: https://lernajs.io

We can also choose not to use Lerna here and treat all web-related micro services as completely independent.

### CODE REVIEW

**Comment by cseed** [comment]
@catoverdrive bump.  If you're not planning to be on team web front-end, let's get someone else to look at this.

**Comment by catoverdrive** [comment]
ok. I've reassigned this to @danking---I don't think I can commit the bandwidth right now to get up to speed and stay up to speed on front-end stuff right now, unfortunately.

**Comment by akotlar** [comment]
@cseed stated that he doesn't want this structure, where web-related JS packages can be managed together. I'm closing this in favor of moving web-client and auth up from /web/packages/ to /auth and /web-client.

First step will still be PR'ing the lock files.

**Comment by danking** [comment]
OK, assign that PR to me.

**Pull request closed without merging**
