### PR TITLE
[release] Update changelog for 0.2.62.

### PR DESCRIPTION
**Pull request by tpoterba**
Assigned Dan in case he needs to add batch changes.

### CODE REVIEW

**Comment by danking** [comment]
@pwc2 can you PR a removal of the datasets today? If not, I'll do it

**Comment by danking** [comment]
I'll approve once https://github.com/hail-is/hail/pull/9985 merges.

**Comment by johnc1231** [comment]
Can we get #9986 into this one as well? Qi asking for some version updates for Terra folks

**Comment by tpoterba** [comment]
I want to get this out for Grace's team to run VEP. No reason we can't cut another release tomorrow.

**Comment by johnc1231** [comment]
Fine with me

**Review by danking — APPROVED** [review]

**Pull request merged**
