### PR TITLE
PTypes 16: Various "View" classes use ptypes

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by cseed** [comment]
Something in the diff is squirrelly, do you need a rebase?

**Comment by tpoterba** [comment]
there

**Comment by tpoterba** [comment]
(needs to wait for ptypes-15 to go in)

**Comment by tpoterba** [comment]
(and then will need another rebase)

**Comment by cseed** [comment]
15 went in.

**Comment by cseed** [comment]
This still has diffs from 15.  (And is failing.)

**Comment by tpoterba** [comment]
sorry, thought I'd fixed it

**Pull request merged**
