### PR TITLE
[vdc] update playbook for using deploy account

### PR DESCRIPTION
**Pull request by danking**
I verified this manually. The deploy account didn't exist when I started this PR, but it still had a role grant in the project's IAM policy. Now the account still does not exist *and* the role grant is gone.

The `login` forces you to switch to your account since we're deleting the service account (as which you're probably authenticated).

### CODE REVIEW

**Comment by danking** [comment]
bump

**Comment by cseed** [comment]
Can you refresh my memory on what this is about?  I basically thought everything in vdc/ was complete bitrot.  This is for deploying ... a new Hail Python package?

**Comment by danking** [comment]
The deploy service account was unnecessarily privileged and not actively used. AFAICT, it's used only by this make file to stand up a new hail vdc from scratch. I removed the deploy service account and modified this makefile to create it, use it, and then destroy it when finished.

If this is all bitrot, then I suppose it doesn't matter. I tested that these new and modified targets work as expected.

What did you use to set up Konrad's project?

**Comment by danking** [comment]
bump @cseed

**Pull request merged**
