### PR TITLE
Tensor types

### PR DESCRIPTION
**Pull request by danking**
cc: @cseed @jbloom22 @daniel-goldstein @patrick-schultz 

Here's some type rules for distributed tensor types and their operations.

I have some ideas for the python syntax as well, but they're not included here.

checking this in until we're done fleshing out seems OK since I'd like to think of this as a shared collaborative document?

### CODE REVIEW

**Comment by danking** [comment]
@hail-is/tensors fyi

**Comment by patrick-schultz** [comment]
Some initial thoughts:
* I'm not sure we should have implicitly broadcasting operations in the IR. It seems simpler to make broadcast an explicit operation, which we make sure to deforest. In fact, broadcast is a special case of the generic tensor index operation I'll describe below. Implicitly broadcasting operations could be provided in the Python interface, making broadcasts explicit when constructing the IR.
* I'm also not sure how much special treatment we should give to block matrices in the IR. I now like to think of block matrices as just 4-tensors, with matrix operations like matrix multiplication lowering to operations on 4-tensors. If we allow tensors to have some distributed dimensions and some "small" dimensions, then at least in the backend we might not need special handling of block structures. It may still be helpful to have a special block matrix/tensor representation at the top level IR, or maybe that should only live in Python—I'm not sure.

Here's a proposal for a set of primitive tensor operations.

* Outer product: Takes two tensors, T1 and T2, with shapes [n1, ..., ni] and [m1, ..., mj], and entry types t1 and t2, and makes a tensor Out with shape [n1, ..., ni, m1, ..., mj] and entry type (t1, t2). If we want to support sparse tensors, this should take a flag specifying how the sparse structure of the output is determined from those of the inputs. I'll call the possible flags "and", "or", and "true".

  The "and" flag says that Out(n, m) is defined iff T1(n) AND T2(m) are both defined. If we will be multiplying the pairs, or applying any other operation with our default missingness semantics, this is the appropriate setting.
  The "or" flag says Out(n, m) is defined iff T1(n) OR T2(m) is defined, as is appropriate if we are adding the pairs.
  "true" just means make Out dense, regardless of the sparsity of the inputs.

* Map. I don't think there's much to say here.

* Generic index operations (not sure what to call these). I'll first give some examples using informal notation, then I'll give a proposal for an IR representation. I'll say "sum" everywhere, but that could be any aggregation.

  Let T be a 1-tensor. O represents the output of the operation. Then
  * `T(i) -> O()` is the sum of T.
  * `T(i) -> O(i)` is identity.
  * `T(i) -> O(i, i)` makes a square matrix whose diagonal is T.
  * `T(i) -> O(i, j)` and `T(i) -> O(j, i)` broadcast T over a matrix in the two possible directions.

  Now let T be a 2-tensor.
  * `T(i, j) -> O(i)` is the vector of row-sums of T.
  * `T(i, i) -> O(i)` is the diagonal of T.
  * `T(i, j) -> O(j, i)` is transposition.

  How do we represent matrix multiplication? Let T1 and T2 be 2-tensors. Then letting `T = Out(T1, T2, "and").map((x, y) => x * y)`, the matrix product is given by
  * `T(i, j, j, k) -> O(i, k)`.

  In general, an index operation on T requires specifying an output tensor O (including its shape, though you can deduce that in non-broadcasting cases), a set of index variables (eg. "i, j, k"), and an assignment of a variable to each dimension of T and O. 

  More abstractly, let DT and DO be the sets of dimensions of T and O. An index operation consists of a set I and two functions DT -> I <- DO, a "cospan". These operations compose by cospan composition, which involves a pushout (a disjoint union and a quotient).

  Let i: DT -> I and o: DO -> I be the two maps assigning index variables. It helps to consider some special cases (compare to the examples above):
  * If i is surjective, and o is identity, this is extracting a diagonal from T.
  * If i is injective, and o is identity, this is a broadcast.
  * If i is identity, and o is surjective, this embeds T as a diagonal of a higher-dimensional output tensor.
  * If i is identity, and o is injective, this is a pure aggregation, summing out some dimensions of T.

  To make composition easy to compute, we could represent an index operation using a union-find structure for I. In other words, an index operation consists of a union-find structure I, and two arrays of points of I, encoding the two functions above. Then the composition of (T, I1, M) and (M, I2, O) is (T, I', O), where I' is computed by taking the union I1+I2, then for each dimension of M, unioning the assigned points of I1 and I2.

**Comment by cseed** [comment]
I think the current proposal is to have distributed and "small" dimensions, but the distributed dimensions specify their blocking (rather than just being marked "distributed" which I think is your proposal).  Blocks aren't heterogenous in our current setup (last block can be short) and I think that needs to be clarified in your proposal.  Slicing has similar complications.  I think the blocking should specify the list of sizes of each block, which makes it closed under slicing.

I agree the user interface should do implicit broadcast but in the IR it should be explicit.

 > If we want to support sparse tensors

I vote we punt on sparse vectors for the time being. (In the sparse case, I think sparsity of the output should be inferred by analysis rather than specified.  I think statically knowing the sparsity relationship is going to a rarity.)

The key point here is that Patrick's operations are incredibly general so this proposal needs to be paired with an compilation strategy that guarantees his operations are never actually realized directly (e.g. deforestation, fusing operations (e.g. broadcast) into their consumers) while also generating BLAS-level performance.  I propose we plan to build against BLAS while we investigate more general codegen strategies.  To that end, I've suggested we read up on a few related projects in study group: taco (hat tip Patrick), TensorComprehensions, TVM (tensor virtual machine) and Halide.  Might be other relevant ones (TF/XLA?)  Few questions to ask:
 - Can we steal good ideas for our IR?
 - Can we target their IR?
 - Can we integrate this with our stack?
 - What's the performance like (compile time, runtime)?

We'll need some more prosaic operators:
 - constructors: from array with shape, from shape and a function of indices
 - get shape.
 - index: get an element from a tuple of integers.  This is only allowed for local arrays.
 - slice: get another ndarray from a sequence of integers, ranges, or array of indices.
 - reshape.  Maybe local only?  Or clarified in the distributed case.

I think we'll need some additional basic operations supported by numpy (e.g. concatenate, tile), but this is a good start.

**Comment by danking** [comment]
Will open a dev post with updated thoughts when I get to updating my thoughts.

**Pull request closed without merging**
