### PR TITLE
[batch] fix image not exist on create container

### PR DESCRIPTION
**Pull request by jigold**
I think this is a race condition with another process trying to pull the same image after the current process has pulled the image. That would mostly be solved by a per user Docker cache, but I think this solution is still needed as you could have a race condition on the cache timeout boundaries.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/batch/worker.py", line 287, in run
    name=f'batch-{self.job.batch_id}-job-{self.job.job_id}-{self.name}')
  File "/usr/local/lib/python3.6/site-packages/batch/worker.py", line 91, in docker_call_retry
    return await f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/aiodocker/containers.py", line 48, in create
    url, method="POST", data=config, params=kwargs
  File "/usr/local/lib/python3.6/site-packages/aiodocker/docker.py", line 223, in _query_json
    path, method, params=params, data=data, headers=headers, timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/aiodocker/docker.py", line 291, in __aenter__
    resp = await self._coro
  File "/usr/local/lib/python3.6/site-packages/aiodocker/docker.py", line 206, in _do_query
    raise DockerError(response.status, json.loads(what.decode("utf8")))
aiodocker.exceptions.DockerError: DockerError(404, 'No such image: gcr.io/hail-vdc/ci-utils:e9pnvtf1078g')
```

### CODE REVIEW

**Comment by jigold** [comment]
It's not in pulling. It seems like it's actually in show based on the stack trace. I assumed it was in `create` because this appeared in the stack trace `name=f'batch-{self.job.batch_id}-job-{self.job.job_id}-{self.name}'` and that's the only place that's used. Let me look at the worker logs.

**Comment by jigold** [comment]
It was an old worker that didn't have the idempotent updates. The error was in create.

**Comment by jigold** [comment]
I checked the test failure should be fixed by #8131

**Comment by danking** [comment]
I still don't understand how the euro you posted above relates to the changes in this PR.

**Comment by jigold** [comment]
I added another delay if we can't get the image in container create expecting that eventually the image will exist once the second process has finished pulling it.

**Comment by jigold** [comment]
Closing this and making an issue until we understand why it's happening better.

**Pull request closed without merging**
