### PR TITLE
[query] eliminate optimization that can blow RAM

### LINKED ISSUE #13606: [query] gnomAD pipeline blows RAM if using split_multi
### What happened?

Here's a tail of the log showing the rapidly increasing RAM use.

I'm working on a simple replicable pipeline now. Does not depend on the use of `filter_changed_loci`.

```
2023-09-11 16:22:59.815 : INFO: RegionPool: REPORT_THRESHOLD: 1.0G allocated (662.3M blocks / 363.4M chunks), regions.size = 3, 0 current java objects, thread 24: Thread-3
2023-09-11 16:23:01.488 : INFO: executing D-Array [table_scan_prefix_sums_singlestage] with 1 tasks, contexts size = 430.00 B, globals size = 2.52 MiB
2023-09-11 16:23:01.540 : INFO: RegionPool: initialized for thread 115: Executor task launch worker for task 0.0 in stage 37.0 (TID 442)
2023-09-11 16:23:01.567 : INFO: RegionPool: REPORT_THRESHOLD: 2.2M allocated (64.0K blocks / 2.1M chunks), regions.size = 1, 0 current java objects, thread 115: Executor task launch worker for task 0.0 in stage 37.0 (TID 442)
2023-09-11 16:23:01.572 : INFO: RegionPool: REPORT_THRESHOLD: 4.2M allocated (64.0K blocks / 4.1M chunks), regions.size = 1, 0 current java objects, thread 115: Executor task launch worker for task 0.0 in stage 37.0 (TID 442)
2023-09-11 16:23:01.573 : INFO: RegionPool: REPORT_THRESHOLD: 4.3M allocated (64.0K blocks / 4.2M chunks), regions.size = 1, 0 current java objects, thread 115: Executor task launch worker for task 0.0 in stage 37.0 (TID 442)
2023-09-11 16:23:01.573 : INFO: RegionPool: REPORT_THRESHOLD: 4.3M allocated (128.0K blocks / 4.2M chunks), regions.size = 2, 0 current java objects, thread 115: Executor task launch worker for task 0.0 in stage 37.0 (TID 442)
2023-09-11 16:23:01.573 : INFO: RegionPool: REPORT_THRESHOLD: 12.3M allocated (192.0K blocks / 12.1M chunks), regions.size = 3, 0 current java objects, thread 115: Executor task launch worker for task 0.0 in stage 37.0 (TID 442)
2023-09-11 16:23:01.579 : INFO: RegionPool: REPORT_THRESHOLD: 12.4M allocated (192.0K blocks / 12.2M chunks), regions.size = 3, 0 current java objects, thread 115: Executor task launch worker for task 0.0 in stage 37.0 (TID 442)
2023-09-11 16:23:01.582 : INFO: RegionPool: REPORT_THRESHOLD: 35.3M allocated (768.0K blocks / 34.5M chunks), regions.size = 12, 0 current java objects, thread 115: Executor task launch worker for task 0.0 in stage 37.0 (TID 442)
2023-09-11 16:23:01.588 : INFO: RegionPool: REPORT_THRESHOLD: 57.7M allocated (768.0K blocks / 56.9M chunks), regions.size = 12, 0 current java objects, thread 115: Executor task launch worker for task 0.0 in stage 37.0 (TID 442)
2023-09-11 16:23:01.604 : INFO: RegionPool: REPORT_THRESHOLD: 74.5M allocated (768.0K blocks / 73.7M chunks), regions.size = 12, 0 current java objects, thread 115: Executor task launch worker for task 0.0 in stage 37.0 (TID 442)
2023-09-11 16:23:01.715 : INFO: RegionPool: REPORT_THRESHOLD: 139.5M allocated (1.0M blocks / 138.5M chunks), regions.size = 16, 0 current java objects, thread 115: Executor task launch worker for task 0.0 in stage 37.0 (TID 442)
2023-09-11 16:23:54.351 : INFO: RegionPool: REPORT_THRESHOLD: 264.3M allocated (1.7M blocks / 262.6M chunks), regions.size = 16, 0 current java objects, thread 115: Executor task launch worker for task 0.0 in stage 37.0 (TID 442)
2023-09-11 16:23:55.562 : INFO: RegionPool: REPORT_THRESHOLD: 513.1M allocated (2.3M blocks / 510.8M chunks), regions.size = 16, 0 current java objects, thread 115: Executor task launch worker for task 0.0 in stage 37.0 (TID 442)
2023-09-11 16:23:55.799 : INFO: RegionPool: REPORT_THRESHOLD: 1.0G allocated (3.1M blocks / 1.0G chunks), regions.size = 16, 0 current java objects, thread 115: Executor task launch worker for task 0.0 in stage 37.0 (TID 442)
2023-09-11 16:23:56.277 : INFO: RegionPool: REPORT_THRESHOLD: 2.0G allocated (4.4M blocks / 2.0G chunks), regions.size = 16, 0 current java objects, thread 115: Executor task launch worker for task 0.0 in stage 37.0 (TID 442)
2023-09-11 16:23:57.231 : INFO: RegionPool: REPORT_THRESHOLD: 4.0G allocated (7.3M blocks / 4.0G chunks), regions.size = 16, 0 current java objects, thread 115: Executor task launch worker for task 0.0 in stage 37.0 (TID 442)
2023-09-11 16:23:59.198 : INFO: RegionPool: REPORT_THRESHOLD: 8.0G allocated (12.9M blocks / 8.0G chunks), regions.size = 16, 0 current java objects, thread 115: Executor task launch worker for task 0.0 in stage 37.0 (TID 442)
2023-09-11 16:24:40.382 : INFO: RegionPool: REPORT_THRESHOLD: 16.0G allocated (4.6G blocks / 11.4G chunks), regions.size = 16, 0 current java objects, thread 115: Executor task launch worker for task 0.0 in stage 37.0 (TID 442)
2023-09-11 16:25:11.138 : INFO: RegionPool: REPORT_THRESHOLD: 32.0G allocated (9.2G blocks / 22.8G chunks), regions.size = 16, 0 current java objects, thread 115: Executor task launch worker for task 0.0 in stage 37.0 (TID 442)
```

### Version

0.2.120

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by danking**
CHANGELOG: On some pipelines, since at least 0.2.58 (commit 23813afd5b), Hail could use essentially unbounded amounts of memory. This change removes "optimization" rules that accidentally caused that.

Closes #13606

### CODE REVIEW

**Review by patrick-schultz — CHANGES_REQUESTED** [review]
These optimizations are too important to just disable. I think a better quickfix is to do
```
    case ToStream(ToArray(s), false) if s.typ.isInstanceOf[TStream] => s

    case ToStream(Let(name, value, ToArray(x)), false) if x.typ.isInstanceOf[TStream] =>
      Let(name, value, x)
```

The right fix is probably to add a `requiresMemoryManagementPerElement` flag to `StreamMap`---which could be generally useful when the producer didn't care about memory management, but the map body allocates a lot and wants to free after each row---and then use that to make these smarter:
```
    case ToStream(ToArray(s), false) if s.typ.isInstanceOf[TStream] => s
    case ToStream(ToArray(s), true) if s.typ.isInstanceOf[TStream] =>
      StreamMap(s, uid, Ref(uid), requiresMemoryManagementPerElement = true)

    case ToStream(Let(name, value, ToArray(x)), false) if x.typ.isInstanceOf[TStream] =>
      Let(name, value, x)
    case ToStream(Let(name, value, ToArray(x)), false) if x.typ.isInstanceOf[TStream] =>
      Let(name, value, StreamMap(x, uid, Ref(uid), requiresMemoryManagementPerElement = true))
```

And I still don't fully understand why these were deoptimizing the gnomad pipeline.

**Comment by danking** [comment]
FWIW, I finally found a simpler reproducer. It really takes some doing to convince the simplifier to apply this rule.

This operation should use a constant ~1GiB of RAM (in reality, in a non-broken pipeline it uses closer to 8GiB, but, still, a constant amount of RAM), but in reality memory use grows with each row processed

```python3
import hail as hl
ht = hl.utils.range_table(1)
ht = ht.key_by()
ht = ht.select(rows = hl.range(10))
ht = ht.explode('rows')
ht = ht.annotate(garbage=hl.range(1024 ** 3))
ht.write('/tmp/foo.ht', overwrite=True)
```
The simplifier cannot simplify the pipeline if the key is still present so this pipeline is sufficient to restore normal memory usage:
```python3
import hail as hl
ht = hl.utils.range_table(1)
ht = ht.select(rows = hl.range(10))
ht = ht.explode('rows')
ht = ht.annotate(garbage=hl.range(1024 ** 3))
ht.write('/tmp/foo.ht', overwrite=True)
```

The "bad" `WritePartition` body IR looks like this:
```
(StreamFlatMap __iruid_447
  (StreamRange -1 True
    (GetField start (Ref __iruid_446))
    (GetField end (Ref __iruid_446))
    (I32 1))
  (StreamMap __iruid_448
    (StreamRange 1 False (I32 0) (I32 10) (I32 1))
    (InsertFields
      (Literal Struct{} <literal value>)
      ("rows" "garbage")
      (rows (Ref __iruid_448))
      (garbage
        (ToArray
          (StreamRange 2 False
            (I32 0)
            (I32 1073741824)
            (I32 1)))))))
```
The "good" IR looks like this:
```
(StreamFlatMap __iruid_480
  (StreamRange -1 True
    (GetField start (Ref __iruid_479))
    (GetField end (Ref __iruid_479))
    (I32 1))
  (Let __iruid_481
    (MakeStruct
      (idx (Ref __iruid_480))
      (rows
        (ToArray
          (StreamRange 1 False (I32 0) (I32 10) (I32 1)))))
    (StreamMap __iruid_482
      (ToStream True (GetField rows (Ref __iruid_481)))
      (InsertFields
        (Ref __iruid_481)
        ("idx" "rows" "garbage")
        (rows (Ref __iruid_482))
        (garbage
          (ToArray
            (StreamRange 2 False
              (I32 0)
              (I32 1073741824)
              (I32 1))))))))
```

Notice, in particular, that the `StreamMap` inside the `StreamFlatMap` uses memory management because the originating `ToStream` uses memory management.

**Comment by danking** [comment]
Issue for StreamMap memory management: https://github.com/hail-is/hail/issues/13623

**Comment by danking** [comment]
@patrick-schultz bump for tomorrow

**Review by patrick-schultz — APPROVED** [review]
That's a very clear example, thanks!

**Pull request merged**
