### PR TITLE
[lint] reintroduces black for hail directory

### PR DESCRIPTION
**Pull request by iris-garden**
See https://github.com/hail-is/hail/pull/14120, which will add the resultant commit from this PR to `.git-blame-ignore-revs` once this PR is squashed and merged.

### CODE REVIEW

**Comment by daniel-goldstein** [comment]
Thanks @iris-garden I'm excited for everything to be consistently formatted. Before we merge, do you know if there are any large Query python PRs at the moment that would hit heavy merge conflicts with this change?

**Comment by iris-garden** [comment]
ooo good point; i think if anyone has merge conflicts after this goes into `main`, they should be able to do

```bash
git checkout main -- Makefile pyproject.toml
black hail/
git add .
git commit -m "linted with black"
```

i also changed these files manually because `black` moved the `noqa`s for a couple imports around such that the other checks weren't passing:
* `hail/python/hail/__init__.py`
* `hail/python/hail/ggplot/__init__.py`
* `hail/python/hailtop/hailctl/batch/submit.py`
* `hail/python/hailtop/hailctl/batch/initialize.py`
* `hail/python/hailtop/hailctl/dev/cli.py`

so as long as no one is messing with the imports in those files, i believe the above should take care of any conflicts

but i'm posting on zulip to see if anyone has a branch they can try that out with and then diff against this branch and let us know if it's too arduous for a big changeset

**Comment by iris-garden** [comment]
alright, i tried this out on my fork with jackie's changeset from https://github.com/hail-is/hail/pull/14018, and there were 14 [conflicts](https://github.com/iris-garden/hail/pull/1/conflicts) across three files, and as far as i can tell all of those should be easily resolvable by just taking everything from the PR branch, rather than the linting branch

**Comment by iris-garden** [comment]
per the rest of the team on [zulip](https://hail.zulipchat.com/#narrow/stream/127527-team/topic/linting/near/411070692), people either don't have big python changes in flight, or are okay with resolving the merge conflicts left over after running the steps from my other comment!

**Review by daniel-goldstein — APPROVED** [review]
Awesome, thank you for doing this!

**Pull request merged**
