### PR TITLE
flatten py in lmm

### PR DESCRIPTION
**Pull request by jbloom22**

### CODE REVIEW

**Comment by tpoterba** [comment]
what does this do?

**Comment by jbloom22** [comment]
changes (n, 1) vector to (n) array

**Comment by tpoterba** [comment]
does it fix a bug? can we test it?

**Comment by jbloom22** [comment]
Yes, it fixes a bug that resulted in a failed check on the dimension of y. I've added a regression test.

http://discuss.hail.is/t/breaking-change-hail-0-2-removed-kinshipmatrix-linear-mixed-regression/578/16

**Pull request merged**
