### PR TITLE
[hail] diagnose.sh

### PR DESCRIPTION
**Pull request by danking**
@cseed @tpoterba thoughts?

Once this is merged, we can just tell people to run

```bash
curl -LO https://raw.githubusercontent.com/hail-is/hail/master/hail/diagnose.sh | bash
```

and send us the output. We can include all sorts of useful diagnostics here. 

I only upload the log and core files to a pastebin if you pass an argument to the script a la:

```bash
curl -LO https://raw.githubusercontent.com/hail-is/hail/master/hail/diagnose.sh | bash -s foo
```

### CODE REVIEW

**Comment by tpoterba** [comment]
can we make this an executable in the PyPI package? then you can just run `diagnose_hail`

**Comment by tpoterba** [comment]
the script may be clearer and easier to extend if written in python, too.

**Comment by tpoterba** [comment]
I :heart: the concept

**Comment by danking** [comment]
I can move some of it over to a python diagnose, but I'm also targeting the "I installed hail, but import hail fails".

**Comment by danking** [comment]
@tpoterba I added `hl.debug_info()` which is maybe helpful?

I guess we're really talking about something that sanity checks the environment but assuming we already have hail pip-installed. What would you want to do? I guess we could check some spark stuff, try to create a context, if that fails tell the user its a spark problem? We could just do that in init though.

**Comment by tpoterba** [comment]
er, this is totally fine. Though I think we should also have a `hl.diagnose` function which tries to poke around at spark/native libs/etc. There's a separate issue for this.

**Pull request merged**
