### PR TITLE
Revert "[batch]memory cpu plot"

### PR DESCRIPTION
**Pull request by jigold**
There's some issues that need to be fixed when @CDiaz96 comes back from vacation... The units on the plot are wrong and we're not handling missing data well.

Reverts hail-is/hail#11652

### CODE REVIEW

**Comment by jigold** [comment]
Screen Shot 2022-03-28 at 12 02 10 AM
Screen Shot 2022-03-28 at 12 07 14 AM

**Comment by jigold** [comment]
I'm also skeptical that we're getting any actual data so we'd need to check the resource usage code as well.

**Review by daniel-goldstein — APPROVED** [review]

**Comment by danking** [comment]
We’re definitely getting data though the displayed units are swapped between cpu and men: https://batch.hail.is/batches/1382976/jobs/65

**Comment by danking** [comment]
I think you can get weird plots when there’s only one data point. We should probably hide the plots if there’s fewer than 12 points (I think that’s one minute at our sampling rate)

**Pull request merged**
