### PR TITLE
[notebook2] multiple notebooks

### PR DESCRIPTION
**Pull request by akotlar**
stacks on #5540. Will re-assign when notebook2-no-svc is merged.

This is needed because, unwittingly due to networking issues, or just having 2 open sessions, two notebooks could be created. If so, this would trigger the assert len(notebooks) == 1 and prevent the user from using the service again.

Adresses: https://github.com/hail-is/hail/issues/5487

Relevant commits:
https://github.com/hail-is/hail/pull/5549/commits/901b1e16daeda9209424319ebbeea2b451862876

Once that goes in, a few small changes to notebook.py to store multiple notebooks in a session (and pass the notebooks array to templates), and then loop over the array in notebook-state.html (which retains all of the same per-notebook ui). 

I also removed the explicit reachability check on refresh for {% if ready %}. I believe when you .watch(list_namespaced_pods), the first request gets up-to-date status, so no real need to separately check reachability on refresh (we could back port this to #5540 if needed)

screen shot 2019-03-06 at 3 58 32 pm

cc @cseed

### CODE REVIEW

**Comment by danking** [comment]
@akotlar if you use one of these keywords the issue is auto-closed https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by danking** [comment]
Also, I think you meant #5487

**Comment by akotlar** [comment]
> Also, I think you meant #5487

Yeah, copy paste fail, thanks

**Comment by akotlar** [comment]
> @akotlar if you use one of these keywords the issue is auto-closed https://help.github.com/en/articles/closing-issues-using-keywords

Thanks, I didn't want to close the issue until this was merged. Is that not appropriate?

**Comment by danking** [comment]
That GitHub feature only closes the referenced issues when the referencing PR is merged

**Comment by akotlar** [comment]
> That GitHub feature only closes the referenced issues when the referencing PR is merged

cool, thanks

**Pull request closed without merging**
