### PR TITLE
[query] no SRVB in NDArraySVD or NDArrayQR

### PR DESCRIPTION
**Pull request by patrick-schultz**

### CODE REVIEW

**Review by tpoterba — APPROVED** [review]

**Comment by tpoterba** [comment]
great! 

hold off on other ndarray emitter rules until #9960 goes in? I think I may have done one or two as a driveby.

**Comment by patrick-schultz** [comment]
No problem. Sorry, just searched for StagedRegionValueBuilder in Emit.scala and started with the first hit.

**Comment by tpoterba** [comment]
No problem! This is all great!

**Comment by tpoterba** [comment]
The failure was a test_query one, I kicked it.

**Comment by patrick-schultz** [comment]
Yeah, I've kicked it a couple times already. Not sure what's going on.

**Pull request merged**
