### PR TITLE
Change min_block_size default value

### PR DESCRIPTION
**Pull request by tpoterba**
Do you remember if there's a reason it's 1? I don't want Big Brother telling me how many blocks to use, and I doubt our users do either!

### CODE REVIEW

**Comment by danking** [comment]
I think this could interact badly with Spark's partitioning logic. That would appear in the text file imports.

We should probably rewrite the text file stuff the same way we rewrote import_bgen to use our own, sensible, partitioning logic.

I guess the worst thing that happens is a small text file is broken into one partition per-line.

**Comment by tpoterba** [comment]
even with min size at 0, the default behavior in import_table (min_partitions=None) will use the default split size.

But it's impossible to get partitions smaller than the min_block_size, which is very annoying

**Comment by tpoterba** [comment]
> I guess the worst thing that happens is a small text file is broken into one partition per-line.

Yeah, this doesn't seem so bad

**Comment by konradjk** [comment]
FWIW I basically do this all the time anyway, without any major adverse issues yet...

**Pull request merged**
