### PR TITLE
Expose 'array_elements_required' in 'import_vcf'

### LINKED ISSUE #3341: expose format field array_required flag in import_vcf
It exists on LoadVCF in Scala, but isn't exposed in Python.

### PR DESCRIPTION
**Pull request by jigold**
Fixes #3341

### CODE REVIEW

**Comment by jigold** [comment]
I borrowed the MissingArrayBuilder from #3458. I tried to unify this with ArrayBuilder with inheritance / trait, but was having trouble doing so.

**Comment by jigold** [comment]
Good catch. 

my branch: 1 loop, best of 3: 1min 58s per loop
master: 1 loop, best of 3: 2min 6s per loop

**Comment by tpoterba** [comment]
nice job Jackie!

**Comment by jkeebler** [comment]
Thank you Jackie!!

**Pull request merged**
