### PR TITLE
Fix bug preventing write if `va == NA`

### PR DESCRIPTION
**Pull request by tpoterba**
Add random generation of missingness to Type.genValue

### CODE REVIEW

**Comment by danking** [comment]
This seems like an odd bug?
https://ci.hail.is/repository/download/HailSourceCode_HailMainline_HailCiSpark1/2980:id/build/reports/tests/classes/org.broadinstitute.hail.io.ExportVcfSuite.html#testReadWrite

**Comment by tpoterba** [comment]
It's incredibly strange and infuriating.  Somehow a written VCF file becomes empty before it's reread.  It's not tied to a certain VDS, because when I skip directly to the problem which occurs on the 8th VDS generated with seed 1 (don't read/write the first 7) it reads/writes just fine.

**Comment by danking** [comment]
Woah.

**Comment by danking** [comment]
@tpoterba Is this fixed by your revolution this morning?

**Comment by tpoterba** [comment]
Yes, once the Map branch goes in, this should work (With a rebase)

**Comment by danking** [comment]
I did a rebase for you. Doesn't seem fixed. :(

**Comment by tpoterba** [comment]
The TDict -> TMap change has to go in first.  If that doesn't go in in the next day or so, I'll pull out the change and submit it separately.

**Pull request merged**
