### PR TITLE
bgen add n_partitions and block_size, remove min_partitions.

### PR DESCRIPTION
**Pull request by cseed**
Fixed problem where number of partitions was 2 by default (?!).  chr1
now imports as 293 partitions, as expected.

Don't use any Hadoop settings.  That's all madness.

Also, spread n_partitions across multiple files correctly.

### CODE REVIEW

**Comment by danking** [comment]
@cseed approved, though I don't see the change to compile once per partition.

**Comment by cseed** [comment]
Oops, I forgot to push it.  I'll include the change in the next MatrixBGENReader PR.

**Comment by jigold** [comment]
@cseed Still running the pipeline, but can confirm I got 293 partitions for chr22 and the import step took about 1 minute.

```
2018-07-18 15:39:30 Hail: INFO: Number of BGEN files parsed: 1
2018-07-18 15:39:30 Hail: INFO: Number of samples in BGEN files: 487409
2018-07-18 15:39:30 Hail: INFO: Number of variants across all BGEN files: 1255683
2018-07-18 15:40:37 Hail: INFO: Coerced almost-sorted dataset
2018-07-18 15:40:39 Hail: INFO: interval filter loaded 5 of 293 partitions
```

**Comment by cseed** [comment]
Great, thanks Jackie!  Do you remember about how long the import step took for 0.1?

Second, you're running many linear regressions, right?  If those still fail (or run much slower than 0.1), can you also try just a single linear regression?  That's a simpler baseline to start with.

**Comment by jigold** [comment]
Looks like slightly slower in 0.1
```
2018-06-26 01:47:57 Hail: INFO: Number of BGEN files parsed: 1
2018-06-26 01:47:57 Hail: INFO: Number of samples in BGEN files: 487409
2018-06-26 01:47:57 Hail: INFO: Number of variants across all BGEN files: 1255683
2018-06-26 01:49:08 Hail: INFO: Coerced almost-sorted dataset
2018-06-26 01:49:08 Hail: INFO: No multiallelics detected.
2018-06-26 01:49:09 Hail: INFO: interval filter loaded 27 of 586 partitions
```

I'll kill what I have and run a single regression, since this will take a long time.
```
2018-07-18 15:39:30 Hail: INFO: Number of BGEN files parsed: 1
2018-07-18 15:39:30 Hail: INFO: Number of samples in BGEN files: 487409
2018-07-18 15:39:30 Hail: INFO: Number of variants across all BGEN files: 1255683
2018-07-18 15:40:37 Hail: INFO: Coerced almost-sorted dataset
2018-07-18 15:40:39 Hail: INFO: interval filter loaded 5 of 293 partitions
2018-07-18 15:43:13 Hail: WARN: 126215 of 487409 samples have a missing phenotype or covariate.
2018-07-18 15:43:13 Hail: INFO: linear_regression: running on 361194 samples for 110 response variables y,
    with input variable x, intercept, and 25 additional covariates...
2018-07-18 15:44:06 Hail: WARN: 132571 of 487409 samples have a missing phenotype or covariate.
2018-07-18 15:44:06 Hail: INFO: linear_regression: running on 354838 samples for 1 response variable y,
    with input variable x, intercept, and 25 additional covariates...
2018-07-18 15:44:59 Hail: WARN: 132781 of 487409 samples have a missing phenotype or covariate.
2018-07-18 15:44:59 Hail: INFO: linear_regression: running on 354628 samples for 1 response variable y,
    with input variable x, intercept, and 25 additional covariates...
2018-07-18 15:45:42 Hail: WARN: 133165 of 487409 samples have a missing phenotype or covariate.
2018-07-18 15:45:42 Hail: INFO: linear_regression: running on 354244 samples for 1 response variable y,
    with input variable x, intercept, and 25 additional covariates...
2018-07-18 15:46:57 Hail: WARN: 132601 of 487409 samples have a missing phenotype or covariate.
2018-07-18 15:46:57 Hail: INFO: linear_regression: running on 354808 samples for 1 response variable y,
    with input variable x, intercept, and 25 additional covariates...
```

Also, the default parallelism in 0.1 was better for the same interval: 27 partitions to 5 partitions.

**Comment by jigold** [comment]
Let's move this conversation to email or zulip.

**Pull request merged**
