### PR TITLE
[devbin] Local UI development proxy server

### LINKED ISSUE #13629: [batch] Batch should support a fast local UI development mode
### What happened?

In particular, edits to HTML, CSS, SASS, and JavaScript should update the UI in real-time. This development-mode UI should support fetching data from either from a live backend (in any namespace) or should have an easy way for the developer to intercede (by programing) and return mock data.

### Version

0.2.122

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by daniel-goldstein**
This adds a script that runs an `aiohttp` server on localhost that by default proxies all requests to whatever batch namespace `hailctl` is pointed to but serves static assets and renders all HTML locally. This allows for local editing of HTML / CSS / SCSS files.

To run, this branch needs to be deployed in the relevant namespace (to pick up the changes to `web_common.py`), and you need to have the `sass` CLI installed (`brew install sass/sass/sass`). Then run in a separate terminal `make devserver SERVICE=batch` and open up `localhost:8000`. If you want to supply fake data instead of proxying an endpoint to the k8s deployment of the service, you can override that endpoint in `dev_proxy.py`.

If this looks good, I'll add the above instructions to the dev docs.

Resolves #13629

### CODE REVIEW

**Comment by daniel-goldstein** [comment]
@iris-garden bump

**Comment by daniel-goldstein** [comment]
@iris-garden bump. It's a bit tedious to keep resolving the requirements conflicts

**Comment by danking** [comment]
WIP until I get things merged

**Comment by iris-garden** [comment]
@daniel-goldstein sorry for the slow review turnaround! the code looks good to me, and i'll try it out tomorrow morning to make sure i don't have any additional feedback. thanks!

**Comment by iris-garden** [comment]
to be included in the dev docs:

the devserver uses the `default_namespace` configured via `hailctl dev config`, so make sure to change that to your dev namespace or the default namespace as desired

**Pull request merged**
