### PR TITLE
Typecheck VDS methods

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by tpoterba** [comment]
This exposed a problem with typecheck - you can't check arguments that need to be the class you're defining, like `concordance` or `join`. 

I marked these as `anytype` for now. I will ruminate on this.

**Comment by cseed** [comment]
Yes!  Same problem we had trying to typecheck the self object.  Here's an idea: `@typecheck_method(..., other=selftype, ...)` and it verifies the type of `other` is the same as the type of `args[0]`.

**Comment by tpoterba** [comment]
I had exactly the same idea, but it causes problems with inheritance.

**Comment by tpoterba** [comment]
Let's merge this so people don't get horrible error messages for now. I'll make an issue to make typecheck more powerful.

**Comment by cseed** [comment]
Agreed.

You can walk up from self to find the definition of f.__name__ that corresponds to this call, but that doesn't work because the user might have explicitly call the definition of a function on a parent class.

```
class A(object):
  def f(self):
    return 5
class B(A):
  def f(self):
    return 7

A.f(self)
```

**Pull request merged**
