### PR TITLE
[query] Improve code generation of If/Coalesce

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by tpoterba** [comment]
https://gist.github.com/tpoterba/203a24cad9082bfe82e6119bae574f43

**Comment by tpoterba** [comment]
```
linear_regression_rows_nd      15.7%    386.143     60.770
```

**Comment by johnc1231** [comment]
So this made a big difference across the board. This is why we need benchmarks nightly, would have caught this.

**Review by johnc1231 — APPROVED** [review]

**Comment by tpoterba** [comment]
yep, absolutely.

**Pull request merged**
