### PR TITLE
[ci] Build skopeo from source

### PR DESCRIPTION
**Pull request by daniel-goldstein**

### CODE REVIEW

**Review by danking — APPROVED** [review]

**Comment by lgruen** [comment]
`skopeo` is part of the standard Ubuntu 2**2**.04 repo, but probably that's a bit more difficult to update to? Building Hail on 22.04 seems to work fine though.

**Comment by daniel-goldstein** [comment]
Ya this would be more ideal, but since 22.04 is so new I anticipate there might be a couple of bumps. For example, I think GCP's logging agent we've been using for years might not be supported on the newer Ubuntu, since the agent is now considered legacy.

**Comment by daniel-goldstein** [comment]
The Red Hat folks appear to have restored the package, so we could remove this workaround. However, they're not going to maintain it so we will either have to build from source or ultimately upgrade.

**Comment by danking** [comment]
Do we have a logging agent installed inside the containers themselves? I'd have thought that was on the worker VM. Seems like we could go to 22.04 in all the containers. It does mean our worker VM is out of sync with the containers.

**Comment by daniel-goldstein** [comment]
Ah ya that's a good point, we could indeed move forward for the containers.

**Pull request merged**
