### PR TITLE
[batch] Add warnings for non-gcr images

### PR DESCRIPTION
**Pull request by jigold**
I'm not sure why we had the default be ubuntu:latest but I think 18.04 is better.

### CODE REVIEW

**Comment by konradjk** [comment]
When does this get triggered?

**Comment by jigold** [comment]
Not sure I understand what you mean. When the image name doesn't start with gcr.io in the backend code for the service. You can't check it until you call b.run()

**Comment by konradjk** [comment]
Yeah I meant what point in the pipeline. One could check on `j.image` (or `hb.Batch(..., default_image=...)`), but maybe `b.run` is best - is it only triggered once per batch, or once per offending job, or once per offending unique image?

**Comment by jigold** [comment]
It should be triggered once per offending unique image. I ran the same job three times each for ubuntu:18.04 and ubuntu:16.04 for a total of 6 jobs.

```
wmecc-475:hail jigold$ python3 batch/test_image_warnings.py
/Users/jigold/hail/hail/python/hailtop/batch/backend.py:478: UserWarning: Using an image ubuntu:18.04 not in GCR. Jobs may fail due to Docker Hub rate limits.
  UserWarning)
/Users/jigold/hail/hail/python/hailtop/batch/backend.py:478: UserWarning: Using an image ubuntu:16.04 not in GCR. Jobs may fail due to Docker Hub rate limits.
  UserWarning)
```

**Review by konradjk — APPROVED** [review]

**Pull request merged**
