### PR TITLE
[notebook/workshop] add resource link

### PR DESCRIPTION
**Pull request by akotlar**
2 files because #7273 hasn't gone in yet.

### CODE REVIEW

**Comment by cseed** [comment]
This builds on another PR, can you mark label it stacked?  Then, when the other PR goes in and you rebase, remove the label.  Thanks!

**Comment by tpoterba** [comment]
the stacked label prevents merging of approved PRs, to wait for the parent PR.

**Comment by akotlar** [comment]
> the stacked label prevents merging of approved PRs, to wait for the parent PR.

interesting

**Comment by akotlar** [comment]
would the stack label of a child block merge of an approved parent though?

**Comment by tpoterba** [comment]
nope!

**Comment by cseed** [comment]
Also, I think except in trivial cases (e.g. the child is 1 commit, and the parent is stable), it can be hard to review a child PR and the tag is a signal to the reviewer to hold off until it is really ready.

**Comment by akotlar** [comment]
> Also, I think except in trivial cases (e.g. the child is 1 commit, and the parent is stable), it can be hard to review a child PR and the tag is a signal to the reviewer to hold off until it is really ready.

This was pretty trivial, except I made the mistake of trying to reuse a branch (the remote was already deleted after merge) which meant it looked like 25 commits :(

**Pull request merged**
