### PR TITLE
[query/service] switch all skipped tests to fails tests

### PR DESCRIPTION
**Pull request by danking**

### CODE REVIEW

**Comment by johnc1231** [comment]
Seems like you have one syntax error still.

**Comment by danking** [comment]
OK, this passes all the tests except for `test_vcf_parser_golden_master__gvcf_GRCh37` which inexplicably hangs.

I've marked that as skip.

I've attached the WIP tag because the longest tests now take 47 minutes. I'll leave this PR up as a canary for when a `main` change fails service tests. However, I won't merge it until we improve test latency.

cc: @tpoterba

**Comment by danking** [comment]
This is not substantially slower than the current service backend tests.

**Comment by danking** [comment]
Bump. I am ready to merge this.

**Comment by danking** [comment]
bump!

**Comment by tpoterba** [comment]
I looked at this a few days ago and thought it was still a draft. Sorry! Looking now.

**Comment by danking** [comment]
no worries, thanks!

**Pull request merged**
