### PR TITLE
[batch/ui] adds "always run" to job and batch UIs

### PR DESCRIPTION
**Pull request by iris-garden**
Closes https://github.com/hail-is/hail/issues/14210.

Shows whether a Job is "Always Run" on the Batch page:

Screenshot 2024-03-28 at 14 10 04

and on the Job page:

Screenshot 2024-03-28 at 14 10 11

### CODE REVIEW

**Comment by ehigham** [comment]
Looks good! One thing that comes to mind is why not just an "Always Run" attribute that's existance dictates whether or not a job is always run?

**Comment by iris-garden** [comment]
@ehigham the only reason i represented it this way is because that's how it is in the database, like we have job attributes and then we have the always run flag for a job separately from those, but on the frontend i don't think there would be a problem with representing it as an attribute. i could change the new table column on the Batch page to be Attributes and put "Always Run" in there only for jobs that are always run, and i could also move "Always Run" to the Attributes header on the Job page, instead of the Properties header. happy to make either or both changes, just lmk!

**Comment by ehigham** [comment]
> @ehigham the only reason i represented it this way is because that's how it is in the database, like we have job attributes and then we have the always run flag for a job separately from those, but on the frontend i don't think there would be a problem with representing it as an attribute. i could change the new table column on the Batch page to be Attributes and put "Always Run" in there only for jobs that are always run, and i could also move "Always Run" to be under the Attributes header on the Job page, instead of the Properties header. happy to make either or both changes, just lmk!

That sounds not too dissimilar to how google adds 'labels' to tabular data. Personally I prefer that style, especially as more information gets added and tables get wider.
That said, I don't know how much extra data we'd want to add to this UI so that route may be slightly crystal-balling! Let's keep it simple for now as you've done already and consider something like that in the future if we have more data to add.

**Review by ehigham — APPROVED** [review]

**Comment by daniel-goldstein** [comment]
Popping in here with some context/suggestion but please take it or leave it! Very very few jobs in practice are AlwaysRun, and this ticket originated because of confusion that a cancelled batch still had `Ready` jobs. In a way you can consider AlwaysRun a modifier that affects the job's state machine. Maybe for the page with the jobs table, instead of just exposing the data we could tackle this particular confusion by making the state column for AlwaysRun jobs that are not in completed states (success / failed / error) like `Ready (always run)`?

**Comment by iris-garden** [comment]
@ehigham @daniel-goldstein replaced the always run column on the batch page with an indication in parentheses of when a job is always run. here's what it looks like when an always run job is in a non-completed state:

Screenshot 2024-04-04 at 10 35 22

and here's what it looks like when it's in a completed state:

Screenshot 2024-04-04 at 10 35 29

i didn't change the job page from what it was during the first review. lmk if that looks good to y'all!

**Review by ehigham — APPROVED** [review]
Looks great!

**Pull request merged**
