### PR TITLE
[test-dataproc] use regional buckets instead of soon-to-be-deleted multi-regional buckets

### PR DESCRIPTION
**Pull request by danking**
Part of https://github.com/hail-is/hail/issues/13507

### CODE REVIEW

**Review by ehigham — APPROVED** [review]

**Comment by danking** [comment]
a dev deploy of test-dataproc https://ci.hail.is/batches/8123862

**Comment by danking** [comment]
New dev deploy after switching from `gs://b` to `b` because that's apparently the format dataproc wants. https://ci.hail.is/batches/8125093

**Comment by danking** [comment]
Permissions issues discovered, trying again:
https://ci.hail.is/batches/8126244

**Comment by danking** [comment]
Another missing permission discovered. Trying again:
https://ci.hail.is/batches/8126260

**Comment by danking** [comment]
Still fighting permissions issues:
https://ci.hail.is/batches/8126264

**Comment by danking** [comment]
🤦 
https://ci.hail.is/batches/8126288

**Comment by danking** [comment]
Some day I'll get this to work.
https://ci.hail.is/batches/8126596

**Comment by danking** [comment]
I added hail-1kg to the requester pays buckets. I'm pretty sure that used to be a private non-requester-pays bucket. Now it's a public requester-pays bucket.

https://ci.hail.is/batches/8126620

**Comment by danking** [comment]
OKAY! It passes.

**Pull request merged**
