### PR TITLE
[ci] Fix excluded steps

### PR DESCRIPTION
**Pull request by jigold**

### CODE REVIEW

**Comment by daniel-goldstein** [comment]
Is this broken for you on the newest version of main? I encountered this and found that my `hailctl` was old and wasn't pushing an empty list for the excluded steps. Not sure if that's the best design instead of accepting optional arguments.

**Comment by daniel-goldstein** [comment]
I guess that makes this change backwards incompatible, so for that reason we can make this optional

**Comment by jigold** [comment]
bump?

**Comment by daniel-goldstein** [comment]
Closing because this is due to not picking up changes in local hailctl.

**Pull request closed without merging**
