### PR TITLE
[hailctl] Spark monitor

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by johnc1231** [comment]
I checked out your branch, ran `make install-hailctl`, started a cluster, connected to a notebook, and ran `hl.utils.range_table(1_000_000, 10000)._force_count()`. Did not see any monitor UI show up.

**Comment by johnc1231** [comment]
Though running: `pprint(dict(os.environ.items()))`, yielded:

```
{'CLICOLOR': '1',
 'GIT_PAGER': 'cat',
 'HOME': '/root',
 'INVOCATION_ID': '0faec80a970f4cf29ce69112519fe641',
 'JOURNAL_STREAM': '8:38888',
 'JPY_PARENT_PID': '5858',
 'LANG': 'en_US.UTF-8',
 'LOGNAME': 'root',
 'MPLBACKEND': 'module://ipykernel.pylab.backend_inline',
 'PAGER': 'cat',
 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
 'SHELL': '/bin/sh',
 'SPARKMONITOR_KERNEL_PORT': '38853',
 'TERM': 'xterm-color',
 'USER': 'root'}
```

**Comment by tpoterba** [comment]
huh. I just tested again and it worked!

**Comment by johnc1231** [comment]
I'll try again tomorrow, maybe I made a mistake.

**Comment by tpoterba** [comment]
bad news, though -- after playing with the thing a bit longer and trying to bump the partition number up, it's really not reliable. At all.

**Comment by tpoterba** [comment]
I think we should probably go back to jupyter spark.

**Comment by danking** [comment]
:((((((((((((

**Comment by tpoterba** [comment]
aha it gets a push for every task end! Running even a 5000-partition short job is a denial of service attack against the extension

**Comment by tpoterba** [comment]
after running one 5000-partition job, the extension log is 5k lines

**Comment by tpoterba** [comment]
OK, give this a try, John. I fixed the Spark UI linking issue, and added some other QoL features.

**Comment by tpoterba** [comment]
The changes to the fork are in a PR here: https://github.com/hail-is/sparkmonitor/pull/1/files

This PR points to an artifact built from that PR.

**Comment by tpoterba** [comment]
@johnc1231 fixed the problem, ready to go.

**Pull request merged**
