### PR TITLE
[cxx] Cease development of current C++ backend.

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by tpoterba** [comment]
This cuts really deep.

**Comment by tpoterba** [comment]
This cuts really deep.

**Comment by johnc1231** [comment]
Maybe just comment out the ndarray tests? I'm going to use them in near future

**Comment by tpoterba** [comment]
the scala one? just add it back from here:
https://github.com/hail-is/hail/pull/7002/commits/09730647aa8e68157e0fa2e33fdd8f184d30d764

The Python ones are turned off without removing the code.

**Comment by johnc1231** [comment]
The python ones. I didn't actually read the diff because I was on my phone, just saw "remove ndarraywrite tesr" commit message. Thanks

**Comment by cseed** [comment]
Really need a :sad_trombone: emoji

**Pull request merged**
