### PR TITLE
[hail] Add EType serializer/deserializer and tests

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by chrisvittal** [comment]
There's a part of me that's uncertain if this is the best course of action for Serialization/Deserialization of types in general. Now would be about the time to change it. Would it be so bad to just write the types as JSON? I know there's an issue surrounding the field indices for structs/tuples that we'd need to resolve but ETypes should never need to go across the Java/Python boundary and so we shouldn't need a text representation that needs to be in the IR.

**Comment by tpoterba** [comment]
I generally think that automatic case class deserialization was a mistake. Writing our own serialization/deserialization format gives us much more flexibility. I think this design will probably support development for quite some time.

**Comment by tpoterba** [comment]
There's also nothing stopping us from embedding json strings in here in the future.

**Comment by tpoterba** [comment]
`EJSON(\"json here\")`

**Comment by chrisvittal** [comment]
I think I may believe the opposite here. I don't think that automatic case class (de)serialization was a mistake. I think it correct, and that lack of flexibility here is a _good_ thing which forces us to carefully consider what gets written to permanent storage, and thus what we need to support forever.

**Comment by tpoterba** [comment]
> I think I may believe the opposite here. I don't think that automatic case class (de)serialization was a mistake. I think it correct, and that lack of flexibility here is a good thing which forces us to carefully consider what gets written to permanent storage, and thus what we need to support forever.

the thing I don't like is the extra Scala type baggage that comes along with JSON serialization -- if, for instance, we want to change the type signature of `RVDType` to add a field (or something), then even if there's a natural way to add a default for value for that field, the serialization will likely break.

The way things are written here, the data on disk (strings) are handled explicitly by code that we can change whenever we want. Two examples of things that are trivial in this model but hard with JSON case class serialization:
 - Renaming an EType subclass.
 - Introducint EOptional instead of `required` being a class field.

**Comment by tpoterba** [comment]
I think my argument centers around this piece:

> carefully consider what gets written to permanent storage

I absolutely agree that we must do this, but feel that JSON abstracts away what actually gets written to disk in a way that makes it harder to reason about changing the system.

**Comment by tpoterba** [comment]
Shall we find a time tomorrow to walk through the stacked PR together? I think that would probably be easiest for both of us.

**Pull request merged**
