### PR TITLE
Release 0.2.34

### PR DESCRIPTION
**Pull request by johnc1231**
I listed everything I'm aware of, though it's possible that some internal changes may have made performance impacts I don't know about.

### CODE REVIEW

**Comment by johnc1231** [comment]
Adding the WIP label to prevent merging until Tim has given the ok on benchmarks

**Comment by tpoterba** [comment]
https://gist.github.com/tpoterba/7bded33d0e3f0b4591d07187b245c71d

**Comment by johnc1231** [comment]
Why did `split_multi` get so much worse?

**Comment by tpoterba** [comment]
that's almost certainly within the (considerable) measurement noise. I'll run that benchmark locally to make sure.

**Pull request merged**
