### PR TITLE
Notebook2: add libsass to docker image

### PR DESCRIPTION
**Pull request by akotlar**
Dependency was only added to environment.yml, causing the container to fail to run. Would be nice if we could specify in one place.

### CODE REVIEW

**Comment by akotlar** [comment]
> Is this something where you need to add a new docker image to the gcr registry with the package installed? I think for pipeline I had to add new lines to `Dockerfile.pr-builder` and then run `make hail-ci-build-image` and `make push-hail-ci-build-image`.

This is just a replacement for notebook, and yeah, basically what you described. This PR adds a dependency (lib sass, corresponding to the `import sass` line in notebook/notebook.py), which will fix the crashloopbackoff currently seen on our cluster (a PR was merged but this was missed).

**Comment by jigold** [comment]
So you already created a new docker image?

**Comment by akotlar** [comment]
I believe it should be made by ci

**Comment by akotlar** [comment]
Specifically : https://github.com/akotlar/hail/blob/3b639cf77e2ad44c3422b619a36cf33523032953/notebook2/hail-ci-deploy.sh

**Comment by danking** [comment]
@jigold Notebook has no tests, so it doesn't have an environment.yml that needs to be updated in the hail-ci-build-image. This configuration is only for the run-time service.

**Pull request merged**
