### PR TITLE
[batch] Add type annotations for hailtop version of batch

### PR DESCRIPTION
**Pull request by jigold**

### CODE REVIEW

**Comment by danking** [comment]
It looks like pylint/flake8 don't like the import structure. I say we just import them! I don't think it affects performance in any meaningful way.

**Comment by jigold** [comment]
They're circular imports I thought.

**Comment by danking** [comment]
I'll have to think about the circular thing, but I learned that
```
    from __future__ import annotations
```
let's you use names directly rather than as strings.

**Comment by jigold** [comment]
I'm running into this same problem. Going to try upgrading flake8 to see if that helps.
https://github.com/PyCQA/pyflakes/issues/290

**Comment by danking** [comment]
great!

**Comment by danking** [comment]
@jigold this should pass now. I also learned that Mypy checks each command line argument as an independent module. Instead of specifying individual files, we have to tell it to check `batch`. I also added `google_storage.py` in an ill-fated attempt to let batch use that. I think we can only type check modules that depend on one another by installing them first. We'll leave that for future work.

**Comment by jigold** [comment]
There's some major test errors.

**Comment by danking** [comment]
worker.py was missing for some reason. I restored it to the version from master.

**Comment by danking** [comment]
OK! I think I finally squashed all the bugs

**Comment by danking** [comment]
There were version incompatibilities between dev-requirements.txt and docker/requirements.txt. I aligned all the versions and pulled some purest things up into docker/requirements.txt.

**Pull request merged**
