### PR TITLE
add TableScan IR node

### PR DESCRIPTION
**Pull request by catoverdrive**
can't handle changing the key, and currently doesn't check. I would probably want to just put the checks in python; would that be reasonable?

### CODE REVIEW

**Comment by patrick-schultz** [comment]
It makes me nervous having preconditions on scala functions that are only checked or documented upstream in python.

**Comment by catoverdrive** [comment]
I can add a comment above the definition as we've done with other IR nodes? I think it's not super straightforward to check in Scala.

**Comment by patrick-schultz** [comment]
I'm happy with that.

**Comment by cseed** [comment]
Why isn't this just in TableMapRows?  Then you can do `t.select(x = 5, y = f(t.y), z = hl.scan.mean(t.w))` (or just `hl.agg.mean(t.w)` or `hl.scan(hl.agg.mean(t.w))`?)

It can be added similarly to MatrixMapRows and MatrixMapCols.  MatrixMapEntries is trickier: in general the traversal order doesn't matter, but if you're doing a scan, it does.  I see three options: have MatrixTable select_entries (which maybe just calls to select_entries_by_row) and select_entries_by_{row, col}, have select_entries take some kind of flag, but I don't know if we can do that since select_entries takes **kwargs, or have a separate scan_entries_by_{row, col} method on MatrixTable.

I kind of lean towards the first one.  @tpoterba, thoughts?

**Comment by catoverdrive** [comment]
closing this to add an ApplyScanOp IR node instead.

**Pull request closed without merging**
