### PR TITLE
[release] Update changelog for 0.2.15.

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by tpoterba** [comment]
would prefer if #6313 went in first -- don't want to deoptimize anyone's pipelines!

**Comment by tpoterba** [comment]
Should be ready to go!

**Comment by tpoterba** [comment]
thank goodness for random batch failures!

**Comment by catoverdrive** [comment]
My PR went in, but I believe we're also waiting on some fixes from #6322 to go in as well.

**Comment by tpoterba** [comment]
don't approve until deployment is working again, please

**Pull request merged**
