### PR TITLE
[feature] Add checkpoint methods to MT/Table

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by tpoterba** [comment]
Konrad asked the same question, I told him we can add that feature back-compatibly, but it's not trivial.

**Comment by tpoterba** [comment]
right now that no-args thing is `persist()`

**Comment by konradjk** [comment]
I'm actually not sure it's exactly persist. I think persist would hold some in memory and spill to disk, right? Or does it actually write the whole thing?

**Comment by cseed** [comment]
> we can add that feature back-compatibly, but it's not trivial

It's not trivial?  Then shouldn't we figure it out now?  `persist` is a totally different beast.  I think we'd both argue the users shouldn't have to know the difference between these things.  Should persist just write/read?

**Comment by tpoterba** [comment]
sorry, wasn't clear. I don't think it's trivial to figure out what a no-args checkpoint should do, but it IS trivial to make that change back-compatibly when we do.

**Comment by cseed** [comment]
Wait, what's wrong with just getting a temporary path with `new_temp_file`?

**Comment by konradjk** [comment]
that's what I suggested

**Comment by cseed** [comment]
Tim, can you shoot me down, too?

**Comment by tpoterba** [comment]
ugh, I'm still exhausted from shooting Konrad down.

**Pull request merged**
