### PR TITLE
[query] Use error code for ArrayRef

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by tpoterba** [comment]
I probably missed some, let's see what the tests find.

**Comment by tpoterba** [comment]
ah, crap, this requires more thought. indexArray is the function that python calls, we basically never generate ArrayRef.

**Comment by johnc1231** [comment]
Could we just change the Python to generate `ArrayRef`? Not clear to me why we use `indexArray` instead.

**Comment by tpoterba** [comment]
indexArray does python-style lookups, e.g. `[-1]` is the last element.

**Comment by tpoterba** [comment]
I think what we want is an error code on apply nodes! There are lots of functions that can throw errors.

**Pull request closed without merging**
