### PR TITLE
[batch] expose ABC Resource to users (previously #9515)

### PR DESCRIPTION
**Pull request by danking**
CHANGELOG: The Resource class is now also available at hailtop.batch.Resource.

I screwed up my branches. This is just #9515.

### CODE REVIEW

**Comment by jigold** [comment]
You need to rebase.

**Comment by danking** [comment]
rebased

**Review by jigold — APPROVED** [review]

**Comment by danking** [comment]
Which PR?

**Comment by jigold** [comment]
You have a bunch of stuff in here that is not related to this PR.

**Comment by danking** [comment]
Fixed. My local branch situation was really fucked up temporarily.

**Review by jigold — APPROVED** [review]

**Pull request merged**
