### PR TITLE
History time zone to utc

### PR DESCRIPTION
**Pull request by jigold**

### CODE REVIEW

**Comment by jigold** [comment]
I ran this at 10:18AM EST. This is the new output:
```
# 2017-09-22T14:17:35.270508
```
@danking @konradjk Can you confirm this is what you wanted?

**Comment by danking** [comment]
@jigold this doesn't look right, it should have had a `-06:00` suffix.

**Comment by danking** [comment]
Ridiculous. `utcnow` doesn't return a time without a timezone, even though the time zone should obviously be UTC.

**Comment by danking** [comment]
Ok, @jigold looks like the only sensible way to do this is to add an

```
import pytz
```
```
now = datetime.datetime.utcnow().replace(tzinfo=pytz.utc)
```
According to a note in the Python 2.7 docs [there are no tzinfo instances in the standard library](https://docs.python.org/2/library/datetime.html#tzinfo-objects).

We should add the dependency on pytz to [environment.yml](https://github.com/hail-is/hail/blob/master/python/hail/environment.yml).

**Comment by danking** [comment]
Or we can leave it like it is now, and everyone must assume that the timestamp is UTC, even though this violates ISO 8601:

> If no UTC relation information is given with a time representation, the time is assumed to be in local time.
https://en.wikipedia.org/wiki/ISO_8601

**Comment by konradjk** [comment]
I don't mind assuming it's UTC. At least to me, if there's no time zone, it's UTC

**Comment by konradjk** [comment]
Oh hmm, just read @danking's last message. Well, up to you all. I don't think it matters as much as long as it's well-documented.

**Comment by danking** [comment]
I was just being cranky. Violating ISO 8601 is probably OK, we should add a tag or something that tells us to fix this properly when we switch to python 3 (which has sensible default `tzinfo`'s in the standard library)

**Comment by jigold** [comment]
@danking If Konrad is fine with this for now and Python 3 will fix the issue, I think we should keep this PR as is and avoid adding additional dependencies. I'll add checking the time zone to the 0.2 to-do list and we can revisit once we've switched to Python 3.

**Pull request merged**
