### PR TITLE
[batch] Mitigate too many resources with same prices

### PR DESCRIPTION
**Pull request by jigold**
I left out the cloud specific check and just make it so we don't have this problem again on any cloud.

### CODE REVIEW

**Review by danking — DISMISSED** [review]
let's check for equality

**Comment by jigold** [comment]
I'm putting the WIP tag for Monday. I changed the code slightly from before. I checked and the test PR driver logs were at least clean.

**Review by danking — APPROVED** [review]
LGTM

**Comment by jigold** [comment]
I forgot there was a WIP on here. Will take it off tomorrow morning.

**Pull request merged**
