### PR TITLE
[notebook] fix for k8s vulnerability

### PR DESCRIPTION
**Pull request by cseed**
FYI @akotlar

### CODE REVIEW

**Comment by akotlar** [comment]
Working on the non-root pr. I think we should remove --allow-root in Dockerfile.hail-jupyter?

**Comment by tpoterba** [comment]
I'm pretty sure GitHub will merge this with the commit message (instead of PR title/comments) since it's a single commit. oh well.

**Comment by konradjk** [comment]
well, it's a temporary fix anyway that will be reverted in due course, so meh

**Comment by tpoterba** [comment]
yeah, it just makes it a little harder to make the changelog.

**Comment by cseed** [comment]
@tpoterba sorry, may bad, I amended the commit message and re-pushed.

**Pull request merged**
