### PR TITLE
[hail] Strengthen containsAgg and containsScan.

### PR DESCRIPTION
**Pull request by tpoterba**
I believe this will solve a bug Alicia is hitting, but I am having
trouble replicating it without the ability to run her pipeline.

### CODE REVIEW

**Comment by chrisvittal** [comment]
Does the issue not replicate on synthetic data?

I know this seems small, but I'm worried about this strengthening causing more breakage.

**Comment by tpoterba** [comment]
It's not the data, it's a complicated pipeline to replicate.

I can try harder.

**Comment by chrisvittal** [comment]
Can we give Alicia a build based on this commit and see if it solves the issue?

**Comment by tpoterba** [comment]
I think I see how to make a failing example

**Comment by tpoterba** [comment]
ok, added failing test!

**Pull request merged**
