### PR TITLE
LD Prune

### PR DESCRIPTION
**Pull request by jigold**
- Added ld_prune method
 - Docs for ld_prune
 - Removed local_prune_threshold -- max of 2 local prunes
 - new GeneralRDD class
 - fixed issues with AdjustedPartitionsRDD

### CODE REVIEW

**Comment by jigold** [comment]
@cseed The current code only does a repartition if the number of variants per partition in the input dataset is greater than the queue size - should I always force a repartition to occur to rebalance after the first prune step?

**Comment by jigold** [comment]
@cseed: Bit packing is working. The R2 issue was from trying to pass in one array of Longs with mapPartitions.  I tried the new version on google cloud and it didn't finish (looked like it was stuck). Can you confirm I am not missing a persist in the global prune?

Locally, here's the timing for 100K variants, 2535 samples, 1GB of data:
PLINK:
1 core: 28.419s, 27.995s
(doesn't scale)

Hail (bit packed):
1 core: 1m3.5s
2 cores: 42.974s
4 cores: 37.295s
8 cores: 36.632s

**Comment by cseed** [comment]
Just 2x PLINK!  This is great!  Jon's new hardcallIterator is in: https://github.com/hail-is/hail/pull/1312.  Do you want to try using it?  It should give another nice speedup.

**Comment by jigold** [comment]
With Jon's hardCallIterator:

PLINK:
1 core: 28.419s, 27.995s
(doesn't scale)

Hail (bit packed, hard call iterator)
1 core: 54.404s
2 cores: 38.107s
4 cores: 33.410s
8 cores: 35.097s

**Comment by jigold** [comment]
@cseed Back to you

**Comment by johnc1231** [comment]
Fixes #99

**Comment by jbloom22** [comment]
@jigold re-open once you've rebased

**Pull request closed without merging**
