### PR TITLE
[batch] Support python 3.11 in default python jobs

### PR DESCRIPTION
**Pull request by chrisvittal**

### CODE REVIEW

**Review by daniel-goldstein — DISMISSED** [review]

**Comment by chrisvittal** [comment]
Does one of use need to run the command to actually publish the image?

**Comment by daniel-goldstein** [comment]
Hrm ya it looks like you'll also need to add these images to `docker/hailgenetics/python-dill/push.sh` (annoying that those images are duplicated) and then run the two targets in `docker/hailgenetics/Makefile` in order.

**Comment by chrisvittal** [comment]
hmm
```
$ make publish-python-dill && make mirror-dockerhub-images
DOCKER_PREFIX=us-docker.pkg.dev/hail-vdc/hail bash python-dill/push.sh
+ for version in 3.8 3.8-slim 3.9 3.9-slim 3.10 3.10-slim 3.11 3.11-slim
+ public=hailgenetics/python-dill:3.8
+ DOCKER_BUILDKIT=1
+ docker build --build-arg PYTHON_VERSION=3.8 --file Dockerfile.out --build-arg BUILDKIT_INLINE_CACHE=1 --tag hailgenetics/python-dill:3.8 .
[+] Building 0.0s (2/2) FINISHED                                                                                                                                                                                                                                                                                   docker:desktop-linux
 => [internal] load build definition from Dockerfile.out                                                                                                                                                                                                                                                                           0.0s
 => => transferring dockerfile: 2B                                                                                                                                                                                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                                                                    0.0s
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount969738803/Dockerfile.out: no such file or directory
```

**Comment by daniel-goldstein** [comment]
🤦‍♂️ i bet changing Dockerfile.out to Dockerfile will work that's bitrotted

**Review by daniel-goldstein — APPROVED** [review]

**Pull request merged**
