### PR TITLE
Expanded python docs and changed the theme

### PR DESCRIPTION
**Pull request by jigold**
- Read the docs theme
- Each class has separate page
- Getting started modified for python
- Overview page added

### CODE REVIEW

**Comment by cseed** [comment]
This looks really great.  My one comment is that I think Hail expressions, when written standalone (like in Overview) when not part of a larger python expression, should not be in quotes.

**Comment by jigold** [comment]
I just told you and @danking to put your expressions in single quotes on your PRs. I'm fine with not single quote, but then I'll figure out how to turn off syntax highlighting.

**Comment by cseed** [comment]
Ah, good point.  It looks like the directive `.. highlight:: none` will set the highlighting to none.  Not sure how to do it inline.

**Comment by cseed** [comment]
Ah, inline doesn't do syntax highlighting, looks like.

**Comment by jigold** [comment]
back to you

**Pull request merged**
