### PR TITLE
Add NDArrays to create_all_values test

### PR DESCRIPTION
**Pull request by johnc1231**

### CODE REVIEW

**Comment by tpoterba** [comment]
needs bump?

**Comment by danking** [comment]
The bug here appears to be that ndarray serializes to JSON in a format that we cannot deserialize:
```
E           is.hail.utils.HailException: scala.MatchError: could not convert "{flags: 0, offset: 0, shape: (2, 3), strides: (12, 4), data: [1,2,3,4,5,6]}" to ndarray<int32, 2> in column "nd"
```
I guess the big question for this PR is what is the serialized representation of an ndarray? Once we decide on that we can start testing for round-trip ability. Site of necessary changes appears to be `AnnotationImpex.scala`.

I propose `{shape, strides, data}`, does that seem right John?

**Comment by johnc1231** [comment]
Right now it still serializes with `offset` and `flags` as well, pointless though they are. There seem to be multiple things failing in this PR. One of them is `expand_types`, which is why I brought it up yesterday. This thing is like 4th on my list behind fixing Konrad's bug, regions, and team meeting on Tuesday. If you'd prefer I closed for now I can

**Comment by danking** [comment]
Yeah, let's close and re-open when we have bandwidth for it.

**Pull request closed without merging**
