### PR TITLE
[query][fs] fix local and google fs, port test_backward_compatability

### PR DESCRIPTION
**Pull request by danking**
I cannot enable these tests because both the local and service backend fail due to this error:

```
E               Java stack trace:
E               java.lang.AssertionError: assertion failed:
E                 ir key: [Ljava.lang.String;@28f4484b
E                 lowered key: WrappedArray()
E               	at scala.Predef$.assert(Predef.scala:223)
E               	at is.hail.expr.ir.lowering.LowerTableIR$.lower$1(LowerTableIR.scala:1101)
E               	at is.hail.expr.ir.lowering.LowerTableIR$.apply(LowerTableIR.scala:1118)
E               	at is.hail.expr.ir.lowering.LowerToCDA$.lower(LowerToCDA.scala:67)
E               	at is.hail.expr.ir.lowering.LowerToCDA$.lower(LowerToCDA.scala:36)
E               	at is.hail.expr.ir.lowering.LowerToCDA$.apply(LowerToCDA.scala:16)
E               	at is.hail.expr.ir.lowering.LowerToDistributedArrayPass.transform(LoweringPass.scala:75)
E               	at is.hail.expr.ir.lowering.LoweringPass.$anonfun$apply$3(LoweringPass.scala:15)
E               	at is.hail.utils.ExecutionTimer.time(ExecutionTimer.scala:81)
E               	at is.hail.expr.ir.lowering.LoweringPass.$anonfun$apply$1(LoweringPass.scala:15)
E               	at is.hail.utils.ExecutionTimer.time(ExecutionTimer.scala:81)
E               	at is.hail.expr.ir.lowering.LoweringPass.apply(LoweringPass.scala:13)
E               	at is.hail.expr.ir.lowering.LoweringPass.apply$(LoweringPass.scala:12)
E               	at is.hail.expr.ir.lowering.LowerToDistributedArrayPass.apply(LoweringPass.scala:70)
E               	at is.hail.expr.ir.lowering.LoweringPipeline.$anonfun$apply$1(LoweringPipeline.scala:14)
E               	at is.hail.expr.ir.lowering.LoweringPipeline.$anonfun$apply$1$adapted(LoweringPipeline.scala:12)
E               	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
E               	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
E               	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
E               	at is.hail.expr.ir.lowering.LoweringPipeline.apply(LoweringPipeline.scala:12)
E               	at is.hail.backend.local.LocalBackend._jvmLowerAndExecute(LocalBackend.scala:88)
E               	at is.hail.backend.local.LocalBackend._execute(LocalBackend.scala:124)
E               	at is.hail.backend.local.LocalBackend.$anonfun$execute$1(LocalBackend.scala:131)
E               	at is.hail.expr.ir.ExecuteContext$.$anonfun$scoped$3(ExecuteContext.scala:47)
E               	at is.hail.utils.package$.using(package.scala:627)
E               	at is.hail.expr.ir.ExecuteContext$.$anonfun$scoped$2(ExecuteContext.scala:47)
E               	at is.hail.utils.package$.using(package.scala:627)
E               	at is.hail.annotations.RegionPool$.scoped(RegionPool.scala:13)
E               	at is.hail.expr.ir.ExecuteContext$.scoped(ExecuteContext.scala:46)
E               	at is.hail.backend.local.LocalBackend.withExecuteContext(LocalBackend.scala:69)
E               	at is.hail.backend.local.LocalBackend.execute(LocalBackend.scala:128)
E               	at is.hail.backend.local.LocalBackend.$anonfun$executeJSON$1(LocalBackend.scala:145)
E               	at is.hail.utils.ExecutionTimer$.time(ExecutionTimer.scala:52)
E               	at is.hail.backend.local.LocalBackend.executeJSON(LocalBackend.scala:143)
E               	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
E               	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E               	at java.lang.reflect.Method.invoke(Method.java:498)
E               	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
E               	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
E               	at py4j.Gateway.invoke(Gateway.java:282)
E               	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
E               	at py4j.commands.CallCommand.execute(CallCommand.java:79)
E               	at py4j.GatewayConnection.run(GatewayConnection.java:238)
E               	at java.lang.Thread.run(Thread.java:748)
```

cc: @cseed , I'm not sure I got the changes to fs right.

### CODE REVIEW

**Comment by danking** [comment]
bump (@cseed I'd like you to take a look at the FS changes, just a couple lines)

**Comment by danking** [comment]
bump

**Comment by cseed** [comment]
This looks fine assuming it passes, although I don't understand the legacy FS stuff very well, Alex wrote it.  I think I can start replacing it with AsyncFS soon.

**Review by tpoterba — APPROVED** [review]
looks good to me

**Comment by tpoterba** [comment]
I think those failures are due to legacy tables not being keyed. See the workaround in the interpreted path here:
https://github.com/hail-is/hail/blob/bb7f847d9b3af888d4a59376fdd70900265bdeda/hail/src/main/scala/is/hail/expr/ir/TableIR.scala#L877-L881

**Pull request merged**
